### ISSUE TITLE
How to get shinyDirButton to load the choices of multiInput ?

### ISSUE THREAD

**Issue by biodan25** [dreamRs/shinyWidgets#101]
I'm relatively new to shinyWidgets and am  having trouble getting the 'choices' param of the multiInput widget to load the output of the shinyDirButton. Any help would be welcome!

I tried eventReactive but couldn't get that to work either.  BTW, I also tried setting the inputId of the multiInput="mfiles" too.  The documents say the 'choices' param is a list, but the examples all show a vector of fruit labels. Is there some special casting necessary to get the multiInput 'choices' param to display the list of files from the shinyDirButton output?

```
ui = fluidPage(
    mainPanel(titlePanel("Connect dir chooser with multiInput"),
              shinyDirButton('directory', 'Folder select', 'Please select a folder'),
              tableOutput(outputId = "mfiles")  ,
                fluidRow(column(6,
                     wellPanel(
                        multiInput(
                          inputId = "xpt", label = "Files :",
                          choices <-  "mfiles",
                          selected = "", width= '400px' 
                       )
                ))
          )
   )
)
```

```
server = function(input, output, session) {
  volumes <- getVolumes()
  shinyDirChoose(input, 'directory', roots = volumes, session=session)
  path1 <- reactive({
    return(print(parseDirPath(volumes, input$directory)))
  })
  observe({
    if(!is.null(path1)){
      output$mfiles <- renderText({ list.files(path1())})   
    }
  }) 
}
```

```
shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Hello,
You have to use the server logic to modify `multiInput` choices and use `updateMultiInput` with the result of `path1()`. Warning: `updateMultiInput` is only available from dev version of `shinyWidgets`, re-install from GitHub !

Try this example : 

```r
# you'll need dev version
# devtools::install_github("dreamRs/shinyWidgets")

library(shiny)
library(shinyWidgets)
library(shinyFiles)

ui <- fluidPage(
  titlePanel("Connect dir chooser with multiInput"),
  shinyDirButton(id = 'directory', label = 'Folder select', title = 'Please select a folder'),
  fluidRow(
    column(
      width = 6,
      wellPanel(
        multiInput(
          inputId = "xpt", label = "Files :",
          choices =  "",
          selected = "", 
          width = '400px' 
        ),
        verbatimTextOutput(outputId = "mfiles")
      )
    )
  )
)
server <- function(input, output, session) {
  
  volumes <- getVolumes()
  shinyDirChoose(input = input, id = 'directory', roots = volumes, session = session)
  path1 <- reactive({
    parseDirPath(volumes, input$directory)
  })
  
  observeEvent(path1(), {
    updateMultiInput(session = session, inputId = "xpt", choices = list.files(path1()))
  })
  
  output$mfiles <- renderPrint({ input$xpt })
}
shinyApp(ui = ui, server = server)
```

Victor

**Comment by biodan25** [comment]
Many thanks for the rapid reply!  However, after installing the dev version with devtools::install_github("dreamRs/shinyWidgets") , I seem to be missing a function, dropNulls

```Warning: Error in dropNulls: could not find function "dropNulls"```

my sessionInfo() shows:
shinyWidgets_0.4.3.970 shinyFiles_0.7.0

**Comment by pvictor** [comment]
Yep that's the one ! Still your error is weird ... 😲

**Comment by vnijs** [comment]
@pvictor and @biodan25 I tried the 2nd example above with the latest version of `shinyFiles` on GitHub and it seemed to work fine. This version will likely be pushed to CRAN shortly. Install using:

`devtools::install_github("thomasp85/shinyFiles")`

BTW In case either of you are interested in contributing to shinyFiles there are some JS related enhancements that would be very nice to have (e.g., the issues below) but JS is, unfortunately, not my area of expertise.

https://github.com/thomasp85/shinyFiles/issues/79
https://github.com/thomasp85/shinyFiles/issues/91

https://github.com/thomasp85/shinyFiles/pull/82
