### ISSUE TITLE
dropdownButton closes on any click when inserted by insertUI

### ISSUE THREAD

**Issue by thothal** [dreamRs/shinyWidgets#105]
I observed that when you insert a `dropdownButton`  via `insertUI` the button is unusable. I tracked down the root cause and I found out that for some reason `dropBtn`  is never fired when `dropdownButton` is inserted via `insertUI`.

In the app below you will notice, that when you are trying to select an element in the `selectInput` of the second dropdown, the dropdown menu closes immediately making the dropdown basically unusable.

As mentioned above, I could track this behaviour down to the fact that `dropBtn` was never called. So if you call `dropBtn` manually via the `actionButton` the second dropdown works as intended.

This may be related to rstudio/shiny#1545. However, when fiddling with the code and inserted the script in the head (as mentioned in rstudio/shiny#1545) it did not work either.

```
library(shiny)
library(shinyWidgets)
library(shinyjs)

makeDropdown <- function(id, title, ...) {
  dropdownButton(h3(title),
                 selectInput(paste0("sel", id), 
                             "Select", 
                             1:2),
                 inputId = id, 
                 icon = icon("cog"), 
                 ...)
}

ui <- fluidPage(useShinyjs(), 
                fluidRow(actionButton("fix", "Fix Dropdown"),
                         makeDropdown("working", "Working")))

server <- function(input, output, session) {
  insertUI(".row", 
           ui = makeDropdown("not_working", "Not Working", status = "info"))
  observeEvent(input$fix, runjs("dropBtn('#dropdown-not_working', true);"))
}
```

**Comment by pvictor** [comment]
It's fixed, I used input bindings from Shiny to execute the JavaScript, no need to `dropBtn` anymore.
This should not impact normal behaviour, but if you can test that everything that works before still works, that will be great !

Victor

**Comment by thothal** [comment]
First tests worked like a charm - thanks for the rapid feedback. Any chance that this fix will make it to CRAN soon? Reason I am asking is that our company's rule is to use only packages from CRAN and not Github packages. So in order to use that productively I need to rely on the CRAN package.

**Comment by pvictor** [comment]
I think CRAN is closed this week, I'll prepare a release for next week.
