### ISSUE TITLE
open dropdownbutton from inside another dropdownbutton

### ISSUE THREAD

**Issue by madmark81** [dreamRs/shinyWidgets#108]
Hey Victor, 

do you have some experience with how to deal with running a dropdownButton from inside the modal dialog of another dropdownButton? Without any extra code, trying to open it the first modal dialog disappears and the second one never appears. 

Vice versa, when you close the second one, the first one should come back  (or still be open). 

Also, did you have any luck yet with the other easyclose issue I spoke to you about last year, how sweetalert messages and other items make the modal dialog close while you would like it to stay open? 

Cheers, Mark

**Comment by pvictor** [comment]
Hi Mark,

That's complicated with Bootstrap's dropdown and so doesn't work with `dropdownButton`, but that's possible with `dropdown` which is implemented in a different way.

Nope, but I'm going to take a look again since I made some changes for `dropdownButton` javascript-side.

Victor

**Comment by madmark81** [comment]
It's probably an unwise approach anyway. I have since then moved along and created a different way to build a satisfying user interface segment that fits my needs. You can close this if you wish
