### ISSUE TITLE
strange conflict with javascript for observing shiny is busy

### ISSUE THREAD

**Issue by ghost** [dreamRs/shinyWidgets#109]
see the case explained here: 
https://stackoverflow.com/questions/52313596/disable-elements-when-shiny-is-busy

**Comment by pvictor** [comment]
With last release, I don't see any problems.
Try re-install from Github : 

```r
devtools::install_github("dreamRs/shinyWidgets")
```

Victor

**Comment by madmark81** [comment]
I just downloaded it, it's not closing with the button still......

**Comment by pvictor** [comment]
Sorry Mark, my bad, forgot to push......
Please retry, you have shinyWidgets version 0.4.3.993

Victor

**Comment by madmark81** [comment]
Haha ok. Will try tonight.
If you dont push, we push you ;)

Thanks man

**Comment by madmark81** [comment]
yes! it works! cool. I'll look into the dropdownbutton plus dropdown now

Thanks Victor

**Comment by madmark81** [comment]
some follow up questions:

- Dropdown doesn't close by click outside. Can this be changed, or can I
add a button with some code to close it (and not close the other
dropdownbutton)
- I style the dropdownbutton popups position with this kind of code:
    tags$head(tags$style(HTML('
 #MyDropDown  {height: 40px; width: 40px; padding: 0;border-radius: 6px;
border-width:2px; background-color: white; border-color: #339FFF; color:
#339FFF}
                              #dropdown-menu-MyDropDown {left: 70px; top:
-397px;height:690px},
                           ')
How do I target the dropdown popup in the same way? Haven't been able to
figure out what tag to target for the left and top placement

**Comment by pvictor** [comment]
Can you provide a reproducible example please ?

**Comment by madmark81** [comment]
Will do tomorrow
