### ISSUE TITLE
use reset button of searchInput in server()

### ISSUE THREAD

**Issue by heylue** [dreamRs/shinyWidgets#11]
Hello !

Would it be possible to access the **reset** button of the `searchInput` as a proper input ?
I would like to attach an event to it other than just reseting the searchfield, using `observeEvent`.
On the simpliest form, it would be something like so : 

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      textInput(inputId="text", value=NULL),
      searchInput(inputId ="search", value=NULL)
    )
  )
)

server <- function(input, output) {
  observeEvent(search$reset){
    updateTextInput("text", value = "RESET!")
  }
}

shinyApp(ui = ui, server = server)
```

Maybe is it only possible in Jquery ?

Thanks !

**Comment by pvictor** [comment]
Hi!

Yes this is totally possible. I've updated the function, now the reset button act like an `actionButton`, you can access its value by pasting "_reset" after the id of `searchinput`, e.g. `input$<inputId>_reset`. With your example it will be `input$search_reset` : 

```r

library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      textInput(inputId = "text", label = "Text", value = NULL),
      searchInput(inputId = "search", label = "Search", value = NULL, btnReset = icon("remove")),
      
      tags$p("Reset button value :"),
      verbatimTextOutput(outputId = "res")
    ),
    mainPanel()
  )
)

server <- function(input, output, session) {
  
  output$res <- renderPrint({
    input$search_reset # this is the value for reset button
  })
  
  observeEvent(input$search_reset, {
    updateTextInput(session = session, inputId = "text", value = "RESET!")
  })
}

shinyApp(ui = ui, server = server)

```

Is this behavior answer your need ?

Victor

**Comment by heylue** [comment]
Yes, perfectly. I also tested the "search" action button and it works fine.

Many thanks 👍
