### ISSUE TITLE
airdateDropper

### ISSUE THREAD

**Issue by madmark81** [dreamRs/shinyWidgets#110]
Hi Victor, 

i'm playing around with your airdatepicker, with range is true. 
Do you think there is a way to make the icon button on the right functional, as a "submit" dates 

The reason is this: I'm using javascript to block shiny when its busy for any reason, and it messes with the ranged airdatepicker together with observe. As soon as you select the first date, this will fire the observeEvent looking at it, eventhough I block the code inside by req(length('mydatepicked') ==2) or some equivalent, and the busy code will then cause the datepicker to collapse. 

it could be nice to have the code not react at all to dates being selected until the user presses a submit button. I can add my own submit button off course, easily, but perhaps it would be nicer to have this as part of the (now non functional) button next to the date bar of the airdatepicker. 

cheers. 

Mark

**Comment by pvictor** [comment]
Hi Mark,
It's not actually a button, just a Bootstrap addon.
You can use `update_on = 'close'` to prevent update on each change and update only when datepicker is closed.

Victor

**Comment by madmark81** [comment]
Is there a way to add an ID to the icon? I would like to use shiny's onclick functionality to open a modal dialog with a plot 
https://www.rdocumentation.org/packages/shinyjs/versions/0.0.7.0/topics/onclick

**Comment by madmark81** [comment]
perhaps the simplest solution (if that's possible) is to add an inputId to the icon that is whatever the user sets as inputId for the airdatepickerInput plus an extension; i.e.   inputId = paste(inputId, 'icon', sep = '-')
to the function code that makes the pickers?

**Comment by pvictor** [comment]
Done! You can try:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
    airDatepickerInput(
    inputId = "DateRange",
    label = "Select multiple dates:",
    placeholder = "You can pick 5 dates",
    multiple = 5, clearButton = TRUE
  ),
  verbatimTextOutput("res_date"),
  verbatimTextOutput("res_button")
)

server <- function(input, output, session) {
  output$res_date <- renderPrint(input$DateRange)
  output$res_button <- renderPrint(input$DateRange_button)
}

shinyApp(ui, server)
```

Victor

**Comment by madmark81** [comment]
cool. lets close the issue.
