### ISSUE TITLE
Can't listen to dropdown being clicked

### ISSUE THREAD

**Issue by madmark81** [dreamRs/shinyWidgets#111]
I'd like to fire code linked to the dropdown being clicked (opened) but I can't seem to get an observeEvent to work. Also it seems that the inputId is changed by the widget by adding suffixes to it like 'sw-drop'or 'sw-btn'. 

demo app, none of the three observers react

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  

                 dropdown(inputId = "MyDropDown2",
                          
                          tags$h3("List of Input"))
  )

server <- function(input, output, session){
  
  
  
  
  observeEvent(input[['sw-drop-MyDropDown2']],{
    print('here')
  })
  
  observeEvent(input[['MyDropDown2']],{
    print('here 2')
  })
  
  observeEvent(input[['sw-btn-MyDropDown2']],{
    print('here 3')
  })
  
}

shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Hi Mark,
Yes you're right, `dropdown`'s behavior was not the same than `dropdownButton`, that's fixed. In last version, it'll be your second `observeEvent` that be fired.

Victor
