### ISSUE TITLE
Extraneous 3px margin?

### ISSUE THREAD

**Issue by mbacou** [dreamRs/shinyWidgets#113]
The extra `3px` margin creates minor alignment and spacing problems when combined with other Shiny widgets, not sure why this is necessary?
https://github.com/dreamRs/shinyWidgets/blob/ab7b617d72f79fede7cc58b945a91b81968a4b05/R/input-switch.R#L80

With the 3px margin...
![image](https://user-images.githubusercontent.com/260325/46447297-f1a06f80-c74e-11e8-83b7-ca687c93dca3.png)

... and without (better)
![image](https://user-images.githubusercontent.com/260325/46447311-0846c680-c74f-11e8-9f36-5a6e4505bd62.png)

**Comment by pvictor** [comment]
Indeed, it seems useless.... I don't remember why I added that. I deleted it.

Thank you !

Victor
