### ISSUE TITLE
PickerInput incorrectly assigns groups with single member

### ISSUE THREAD

**Issue by Thomas-Hirsch** [dreamRs/shinyWidgets#114]
I have a list of categories with two levels of hierarchy, so I thought using the options group method would be appropriate. However, it appears that when a group only contains one category, it renders the name rather than the value. I'm not sure if there is a better way of transforming the data than the way I've done it.

For example, given a data frame looking like this, called `my_data`:

Cat1 | Cat2
------------ | -------------
upper | A
upper | B
upper | C
lower | a
lower | b
lower | c
singleton | some_value

I generate the list as so:
`my_options_list <- split(my_data, my_data$cat1) %>% lapply(function(x) x <- x$cat2)`

This results in a list much like the option groups example in the ShinywidgetsGallery, with the addition of my singleton example. But when updating the choices via updatePickerInput, it outputs "singleton" as the value, rather than the name of the group.

**Comment by pvictor** [comment]
Hi,
That's because your choices are vectors, they must be lists to be displayed correctly. Try this : 

```r

library(tibble)
my_data <- tribble(
  ~cat1,	~cat2,
  "upper",	"A",
  "upper",	"B",
  "upper",	"C",
  "lower",	"a",
  "lower",	"b",
  "lower",	"c",
  "singleton",	"some_value"
)
# Dont work: list of vector
split(my_data$cat2, my_data$cat1)
# Work: list of lists
lapply(split(my_data$cat2, my_data$cat1), as.list)


library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  pickerInput(
    inputId = "somevalue",
    label = "A label:", 
    choices = lapply(split(my_data$cat2, my_data$cat1), as.list)
  ),
  verbatimTextOutput("value")
)

server <- function(input, output, session) {
  output$value <- renderPrint({ input$somevalue })
}

shinyApp(ui, server)
```
![image](https://user-images.githubusercontent.com/4415580/46575152-3119c680-c9b0-11e8-8687-1acc6b70d50a.png)


Victor
