### ISSUE TITLE
Airdatepicker

### ISSUE THREAD

**Issue by madmark81** [dreamRs/shinyWidgets#115]
Hi Victor, 

first of all, thanks for constantly giving feedback to everyone's questions! 

one small question about airdatepicker. Do you know what css code to use to make the airdatepicker open below the input field rather than above? 
in a fashion like this for instance where i change some elements of the airdatepicker box. 

 tags$head(tags$style(HTML(' #DateRange {height:40px;  border-color:#339fff;  border-width: 2px}')))

**Comment by pvictor** [comment]
Hi Mark,
Thanks :) I do my best !
Your issus confuses me, the default behavior is to display the calendar below. I must not have understood something.

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  # tags$head(tags$style(HTML(' #DateRange {height:40px; border-color:#339fff; border-width: 2px}'))),
  airDatepickerInput(
    inputId = "DateRange",
    label = "Select multiple dates:",
    placeholder = "You can pick 5 dates",
    multiple = 5, clearButton = TRUE
  ),
  verbatimTextOutput("res")
)

server <- function(input, output, session) {
  output$res <- renderPrint(input$DateRange)
}

shinyApp(ui, server)
```

![image](https://user-images.githubusercontent.com/4415580/46632855-3e6bb800-cb4c-11e8-91a6-2d3f363b38e1.png)

Victor

**Comment by madmark81** [comment]
never mind, I'm an idiot it seems (or possibly too tired after a day of
coding). Overlooked that I actually already added a position argument to
the airdatepiicker while searching in the css code of my app.
position = 'bottom center' instead of the default was in my code.

My apologies.  Turns out it is easy to get confused when your app is 10.000
lines of code haha

**Comment by pvictor** [comment]
No worries Mark, good luck with your app!

Victor
