### ISSUE TITLE
Reactive pickerInput default select is inaccurate

### ISSUE THREAD

**Issue by warrrach** [dreamRs/shinyWidgets#116]
Hi, I have a markdown file and I am using reactive shiny inputs in it. I have three pickerInputs - The selected value's of the second one depend on the input of the first, and the selected values of the third one depend on the input of the second. This works fine when only one choice is selected from the first or second pickerInput, but when more than one choice is selected (or select all is clicked) the second and third pickerInputs default to random choices. I should mention that the list of choices (a_choices, b_choices, and c_choices) are columns coming from an embedded SQL data table.

`fluidPage(fluidRow(box(
  column(
    width = 4,
    pickerInput(
      "a",
      "A",
      choices = table$a_choices,
      selected = params$a,
      multiple = T,
      options = list(`actions-box` = TRUE)
    )
  ),
  column(width = 4, renderUI({
    pickerInput(
      "b",
      "B",
      choices = table$b_choices[table$a_choices == input$a],
      selected = table$b_choices[table$a_choices == input$a],
      multiple = T,
      options = list(`actions-box` = TRUE)
    )
  })),
  
  column(width = 4, renderUI({
    pickerInput(
      "c",
      "C",
      choices = table$c_choices[table$b_choices == input$b] ,
      selected = table$c_choices[table$b_choices == input$b] ,
      multiple = T,
      options = list(`actions-box` = TRUE)
    )
  }))`

**Comment by pvictor** [comment]
Hi,
Maybe do that : 
```r
# replace this and others
table$b_choices[table$a_choices == input$a]
# by
unique(table$b_choices[table$a_choices == input$a])
```

if this still does not work, please provide a reproducible example.

Victor
