### ISSUE TITLE
Update the value of noUiSliderInput() continuously, even while dragging

### ISSUE THREAD

**Issue by yanirmor** [dreamRs/shinyWidgets#121]
Hello,
First - it's a good chance to say thank you for the awesome package. I use it all the time!

I stumble upon an issue where the value of `noUiSliderInput()` is updated only after the dragging was completed (namely, the mouse click was released).

It will be very useful to have the option of having the value continuously updated, even during the dragging (namely, before the mouse click was released).

Some more info [here.](https://stackoverflow.com/questions/52968346/is-it-possible-to-read-data-from-shinywidgetsnouisliderinput-while-the-slide) 

Thank you!
Yanir

**Comment by pvictor** [comment]
Hi,
Glad you like the package :)
I added argument `update_on` to `noUiSlider`, install from GitHub and try : 

```r
library(shiny)
library(shinyWidgets)

shinyApp(
  ui = fluidPage(
    noUiSliderInput(
      inputId = "the_slider", label = NULL, 
      min = 0, max = 10, step = 1, value = 5, 
      behaviour =  c("snap"), update_on = "change"
    ),
    verbatimTextOutput("slider_value")
  ), 
  server = function(input, output, session) {
    output$slider_value <- renderPrint(input$the_slider)
  }
)
```

Victor

**Comment by yanirmor** [comment]
Amazing! Thank you so much!
