### ISSUE TITLE
pickerOptions not found

### ISSUE THREAD

**Issue by MokeEire** [dreamRs/shinyWidgets#122]
I am using the new pickerOptions function in lieu of the previous list format:

    renderUI({
      pickerInput(
        inputId = "year",
        label = "Select Year",
        choices = c("All",sort(unique(df$data()$Year))),
        selected = "All",
        options = pickerOptions(
          actionsBox = TRUE,
          color = "#fff",
          size = 10,
          selectedTextFormat = "count > 3"
        ),
        multiple = F
      ) 
    })

This results in the error: `Warning: Error in pickerOptions: could not find function "pickerOptions"`

I also tried shinyWidgets::pickerOptions and this resulted in an error: `Warning: Error in : 'pickerOptions' is not an exported object from 'namespace:shinyWidgets'`

This is being created within a Flexdashboard Rmd file in R version 3.5.1.

**Comment by pvictor** [comment]
Which version of `shinyWidgets` do you use ?

```r
packageVersion("shinyWidgets")
```

You need >= 0.4.4

`color` isn't a valid argument for `pickerOptions`.

**Comment by MokeEire** [comment]
I have 0.4.4.  Is trying to use `color` the reason for the error?  I have since reverted to using `list` rather than `pickerOptions`.

A separate but related issue - how does one change the colour from grey/black to white/light grey like the default selectInput style?
