### ISSUE TITLE
Unrelated to widgets question

### ISSUE THREAD

**Issue by madmark81** [dreamRs/shinyWidgets#125]
Hey victor, just because I thought you're one very talented guy with lots of shiny experience, 
I would like to ask you whether you have ever come across or managed to build a proper vertical sliderInput. I've tried to build one myself, but i'm stuck with a vertical slider where the mouse dragging is still happening horizontal. 

thanks for the good work once again! I'll send you a bit of footage in the coming months once my App is fully finished

**Comment by pvictor** [comment]
Hi Mark,
You can try `noUiSliderInput`, it has a vertical mode : 

```r
demoNoUiSlider(example = "more")
demoNoUiSlider(example = "color")
```

Victor

**Comment by madmark81** [comment]
Ah nice, I'm trying to modify one now to look similar to the other
horizontal sliders.
thanks

**Comment by madmark81** [comment]
Is there a way to add min, max and current value tags to these things ?

**Comment by pvictor** [comment]
Yes, with argument `pips` and something like this : 

```r
library( shiny )
library( shinyWidgets )


ui <- fluidPage(
  
  tags$br(),
  
  noUiSliderInput(
    inputId = "noui2", 
    label = "Slider vertical:",
    min = 0, 
    max = 1000,
    step = 50,
    value = c(100, 400),
    margin = 100,
    orientation = "vertical",
    pips = list(
      mode = "range",
      density = 3
    ),
    width = "100px", height = "300px"
  ),
  verbatimTextOutput(outputId = "res2")
  
)

server <- function(input, output, session) {

  output$res2 <- renderPrint(input$noui2)
  
}

shinyApp(ui, server)
```

For more, see online docs : https://refreshless.com/nouislider/pips/

Victor

**Comment by madmark81** [comment]
Last question,

do you know how to get rid of the 2 horizontal bars in the slider handle? I
restyled the bar but those keep showing up.

I tried something like this : tags$head(tags$style(HTML('

.noUi-vertical .noUi-handle {    width: 0px;
    height: 0px;
                          left: 0px;
                          top: 0px; } '))

but they still show up.

Rest of the CSS to make the silder look the way I did it this:
                           .noUi-vertical {width: 6px;}
                         .noUi-connect {background: #399fff;}
                          .noUi-vertical .noUi-handle {width: 14px; height:
14px; top:0px;  border: 1px solid #AAA; background: #DDD; border-radius:
27px; -moz-border-radius: 27px; box-shadow: 1px 1px 3px rgba(0,0,0,0.3);
left: -6px; cursor: pointer;}

**Comment by madmark81** [comment]
Victor, did you have a chance to look at my last comment here? Perhaps you missed it.

**Comment by pvictor** [comment]
Hello Mark,

Try this : 

```r
tags$style(".noUi-handle:after, .noUi-handle:before {display: none !important}")
```

Victor

**Comment by madmark81** [comment]
That worked! thanks
