### ISSUE TITLE
toggleDropdown() for dropdown()

### ISSUE THREAD

**Issue by serkserk** [dreamRs/shinyWidgets#130]
Hi, thanks for you package, it's amazing,

I'm trying to close my dropdown window from either a clik on a button inside the dropdown or any other way but I can't acheive that. There is a way for dropdownButton() but not dropdown()

I tried to change the state of the input$<dropdown_id>_state but it's read only.

And is there any place where I can learn all the css "tag" like #sw-content-dropdown, .sw-dropdown-in etc  to manipulate the widget?
Thanks

**Comment by pvictor** [comment]
Hello!
You're welcome!
Yes there's no method in `shinyWidgets` to close dropdown from the server, but you can achieve this with `shinyjs` package, check ths example:

```r
library("shiny")
library("shinyWidgets")
library("shinyjs")

ui <- fluidPage(
  useShinyjs(),
  tags$h2("pickerInput in dropdown"),
  br(),
  dropdown(
    
    inputId = "mydropdown",
    
    tags$h3("List of Input"),
    
    pickerInput(inputId = 'xcol2',
                label = 'X Variable',
                choices = names(iris),
                options = list(`style` = "btn-info")),
    

    actionButton(inputId = "close", label = "Close dropdown"),
    
    style = "unite", icon = icon("gear"),
    status = "danger", width = "300px",
    animate = animateOptions(
      enter = animations$fading_entrances$fadeInLeftBig,
      exit = animations$fading_exits$fadeOutRightBig
    )
  ),
  
  plotOutput(outputId = 'plot2')
)

server <- function(input, output, session) {
  
  # close dropdown when button inside is clicked
  observeEvent(input$close, shinyjs::click("mydropdown"))
  
  
  
}

shinyApp(ui = ui, server = server)
```

Tell me if it's good enough for you.

Victor

**Comment by serkserk** [comment]
Thanks this work well !
I tried shinyjs early with `hide()` but it didnt go well
