### ISSUE TITLE
Checkbox icon no longer working?

### ISSUE THREAD

**Issue by philstraforelli** [dreamRs/shinyWidgets#131]
Hi Victor,

If I use the following code:

    awesomeRadio(inputId = "country", label = "",
                       choices = c("Canada", "USA"), selected = "Canada",
                       checkbox = TRUE, inline = TRUE)

I end up with the following:
![capture](https://user-images.githubusercontent.com/22040238/49389882-3bb8b980-f6dc-11e8-8acf-703abb672354.PNG)

This issue seems to have arisen in the last few weeks, although I'm not sure what started it. Obviously a low priority issue because I can just remove the `checkbox` argument, but I just wanted to let you know.

**Comment by pvictor** [comment]
Hi!

Try dev version, it should work, @AshesITR has fixed this in https://github.com/dreamRs/shinyWidgets/pull/129

It's because of last `shiny` update.

Victor

**Comment by philstraforelli** [comment]
Confirmed, thanks Victor.
