### ISSUE TITLE
Shiny 1.2.0 breaks FontAwesome on shinyWidgets

### ISSUE THREAD

**Issue by dylancis** [dreamRs/shinyWidgets#132]
Hi there-
Since shiny upgraded to 1.2.0 there is incompatibility with `shinyWidgets ::awesomeCheckbox`
Using the below:
```
 awesomeCheckbox(
          inputId = "dayFirst",
          label = "Day field precedes month field in dates",
          value = TRUE,
          status = "primary"
        ) 
```
Gives on the screen - BAD:
![image](https://user-images.githubusercontent.com/4976433/49463289-f5547f00-f7ef-11e8-8cb1-f3f7fbca155a.png)

When I downgrade shiny 1.1.0 - I got this instead: GOOD:
![image](https://user-images.githubusercontent.com/4976433/49463495-6eec6d00-f7f0-11e8-85d4-3d5a5ef6ccd4.png)

I am aware shiny 1.2.0 introduced [beaking changes](https://github.com/rstudio/shiny/blob/master/NEWS.md#breaking-changes-1) for other packages using **FontAwesome**.

Thank you for your help, Dylan

**Comment by pvictor** [comment]
Hello Dylan,

Try dev version, it works (confirmed in #131 ), @AshesITR  has fixed this in #129


Victor
