### ISSUE TITLE
updateSearchInput() trigger doesn't work in Shiny modules

### ISSUE THREAD

**Issue by cvmartin** [dreamRs/shinyWidgets#133]
Hi: first of all thanks for such great package as it is shinyWidgets; 
I am getting quite deep in Shiny by modularizing UI+server units of code, and I found that the *trigger* parameter in updateSearchInput() doesn't work inside Shiny modules.

I could reproduce easily the problem just modularizing the example already included in updateSearchInput():

```
# The module --------------------------------------------------------------
moduleSearchInput <- function(id, title) {
  ns <- NS(id)
  
  div(style = "padding:10px; margin:10px; border-style:solid; border-width:2px;",
    tags$h2(title),
    searchInput(
      inputId = ns("search"), label = "Enter your text",
      placeholder = "A placeholder",
      btnSearch = icon("search"),
      btnReset = icon("remove"),
      width = "450px"
    ),
    br(),
    verbatimTextOutput(outputId = ns("res")),
    br(),
    textInput(
      inputId = ns("update_search"),
      label = "Update search"
    ),
    checkboxInput(
      inputId = ns("trigger_search"),
      label = "Trigger update search",
      value = TRUE
    )
    )
  }

moduleSearch <- function(input, output, session) {
  output$res <- renderPrint({
    input$search
  })
  
  observeEvent(input$update_search, {
    updateSearchInput(
      session = session,
      inputId = "search",
      value = input$update_search,
      trigger = input$trigger_search
    )
  }, ignoreInit = TRUE)
}

# The app -----------------------------------------------------------------
  library(shiny)
  library(shinyWidgets)
  
  ui <- fluidPage(
    moduleSearchInput("module1", "First module"),
    moduleSearchInput("module2", "Second module")
  )
  
  server <- function(input, output, session) {
    callModule(moduleSearch, "module1")
    callModule(moduleSearch, "module2")
  }
  
  shinyApp(ui, server)
```

As you can see, checking the *Trigger update search* box doesn't make any difference. One has to update the input "manually", by pressing the search button, for instance. 

I have tried to find a workaround using shinyjs::click() over the search button whenever the values should be updated, but I found that this solution is quite buggy. 

Any suggestion is welcome; thanks in advance.

**Comment by pvictor** [comment]
Hi Carlos!
Thanks for the amazing reprex! Very thorough!
In fact clicking the button is what I do in the js bindings to trigger the update, I was using the wrong id. Thanks for reporting this, it should work in dev version 0.4.4.910, tell me if it's good for you !

Victor

**Comment by cvmartin** [comment]
Hi Victor, 
Thank you very much for your quick reply; the fresh dev version works perfectly fine. Thanks again!
Carlos
