### ISSUE TITLE
Clear the airdatepicker with update code

### ISSUE THREAD

**Issue by madmark81** [dreamRs/shinyWidgets#134]
Hey Victor, 

I tried a bunch of ways, but can't figure it out. What is the way to empty the textbox of the airdatepicker with update command? 
updateAirDateInput(session, inputId = 'DateRange', value = c("") and other attempts failed

thanks

**Comment by pvictor** [comment]
Hello Mark,
There is a `clear` argument that can be used exactly for this use case.

Victor
