### ISSUE TITLE
Multiple selection on pickerInput within dropdown causes dropdown menu close

### ISSUE THREAD

**Issue by matt-fagan** [dreamRs/shinyWidgets#136]
Hey there folks. I don't know if you guys are still keeping this code base alive, but I sure hope so. This is really incredible, impressive stuff that I couldn't set down and write if I had a whole year to do it.

But I digress. I suspect this is related to the pickerInput - dropdownButton issue, but I've found that any form of multiple selection with pickerInput in a dropdown leads to a close of the entire dropdown menu upon exiting the input. I can't record my screen unfortunately, but updating the example for dropdown() to include a multiple pickerInput can reveal this: 
![image](https://user-images.githubusercontent.com/28901122/49975229-d641a580-fef1-11e8-875b-8e36bd6be861.png)

Upon exiting the input selection, regardless of where one clicks, the entire control dropdown menu closes. Is this a known bug? If so, are there any workarounds? Any input would be really appreciated; I've got a specific use case to take advantage of the large number of selections that pickerInput can handle with its selected-text-format argument, but with the entire menu closure this becomes more of a hassle in implementation than a help.

Regardless, thank you for this incredible augmentation. I can't wait to utilize it more in my applications.

Best,
Matt

**Comment by pvictor** [comment]
Hello Matt,
Glad you like the package :)

Are you using `dropdown` or `dropdownButton` ? 
`pickerInput` doesn't work in `dropdownButton` indeed.

Try this, should work: 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  dropdown(
    label = "Controls", 
    icon = icon("sliders"),
    status = "primary",
    pickerInput(
      inputId = "n",
      label = "Number of observation:",
      choices = 1:20,
      multiple = TRUE
    )
  )
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)

```

Best,

Victor
