### ISSUE TITLE
airDatepickerInput not respecting language setting in flexdashboard

### ISSUE THREAD

**Issue by stefanavey** [dreamRs/shinyWidgets#138]
`airDatepickerInput()` does not respect the language setting when running in a flexdashboard.  Here is a comparison of traditional shiny app vs dashboard.

## Shiny App (language is English)

This works as expected.

    library(shiny)
    library(shinyWidgets)
    
    ui <- fluidPage(
        airDatepickerInput(
            inputId = "default",
            label = "First example:",
            language = "en"
        ),
        verbatimTextOutput("res_date")
    )
    
    server <- function(input, output, session) {
        output$res_date <- renderPrint(input$default)
    }
    
    shinyApp(ui, server)
    
![image](https://user-images.githubusercontent.com/6976841/50231327-8c870e00-037c-11e9-92a7-9c64440f9bfb.png)

## Flexdashboard (language is not English)

I think the language is Russian so the language parameter is not being respected.  Not sure if this is an issue on flexdashboard or shinyWidgets side.

    ---
    title: "Test in Flexdashboard"
    runtime: shiny
    output: 
      flexdashboard::flex_dashboard
    ---
    
    Sidebar {.sidebar}
    =======================================================================
    
    ```{r}
    
    library(flexdashboard)
    library(shiny)
    library(shinyWidgets)
    
    airDatepickerInput(
        inputId = "default",
        label = "First example:",
        language = "en")
    
    output$res_date <- renderPrint(input$default)
    verbatimTextOutput("res_date")
    
    ```

![image](https://user-images.githubusercontent.com/6976841/50231297-79743e00-037c-11e9-9637-6d74cdb12865.png)

**Comment by pvictor** [comment]
Hello Stefan,

Thanks for the example!
Weird, an issue with a dependency. This should be fixed in dev version, re-install from GitHub and re-try !

Victor

**Comment by stefanavey** [comment]
Tested and it now works as expected in flexdashboard too. Thanks for the quick fix!
