### ISSUE TITLE
multiInput() allow single choice only

### ISSUE THREAD

**Issue by BetweenTwoTests** [dreamRs/shinyWidgets#14]
This has completely replaced the original Shiny input widgets for me!

I have one question about your multiInput() widget. This is less of an "issue" but more of a "feature request". I really like the look of the two column selector. Is it possible to only allow 1 item selected (i.e. disable multiple). Although the name seems to imply "multiple", the UI of the two column view is very attractive. 

I attempted to use `shinyjs::disable()` on it without success. Is it possible to have an option to only allow 1 choice selected and the selected choice displayed on the right? If a second choice is selected, then remove & replace the previously selected.

**Comment by pvictor** [comment]
I'm glad you find this package useful!

I don't think that's possible with this plugin... (without hardcoding it in js, which can be a solution but will take some times).
You can find the JavaScript lib here : https://github.com/Fabianlindfors/multi.js
I'll look into alternative or similar widgets.

Victor

**Comment by pvictor** [comment]
Last multi.js release support a `limit` options, so you can do (that's not exactly what you asked, but this is close):

```r

# install dev version
# devtools::install_github("dreamRs/shinyWidgets")

library("shiny")
library("shinyWidgets")

ui <- fluidPage(
  multiInput(
    inputId = "id", label = "Fruits :",
    choices = c("Banana", "Blueberry", "Cherry",
                "Coconut", "Grapefruit", "Kiwi",
                "Lemon", "Lime", "Mango", "Orange",
                "Papaya"),
    options = list(limit = 1),  #  <-------- here
    width = "350px"
  ),
  verbatimTextOutput(outputId = "res")
)

server <- function(input, output, session) {
  output$res <- renderPrint({
    input$id
  })
}

shinyApp(ui = ui, server = server)

```

**Comment by ViolaPsch** [comment]
Hey, 
I use `multiInput `for displaying flags and am wondering whether there is a way to do the opposite @BetweenTwoTests aked: Can I set a minimum for the number of items that should be selected?
Thank you 🙏,
Viola

**Comment by pvictor** [comment]
Hi @ViolaPsch ,
No, there's no options to set a minimum number of items to be selected. I don't think I know of any widget with this option.
My solution will be to display an informative text under the widget and then use `req(length(input$id) > 3)` in reactive context to be sure there more than 3 items selected (you can also look to `?shiny::need`).

Here's an example with an alert info: 

```r
library(shiny)
library(shinyWidgets)


ui <- fluidPage(
 tags$h3("Fruit selector"),
 fluidRow(
   column(
     width = 4,
     multiInput(
       inputId = "id",
       label = "Fruits :",
       choices = c("Banana", "Blueberry", "Cherry",
                   "Coconut", "Grapefruit", "Kiwi",
                   "Lemon", "Lime", "Mango", "Orange",
                   "Papaya"),
       selected = "Banana", 
       width = "100%"
     ),
     uiOutput(outputId = "info")
   ),
   column(
     width = 8,
     verbatimTextOutput(outputId = "res")
   )
 )
)

server <- function(input, output, session) {
  
  output$info <- renderUI({
    if (length(input$id) < 3) {
      alert(
        icon("info"), 
        "You need to eat at least 3 fruits! (", 3 - length(input$id), "more to pick)",
        status = "info"
      )
    }
  })
  
  output$res <- renderPrint({
    input$id
  })
}

shinyApp(ui = ui, server = server)
```

Victor

**Comment by ViolaPsch** [comment]
Thank you, @pvictor! This is a good idea. 🙂

**Comment by ccmerry** [comment]
I believe the "limit" option no longer works. It was working for me a few months ago. After I updated R, it is not working. I ran the example @pvictor provided back in 2018 and experienced the same issue. No items in choices are able to be selected or deselected.
