### ISSUE TITLE
Add custom localization for the airDatepickerInput

### ISSUE THREAD

**Issue by artemklevtsov** [dreamRs/shinyWidgets#140]
Hi,

How can I add a custom localization? My language are missing in the predefined set

**Comment by pvictor** [comment]
Hello,

You have to complete a a file like those available here : https://github.com/dreamRs/shinyWidgets/tree/master/inst/www/air-datepicker/i18n

Example for english : 

```
;(function ($) { $.fn.datepicker.language['en'] = {
    days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    daysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    daysMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    months: ['January','February','March','April','May','June', 'July','August','September','October','November','December'],
    monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    today: 'Today',
    clear: 'Clear',
    dateFormat: 'mm/dd/yyyy',
    timeFormat: 'hh:ii aa',
    firstDay: 0
}; })(jQuery);
```

It's maybe possible to add directly this script into a shinyapps, but not tested.

You can make a PR to add a new file for your language in `inst/www/air-datepicker/i18n` (and add the name of your language in the `match.arg` call in `airDatepickerInput`).

Or just reply with the script above in the desirfed language, and I'll add it to the package.

Victor

**Comment by artemklevtsov** [comment]
Thank you. Sent #141.

**Comment by micahwilhelm** [comment]
I think it would be better if you added an option to specify the 'firstDay' of the week directly in the function. Currently, there is no way to override this because the localisation is done via language selection. Unfortunately, not all English speaking countries start their week on Sunday.

**Comment by pvictor** [comment]
I added `firstDay` arg, try: 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  airDatepickerInput(
    inputId = "date",
    label = "Select date:",
    firstDay = 4
  ),
  verbatimTextOutput("res")
)

server <- function(input, output, session) {
  output$res <- renderPrint(input$date)
}

shinyApp(ui, server)
```
