### ISSUE TITLE
Combining pickers: using Live search and Multiple together

### ISSUE THREAD

**Issue by owczarz-eca** [dreamRs/shinyWidgets#142]
Assuming I have application like this (adjusted example from issue #7): 

```
library("shiny")
library("shinyWidgets")


# Countries
countries <- c(
    "United Kingdom", "Germany", "United States of America", "Belgium", "China", "Spain", "Netherlands", "Mexico",
    "Italy", "Canada", "Brazil", "Denmark", "Norway", "Switzerland", "Luxembourg", "Israel", "Russian Federation",
    "Turkey", "Saudi Arabia", "United Arab Emirates"
)

ui <- fluidPage(
    tags$h2("Select countries to drill down"),
    
    dropdown(
        circle = TRUE, status = "default", icon = icon("sliders"), width = "300px",
        pickerInput(inputId = "Adverts",
                    label = "Countries",
                    choices = countries, # a list of strings
                    options = list(`actions-box` = TRUE, `live-search` = TRUE),
                    multiple = TRUE)
    ),
    verbatimTextOutput(outputId = "res")
)

server <- function(input, output, session) {

    output$res <- renderPrint({
        input$Adverts
    })
}

shinyApp(ui = ui, server = server)
```
I would like to **combine live search and multiple selection**. For example, I am interested in some countries that contain letter **G** (but **only** Germany and Belgium). Therefore, I search for **G** in the search box and I want to pick two countries (Germany and Belgium). Once I click on Germany the search menu **expands and renders all available choices** , hence disregarding the search input **G**. Is there a way to fix it? The same logic applies to unselecting choices, I am able to `select all` countries with **G** but when I try to unselect UK the list expands again.

**Comment by trafficonese** [comment]
I ran into the same problem and played a bit with the source code.
I found, that when the following line https://github.com/dreamRs/shinyWidgets/blob/02bb84e4a2eb45b3b422af084a61b2e9b4415cec/inst/assets/selectPicker/picker-bindings.js#L66  is removed, the list doesn't reload and so far I couldn't see any problems with it.

@pvictor What is the `refresh` for exactly? Could it be removed?

**Comment by yurasik2000** [comment]
Same problem. Suggested by @trafficonese solution dosen't work for me. R 3.3.3 ShinyWidgets 0.4.9

**Comment by pvictor** [comment]
Hi,
You're right @trafficonese , this line seems unnecessary, and without it solve this issue.

So this should work now after re-installing from GitHub.

@yurasik2000 , if modifying picker JavaScript bindings, you have to run this code after to compile all bindings : 

https://github.com/dreamRs/shinyWidgets/blob/6b0034c65f1632c872d21ab74256772b44c97a3d/inst/assets/tools.R#L35
