### ISSUE TITLE
The dropupAuto parameter vs 'dropup-auto' with window restrictions

### ISSUE THREAD

**Issue by dalekube** [dreamRs/shinyWidgets#144]
The 'dropupAuto' option (pickerOptions) does not work. I believe this data attribute is now called 'dropup-auto'. I confirmed that 'dropup-auto' works.

For example:
`pickerInput("USER",label="User",multiple=F,choices=users,options = list("dropup-auto"=FALSE))`

**Comment by pvictor** [comment]
Hello,

`pickerOptions` returns the correct attribute : 

```
 pickerOptions(dropupAuto = FALSE)
# $`dropup-auto`
# [1] FALSE
```

`dropupAuto` is just the argument of the function, because `dropup-auto` isn't a valid R name.

Victor

**Comment by dalekube** [comment]
Here is a simple and specific

 example that shows how the two parameters work differently when the window of the browser constricts the input's surroundings. The first input (using "dropupAuto=FALSE") continues to drop the menu upward, but the second input (using "'dropup-auto'=FALSE") coerces the menu downward as expected even though the browser window limits the visibility. 


    library(shiny)
    library(shinyWidgets)

    shinyApp(
    ui = fluidPage(
    
    div(style="height:300px;"),
    
    # input with the "dropupAuto" parameter
    pickerInput(
      inputId="test",
      label="Using dropupAuto = FALSE",
      multiple=F,
      choices=c("dog","cat","mouse","pig","horse"),
      options = list(dropupAuto=FALSE)
      ),
    
    # input with the "dropup-auto" parameter
    pickerInput(
      inputId="test",
      label="Using 'dropup-auto' = FALSE",
      multiple=F,
      choices=c("dog","cat","mouse","pig","horse"),
      options = list("dropup-auto"=FALSE)
      )
    ),
  
    server = function(input, output) {}
    )
![dropup](https://user-images.githubusercontent.com/12777137/51779378-b09ce400-20cc-11e9-846a-e01b0d9f4b24.gif)
