### ISSUE TITLE
Is it possible to keep original color of actionBttn after pressing it?

### ISSUE THREAD

**Issue by artofstat** [dreamRs/shinyWidgets#146]
I would like the color of an actionBttn not change to a more faded version once it is pressed, but keep the original color intensity. Is that possible?

Many thanks for this wonderful package,

Bernhard Klingenberg

**Comment by artofstat** [comment]
It may work via an ```updateActionBttn``` command, but there is none.

**Comment by pvictor** [comment]
Hi!

Are you refering to `actionBttn` with `style = "simple"` ? The only solution I found is to add : 

```r
tags$style(".bttn-simple:focus {opacity: 1 !important;}")
```

somewhere in your UI. I don't think there's something to do with `updateActionBttn` (you can try `updateActionButton` it will work on `actionBttn` nonetheless)

Here a full example: 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$h2("Awesome action button"),
  
  tags$style(".bttn-simple:focus {opacity: 1 !important;}"),
  
  tags$br(),
  actionBttn(
    inputId = "bttn1",
    label = "Go!",
    color = "primary",
    style = "simple", 
  ),
  
  tags$br(),
  verbatimTextOutput(outputId = "res_bttn1")
)

server <- function(input, output, session) {
  
  output$res_bttn1 <- renderPrint(input$bttn1)
  
}

shinyApp(ui = ui, server = server)
```

Victor

**Comment by artofstat** [comment]
Thanks! This helps, but is only "half" of the behavior I had in mind. I simply want the button to behave as if it were never pressed. (Sort of like a refresh button.) 
So, with `style = "simple"`, once pressed, it should return the original color (as you showed with your code above), but also, on hovering over it, should fade again, which is its initial behavior. Similar, with `style = "jelly"`, the button should expand again although it had been pressed previosuly.

I checked [shinyjs](https://github.com/daattali/shinyjs) which allows to reset shiny ui elements, but found under the documentation for the reset function: "Note that actionButton is not supported, meaning that you cannot reset the value of a button back to 0."
