### ISSUE TITLE
Issue retrieving Bootstrap's version in case of using "selectPicker"

### ISSUE THREAD

**Issue by Diniodoc** [dreamRs/shinyWidgets#147]
Hello I’m just playing around with some shiny webapps and found the beautiful "shinyWidgets" package.
Now I’m facing the problem, that sometimes my shiny-dashboard-apps are not displayed correctly in IE and Edge (Chrome and FF are working well). The debugging-console is always throwing the following warning:

```
There was an issue retrieving Bootstrap's version. 
Ensure Bootstrap is being loaded before bootstrap-select 
and there is no namespace collision. 
If loading Bootstrap asynchronously, the version may need
 to be manually specified via 
$.fn.selectpicker.Constructor.BootstrapVersion.
TypeError: Cannot read property 'Constructor' of undefined
    at bootstrap-select.min.js:8
```

I think sometimes there is a problem when loading additional js in an unfortunate order or timing, which causes the problem that js is not working correctly and shiny objects cannot be created in the right way. 
Is that possible and does anybody know how solve the warning?

Here is a minimal example.

```
library(shinydashboard)
library(shinyWidgets)

ui <- dashboardPage(
  dashboardHeader(title = "ISSUE"),
  dashboardSidebar(),
  dashboardBody(
    box(
      pickerInput(
        "pickerInput1",
        "Test:",
        c("One" = "One","Two" = "Two")
      )
    )
  )
)
server <- function(input, output) {}
shinyApp(ui, server) 
```

**Comment by pvictor** [comment]
Hello,
Yes there's currently no trivial way to order dependencies...
What's the issue exactly ? I have no issue with IE or Edge, even with the JS error.

If you want to get rid of the error, here's a way : you have to suppress the dependencies concerned and reinject them in proper order : 

```r
library(shiny)
library(shinydashboard)
library(shinyWidgets)

# get bootstrap dependency
bsDep <- shiny::bootstrapLib()
bsDep$name <- "bootstrap2"

# get pickerInput dependency
pkDep <- htmltools::findDependencies(shinyWidgets:::attachShinyWidgetsDep(tags$div(), widget = "picker"))
pkDep[[2]]$name <- "picker2"

ui <- dashboardPage(
  dashboardHeader(title = "ISSUE"),
  dashboardSidebar(),
  dashboardBody(
    
    # Suppress dependencies
    htmltools::suppressDependencies("selectPicker"),
    htmltools::suppressDependencies("bootstrap"),
    
    # reinject them
    bsDep, pkDep, 
    
    box(
      pickerInput(
        "pickerInput1",
        "Test:",
        c("One" = "One","Two" = "Two")
      )
    )
  )
)
server <- function(input, output) {}
shinyApp(ui, server) 
```

Victor

**Comment by Diniodoc** [comment]
So, I’ve experimented around and was finally able to get rid of the error with your upper hints. 
Thank you again!

Unfortunately, that was not the reason for the higher problem.
My search continues elsewhere, and I close this issue.
