### ISSUE TITLE
pickerInput inside dropdownButton

### ISSUE THREAD

**Issue by Minded13** [dreamRs/shinyWidgets#15]
Hi!

First of all, thanks for your great package! I pimp my apps since I've get it!

pickerInput don't work as expected when inside a dropdownButton : dropdown panel is closed when the picker menu is clicked. Here's a reproducible example : 
`if (interactive()) {
	library("shiny")
	library("shinyWidgets")
	
	ui <- fluidPage(
			fluidRow(
					column(1, 
							dropdownButton(icon = icon('gear'), width = "400px", 
									pickerInput(
											inputId = "id", label = "Fruits :",
											choices = c("Banana", "Blueberry", "Cherry"),
											selected = "Banana", width = "350px"
									)
							)
					),
					column(11, br(), verbatimTextOutput(outputId = "res"))
			)
	)
	
	server <- function(input, output, session) {
		output$res <- renderPrint({
					input$id
				})
	}
	
	shinyApp(ui = ui, server = server)
}
`
And I've a little request : can you put the code on the "other stuffs" page of shinyWidgetsGallery(), specially for the second dropdown button? It's animation is really nice! I'm less interested by the panel slide animation...

Thanks again for your work!

**Comment by pvictor** [comment]
Hi!

Ahaha nice! Glad you like the package!

Yes, `pickerInput` doesn't work in `dropdownButton`, that's related to issue #3 ...
That's why there is a second dropdown function !
This one works with `pickerInput` and add animations (optionnal), but is a little more experimental.

Here the example in the gallery, select boxes are `pickerInput` : 

```
library("shiny")
library("shinyWidgets")

ui <- fluidPage(
  tags$h2("pickerInput in dropdown"),
  br(),
  dropdown(
    
    tags$h3("List of Input"),
    
    pickerInput(inputId = 'xcol2',
                label = 'X Variable',
                choices = names(iris),
                options = list(`style` = "btn-info")),
    
    pickerInput(inputId = 'ycol2', 
                label = 'Y Variable',
                choices = names(iris),
                selected = names(iris)[[2]], 
                options = list(`style` = "btn-warning")),
    
    sliderInput(inputId = 'clusters2', 
                label = 'Cluster count', 
                value = 3,
                min = 1, max = 9),
    
    style = "unite", icon = icon("gear"), status = "danger", width = "300px",
    animate = animateOptions(enter = animations$fading_entrances$fadeInLeftBig,
                             exit = animations$fading_exits$fadeOutRightBig)
  ),
  
  plotOutput(outputId = 'plot2')
)

server <- function(input, output, session) {
  
  selectedData2 <- reactive({
    iris[, c(input$xcol2, input$ycol2)]
  })
  
  clusters2 <- reactive({
    kmeans(selectedData2(), input$clusters2)
  })
  
  output$plot2 <- renderPlot({
    palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
              "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))
    
    par(mar = c(5.1, 4.1, 0, 1))
    plot(selectedData2(),
         col = clusters2()$cluster,
         pch = 20, cex = 3)
    points(clusters2()$centers, pch = 4, cex = 4, lwd = 4)
  })
  
}

shinyApp(ui = ui, server = server)
```

PS : I will update the gallery to show the code for the dropdowns

Victor

**Comment by Minded13** [comment]
Thanks a lot for your quick reply and for examples.

I'm really sorry because I didn't look at closed issues before reporting. My bad, I'm new to github and I will remember that.

Goodbye!
