### ISSUE TITLE
Stop dropdownbutton from opening

### ISSUE THREAD

**Issue by madmark81** [dreamRs/shinyWidgets#151]
Hi Victor, 

I'm looking to stop a dropdownbutton to open when clicked based on a condition to avoid renderUI errors on missing input.

When a user clicks on a `dropdownButton`, it normally opens a panel. In my case, this panel contains `renderUI `elements that depend on various variables. 
If these variables do not exist yet, the `renderUIs `will cause errors to spit out. 

What I would like to know is whether there is a way to look at the click
`observeEvent(input$MydropdownButton, { ....})`
and then stop it from opening the panel if a condition is not met. 

What I would like to do is give the user a sweetalert instead that informs the user of which options he has to create or load the needed data. 

- I know I can use `shinyjs::disable('MydropdownButton')`  inside an observer with `if `statement, but this would not allow me to trigger the `sweetalert `on a click anymore

- I've tried something like this: 
```
observeEvent(input$MydropdownButton, { 
if(!is.null(values$neededData)) { 'just open the dropdownbutton' } 
else { toggleDropdownButton('TestDrop')
'run sweetalert code'} 
})
```

But the `toggleDropdownButton `will only close the `dropdownButton `panel once it's already triggered to open, and thus shiny tried to `render `the `ui `element, with the resulting error, rather than block it from opening. 

Here is a full `server `and `ui `code piece to demonstrate it: 

```
shinyServer = function(input, output, session) {
  
  values <- reactiveValues()

  output$Reset_Threshold <- renderUI({
    if(values$randomNr == 2) { actionButton(inputId = "Reset_Threshold", label = icon("undo")) }
    else if(values$randomNr == 1) { actionButton(inputId = "Reset_Threshold", label = icon("table"))  }
  })
  
  observeEvent(input$TestDrop, { 
    if(!is.null(values$Filter_df)) { print('no problems')}
    else {  toggleDropdownButton('TestDrop') 
      # Run a sweetalert here is what I want to do
    }
    })
}
```
library(shiny)
library(shinyWidgets)

```
ui <- fluidPage(
  dropdownButton(inputId= "TestDrop", 
                 uiOutput('Reset_Threshold'),
                 icon = icon("table"), tooltip = tooltipOptions(title = "Click"))
  )
```

**Comment by madmark81** [comment]
Consider this closed. Some discussion on SO made me believe that this is not possible, and I have instead opted for rendering a regular button when the mentioned condition is false, and render a dropdownButton when the condition is true

**Comment by pvictor** [comment]
Hello Mark,
Sorry I couldn't help, it seemed complicated to me to implement something like this...

Victor

**Comment by madmark81** [comment]
no worries, like I said, I have found a good solution by conditional
rendering button vs dropdownbutton
