### ISSUE TITLE
Customize labels to an exponential text format on a vertical noUiSliderInput in R Shiny

### ISSUE THREAD

**Issue by ghost** [dreamRs/shinyWidgets#152]
Hello Victor, 

On a `noUiSliderInput`, I'm trying to change the labels from pips (i.e. -1 and 4 for min and max) to be displayed as 10^-1 and 10^4, or even better, with the powers as superscript instead of the '^' 
Do you know how to achieve this? 

I have tried to look at the documentation you linked in another issue here on `noUiSliderInputs `and first try to experiment with adding a prefix by adding this inside ```pips( ....) ,```

```      format= wNumbFormat( prefix= 'A'  )```

but  I ended up with no labels at all anymore. 
I'm posting a question on Stackoverflow with this problem as well. 

thanks for any possible help. 
[](https://stackoverflow.com/questions/54556304/customize-labels-to-an-exponential-text-format-on-a-vertical-nouisliderinput-in)

**Comment by madmark81** [comment]
I used a javascript solution in the end, the example can be found here on Stackoverflow
https://stackoverflow.com/questions/54618717/using-javascript-to-alter-nouislider-tags-in-r-shiny-error-when-performing-math
