### ISSUE TITLE
Default value for pickerInput when selected = NULL

### ISSUE THREAD

**Issue by aswansyahputra** [dreamRs/shinyWidgets#153]
Hi, thanks for the amazing package!

From the documentation of pickerInput, `NULL` as default value is only possible when `multiple = TRUE` and `selected = NULL`. Is it possible to also have `NULL` as the default value when `multiple = FALSE` and `selected = NULL`? 

Regards,
Aswan

**Comment by pvictor** [comment]
Hello!

You can cheat by making a multiple picker and limit max choice to 1 : 

```r
library("shiny")
library("shinyWidgets")

ui <- fluidPage(
  pickerInput(
    inputId = "somevalue",
    label = "A label", 
    choices = c("a", "b", "c", "d"),
    selected = NULL,
    multiple = TRUE,
    options = pickerOptions(maxOptions = 1)
  ),
  verbatimTextOutput("value")
)

server <- function(input, output) {
  
  output$value <- renderPrint({
    input$somevalue
  })
  
}

shinyApp(ui, server)
```

Victor

**Comment by aswansyahputra** [comment]
Hi Victor!

Thank you! It's working flawlessly, finally I can implement it in my shinyapps. Really appreciate your help!

Aswan
