### ISSUE TITLE
dropdown disappears after first selection of range airDatepickerInput 

### ISSUE THREAD

**Issue by Diniodoc** [dreamRs/shinyWidgets#155]
Hello,

i'm trying to integrate the beautiful airDatepickerInput with the range-option into a dropdown. The problem is, that the dropdown menu is closing after the first dateselection of a range.
I tried different combination of the options “update_on” and “autoClose” but can’t get rid of the mentioned problem.

Another question is, how to update the minDate or maxDate of the datepicker? It should work via updateAirDateInput(...,options = list(...)) (the BTN in my example)
But after using the updateAirDateInput in that way, the airDatepickerInput is not reacting anymore on inputs or the clear-button.

Am I overlooking something or is that a bug in combination with the dropdown?

A short example:

```
if (interactive()) {
  
  library(shiny)
  library(shinyWidgets)
  
  ui <- fluidPage(
    
    h4("Issue using range airdatepicker in dropdown"),
    verbatimTextOutput("res"),
    
    dropdown(
      label="dropDown",
      tags$h3("dropDown disappears after first date selection"),
      style = "unite", icon = icon("gear"),
      
      
      airDatepickerInput(
        inputId = "airdatepicker",
        range = TRUE,
        separator = " to ",
        minDate = "2018-01-01",
        maxDate = "2018-12-31",
        label = "RangePicker:",
        placeholder = "Select Range",
        clearButton = TRUE,
      )
      
    ),
    tags$h3("Button to change value AND minDate?"),
    actionButton("button", "BTN")
  )
  
  server <- function(input, output, session) {
    output$res <- renderPrint(input$airdatepicker)
    
    observeEvent(input$button, {
      updateAirDateInput(session,
                         "airdatepicker",
                         value= c("2015-01-01","2016-12-31"),
                         options = list(minDate="2015-01-01")
      )
    })
    
  }
  
  shinyApp(ui, server)
  
}

```

THX

**Comment by trafficonese** [comment]
I have a similar problem and i think it's related to this issue.
I posted a short example on [Stackoverflow](https://stackoverflow.com/questions/57573316/how-to-avoid-collapsing-with-shinywidgets-dropdown-and-a-datatable?noredirect=1#comment101609238_57573316).

**Comment by pvictor** [comment]
Oups, sorry to answer so late.

This should be fixed for `airDatepicker` & `DT`, e.g. : 

### airDatepicker
```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  
  h4("Issue using range airdatepicker in dropdown"),
  verbatimTextOutput("res"),
  
  dropdown(
    label="dropDown",
    tags$h3("dropDown disappears after first date selection"),
    style = "unite", 
    icon = icon("gear"),
    
    airDatepickerInput(
      inputId = "airdatepicker",
      range = TRUE,
      separator = " to ",
      minDate = "2018-01-01",
      maxDate = "2018-12-31",
      label = "RangePicker:",
      placeholder = "Select Range",
      clearButton = TRUE,
    )
    
  )
)

server <- function(input, output, session) {
  
  output$res <- renderPrint(input$airdatepicker)
  
}

shinyApp(ui, server)
```

### DT

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  br(),br(),br(),
  p("How to go to the next page, without collapsing?"),
  uiOutput("irisdrop", inline = TRUE)
)

server <- function(input, output, session) {
  output$irisdrop <- renderUI({
    dropdown(
      circle = FALSE, 
      inputId = "iris",
      label = "iris", 
      status = "primary", 
      DT::datatable(
        iris, rownames = NULL,
        height = "100%",
        selection = "none"
        
      )
      
    )
  })
}

shinyApp(ui, server)
```

Victor

**Comment by Diniodoc** [comment]
And sorry again to answer so late.

You are right but the issue is only partially solved. 
The dropdown menu is still closing after using the upper navigation elements (e.g. year, left or right)


**Your airDatepicker code example** 

![image](https://user-images.githubusercontent.com/16168355/67012099-131d9080-f0f1-11e9-9346-aece078dc400.png)

**Used packages:**

Package | Version
--------- | --------
shiny | 1.4.0.9000
shinyWidgets  | 0.4.9.900


Thank you
Diniodoc

**Comment by pvictor** [comment]
Ok I tried something else, can you test again please ?
Victor

**Comment by markusdumke** [comment]
Hi, any news on this topic? I would love to use `airDatepickerInput`, `airYearpickerInput` but it closes the dropdown as described, when a selection is made, which leads to a poor user experience. See reprex below (with shinyWidgets 0.5.4)

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  dropdownButton(
    airDatepickerInput(
      "date",
      "Date"
    )
  )
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```
