### ISSUE TITLE
Request: Provide code for "other stuffs" displays in shinyWidgetsGallery()

### ISSUE THREAD

**Issue by philstraforelli** [dreamRs/shinyWidgets#16]
As it is, it's not clear how to get the code for the 2 examples being currently displayed in "Other stuffs".

**Comment by pvictor** [comment]
Hi,
The code for widgets in "dropdowns & sweetalert" (i renamed the tab for the occasion)  is available in the Github version of the package , e.g. : 

```
devtools::install_github("dreamRs/shinyWidgets")
shinyWidgets::shinyWidgetsGallery()
```
I'll submit to CRAN next week.
And I'll upload the online gallery when my shinyapps.io credits will be back.

Victor
