### ISSUE TITLE
addSpinner reactiveValues vs. eventReactive

### ISSUE THREAD

**Issue by jokedurnez** [dreamRs/shinyWidgets#160]
Hi,
I'm trying to switch from eventReactive to reactiveValues, since I have multiple events that should change the same reactive variable.  I can't seem to get the spinner to work correctly.

Below is a minimal working script:
when situation 1 is run, the spinner does not appear while the plot is being updated with the new data.
With situation 2, the spinner works as expected.

I assume this is related to the difference between reactive and observe, but I don't know how to make the spinner work.

Again: I have multiple events that have a very different effect on the variable (rawdata in this case), so reactiveValues is really ideal here...

```
ui <- fluidPage(
    actionButton(inputId = "plotter", "MAKEPLOT"),
    addSpinner(plotOutput("plot", height = "200px"))  
)

server <- function(input, output) {
    
    # situation 1: spinner not working
    rawdata <- reactiveValues(vals = rnorm(100))
    observeEvent(input$plotter, {
        Sys.sleep(1)
        rawdata$vals <- rnorm(100)
    })
    output$plot <- renderPlot({hist(rawdata$vals)})
    
    # situation 2: spinner working
    # rawdata <- eventReactive(input$plotter, {
    #     Sys.sleep(1)
    #     rnorm(100)
    # }, ignoreNULL=FALSE)
    # output$plot <- renderPlot({hist(rawdata())})
}

shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Hi,
Indeed `observeEvent` doesn't trigger the output invalidation client-side, you can do it manually with package [`shinyjs`](https://github.com/daattali/shinyjs) : 

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  
  shinyjs::useShinyjs(), # <----- here use shinyjs
  
  actionButton(inputId = "plotter", "MAKEPLOT"),
  fluidRow(
    column(
      width = 6,
      addSpinner(plotOutput("plot"))
    )
  )
)

server <- function(input, output) {

  rawdata <- reactiveValues(vals = rnorm(100))
  observeEvent(input$plotter, {

    shinyjs::addCssClass( # <----- here force plotOutput to be in recalculating state
      id = "plot", 
      class = "recalculating"
    ) 

    Sys.sleep(5)
    rawdata$vals <- rnorm(100)
  })
  output$plot <- renderPlot({hist(rawdata$vals)})
  
}

shinyApp(ui = ui, server = server)
```

Let me know if it works for you !

Victor

**Comment by jokedurnez** [comment]
This works, thanks so much, @pvictor !
