### ISSUE TITLE
progressBar showing Value instead of Percent when display_pct=T

### ISSUE THREAD

**Issue by smanoj81994** [dreamRs/shinyWidgets#166]
I was testing out the progressBar function from shinyWidgets on my app and noticed that when display_pct=T the bar is showing the value instead of (value/total)*100.
This bug was not there in the older version of the package. On comparing the function definition it seems that the final paste inside the function should be displaying percent instead of value.
I have fixed it by specifying the function explicitly but it will great if the CRAN version could be updated.

Thanks

**Comment by pvictor** [comment]
Hi,
Can you provide an example please ?
Thanks

**Comment by smanoj81994** [comment]
Hi,

Below was the function in CRAN shinyWidget version 0.4.3

function (id, value, total = NULL, display_pct = FALSE, size = NULL, 
  status = NULL, striped = FALSE, title = NULL) 
{
  if (!is.null(total)) {
    percent <- round(value/total * 100)
  }
  else {
    percent <- round(value)
  }
  if (!is.null(title) | !is.null(total)) {
    title <- htmltools::tags$span(class = "progress-text", 
      id = paste0(id, "-title"), title, htmltools::HTML("&nbsp;"))
  }
  if (!is.null(total)) {
    total <- htmltools::tags$span(class = "progress-number", 
      htmltools::tags$b(value, id = paste0(id, "-value")), 
      "/", htmltools::tags$span(id = paste0(id, "-total"), 
        total))
  }
  tagPB <- htmltools::tags$div(class = "progress-group", title, 
    total, htmltools::tags$div(class = if (!is.null(size)) 
      paste("progress", size)
    else "progress", htmltools::tags$div(id = id, style = if (percent > 
      0) 
      paste0("width:", percent, "%;"), style = if (display_pct) 
      "min-width: 2em;", class = "progress-bar", class = if (!is.null(status)) 
      paste0("progress-bar-", status), class = if (striped) 
      "progress-bar-striped", role = "progressbar", if (display_pct) 
      **paste0(percent, "%"))))**
  tagPB <- tagList(singleton(tags$head(tags$style(".progress-number {position: absolute; right: 20px;}"))), 
    tagPB)
  attachShinyWidgetsDep(tagPB)
}


notice the highlighted paste0 (last paste0 in the function) has percent variable as argument while the latest version has value as argument. Value in that particular paste0 was creating the issue shown below

![pb](https://user-images.githubusercontent.com/37407283/54680776-bcd37980-4b30-11e9-8466-02d57414613c.PNG)

it shows 11% whereas it should be around 4.9%

hope this helps

**Comment by pvictor** [comment]
Ok, thank you both, the percentage should be displayed correctly now.

Victor
