### ISSUE TITLE
font size in dropdownbutton

### ISSUE THREAD

**Issue by madmark81** [dreamRs/shinyWidgets#167]
I think I haven't set any font-size myself for dropdownButtons in general, so i'm wondering, is it possible that there is some css code in your buttons that sets font-size to 14px for all content of the dropdown panels? It is messing with my style of elements throughout the app (different sizing inside and outside of dropdown panels. 

cheers, 

Mark

**Comment by pvictor** [comment]
Hi Mark,

The font size is set by Bootstrap for the CSS class `dropdown-menu`, and is 14px by default (it's here in Shiny : https://github.com/rstudio/shiny/blob/722b1d0258115c0777a0638ccd63e7ca4cb33564/inst/www/shared/bootstrap/css/bootstrap.css#L3530)

Victor
