### ISSUE TITLE
[enhacement] confirmSweetAlert type: Question

### ISSUE THREAD

**Issue by DrumSergio** [dreamRs/shinyWidgets#168]
Hi, I would like just to ask how do you see to incorporate a new option in `confirmSweetAlert` function.

Instead of success, info, etc.. I would like to see the option "question" with the image of a question mark. I think a lot of times `confirmSweetAlert` is used to select two options, so... why not?

I would like also to change the color of the buttons from the `confirmSweetAlert` function itself. (By the way, how can they be changed if not?)

Thank you!

**Comment by pvictor** [comment]
Hi,
OK I can look to upgrade to sweet alert 2, it'll allow to use `type = "question"` and change buttons colors. See here : https://sweetalert2.github.io/#popup-types
But some changes to make in the package to be fully compatible.

Victor

**Comment by pvictor** [comment]
The upgrade to SweetAlert2 is done, there is now a "question" type, and you can now specify buttons' colors, try : 

```r
library("shiny")
library("shinyWidgets")


ui <- fluidPage(
  tags$h1("Confirm sweet alert"),
  actionButton(
    inputId = "launch",
    label = "Ask a question"
  ),
  verbatimTextOutput(outputId = "res"),
  uiOutput(outputId = "count")
)

server <- function(input, output, session) {
  # Launch sweet alert confirmation
  observeEvent(input$launch, {
    confirmSweetAlert(
      session = session,
      inputId = "myconfirmation",
      type = "question",
      title = "Is Shiny the best R package ?",
      btn_labels = c("No", "Yes"),
      btn_colors = c("#d33", "#3085d6")
    )
  })
  
  # raw output
  output$res <- renderPrint(input$myconfirmation)
  
}

shinyApp(ui, server)
```

**Comment by DrumSergio** [comment]
Thank you very much! Highly appreciate it!
