### ISSUE TITLE
dropdown position with css

### ISSUE THREAD

**Issue by ghost** [dreamRs/shinyWidgets#170]
Hi Victor, 

i'm trying to set the left: 0px; top:0px to whatever position I need the panel of a dropdown() to be, but my attempts result in either NO effect, or the panel is open automatically. 
Do you know what syntax for the css to use to tagert the dropdown only when it is open, and still target a specific dropdown()? 

these attempts don't work at all for my dropdown called #OptionPanelRawPlot
#OptionPanelRawPlot .sw-show.sw-dropdown-content  {display: block; left: -650px; top: -20px;}
#OptionPanelRawPlot sw-dropdown-content animated sw-show  {display: block; left: -650px; top: -20px;}

and this does change the placing, but the panel is now open on start of my app: 
#sw-content-OptionPanelRawPlot  {display: block; left: -650px; top: -20px;}

**Comment by madmark81** [comment]
another question related to this one: I really like the "unite" style. Is there a way to apply this to regular actionButtons with some css in R Shiny?

**Comment by OliBravo** [comment]
You have to set the 'position' property first to be able to use left/top properties

**Comment by pvictor** [comment]
For the second question, there is a function `actionBttn` which is used by `dropdown`, see the gallery for examples.
