### ISSUE TITLE
More colors to progressBar()

### ISSUE THREAD

**Issue by mbacou** [dreamRs/shinyWidgets#172]
I would suggest adding CSS class `bg-{color}` in addition to `progress-bar-{status}` to progressBar() rendering. This would allow passing any Bootstrap color and not just 5 status?

Example:
```html
    <div class="progress-bar bg-teal" id="pbpaidout" role="progressbar" style="width:57%;"></div>
```
![image](https://user-images.githubusercontent.com/260325/55373148-450f3280-54d2-11e9-83cd-a2463861006a.png)

**Comment by pvictor** [comment]
I think those colors are only defined in AdminLte (so if you are using `shinydashboard`), this will not work in a classic Shiny app. Nonetheless I could had an argument to add a custom class, maybe it will make the current way to change color easier : 

````r
library("shiny")
library("shinyWidgets")

ui <- fluidPage(
  column(
    width = 7,
    tags$b("Default"), br(),
    tags$style(
      ".progress-bar-custom {background-color: #D7DF01}" # custom CSS
    ),
    progressBar(id = "pb1", value = 50, status = "custom"), # custom status
    sliderInput(
      inputId = "up1",
      label = "Update",
      min = 0,
      max = 100,
      value = 50
    )
  )
)

server <- function(input, output, session) {
  observeEvent(input$up1, {
    updateProgressBar(
      session = session,
      id = "pb1",
      value = input$up1
    )
  })
}

shinyApp(ui = ui, server = server)
```

Victor

**Comment by mbacou** [comment]
Thanks, yes I think that's a flexible approach.
