### ISSUE TITLE
press and hide airdatepicker icon (calendar)

### ISSUE THREAD

**Issue by omarbenites** [dreamRs/shinyWidgets#173]
Hey there,
First of all, thanks for the fantastic package, it really helps a lot!.
Regarding the issue

- Is there any way to click the calendar button and then show the calendar? Because you press the button but the calendar does not appear.
![image](https://user-images.githubusercontent.com/5264796/55445960-52382a00-5583-11e9-8d06-7ca5b4d471cc.png)

- In addition to this, Is there any way to hide the icon?

![image](https://user-images.githubusercontent.com/5264796/55446005-7b58ba80-5583-11e9-8c58-30f7953890e0.png)

Thanks in advance.

**Comment by pvictor** [comment]
Hi,
* Currently no, the button act like an `actionButton`, it's designed to validate the datre selected server side. But it must be possible to do that in JavaScript
* you can hide the button with `addon = "none"`

Victor
