### ISSUE TITLE
Multiple labels with material switch

### ISSUE THREAD

**Issue by kaushik12** [dreamRs/shinyWidgets#174]
Feature request: I'm wondering if it's possible to have a label on the left and right of the material switch. Currently only able to have it on one of the sides.

**Comment by pvictor** [comment]
Hi,
You can do that if you want both sides labels : put the `materialSwitch` into a tag div, set inline arg to `TRUE` and add your second label in a tag span. An example:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$h3("Material switch examples"),
  
  tags$div(
    materialSwitch(inputId = "switch1", label = "Night mode", inline = TRUE),
    tags$span("Day mode")
  ),
  
  verbatimTextOutput("value1")
  
)
server <- function(input, output) {
  
  output$value1 <- renderText({ input$switch1 })
  
}
shinyApp(ui, server)
```

Victor

**Comment by kaushik12** [comment]
Thank you!
