### ISSUE TITLE
Close and update button inside PickerInput 

### ISSUE THREAD

**Issue by Shivangi-Arora** [dreamRs/shinyWidgets#177]
I would like to have close and update button like select and deselect. Please find the below screenshot. Thankyou

![image](https://user-images.githubusercontent.com/49644551/56131881-4b0f1400-5fa6-11e9-83b2-57d09c7c877f.png)

**Comment by pvictor** [comment]
Hello,
Sorry that doesn't seems to be an option with the library : https://developer.snapappointments.com/bootstrap-select/

Victor
