### ISSUE TITLE
backdrop of dropdownbutton

### ISSUE THREAD

**Issue by ghost** [dreamRs/shinyWidgets#178]
Would it be a nice option to add a way to grayout the backdrop of the dialog windows of dropdownbutton and dropdown in the way sweetalert messages do this? I.e. put a gray transparant layer over the app behind the dialog window to draw focus to the dialog more? 

![image](https://user-images.githubusercontent.com/29946999/56247505-467d5500-60a5-11e9-9a80-8de0de58635e.png)

**Comment by pvictor** [comment]
That's not trivial, but you can lokk at : https://github.com/dreamRs/shinyWidgets/issues/223

Victor
