### ISSUE TITLE
Material Switch div error

### ISSUE THREAD

**Issue by rspreafico** [dreamRs/shinyWidgets#18]
Hi, the latest commit `b0286f78` produces an error with material switch widgets. Head of stack trace:

```
Warning: Error in .tag_validate: class is: form-group shiny-input-container material-switch, needs to be: form-group shiny-input-container
Stack trace (innermost first):
    121: .tag_validate
    120: shinyInput_label_embed
    119: function_list[[k]]
    118: withVisible
```

I do wrap widgets with `div()` so that I can use `shinyjs::reset()`. Thank you.

**Comment by pvictor** [comment]
Hi, i'm sorry for this, it's solved with the las commit.

**Comment by rspreafico** [comment]
Thanks so much for the quick fix!

**Comment by pvictor** [comment]
I added tests to avoid to broke it in the future.
Widgets concerned so far : `pickerInput`, `materialSwitch`, `switchInput`, `searchInput` and `awesomeCheckbox`.
