### ISSUE TITLE
input the multi-character or list from server.R to the 'choices' in pickerInput

### ISSUE THREAD

**Issue by 13479776** [dreamRs/shinyWidgets#183]
i want the application like this (adjusted example from issue #7): 
We can get the 'choices' value in pickerInput at UI.R from the server.R. I tried the renderText, but it does not work.

     library("shiny")
     library("shinyWidgets")

     ui <- fluidPage(
         tags$h2("Select countries to drill down"),
    
         dropdown(
        circle = TRUE, status = "default", icon = icon("sliders"), width = "300px",
        pickerInput(inputId = "Adverts",
                    label = "Countries",
                    **### choices = textOutput("count"),**
                    options = list(`actions-box` = TRUE, `live-search` = TRUE),
                    multiple = TRUE)
        ),
        verbatimTextOutput(outputId = "res")
        )

     server <- function(input, output, session) {

         **output$count <- renderText( "Turkey", "Saudi Arabia", "United Arab Emirates")**

         output$res <- renderPrint({
        input$Adverts
         })
      }

      shinyApp(ui = ui, server = server)

**Comment by pvictor** [comment]
Hello,

To update choices server-side, you should use `updatePickerInput`, e.g. : 

```r
library("shiny")
library("shinyWidgets")

ui <- fluidPage(
  tags$h2("Select countries to drill down"),
  
  dropdown(
    circle = TRUE, status = "default", icon = icon("sliders"), width = "300px",
    pickerInput(
      inputId = "Adverts",
      label = "Countries",
      choices = NULL,
      options = list(`actions-box` = TRUE, `live-search` = TRUE),
      multiple = TRUE
    )
  ),
  verbatimTextOutput(outputId = "res")
)

server <- function(input, output, session) {
  
  observe({
    updatePickerInput(
      session = session,
      inputId = "Adverts",
      choices = c("Turkey", "Saudi Arabia", "United Arab Emirates"),
      selected = "Turkey"
    )
  })
  
  output$res <- renderPrint({
    input$Adverts
  })
}

shinyApp(ui = ui, server = server)
```

Victor

**Comment by 13479776** [comment]
Hi Victor

Yes, it is fine.

However, i would like to observe a fold and and then read the files in the fold. The updatePickerInput can be  select the files for the next work.

I have tried the readDirectoryInput function in the shinyWidgets. I used the readDirectoryInput to selected the fold. But i could not send the files info into the updatePickerInput.

look like this.
          
         
        library("shiny")
       library("shinyWidgets")
       library(shinyDirectoryInput)

       ui <- fluidPage(
  
  
           #shiny-directory-input
          # Application title
            titlePanel("Directory Input Demo"),
            directoryInput('directory', label = 'selected directory', value = '~'),


               pickerInput(
               inputId = "myPicker", 
             label = "Select/deselect all + format selected", 
              choices = NULL, 
               options = list(
                `actions-box` = TRUE, 
                  size = 10,
                 `selected-text-format` = "count > 3"
               ), 
                   multiple = TRUE
              ),
                # ex1
   
               verbatimTextOutput(outputId = "res")
               )

             server <- function(input, output, session) {
  
             ###shiny-directory-input
             observeEvent(
             ignoreNULL = TRUE,
              eventExpr = {
                 input$directory
              },
                     handlerExpr = {
                     if (input$directory > 0) {
                       # condition prevents handler execution on initial app launch
                       path = choose.dir(default = readDirectoryInput(session, 'directory'),
                          caption="Choose a directory...")
                    updateDirectoryInput(session, 'directory', value = path)
                }
                }
                )
  
               updatePickerInput(
                         session = session,
                       inputId = "myPicker",
                       choices = c(basename(list.files(readDirectoryInput(session, 'directory'), pattern =                   "*.mzML$",full.names = T,recursive =TRUE))),
                     selected = ""
                   )
  
                 output$directory = renderText({
                    readDirectoryInput(session, 'directory')
                  })
  
           output$directory = renderText({
           readDirectoryInput(session, 'directory')
          })
  
           ## shinyWidgets box
          output$res <- renderPrint({
           input$myPicker
         })
        }

         shinyApp(ui = ui, server = server)

**Comment by pvictor** [comment]
Sorry that's not an issue with a function from the package. You should ask you're question on [Stackoverflow](https://stackoverflow.com/questions/tagged/r) or [RStudio Community](https://community.rstudio.com/).
