### ISSUE TITLE
checkboxGroupButtons looks strange with bs4Dash

### ISSUE THREAD

**Issue by artemklevtsov** [dreamRs/shinyWidgets#187]
`checkboxGroupButtons` looks strange with bs4Dash.

To reproduce: 
```r
library(shiny)
library(bs4Dash)
library(shinyWidgets)

shiny::shinyApp(
    ui = bs4DashPage(
        enable_preloader = TRUE,
        navbar = bs4DashNavbar(),
        sidebar = bs4DashSidebar(),
        controlbar = bs4DashControlbar(
            checkboxGroupButtons(inputId = "somevalue",
                                 label = "Make a choice: ",
                                 choices = c("A", "B", "C"))
        ),
        footer = bs4DashFooter(),
        title = "test",
        body = bs4DashBody()
    ),
    server = function(input, output) {}
)
```

Result:
![Peek 2019-05-25 23-02](https://user-images.githubusercontent.com/603798/58372007-55c3ae00-7f41-11e9-8a28-f8a25251c6b3.gif)

**Comment by pvictor** [comment]
Hello,
Thanks for reporting that. It was due to a missing class introduce in Bootstrap 4. Should looks fine now.
Poke @DivadNojnarg (for info).

Victor

**Comment by artemklevtsov** [comment]
Thank you for the quick reply and fix.

**Comment by DivadNojnarg** [comment]
thanks @pvictor. Yup with bootstrap 4 these class issues are to be expected. I will reference it in bs4Dash.
