### ISSUE TITLE
Does bootstrap have a reactive date picker? 

### ISSUE THREAD

**Issue by NBRAYKO** [dreamRs/shinyWidgets#19]
Do you think there's a way to add a`dateInput` picker to your package such that individual dates can use custom CSS to reactively show icons/specific values? 

I'm basically trying to create something like the Google flights calendar that shows a value associated with each date
![image](https://user-images.githubusercontent.com/5432686/31966746-ad975b7a-b8d9-11e7-81db-a96a7bbae711.png)

My plan for now is to use `renderUI` and change the CSS in one of your `pickerInput` select boxes. I'd love to contribute and create a proper calendar widget, but not even sure where to begin, have very limited `jQuery` knowledge.

**Comment by pvictor** [comment]
Hi, that will be an interesting widget for sure. I don't know if it's possible to do so with Bootstrap datepicker (implemented in `shiny`). Otherwise we need to find a JavaScript library which implement it, I'll search for one.

I've no immediate solution, sorry.

Victor
