### ISSUE TITLE
selectizeGroup: choose type of input per variable

### ISSUE THREAD

**Issue by Semafoor** [dreamRs/shinyWidgets#191]
Is it possible to add an extra variable in te params-list to select the type of filter?

For instance (in the small example below) to let year be filtered by a dateRange or sliderInput and the other variable filtered by pickerInputs?

I think this addition (allthough really hard to make) would be super useful for lots of people. 

`
library(shiny)
library(shinyWidgets)

data("mpg", package = "ggplot2")

ui <- fluidPage(
  fluidRow(
    column(
      width = 10, offset = 1,
      tags$h3("Filter data with selectize group"),
      panel(heading = 'blabla',
        selectizeGroupUI(inline = FALSE,
          id = "my-filters",
          params = list(
            manufacturer = list(inputId = "manufacturer", title = "Manufacturer:"),
            model = list(inputId = "model", title = "Model:"),
            year = list(inputId = "year", title = 'Year:'),
            trans = list(inputId = "trans", title = "Trans:"),
            class = list(inputId = "class", title = "Class:")
          )
        ), status = "primary"
      ),
      dataTableOutput(outputId = "table")
    )
  )
)

server <- function(input, output, session) {
  res_mod <- callModule(
    module = selectizeGroupServer,
    id = "my-filters",
    data = mpg,
    vars = c("manufacturer", "model", "trans", "class", "year")
  )
  output$table <- renderDataTable(res_mod())
}

shinyApp(ui = ui,
         server = server)

`

**Comment by pvictor** [comment]
Hello,

We have a shiny module in an other package that do what you want I think. The package is [esquisse](https://github.com/dreamRs/esquisse) and the module `filterDF_UI` / `filterDF`, an example : 

```r
library(shiny)
library(shinyWidgets)
library(ggplot2)
library(esquisse)


ui <- fluidPage(
  tags$h2("Filter data.frame"),
  
  radioButtons(
    inputId = "dataset", 
    label = "Data:",
    choices = c(
      "iris", "mtcars", "economics", 
      "midwest", "mpg", "msleep", "diamonds",
      "faithfuld", "txhousing"
    ),
    inline = TRUE
  ),
  
  fluidRow(
    column(
      width = 3,
      filterDF_UI("filtering")
    ),
    column(
      width = 9,
      progressBar(
        id = "pbar", value = 100, 
        total = 100, display_pct = TRUE
      ),
      DT::dataTableOutput(outputId = "table"),
      tags$p("Code dplyr:"),
      verbatimTextOutput(outputId = "code_dplyr"),
      tags$p("Expression:"),
      verbatimTextOutput(outputId = "code"),
      tags$p("Filtered data:"),
      verbatimTextOutput(outputId = "res_str")
    )
  )
)

server <- function(input, output, session) {
  
  data <- reactive({
    get(input$dataset)
  })
  
  res_filter <- callModule(
    module = filterDF, 
    id = "filtering", 
    data_table = data,
    data_name = reactive(input$dataset)
  )
  
  observeEvent(res_filter$data_filtered(), {
    updateProgressBar(
      session = session, id = "pbar", 
      value = nrow(res_filter$data_filtered()), total = nrow(data())
    )
  })
  
  output$table <- DT::renderDT({
    res_filter$data_filtered()
  }, options = list(pageLength = 5))
  
  
  output$code_dplyr <- renderPrint({
    res_filter$code$dplyr
  })
  output$code <- renderPrint({
    res_filter$code$expr
  })
  
  output$res_str <- renderPrint({
    str(res_filter$data_filtered())
  })
  
}

shinyApp(ui, server)
```

Victor
