### ISSUE TITLE
dropdown inside a container with overflow:hidden

### ISSUE THREAD

**Issue by stla** [dreamRs/shinyWidgets#195]
Hello,

 For some reason, I need to set the CSS property `overflow: hidden` to an element which contains a `dropdown`. I really need this CSS property, I cannot remove it. But then the dropdown panel is clipped by the container. Do you have an idea how to solve that ? Maybe I could solve this issue if it were possible to know whether the dropdown is open (by doing something similar to [this](https://stackoverflow.com/questions/31829312/bootstrap-dropdown-clipped-by-overflowhidden-container-how-to-change-the-conta), for the Bootstrap dropdown). Is it possible to know whether the dropdown is open ?

**Comment by stla** [comment]
>  Is it possible to know whether the dropdown is open ?

I found. I'm using the events `shown` and `hidden`. But my solution is not perfect. I remove the CSS property `overflow:hidden` when the dropdown is `shown`, and I put it back when `hidden`. I'm open to a better solution.

**Comment by stla** [comment]
I posted a similar issue on [stackoverflow](https://stackoverflow.com/questions/58691184/dropdown-clipped-by-the-sidebar-panel-when-using-a-scrollbar).

**Comment by pvictor** [comment]
Hello,
Not sure there's a better way than your JS solution...
