### ISSUE TITLE
sweetalert is not module-friendly

### ISSUE THREAD

**Issue by AshesITR** [dreamRs/shinyWidgets#196]
All sweetalert functions wich return an input value (such as `confirmSweetAlert()`) are not module friendly in the sense that `inputId` is used without checking for namespaces.

This causes "naive" programming to not work as expected within modules.

To fix this, the same approach as `shinyjs:::jsFuncHelper` choses is appropriate.
The following code chunk needs to be added to all sweetalert functions which handle an `inputId`:

```r
if (inherits(session, "session_proxy")) {
    inputId <- session$ns(inputId)
}
```

I can cook up a PR with the necessary changes if you want me to?

**Comment by pvictor** [comment]
Hello,
Yes, you're right, that's problematic. My only concern is that it will break existent code that already use namespace manually...
Maybe we should add a warning if we detect that `inputId` already contains the namespace.
Like `grepl(session$ns(""), inputId)`.
What do you think ?

**Comment by AshesITR** [comment]
Hi,
that sounds like a good idea, maybe issue a warning so the check can be removed sometime in the future.
NB we shoud use `startsWith()`. `grepl` is overkill here and may break if some of the parent modules have a whacky `id`. (try `"breaky{2}"` or something the like).
