### ISSUE TITLE
live version does not work

### ISSUE THREAD

**Issue by petermeissner** [dreamRs/shinyWidgets#2]
"Or see the live version here : https://dreamrs-vic.shinyapps.io/shinyWidgets/" ... link does not work

**Comment by pvictor** [comment]
Hello,

Sorry,  my shinyapps.io account is suspended for exceeded usage hours.

You can see the gallery like this : 

```
install.packages("shinyWidgets")
shinyWidgets::shinyWidgetsGallery()
```

Victor
