### ISSUE TITLE
Using dropdown with leaflet: Strange behavior of input widgets

### ISSUE THREAD

**Issue by markdumke** [dreamRs/shinyWidgets#20]
I get strange output when using dropdown with a leaflet map. The dropdown looks then something like this

![bug](https://user-images.githubusercontent.com/14176395/32148186-3b9872c0-bcf3-11e7-9fb3-dc5068cf291b.JPG)

`sliderInput `and `textInput `behave very strangely when I add a leaflet map.

This is the code:
```
library(shiny)
library(leaflet)
library(shinyWidgets)
ui <- fluidPage(
  tabsetPanel(
    tabPanel("Karte",
      leafletOutput("map", height = "150px"),
      dropdown(
        textInput("Art", label = "Art"),
        sliderInput("Jahr", "Jahr", min = 2010, max = 2017,
          value = c(2012, 2017))
      )
    )
  )
)

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet() %>% addTiles() %>% setView(11, 48, 12)
  })
}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Thanks for reporting that, I have the same behaviour, for me it only occurs : 

* in RStudio viewer, it works fine in Chrome or Firefox
* when combined with Leaflet, alone it works fine in RStudio viewer

There's maybe a CSS conflict or a browser compatibility issue, I'll try to identify the cause.

Victor

**Comment by pvictor** [comment]
Hi,
That's solved in Github version. It was caused by a weird behaviour of the CSS property `box-shadow`.
Thanks for reporting the issue.

Victor
