### ISSUE TITLE
SelectizeGroup Module - Select All Option

### ISSUE THREAD

**Issue by Gaurav9112** [dreamRs/shinyWidgets#200]
Hi Team,
Is there any functionality, where in we could add "Select All Option" as one of the options to select all records and filter other dimensions accordingly ?

Any help would be appreciated.

**Comment by pvictor** [comment]
Hello,

Selecting all choices is equivalent to select none, so if you don't make a selection in one of the selectize, all choices are avaible in the other ones. Can you clarify the functionality you want ?

Victor
