### ISSUE TITLE
pickerInput - control input box height to display multiple options

### ISSUE THREAD

**Issue by nik-maheshwari** [dreamRs/shinyWidgets#201]
So I am quite new to this library. I have a working Shiny app, and I want to use pickerInput instead of selectInput without changing the layout of my select box.

```
ui2 <- fluidPage(
  
  selectInput(inputId = "alpha",
              label = "Select an alphabet",
              c("A", "B", "C", "D", "E", "F", "G"), "", selectize = F, size = 4)
)

server2 <- function(input, output, session) {}

shinyApp(ui2, server2)
```

Using `selectize = F` and `size = 4`, I can control the height of the input box to show 4 options. I am trying to find the equivalent code/parameters in `pickerInput` options but have been unsuccessful. The only relevant parameter I came across was `options =  list(size = 4)` but this controls the scrolling, the input box still shows just one option.

Thanks.

**Comment by pvictor** [comment]
Hello,
That's not possible sorry, height is fixed. But you can control what is display inside : 

```r
library("shiny")
library("shinyWidgets")

ui <- fluidPage(
  br(),
  pickerInput(
    inputId = "p1",
    label = "Default",
    multiple = TRUE,
    choices = rownames(mtcars),
    selected = rownames(mtcars)[1:5]
  ),
  br(),
  pickerInput(
    inputId = "p1b",
    label = "Default with | separator",
    multiple = TRUE,
    choices = rownames(mtcars),
    selected = rownames(mtcars)[1:5],
    options = list(`multiple-separator` = " | ")
  ),
  br(),
  pickerInput(
    inputId = "p2",
    label = "Static",
    multiple = TRUE,
    choices = rownames(mtcars),
    selected = rownames(mtcars)[1:5],
    options = list(`selected-text-format`= "static",
                   title = "Won't change")
  ),
  br(),
  pickerInput(
    inputId = "p3",
    label = "Count",
    multiple = TRUE,
    choices = rownames(mtcars),
    selected = rownames(mtcars)[1:5],
    options = list(`selected-text-format`= "count")
  ),
  br(),
  pickerInput(
    inputId = "p3",
    label = "Customize count",
    multiple = TRUE,
    choices = rownames(mtcars),
    selected = rownames(mtcars)[1:5],
    options = list(
      `selected-text-format`= "count",
      `count-selected-text` = "{0} models choosed (on a total of {1})"
    )
  )
)

server <- function(input, output, session) {

}

shinyApp(ui = ui, server = server)
```

Victor

**Comment by yurasik2000** [comment]
Same problem. I have very long choises names. It would be nice if the input form was flexible and could hold all the data.

**Comment by hlendway** [comment]
Hi, my users have asked for that functionality but it would take up too much space on the page. Instead I edited the popup when you mouse over the input you’ll see each selected item on a new line. Here’s what I ended up with: https://github.com/dreamRs/shinyWidgets/issues/238
Maybe an interim solution?
