### ISSUE TITLE
Scroll bars not updating with updatePickerInput

### ISSUE THREAD

**Issue by tyluRp** [dreamRs/shinyWidgets#202]
I am running into an issue with `updatePickerInput()` and how the scroll bars are displayed. In short, I have an app that updates the choices in picker2 based on the choices from picker1. In this context, picker1 just represents the first picker input that users are meant to select choices from, picker2 is the second. I can get this to work with `renderUI()` but not `updatePickerInput()`. I originally used `renderUI()` but have since started using `updatePickerInput()` due to a delay in rendering the picker inputs. See the reproducible examples below:

### With `renderUI()`

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  uiOutput("somevalue1"),
  uiOutput("somevalue2")
)
server <- function(input, output, session) {
  observe({
    output$somevalue1 <- renderUI(
      pickerInput(
        inputId = "somevalue1",
        label = "somevalue1",         
        choices = 1:1000,
        multiple = TRUE,
        selected = NULL,
        options = list(
          `actions-box` = TRUE,
          size = 10,
          `selected-text-format` = "count > 3",
          `live-search` = TRUE
        )
      )
    )
  })
  
  observe({
    if (!is.null(input$somevalue1))
      choices <- which(input$somevalue1 %in% 1:1000)
    else
      choices <- 1:1000

    output$somevalue2 <- renderUI(
      pickerInput(
        inputId = "somevalue2",
        label = "somevalue2",         
        choices = choices,
        multiple = TRUE,
        selected = NULL,
        options = list(
          `actions-box` = TRUE,
          size = 10,
          `selected-text-format` = "count > 3",
          `live-search` = TRUE
        )
      )
    )
  })
}

shinyApp(ui, server)
```

### With `updatePickerInput()`

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  pickerInput(
    inputId = "somevalue1", 
    label = "somevalue1",         
    choices = NULL,
    multiple = TRUE,
    selected = NULL,
    options = list(
      `actions-box` = TRUE,
      size = 10,
      `selected-text-format` = "count > 3",
      `live-search` = TRUE
    )
  ),
  pickerInput(
    inputId = "somevalue2", 
    label = "somevalue2",         
    choices = NULL,
    multiple = TRUE,
    selected = NULL,
    options = list(
      `actions-box` = TRUE,
      size = 10,
      `selected-text-format` = "count > 3",
      `live-search` = TRUE
    )
  )
)
server <- function(input, output, session) {
  observe({
    updatePickerInput(
      session = session,
      inputId = "somevalue1",
      choices = 1:1000
    )
  })
  
  observe({
    if (!is.null(input$somevalue1))
      choices <- which(input$somevalue1 %in% 1:1000)
    else
      choices <- 1:1000
    
    updatePickerInput(
      session = session,
      inputId = "somevalue2",
      choices = choices
    )
  })
}

shinyApp(ui, server)
```

As you can see, the scroll bar doesn't update with `updatePickerInput()`, you can keep scrolling to reveal a bunch of blank choices. As far as I can tell, this seems to be due to the fact that the CSS property `margin-bottom` doesn't update. **What is really strange is that if you modify the choices to something much smaller `1:10` for example, the issue goes away.**

![Capture](https://user-images.githubusercontent.com/35909636/61249125-5d196380-a709-11e9-804d-58703940a08a.PNG)

**Comment by pvictor** [comment]
Hi,
Apparently this happens when option `virtualScroll` is enabled. It's fixed in the last update of the JS library, i will integrate it, meantime you can disable `virtualScroll` (it's automatically turn on when choices are large, that's why it work with `1:10` but not `1:1000`).

To disable it, use : 

```r
pickerInput(
  inputId = "somevalue2", 
  label = "somevalue2",         
  choices = NULL,
  multiple = TRUE,
  selected = NULL,
  options = list(
    `actions-box` = TRUE,
    size = 10,
    `virtual-scroll` = FALSE,  # <<<<====== here
    `selected-text-format` = "count > 3",
    `live-search` = TRUE
  )
)
```

**Comment by tyluRp** [comment]
Awesome, this has fixed the problem. Thank you!

**Comment by pvictor** [comment]
I have updated bootstrap-select library, so if you install dev version, you don't need ``virtual-scroll` = FALSE`.

Victor
