### ISSUE TITLE
airDatepickerInput makes other dateInput invisible

### ISSUE THREAD

**Issue by ColinFay** [dreamRs/shinyWidgets#204]
Hey folks, 

Here's a simple shiny app that allows to switch from a `shiny::dateInput` to a 
`shinyWidgets::airDatepickerInput`: 

``` r
library(shiny)
library(shinyWidgets)
ui <- function(request){
  fluidPage(
    selectInput("which", "aa", choices = c("a", "b")), 
    uiOutput("out"), 
    verbatimTextOutput("date")
  )
}

server <- function(input, output, session){
  ns <- session$ns
  observeEvent( input$which , {
    if (input$which == "a"){
      output$out <- renderUI({
        tagList(
          dateInput(
            "date_val",
            value = "",
            language = "fr",
            "Valeur"
          )
        )
      })
    } else {
      output$out <- renderUI({
        tagList(
          airDatepickerInput(
            "date_val",
            label = "Sélection :",
            range = TRUE,
            value =  c(Sys.Date(), 
                       Sys.Date() + lubridate::days(1))
          )
        )
      })
    }
    
  })
  
  
  output$date <- renderPrint({
    input$date_val
  })
  
}

shinyApp(ui, server)

```

Here's how to reproduce the bug: 

1. Launch the app, the `dateInput` is available
2. change for "b" in the `selectInput`, the `airDatepickerInput` is available
3. change back to "a", the `dateInput` is invisible, but I still can click inside an invisible frame under the selectInput and select a date

![airpickerbug](https://user-images.githubusercontent.com/17936236/61309606-c923c680-a7f2-11e9-8193-d7d55af27bf4.gif)

**Comment by pvictor** [comment]
Hey Colin,
There's a conflict between the JavaScript libraries behind each widget, you can't use both in same app.
I'll check if it's still true.

Victor

**Comment by ColinFay** [comment]
Thanks! 💪

I just noticed that I should have RTFM as it's written there... sorry. 
Closing then. 

Are you aware of any other conflicts in the package?
