### ISSUE TITLE
airdatepicker not rendering in modal

### ISSUE THREAD

**Issue by TFcfgo** [dreamRs/shinyWidgets#207]
Hey there,

wanted to use the airdatepickerInput within a modal. Unfortunately, it does not seem to render properly, the popup is rendered in the background only.

Here I have a minimal working example.

```r
library(shiny)
ui <- fluidPage(
    titlePanel("Old Faithful Geyser Data"),
    sidebarLayout(
        sidebarPanel(),
        mainPanel(
            actionButton("button", "Button")
        )
    )
)

server <- function(input, output) {
    observeEvent(input$button, {
        showModal(modalDialog(
            title = "Modal",
            shinyWidgets::airDatepickerInput(
                "date", 
                label = NULL, 
                clearButton = T,
                minDate = "2000-01-01", 
                maxDate = Sys.Date()
            )
        ))
    })
}
shinyApp(ui = ui, server = server)
```
Thanks for your great work with shiny!

**Comment by pvictor** [comment]
Hello Thomas,

Try to add this line somewhere in your UI : 

```r
tags$style(".datepicker { z-index: 9999 !important; }")
```

Modals in Bootstrap have a [z-index](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index) of `1050`, any value above should work.

Victor

**Comment by Bogaso** [comment]
Hi, is there any way to get the list of all classes that Shiny-widget uses?

**Comment by jordanwebb10** [comment]
Was there ever a fix for this? the recommendation didn't seem to fix the issue.
