### ISSUE TITLE
pickerinput focus -webkit-box-shadow:

### ISSUE THREAD

**Issue by rafaxalv** [dreamRs/shinyWidgets#208]
Hi, 

I have customized the standard inputs from shiny, using the following CSS:
```
                          .selectize-input.focus {
                           border-color:#FFD200;
                           outline: 0;
                           -webkit-box-shadow:0 0 3px rgba(255, 210, 0, 1) !important;
                           box-shadow:0 0 3px rgba(255, 210, 0, 1) !important;
                          }


                          .form-control:focus {
                           border-color:#FFD200;
                           outline: 0;
                           -webkit-box-shadow:0 0 3px rgba(255, 210, 0, 1) !important;
                           box-shadow:0 0 3px rgba(255, 210, 0, 1) !important;
                          }
```
The result is:
I want the box to have a glow when its selected
![image](https://user-images.githubusercontent.com/53751360/62454169-2072e200-b774-11e9-8173-48f3c0a9d0db.png)\

I need to do the same thing with the pickerinput. I have looked over the css on the source code and I tried several different things without the desirable result. Can someone help me here?

**Comment by pvictor** [comment]
Hello,
You can try with class `dropdown-toggle`. behind it's a button, so you probably do the same than yu do for `actionButton`.

Victor
