### ISSUE TITLE
Angle text on sliderTextInput

### ISSUE THREAD

**Issue by MeganStodel** [dreamRs/shinyWidgets#213]
Thanks for the great package!

I'm using `sliderTextInput`, which works well for my purposes, except that when there are a lot of labels, they either get way too small, or if the text size is increased they start to overlap and become unreadable. With `sliderInput`, some of the values would have their labels removed automatically, but this doesn't/can't happen with `sliderTextInput` because they conceptually don't have a numeric value so the unlabelled data would not be obvious. (Perhaps a different answer would be to have a way to hover over the input to see the labels at different ticks?)

Therefore, it would be useful to be able to change the orientation of the labels, so they are 45 or 90 degrees rotated and therefore not overlapping. 

I've got a SO question about this that includes reprex [here](https://stackoverflow.com/questions/57511430/avoid-overlapping-text-in-slidertextinput). 

Thanks!

**Comment by pvictor** [comment]
Hi,
You can rotate text with CSS like in the example below. But I need to look into the JavaScript to see how th choose which labels are displayed, this is for now automatic..

````r
library(shinydashboard)
library(shinyWidgets)
library(shiny)


ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    tags$head(tags$style(
      type = "text/css", 
      ".irs-grid-text {font-size: 12pt !important; transform: rotate(-90deg) translate(-30px);"
    )),
    fluidRow(
      box(uiOutput("month_selection"), height = "200px")
    )
  )
)

server <- function(input, output) {
  output$month_selection <- renderUI({
    sliderTextInput(
      inputId = "month_select",
      label = "",
      grid = TRUE, 
      force_edges = TRUE,
      choices = seq(from = as.Date("2017-01-01"), to = as.Date("2019-12-31"), by = 30)
    )
  })
  
}

shinyApp(ui, server)
```

Victor

**Comment by MeganStodel** [comment]
Thanks Victor!

A slightly strange side effect of that approach is that the first and last labels are shifted inwards for some reason - see here: 

![Screenshot of slider text with shifted labels](https://user-images.githubusercontent.com/16051791/63774100-6f73e900-c8d4-11e9-9430-5fc12f3fe048.png)

So in the above image, you can see that the first label 2017-01-01 is on the third tick mark, despite the label on the slider itself showing the correct position. The others are correctly spaced up until the last one, which is also shifted inwards. 

Do you know what might be causing that? Or how to avoid it?
