### ISSUE TITLE
pickerInput height

### ISSUE THREAD

**Issue by benmarchi** [dreamRs/shinyWidgets#214]
Is there any way of allowing the height of the pickerInput button to change based on the options selected? In particular, is it possible to specify a width for pickerInput, but have the height dynamically change similar to selectInput? Here is a minimal working example of the functionality I am trying to achieve. Notice how the height of the selectInput changes based on the number of items selected.

```
library("shiny")
library("shinyWidgets")

ui <- fluidPage(
  tags$head(tags$style(
    type = "text/css", 
    ".selectize-control.multi .selectize-input.has-items  {max-height: 200px; overflow-y: auto;}"
  )),
  br(),
  pickerInput(
    inputId = "p1",
    label = "Default",
    multiple = TRUE,
    choices = rownames(mtcars),
    selected = rownames(mtcars)[1:5],
    width = '300px'
  ),
  br(),
  selectInput(
    "states", 
    "States",
    rownames(mtcars),
    selected = rownames(mtcars)[1:5],
    width = '300px',
    multiple = TRUE
  )
)

server <- function(input, output, session) {
  
}

shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Hello,
No that's not possible with the [bootstrap-select](https://developer.snapappointments.com/bootstrap-select/) library. The `pickerInput` is in fact a button. Sorry

Victor
