### ISSUE TITLE
bsplus modals changes actionBttn appearance

### ISSUE THREAD

**Issue by tsolloway** [dreamRs/shinyWidgets#215]
We need to use persistent modals in our app, and appreciate the look and feel of your inputs. When we use bsplus' modals, it changes the actionBttn's appearance. Is there a solution?

Yes, we can use bs_button, but we use shinyWidgets throughout the app, and would prefer to not break from that look.

reprex:

```
library(shiny)
library(bsplus)

ui <- fluidPage(
  shinyWidgets::actionBttn(
    "foo1",
    label = "",
    icon = icon("edit")),
  shinyWidgets::actionBttn(
    "foo2",
    label = "",
    icon = icon("edit")) %>%
    bsplus::bs_attach_modal("foo2_modal"),
  bsplus::bs_modal(
    "foo_modal",
    title = "Title",
    body = NULL
  )
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Hello,

Seems to be an issue with {bsplus}, I made a pull request to fix it (https://github.com/ijlyttle/bsplus/pull/63)

Victor

**Comment by pvictor** [comment]
PR have been merged, please use dev version of {bsplus} to make it work : 

```r
devtools::install_github("ijlyttle/bsplus")
```
