### ISSUE TITLE
pickerInput

### ISSUE THREAD

**Issue by MartiusEduardo** [dreamRs/shinyWidgets#216]
Hi,

Is it possible I change the side of the tick (glyphicon-ok) of right side to left side? Before the names (choices)? Or insert a checkbox before the name because people that access the app from cell phones can't see the tick. In the pickerOptions there is a parameter called mobile, that I think is bugged. When I set mobile = TRUE the dropdown does not show for me.

`pickerInput("symbolsId",
                        choices = yahooTickers$Symbol,
                        multiple = TRUE,
                        options = pickerOptions(actionsBox = TRUE,
                                                liveSearch = TRUE,
                                                size = 10,
                                                title = "Selecione os tickers desejados",
                                                selectedTextFormat = "count > 4",
                                                noneSelectedText = "Nenhum ativo selecionado."),
                        choicesOpt = list(subtext = paste("", yahooTickers$Name, sep = " - ")),
                        selected = yahooTickers$Symbol[1])`

**Comment by pvictor** [comment]
Hello,
There's no options to allow this, but you can do it with CSS, e.g. : 

```r
library("shiny")
ui <- fluidPage(
  tags$style(
    ".bootstrap-select.show-tick .dropdown-menu .selected span.check-mark {left: 1px; right: auto !important}"
  ),
  pickerInput(
    inputId = "somevalue", 
    label = "A label", 
    choices = c("a", "b"), 
    options = pickerOptions(showTick = TRUE)
  ),
  verbatimTextOutput("value")
)
server <- function(input, output) {
  output$value <- renderPrint({ input$somevalue })
}
shinyApp(ui, server)
```

Victor
