### ISSUE TITLE
JS error (that breaks all subsequent javascript) when using useShinydashboardPlus()

### ISSUE THREAD

**Issue by daattali** [dreamRs/shinyWidgets#221]
When I call `useShinydashboardPlus()`, I get the following javascript error, which causes all subsequent javascript on the page to break:

```
Uncaught TypeError: Cannot read property 'left' of undefined
    at HTMLDocument.<anonymous> (sidebar.js:48)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.K (jquery.min.js:2)
```

**Comment by pvictor** [comment]
Hi,
Which version do you use ? I thought I had fixed this issue.

Victor

**Comment by daattali** [comment]
Ah I was going to open this issue earlier this week, looks like it was fixed in the version that hit CRAN just 3 days ago!
