### ISSUE TITLE
selectizeGroup does not accept variables with spaces

### ISSUE THREAD

**Issue by Stephonomon** [dreamRs/shinyWidgets#224]
I cannot get the function to accept variable names with spaces such as *"car manufacturer"*

See example

```
library(shiny)
library(shinyWidgets)
library(dplyr)

data("mpg", package = "ggplot2")

mpg <- mpg %>% 
    rename("car manufacturer" = manufacturer)

ui <- fluidPage(
    fluidRow(
        column(
            width = 10, offset = 1,
            tags$h3("Filter data with selectize group"),
            panel(
                selectizeGroupUI(
                    id = "my-filters",
                    params = list(
                        `car manufacturer` = list(inputId = " manufacturer", title = "Manufacturer:"),
                        model = list(inputId = "model", title = "Model:"),
                        trans = list(inputId = "trans", title = "Trans:"),
                        class = list(inputId = "class", title = "Class:")
                    )
                ), status = "primary"
            ),
            dataTableOutput(outputId = "table")
        )
    )
)

server <- function(input, output, session) {
    res_mod <- callModule(
        module = selectizeGroupServer,
        id = "my-filters",
        data = mpg,
        vars = c("manufacturer", "model", "trans", "class")
    )
    output$table <- renderDataTable(res_mod())
}

shinyApp(ui, server)

```

**Comment by pvictor** [comment]
Hi,
Argument `vars` from `selectizeGroupServer` must be a valid variable name, and match the inputId declared in `selectizeGroupUI`. Here you have two problems :

* a space in an inputId : `" manufacturer"`
* a variable `manufacturer` that doesn't exist anymore

Victor

**Comment by lucalamoni** [comment]
I have the same problem but I cannot make the example above work. Any advice?

**Comment by evgeniyftw** [comment]
The bug is there: when using data.frame column name with space (car manufacturer) the filters show that there are no values.
Here is the correct edited example to reproduce the issue:

library(shiny)
library(shinyWidgets)
library(dplyr)

data("mpg", package = "ggplot2")

mpg <- mpg %>% 
  rename("car manufacturer" = manufacturer)

ui <- fluidPage(
  fluidRow(
    column(
      width = 10, offset = 1,
      tags$h3("Filter data with selectize group"),
      panel(
        selectizeGroupUI(
          id = "my-filters",
          params = list(
            `car manufacturer` = list(inputId = "car manufacturer", title = "Manufacturer:"),
            model = list(inputId = "model", title = "Model:"),
            trans = list(inputId = "trans", title = "Trans:"),
            class = list(inputId = "class", title = "Class:")
          )
        ), status = "primary"
      ),
      dataTableOutput(outputId = "table")
    )
  )
)

server <- function(input, output, session) {
  res_mod <- callModule(
    module = selectizeGroupServer,
    id = "my-filters",
    data = mpg,
    vars = c("car manufacturer", "model", "trans", "class")
  )
  output$table <- renderDataTable(res_mod())
}

shinyApp(ui, server)
