### ISSUE TITLE
`shinyWidgets::airDatepickerInput` conflicts with `shiny::dateInput` calendar viewer

### ISSUE THREAD

**Issue by gabriel-msilva** [dreamRs/shinyWidgets#226]
There is a conflict when you load a `shinyWidgets::airDatepickerInput` and a `shiny::dateInput` on the same app. The calendar viewer of `shiny::dateInput` does not show -- it seems it is still there as the focus is on the `dateInput` and the mouse pointer changes on the "invisible" calendar area, but you cannot select a date.

I'm using the latest shinyWidgets from CRAN (v0.4.9), R v3.6.1 (64-bits) and RStudio (v. 1.2.1335, 64-bits). A minimal reprex below:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
    fluidRow(
        shiny::dateInput(
            "shiny_dateInput",
            "Date"
        ),
        
        shinyWidgets::airDatepickerInput(
            "widgets_airDatePicker",
            "Air Date"
        )
    )
)

server <- function(input, output) {
}

shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Hello,
Yes both widgets are incompatible, unfortunately you cannot use both... sorry

Victor
