### ISSUE TITLE
pickerInput label offset

### ISSUE THREAD

**Issue by benmarchi** [dreamRs/shinyWidgets#227]
I have been running into an issue where the label for `pickerInput` widgets have been displaying with an offset relative to the selection box. This appears to be due to an extra `<br>` being added after the label text (with `inline = FALSE`). This issue is complicated by my current workaround for getting standard widget labels to appear inline with their respective inputs. Removing all `<br>` with a jquery is not an option due to other layout requirements. I don't seem to be able to select just `pickerInput` objects and remove the inserted `<br>` after the label. The source for `pickerInput` does seem to be added a `<br>` by default, so I'm looking for a solution via jquery or a simple modification to the `pickerInput` function to allow the `<br>` to be removed to maintain proper alignment. Any help in figuring out this issue would be greatly appreciated.

Minimal working example

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$head(
    tags$style(type="text/css", "label{ display: table-cell; text-align: left; vertical-align: middle; } label.control-label { padding-right: 10px; margin-right: 10px;} .form-group { display: table-row; text-align: left;}")
  ),
  h3('Label offset'),
  pickerInput("in1", label = "Input 1", letters, width = '300px', inline = FALSE)
)

server <- function(input, output, session){
  
}

shinyApp(ui = ui, server = server)
```

jquery attempts

```javascript
$('#form-group').find('br').remove();
$('#shiny-input-container').find('br').remove();
$('#form-group shiny-input-container').find('br').remove();
$('br', '#form-group shiny-input-container').remove();​
```

**Comment by pvictor** [comment]
The `<br>` tag seems indeed useless here, I can remove it, just have to check that it doesn't alter appearance.

Victor
