### ISSUE TITLE
How to force dropdown click on page load

### ISSUE THREAD

**Issue by AlexSemenovIRL** [dreamRs/shinyWidgets#23]
Hi, love the package, use it a lot, thank you very much for creating it! I have a small issue where I need to force the `sw-dropdown` to click open on client visit as I have dependencies under `renderUI`. How can I achieve this? As can be seen from my example the `uiOutput("S1")` doesnt render until the `dropdown` is clicked, but  `uiOutput("S2")` does not.

```
library("shiny")
library("shinyWidgets")
ui <- fluidPage(
  dropdown(style = "unite", icon = icon("gear"),status = "danger", width = "300px",
    uiOutput("S1")
  ),
  uiOutput("S2")
)

server <- function(input, output, session) {
  output$S1 <- renderUI({
    radioGroupButtons("Species", label = "Species", choices = unique(iris$Species), status = "success")
  })
  output$S2 <- renderUI({
    radioGroupButtons("Species2", label = "Species2", choices = unique(iris$Species), status = "success")
  })
}
shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Hi,
Glad you like the package :)
With the last version, everything seems to works fine : 

![image](https://user-images.githubusercontent.com/4415580/32367008-d299c38c-c080-11e7-9d48-7914e76de2ba.png)

![image](https://user-images.githubusercontent.com/4415580/32367016-e051a0e4-c080-11e7-9fee-598ee8e1ce01.png)

You want that the dropdown appear open on page load, is that it ?

Victor

**Comment by AlexSemenovIRL** [comment]
Hi Victor thank you for the reply. Yes I wanted to manipulate the  `radioGroupButtons` on page load. I have moved the `dropdown` to `renderUI` and now it fires twice and this is the behaviour I want (once a `NULL` and then the value, as printed in the `observe` statement: Thank you again. you can now close the issue...

```
library("shiny")
library("shinyWidgets")
ui <- fluidPage(
  uiOutput("S1")
)

server <- function(input, output, session) {
  
  output$S1 <- renderUI({
    dropdown(style = "unite", icon = icon("gear"),status = "danger", width = "300px",
             radioGroupButtons("Species", label = "Species", choices = unique(iris$Species), status = "success"))
    
  })
  observe({
    print(input$Species)
  })
  
}
shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Ok! Sorry I misunderstood, cool solution!
