### ISSUE TITLE
airDatepickerInput() disabled calendar selector of dateInput()

### ISSUE THREAD

**Issue by tyizhou** [dreamRs/shinyWidgets#231]
When I have both dateInput and airDatepickerInput in one app, the calendar selector does not show for dateInput:
``` {r}
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  fluidRow(
    dateInput("dateinput","Date")
    ,airDatepickerInput("airdateinput","Date")
  )
)

server <- function(input,output){
  
}

runApp(shinyApp(ui,server))
```
with airDatepickerInput:
![image](https://user-images.githubusercontent.com/38633619/67401488-8589e700-f5af-11e9-96f8-93bb2d41bccd.png)
without airDatepickerInput:
![image](https://user-images.githubusercontent.com/38633619/67401540-95093000-f5af-11e9-908a-722a2db94122.png)

**Comment by pvictor** [comment]
Hello,
Unfortunately you can't use `dateInput` and `airDatepickerInput` in the same application...
There's a conflict between the 2 functions.

Victor

**Comment by tyizhou** [comment]
Hi Victor, I see, I will close the issue since you noticed the it.
