### ISSUE TITLE
updateMultiInput doesn't support UTF-8 characters

### ISSUE THREAD

**Issue by ehtmal** [dreamRs/shinyWidgets#232]
When CREATE **multiInput()** it work fine with unicode characters. But when you UPDATE using **updateMultiInput()** it won't support unicode characters.

**Create:**
`multiInput("testMultiInput", label = "Select Items", choices = c("小田", "若土"))`
**Evidence:**
_Multi Input show all Japanese characters_
![image](https://user-images.githubusercontent.com/17785585/67854798-956f7100-fb43-11e9-9835-d17b94ac46c7.png)

**Update:**
`updateMultiInput(session, "testMultiInput", choices = c("123小田abc", "123若土def"))`
**Evidence:**
_Multi Input remove all Japanese characters_
![image](https://user-images.githubusercontent.com/17785585/67854848-bc2da780-fb43-11e9-93ef-60cf96a2a42c.png)

As I have checked, other input have same issue.

**Comment by pvictor** [comment]
Hello,
I made a small change to preserve encoding, should work, can you try after installing dev version ?

```r
devtools::install_github("dreamRs/shinyWidgets")
```

Victor

**Comment by pvictor** [comment]
Closing this, I'm preparing an update, but can't guarantee when.
If you've seen this issue with other inputs, please open anoter issue.

Victor

**Comment by MislavSag** [comment]
I have the same problem with `selectizeGroupUI` function. It doesn't show utf-8 characters. I have installed latest version od the package.
