### ISSUE TITLE
progressBar depends on startsWith, but it's not available on R 3.2

### ISSUE THREAD

**Issue by stefanoborini** [dreamRs/shinyWidgets#234]
startsWith is not found. I suspect the requirement for R > 3.1.0 is wrong, as this function is not available in R 3.2

**Comment by pvictor** [comment]
Thanks for reporting that, i replaced `startsWith` by : 

```r
starts_with <- function(x, prefix) {
  substring(x, 1, nchar(prefix)) == prefix
}
```

Victor

**Comment by AshesITR** [comment]
Looks good:

https://stat.ethz.ch/R-manual/R-devel/library/base/html/startsWith.html

Details

startsWith() is equivalent to but much faster than

  substring(x, 1, nchar(prefix)) == prefix

**Comment by pvictor** [comment]
Thanks 👍 , closing now
