### ISSUE TITLE
default inital value for input with selectizeGroup

### ISSUE THREAD

**Issue by mfumagalli68** [dreamRs/shinyWidgets#235]
Hi.

I'm using `shinywidget` package and specifically `selectizeGroup-module`.
In the classic `selectizeInput ` function in Shiny we can specify a default value being display when the user open the app.

I'm wondering if something similar is going to be developed for `selectizeGroup`. 
I already posted a question on stackoverflow 

https://stackoverflow.com/questions/58628726/default-initial-value-for-input-with-selectizegroup?noredirect=1#comment103565012_58628726

**Comment by pvictor** [comment]
Hello,
Sorry that's not possible currently.

Victor

**Comment by ismirsehregal** [comment]
That would mean adding `selected` to the params list, right? I'd be interested too.
