### ISSUE TITLE
awesomeCheckboxGroup Bug with latest version

### ISSUE THREAD

**Issue by meganhartwell-stemcell** [dreamRs/shinyWidgets#24]
Hello, 
I love the package, it makes my apps look much more appealing, thank you for sharing it!
I updated to the latest version of shinyWidgets today (0.3.6) and the awesomeCheckboxGroup input is no longer returning anything if inline=FALSE. However if inline=TRUE it correctly returns the selections. I noticed this on my app as well as on shinyWidgetsGallery(). I believe this is probably a bug in the coding, though I also wondered if it was a conflict with one of my other packages? 

![image](https://user-images.githubusercontent.com/32854661/32351871-27343f12-bfdc-11e7-8c97-777336165d1e.png)

Thank you!

**Comment by pvictor** [comment]
Hi!
Glad to hear you like the package! I'm sure you make beautiful apps :)
You're right that's a bug, it's fixed on the Github version !
Thanks for reporting this!

Kind regards,

Victor

**Comment by meganhartwell-stemcell** [comment]
That's perfect! Thank you! And for your fast response
