### ISSUE TITLE
Options Group doesn't work for list with a vector of length 1

### ISSUE THREAD

**Issue by da11an** [dreamRs/shinyWidgets#240]
pickerInput(
   inputId = "Id082",
   label = "Options 
   choices = list(
      lower = c("a"),
      upper = c("A", "B", "C", "D"))
)
=================
Dropdown picker renders to:
-----
lower
-----
upper
   A
   B
   C
   D
-----

Comments:
"lower" should have an "a" under it

**Comment by pvictor** [comment]
You have to use a `list`, e.g. : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  pickerInput(
    inputId = "Id082",
    label = "Options",
    choices = list(
      lower = list("a"),
      upper = list("A", "B", "C", "D"))
  )
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```

See https://github.com/dreamRs/shinyWidgets/issues/77

Victor

**Comment by da11an** [comment]
This works! Thank you. However, it would be nice if a list of vectors worked the same as a list of lists. But if that isn't going to happen, it would be good if the example on http://shinyapps.dreamrs.fr/shinyWidgets/ (pickerInput > options group) used lists of lists rather than a list of vectors.

Thanks for the help!
