### ISSUE TITLE
updatePickerInput not working with shiny.port set

### ISSUE THREAD

**Issue by Eli-Berkow** [dreamRs/shinyWidgets#242]
Since the update to shinyWidgets 0.5.0 the below code does not seem to work. I am required to set the shiny.port for my application. Without the line `options(shiny.port = 3838)` it works.

```
library(shiny)
library(shinyWidgets)
options(shiny.port = 3838)
ui <- fluidPage(
    pickerInput(
        inputId = "myPicker", 
        label = "Select", 
        choices = ''
    )
)

server <- function(input, output, session) {
    updatePickerInput(session, "myPicker", choices = LETTERS)
}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Works fine for me. What's your environment ?

**Comment by Eli-Berkow** [comment]
Windows 10 and Chrome 78

**Comment by Eli-Berkow** [comment]
I have done some testing and it seems to be Chrome specific.

**Comment by pvictor** [comment]
Tested on Chrome 78.0.3904.108 with no troubles. Is there some JavaScript errors in the chrome console ?

**Comment by Eli-Berkow** [comment]
No JavaScript errors my side. That's really weird. Let me look into it a little more. Definitely a change from 0.4.9 to 0.5.0 and the more complicated example in my app occurs in Edge and IE as well.

**Comment by Eli-Berkow** [comment]
![image](https://user-images.githubusercontent.com/7531794/70131395-e9153300-168a-11ea-964e-17285acd1b6a.png)

**Comment by Eli-Berkow** [comment]
The above example is now working after I updated Chrome to 79. I will need to isolate the problem in my app.

**Comment by Eli-Berkow** [comment]
This example seems to be working now. My app is still problematic but I'll have to pinpoint the specific issue before reposting.
