### ISSUE TITLE
Element.remove polyfill bug

### ISSUE THREAD

**Issue by sgratzl** [dreamRs/shinyWidgets#243]
the polyfill implemented in the sweetalert binding is buggy:

https://github.com/dreamRs/shinyWidgets/blob/3d1785125cc67654fb672b2bf35b1120b699b7f5/inst/assets/sweetalert2/sweetalert-bindings.js#L80-L82

First, it should just override the method if it doesn't exist. Moreover, https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove suggests a polyfill which allows `parentElement` to be null whereas this implementation doesn't. Thus, it is not standard conform and does create problems.

**Comment by pvictor** [comment]
Hello,
Thanks, that's fixed.

Victor
