### ISSUE TITLE
verticalTabsetPanel in static flexdashboard - Error: path for html_dependency not provided

### ISSUE THREAD

**Issue by yogat3ch** [dreamRs/shinyWidgets#245]
Hi shinyWidgets crew,
I'm attempting to render some vertical tabs dynamically from a list object in a static flexdashboard doc. Reprex is below:
    ---
    title: "Untitled"
    output: 
      flexdashboard::flex_dashboard:
        orientation: rows
        vertical_layout: fill
    ---

    ```{r setup, include=FALSE}
    library(flexdashboard)
    library(shinyWidgets)
    library(htmltools)
    library(shiny)
    ```

    Coursework 
    =======================================================================

    ```{r}
    test <- list(Test1 = "Test", Test2 = "Test")
    ```

    ```{r}

    verticalTabsetPanel(selected = "Test1", contentWidth = 10,
      tagList(
        purrr::imap(test, ~ {
            verticalTabPanel(title = .y)
          })
      )
    )
    ```

I've tried adding all of the above to the setup chunk to no avail:
```
rmarkdown::html_dependency_jquery()
rmarkdown::html_dependency_bootstrap("spacelab")
rmarkdown::html_dependency_jqueryui()
```
Any ideas?

**Comment by pvictor** [comment]
Ah yes that was not intended to be used outside Shiny. I've modified JavaScript dependencies, this work now. But to properly generate the vertical tab panel, you should use something like : 

```r
tabs <- list(
  list(title = "Test 1", "Content 1"),
  list(title = "Test 2", "Content 2")
)

do.call(
  what = verticalTabsetPanel, 
  args = lapply(tabs, do.call, what = verticalTabPanel)
)
```

Victor

**Comment by yogat3ch** [comment]
Hi @pvictor,
Thanks for the response and for modifying the package to work in the static markdown context! This change definitely expands what's possible with the package!

Just in case anyone comes across this issue I'll summarize briefly the steps taken to get it to work. 
- Soft reset R (to unload packages) Ctrl-Shift-F10
- devtools::install_github("dreamRs/shinyWidgets")
- Close & open RStudio
- Clear the cache for the Knitr document
- Added the following Chunk

```
tabs <- purrr::imap(Coursework, ~{
    list(title = .y, .x)
  })
.args <- append(purrr::map(tabs, do.call, what = verticalTabPanel), list(color = "#6d94bf", contentWidth = 10))
do.call(what = verticalTabsetPanel, args = purrr::map(tabs, do.call, what = verticalTabPanel))
```
*Note* additional arguments to verticalTabsetPanel must be appended to the map/lapply call - simply wrapping the map call in a list() and adding the extra arguments to verticalTabsetPanel like this:
```
args = list(purrr::map(tabs, do.call, what = verticalTabPanel), color = "#6d94bf")
```
will not work.

Thank you for adding this functionality!
