### ISSUE TITLE
Get list of selected values from selectizeGroupUI 

### ISSUE THREAD

**Issue by delabj** [dreamRs/shinyWidgets#246]
Is there an easy way to get a list of selected variables from the lists created by selectizeGroupUI? 

I've tried using input$name_of_input but it always returns null in a renderPrint() 

```
     selectizeGroupUI(
                   id = "filters",
                   params = list(
                     SR = list(inputId = "super_region", title = "Super Region:"),
                     Reg = list(inputId = "region", title = "Region:"),
                     Turf = list(inputId = "turf", title = "Turf"),
                     Areas = list(inputId = "areas", title = "Areas:", multiple=TRUE)
                   ))
               ),
```

**Comment by pvictor** [comment]
Hi, that's a Shiny module, so you have to prefix `inputId` by module ID separate with `-`, e.g. for the first one : `input[["filters-super_region"]]`.

Victor

**Comment by delabj** [comment]
Looks like it works! Thanks so much, I'm just getting familiar with shiny extensions.
