### ISSUE TITLE
[question] Airdatepickerinput

### ISSUE THREAD

**Issue by Rasmusma1995** [dreamRs/shinyWidgets#247]
I hope it is okay that i post this question here. I've been looking for a solution for some time now, posted this question on servereal other sites and thus far i have come of short. 

I'm having some trouble getting the todaybutton in the shinywidget airdatepickerinput to work.

Is there a way to set value of the airdatepicker to Sys.time() when the todaybutton is clicked regardless of the current value?

Below you will find a simple example.

ui <- fluidPage(
  airDatepickerInput(
    inputId = "DateRange",
    value = Sys.time(),
    todayButton = T
  ),
  verbatimTextOutput("res_date")
)

server <- function(input, output, session) {
  output$res_date <- renderPrint(input$DateRange)
}

shinyApp(ui, server)

**Comment by pvictor** [comment]
Hi @Rasmusma1995 ,
I think that's a bug, I'll look into it.

Victor

**Comment by pvictor** [comment]
Hi,
Please re-install from GitHub, you can now use a `Date` in `todayButton`, it'll set the view of the calendar on the given date and select it. If you use `TRUE` it only set view (previous behavior).
Here an example : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  airDatepickerInput(
    inputId = "today",
    label = "Select today date:",
    todayButton = Sys.Date()
  ),
  verbatimTextOutput("res")
)

server <- function(input, output, session) {
  output$res <- renderPrint(input$today)
}

shinyApp(ui, server)
```

**Comment by Rasmusma1995** [comment]
Thanks!
