### ISSUE TITLE
[BUG] Issue with selected months

### ISSUE THREAD

**Issue by simon-tarr** [dreamRs/shinyWidgets#248]
I believe I've found a bug in the `airMonthpickerInput()` function in `shinyWidgets`. Rather than re-hash all of the issues here, I shall link to my StackOverflow post where user VictorP suggested I post here as a bug:

https://stackoverflow.com/questions/59580548/keep-current-month-selected-in-shinywidgetsairmonthinputpicker

If any further information is required, feel free to drop me a message.

**Comment by pvictor** [comment]
Thanks Simon for reporting the issue.
Two options solve it : 
* Use first date supplied in `value` argument to set the initial view
* Add an extra argument `startView` to set the view, with default to first element of `value` argument

What do you think ?

Victor

**Comment by simon-tarr** [comment]
Thanks for the reply @pvictor.
The extra argument `startView` sounds like a good way to proceed. I'm guessing it will be a reasonably easy fix?

**Comment by pvictor** [comment]
It's fixed, please re-install from GitHub and use : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  airMonthpickerInput(
    inputId = "select_month",
    label = "Select Month", 
    value = as.Date("2019-02-01"),
    startView = as.Date("2019-02-01")
  ),
  verbatimTextOutput("res")
)

server <- function(input, output, session) {
  output$res <- renderPrint(input$select_month)
}

shinyApp(ui, server)
```

If it's good for you, I let you close the issue and answer your question on Stackoverflow to get the points ;)

Victor

**Comment by simon-tarr** [comment]
Thank you Victor, really impressed with the quick bug fix here. Tested my end and all working fine, will close this issue now.
