### ISSUE TITLE
awesomeCheckboxGroup output = NULL when inline parameter set to FALSE

### ISSUE THREAD

**Issue by dStudio-git** [dreamRs/shinyWidgets#25]
Hi there,
Just found out that in latest release awesomeCheckboxGroup is giving NULL is set to FALSE.

**Comment by pvictor** [comment]
Hi,
This is referenced in issue [#24](https://github.com/dreamRs/shinyWidgets/issues/24), and solved in dev version. I'll put this soon on CRAN.

Victor
