### ISSUE TITLE
useTablerDash function in navbarPage

### ISSUE THREAD

**Issue by kaigu1990** [dreamRs/shinyWidgets#255]
Hi，I found a question in shinyWidgetss
When i use `useTablerDash()` and `navbarPage()`，the navbarpage would be abnormal.
For normal navbarpage is below:
![image](https://user-images.githubusercontent.com/22772592/75015210-0821a500-54c3-11ea-8c32-56b84e1b3d48.png)

But if i use `useTablerDash()` , the navbarpage would be:
![image](https://user-images.githubusercontent.com/22772592/75015280-31dacc00-54c3-11ea-890f-5be0ea6d5967.png)

The ui code is like

```
ui = tagList(
  useTablerDash(),
  navbarPage(
    ......
  )
)
```

Look forward your answer.
Thanks!

**Comment by pvictor** [comment]
Hum afraid, that Tabler Dash is incompatible with Bootstrap navbar, what functionnality of tabler are you interested in ?

Victor

**Comment by kaigu1990** [comment]
@pvictor Hi, Victor 
I want to use `tablerCard` function in navbar page, same as examples in https://dreamrs.github.io/shinyWidgets/reference/useTablerDash.html

Kai

**Comment by pvictor** [comment]
Ok thanks, maybe we can compile a version of tabler CSS without the navs. I'll look into into it.
Poke @DivadNojnarg (original author of the function)
