### ISSUE TITLE
updatePickerInput doesn't support UTF-8 characters

### ISSUE THREAD

**Issue by ehtmal** [dreamRs/shinyWidgets#256]
When CREATE **pickerInput()** it work fine with unicode characters. But when you UPDATE using **updatePickerInput()** it won't support unicode characters.

**Create code:**
`pickerInput("testPickerInput", label = "Select Items", choices = c("小田", "若土"))`
![image](https://user-images.githubusercontent.com/17785585/75127262-b9595280-56f0-11ea-9657-df23696713f5.png)

**Update code:**
`updatePickerInput(session, "testPickerInput", choices = c("小田", "若土"))`
![image](https://user-images.githubusercontent.com/17785585/75127417-8e233300-56f1-11ea-98ff-883a8767071f.png)

Related issue: #232

**Comment by pvictor** [comment]
Hello,
Thanks for reporting this, it should be fixed in dev version, can you try ?

Victor

**Comment by ehtmal** [comment]
Thank you very much @pvictor,
Yeah, I should check the dev version first. It worked as you said...

**Update code:**
`updatePickerInput(session, "testPickerInput", choices = c("123小田abc", "123若土abc"))`
![image](https://user-images.githubusercontent.com/17785585/75422255-b9668600-596e-11ea-8267-0d9eb0086927.png)

Next time I'll check the packages version first 😄
Sorry for all the trouble!

**Comment by pvictor** [comment]
I pushed a correction only after I saw your issue :sweat_smile: 
Glad it work :)
