### ISSUE TITLE
switchInput() does nor work under specific conditions

### ISSUE THREAD

**Issue by cvmartin** [dreamRs/shinyWidgets#26]
Hi; first of all, thank you very much for `shinyWidgets`; thanks to it I am building quite fast a rather complex website; first testing it locally, and then uploading the app to my own server in AWS. 

The thing is, I have observed that the function `switchInput()` not always work, and instead the website renders a default Shiny checkbox (that is not reactive; it can be checked / unchecked, but it doesn't trigger the desired action). 

After some experimentation, what I have observed is: 
- `switchInput()` does work locally, but not in the AWS server. I have tried with a couple of virtual machines, and the bug seems reproducible. 
- Also, to observe the malfunction of switchInput(), I have to run it in an AWS server AND inside a `renderUI()` function. If I code a `switchInput()` in `ui.R` instead that in `server.R`, everything is ok. 
- Last, it happens that the rest of the functions of `shinyWidgets `work perfectly, wheter in local or in the cloud, inside or outside `renderUI()`. I haven't been exhaustive, but dropdown menus, checkboxgroup or buttons do work. 

`materialSwitch()` also works fine, so I have a fancy substitute for `switchInput()`. Anyway, I thought that you would like to try to reproduce my observations.

**Comment by pvictor** [comment]
Hi!
Glad you find the package useful ! You can add a star to the package on Github ;)

There's an issue when initializing `switchInput` (and `pickerInput`) server-side (in `renderUI` for example). Try re-installing the package from Github, normally the `switchInput` is initialized, but there's a bug with the width...
I think that's because of HTML dependancies, i will try to fix it.

For the moment, you can use this workaround : add an hidden `switchInput` anywhere in your UI to force attaching dependancies : 

```r

library(shiny)
library(shinyWidgets)
ui <- fluidPage(
  br(),
  tags$div(
    style = "display: none;", switchInput(inputId = "for_dependancies")
  ),
  uiOutput(outputId = "test")
)

server <- function(input, output, session) {
  output$test <- renderUI({
    switchInput(inputId = "mySwitch", label = "Switch 2")
  })
}

shinyApp(ui, server)

```

Victor

**Comment by cvmartin** [comment]
Hi there, 

Indeed, reinstalling the package with `devtools::install_github("dreamRs/shinyWidgets")` worked fine. 
The trick of adding a `switchInput `hidden in the UI part didn't work before the reinstallation, and afterwards it wasn't necessary. 

Thanks for the prompt answer!

**Comment by pvictor** [comment]
Perfect! You're welcome :)
