### ISSUE TITLE
bookmarking dynamically created airDatepickerInput fields and reload previous selection

### ISSUE THREAD

**Issue by motyocska** [dreamRs/shinyWidgets#263]
Hello,

thought I post here to see if you have a thought on bookmarking airDatepickerInput fields and reload previously selected values on restore. I have gotten this far which will reload the number of fields but am stuck at reloading the original selections. Appreciate any input you may have:

library(shiny)
library(shinyWidgets)

ui = function(request) {
  fluidPage(
     headerPanel(" ",windowTitle = "Simulation"),    
    sidebarPanel(
      title = "test",
      id = "main",
      uiOutput("testUI"),
      tags$hr(),      
      tags$hr(),
      bookmarkButton(label = "Save profile") 
    ),
    mainPanel(
      tabsetPanel(type = "tabs")
    )
  )}

server <- shinyServer(function(session, input, output) {
  dabas <- reactiveValues(n = 0)  
  AllInputs<-reactive({
    x<-reactiveValuesToList(input) 
  })
  onBookmark(function(state) {
    state$values$n <- dabas$n
     })
  
  onRestore(function(state) {
    dabas$n <- state$values$n    
  })
  
  onRestored(function(state) {
    insertTextInput()
  })
  
  setBookmarkExclude(
    c("add_daba","rm_daba")
  )
    output$testUI <- renderUI({
    tagList(actionButton("add_daba", "Add daba"),
            actionButton("rm_daba", "Remove daba"),tags$hr(),insertTextInput())    
  })
    observeEvent(input$add_daba,{
    dabas$n <- dabas$n + 1
  })
   observeEvent(input$rm_daba,{
    if (dabas$n > 0) {
      dabas$n <- dabas$n - 1       }    
  })
  
  insertTextInput <- reactive({    
    n <- dabas$n
    if (n > 0) {
      isolate({
        lapply(seq_len(n), function(i) {
          airDatepickerInput(inputId=paste0("textin", i), label = paste0("daba# ",i),
                             placeholder="Click here",     update_on="change",addon='left', width='75%', autoClose=TRUE,startView=Sys.Date(), dateFormat="mm-dd-yy", multiple=1,timepicker =T, value = AllInputs()[[paste0("textin",i )]])
        })}) }
     })  
})

enableBookmarking(store = "url")
shinyApp(ui, server)

thank you,

Andras

**Comment by pvictor** [comment]
Hello,

Can you install from GitHub and retry ?

Victor

**Comment by motyocska** [comment]
Works well Victor, thanks for looking into it.
Andras 
    On Monday, March 30, 2020, 03:29:41 AM EDT, Victor Perrier <notifications@github.com> wrote:  
 
 


Hello,

Can you install from GitHub and retry ?

Victor

**Comment by pvictor** [comment]
Great! You're welcome!
