### ISSUE TITLE
Add custom date/time selection

### ISSUE THREAD

**Issue by stevesolun** [dreamRs/shinyWidgets#264]
I am trying to build a reminder view/app that will connect to my backend.

3 cases:

1) Choose range of dates with same time.
2) Choose random dates and attach time to each one.
3) Choose to use time picker only in AirDatepicker.

Please advise how can I do this? Maybe you can add such functionality.

**Comment by stevesolun** [comment]
@pvictor

**Comment by pvictor** [comment]
Hi,

I added `onlyTimepicker` to `airDatepickerInput()`, so now you can display only the time picker part, e.g. :

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  
  tags$br(),
  
  airDatepickerInput(
    inputId = "time",
    label = "Pick time:",
    timepicker = TRUE,
    onlyTimepicker = TRUE
  ),
  verbatimTextOutput(outputId = "resTime")
)


server <- function(input, output, session) {
  
  output$resTime <- renderPrint( input$time )
  
}


shinyApp(ui = ui, server = server)
```

Victor

**Comment by stevesolun** [comment]
@pvictor Thank you so much!
I need to reinstall the package?

**Comment by pvictor** [comment]
Yes you have to re-install from GitHub:

```r
devtools::install_github("dreamRs/shinyWidgets")
```

**Comment by stevesolun** [comment]
Thanks a lot!
Please advise how can I collect all these inputs and send them back to Python backend.
I will use it with Facebook messenger + webview.

**Comment by pvictor** [comment]
Sorry that's a little outside the scope of this package ^^
