### ISSUE TITLE
How can I select multiple times without calendar, multiple selection of times only?

### ISSUE THREAD

**Issue by stevesolun** [dreamRs/shinyWidgets#265]
Please advise how can I provide my users to select multiple times (10:00, 11:00, 12:34, ... 5pm, 2am ...)
within your date time picker.

**Comment by stevesolun** [comment]
@pvictor

**Comment by stevesolun** [comment]
@pvictor any ideas how can configure it? Please update if you can enable such functionality.

**Comment by pvictor** [comment]
Sorry `airDatepicker` is only made to select one date/time. What you are searching for is not easy and it raises some questions, how many time can a user choose ? Can a user select same time twice ? 
You can always wrap `airDatepickerInput` in a module and call it several times.

**Comment by stevesolun** [comment]
Actually it can be simple - multiple the time slots with a setting inside your function - for example 5 time slots where user can input time or make it like Outlook day pattern - where I can select multiple times.
I think Outlook or mail format of a day (and you can switch between days if needed with toggling the option on or off) will solve the issue.
Is it possible to do this? It will solve a lot of issues!
