### ISSUE TITLE
pickerInput/multiInput `actions-box` select default

### ISSUE THREAD

**Issue by kda-xyt** [dreamRs/shinyWidgets#269]
Hi,
thanks for building this package it's very helpful!
I am wondering if there is an option to go back to the default (in `selected`) in the actions-box for `pickerInput`?

And is there a way to get a similar actions-box in `multiInput`?

thank you

**Comment by pvictor** [comment]
Sorry, there's no automated way to do this, you'll have to implement yourself with `actionButton` and update methods. If you struggle to do this, post an example, I'll help you.

Victor
