### ISSUE TITLE
downloadBttn is only clickable on the label

### ISSUE THREAD

**Issue by Ljupch0** [dreamRs/shinyWidgets#271]
Hi, and thank you for the great package.

I am using downloadButtn with `block=TRUE` argument, with which I am stretching the button to fill the box it is in. However even though the button stretches, the only clickable part is the label of the button. Is there an easy way to stretch the link to cover the entire button and not just the label?

The exact button 
```downloadBttn(outputId = "filtered_csv", label = "Download CSV", style = "material-flat", color = "primary", size="sm", block = TRUE)```

Thanks a lot!

**Comment by pvictor** [comment]
Hello,

Thanks, you're welcome :)

Yes this is confusing for users, I updated the function, if you re-install from GitHub, the whole button is clickable, e.g.:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$h2("Download bttn"),
  downloadBttn(
    outputId = "downloadData",
    style = "bordered",
    color = "primary", 
    block = TRUE
  )
)

server <- function(input, output, session) {
  
  output$downloadData <- downloadHandler(
    filename = function() {
      paste('data-', Sys.Date(), '.csv', sep='')
    },
    content = function(con) {
      write.csv(mtcars, con)
    }
  )
  
}

shinyApp(ui, server)
```

Victor

**Comment by Ljupch0** [comment]
Works! Small issue: When `color="primary"` the color of the button label is not white and hard to read. Fixed with a little css.

**Comment by pvictor** [comment]
Great! Ah yes, I fixed that on GitHub, this should be fine now:

![image](https://user-images.githubusercontent.com/4415580/82239006-6e8a5800-9938-11ea-9df2-cb1edf112d9a.png)
