### ISSUE TITLE
updateRadioGroupButtons only updates first input when called twice in server

### ISSUE THREAD

**Issue by Metlover** [dreamRs/shinyWidgets#272]
Really perplexing behavior. I have two different `radioGroupButtons` on one page, and a button that is designed to clear the inputs of both groups, using `updateRadioGroupButtons` for both inputs. When I push the button, only the first input is cleared - the first being the first `updateRadioGroupButtons` referenced in the `observeEvent`. Snippet attached:

    library(shiny)
    library(shinyWidgets)
    ui <- fluidPage(
      br(),
      actionButton(
        inputId = "bttn1",
        label = "Clear",
        color = "primary",
        style = "bordered"
      ),
      br(),
      br(),
      fluidRow(
        column(
          width = 6,
          radioGroupButtons(
            inputId = 'choiceA',
            label = 'CHOICE A',
            choices = c('Option 1', 'Option 2', 'Option 3'),
            selected = character(0),
            justified = TRUE,
            direction = 'vertical',
            width = '100%'
          )
        ),
        column(
          width = 6,
          radioGroupButtons(
            inputId = 'choiceB',
            label = 'CHOICE B',
            choices = c('Option 1', 'Option 2', 'Option 3'),
            selected = character(0),
            justified = TRUE,
            direction = 'vertical',
            width = '100%'
          )
        )
      )
    )
    server <- function(input, output, session) {
      observeEvent(input$bttn1, {
        updateRadioGroupButtons(
          session,
          inputId = 'choiceA',
          label = 'CHOICE A',
          choices = c('Option 1', 'Option 2', 'Option 3'),
          selected = character(0)
        )
        updateRadioGroupButtons(
          session,
          inputId = 'choiceB',
          label = 'CHOICE B',
          choices = c('Option 1', 'Option 2', 'Option 3'),
          selected = character(0)
        )
      })
    }
    shinyApp(ui = ui, server = server)

Note that swapping the order of the `updateRadioGroupButtons` for choiceA and choiceB affects the behavior of this snippet, where choiceB is cleared but choiceA is not.

**Comment by pvictor** [comment]
Hello,
Yes radios buttons weren't supposed to be resettable, there was a JavaScript error.
I changed this behavior, if you re-install from GitHub, your example should work.

Victor

**Comment by Metlover** [comment]
Perfect! Thank you so much.
