### ISSUE TITLE
awesomeCheckboxGroup issue with observeEvent

### ISSUE THREAD

**Issue by mmoralesIG** [dreamRs/shinyWidgets#273]
Hi, 
I had this awesomeCheckboxGroup inside a DropDownMenu, which is itself inside a Box. The selected items are meant to react with a map (a googlemap). In RStudio worked fined, but when I published the app, it didn't reacted. I changed to a regular selectinput and worked as expected.
So, sadly I had to remove the awesomeCheckboxGroup, but I would wish to use it in the future.
(My shinyWidget version is 0.5.0)
Thank you

**Comment by pvictor** [comment]
Hello,

Mmmmh weird, were there any errors in the JavaScript console? What do you use to deploy applications ? Can you provide an example ?

Victor

**Comment by pvictor** [comment]
Please reopen if you have an example of incorrect behavior.

Victor
