### ISSUE TITLE
airDatepickerInput airDatepickerInput previous inputs cover calendar ("autocomplete")

### ISSUE THREAD

**Issue by mgei** [dreamRs/shinyWidgets#283]
Is there a way to turn off the recommendations from previous selections (autocomplete). They just cover up the nice calendar selection. I don't think there is any benefit from ever having the recommendations displayed.

I have this problem in Chrome browser.

![coveredup](https://user-images.githubusercontent.com/32815823/82798793-53a86e00-9e79-11ea-8ff8-75ee8b3f7998.png)

--------
**edit**

I found a solution that seems to work for now. I added `timepickerOpts = timepickerOptions(list(autocomplete = "new-date-time"))`

```
airMonthpickerInput("period_overall", "Periode wählen", 
                    value = (as.Date(floor_date(Sys.Date(), unit = "month")) - months(2)),
                    min = as.Date("2018-01-01"),
                    max = as.Date(Sys.Date()),
                    range = F, 
                    width = "100%", 
                    timepickerOpts = timepickerOptions(list(autocomplete = "new-date-time")),
                    addon = "none", language = "de")
```
Chrome seems to sometimes ignore `autocomplete = off` according to https://github.com/wagtail/wagtail/issues/5528

**Comment by pvictor** [comment]
Hi, 
Yes that's Chrome autocomplete, I added `autocomplete="off"`, try re-installing from Github : 

```r
devtools::install_github("dreamRs/shinyWidgets")
```

and tell me if it works

Victor

**Comment by pvictor** [comment]
Hello,
Is the issue fix for you ? You can install from CRAN now.

Victor

**Comment by mgei** [comment]
Hello Victor, sorry yes, thanks for the fix :)
