### ISSUE TITLE
Datetimerange on the same date

### ISSUE THREAD

**Issue by tobiasdirksen** [dreamRs/shinyWidgets#284]
I would like to be able to select a datetimerange on the same date, e.g., today from 02:00–02:30. However, when I click on the same date twice it gets deselected. I suggest that when a date is clicked on twice it's regarded as a range, but third time it gets deselected or reselected.

**Comment by pvictor** [comment]
Hello,

That's not doable with `airDatepicker` for the moment, there will be only one timepicker visible under the calendar.
The only way I see to do that, is a datepicker to select the date combined with two `airDatepickerInput(onlyTimepicker = TRUE)` to choose start and end time.

Best,

Victor
