### ISSUE TITLE
Updating icons with 'updateNumericInputIcon'

### ISSUE THREAD

**Issue by SigurdJanson** [dreamRs/shinyWidgets#293]
In issue "updateNumericInputIcon #278" you encouraged us to request a feature that allows updating the icon of a `numericInputIcon`. Hereby, I want to do this.

If I may add a general coment: in my opinion the `numericInputIcon` is treated a bit like an orphan. I think is is a real important widget, e.g. to display a unit along with the number. That is a very common use case, at least for me. But the widget is not part of the demo (http://shinyapps.dreamrs.fr/shinyWidgets/) which makes it hard to find. Thanks for the good work, anyway.

**Comment by pvictor** [comment]
Hello,
That's done for `updateNumericInputIcon`, I have to do the same thing for `updateTextInputIcon`.

Yes not all widgets are in the gallery, I haven't updated it since a while, this is on my todo list, but don't have the time right now...

VIctor
