### ISSUE TITLE
Change color of dropdownButton

### ISSUE THREAD

**Issue by rrpaleja** [dreamRs/shinyWidgets#296]
Hello,

I'm hoping this issue is easy to resolve and the real issue is just my poor css skills. I am trying to change the color of the dropdownButton to a custom color. In this example, it can be black. I set up the dropdownButton as follows:

`
dropdownButton(
                      circle = TRUE, status = "myClass", icon = NULL, width = "400px",
                      tooltip = NULL
                    )
`

Then, I inserted the following:

`tags$head(tags$style(".btn-myClass {color: #000000 !important;}"))`

which did nothing. My guess is that I made an error on the css side. Would you be able to help me out?

Thanks!

**Comment by pvictor** [comment]
Hello,

CSS propertie `color` is for coloring content and you have nothing in your button ;)

Try this:

```r
library(shiny)
library(shinyWidgets)
ui <- fillPage(
  titlePanel("Hello Shiny!"),
  tags$head(tags$style(
    ".btn-myClass { color: blue; background-color: red ; }",
    ".btn-myClass:hover { color: red; background-color: blue ; }"
  )),
  dropdownButton(
    circle = TRUE, 
    status = "myClass", 
    icon = icon("home"), 
    width = "400px",
    tooltip = NULL 
  )
)
server <- function(input, output) {

}
shinyApp(ui = ui, server = server)
```

Victor

**Comment by rrpaleja** [comment]
Ah perfect! @pvictor thank you so much 👍
