### ISSUE TITLE
formatting pip numbers to include a decimal with noUiSliderInput

### ISSUE THREAD

**Issue by tnelsen** [dreamRs/shinyWidgets#298]
I am trying to use noUiSliderInput to create a slider with pips showing a decimal 0.5 as shown below.

pips: {
        mode: 'values',
        values: [0, 0.5, 2, 5, 10, 20, 50],
        format: wNumb({
            decimals: 1
        })
    }

Right now,

noUiSliderInput(inputId = "id", 
        label = "label", 
        value = 10, 
        min = 0, 
        max = 50, 
        tooltips = TRUE, 
        pips = list(mode = "values", 
                         values = c(0, 0.5, 2, 5, 10, 20, 50)),
        step = 0.5, 
        format = wNumbFormat(decimals = 1))

results in the 0.5 being rounded to 1. 

![image](https://user-images.githubusercontent.com/22464223/87187091-7663da00-c2a1-11ea-83fb-4670a7297bee.png)

Is there a way to include the format option in the noUiSliderInput pip list or another way to stop the rounding of the pip values?

**Comment by pvictor** [comment]
Hello,

Install dev version with :

```r
devtools::install_github("dreamRs/shinyWidgets")
```

Then you can use `format` to format pips:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  noUiSliderInput(
    inputId = "id",
    label = "label",
    value = 10,
    min = 0,
    max = 50,
    tooltips = TRUE,
    pips = list(
      mode = "values",
      values = c(0, 0.5, 2, 5, 10, 20, 50),
      format = wNumbFormat(decimals = 1),
      size = 2 # 1 (large) or 2 (small)
    ),
    step = 0.5,
    format = wNumbFormat(decimals = 1),
    width = "100%"
  ),
  verbatimTextOutput("res")
)

server <- function(input, output, session) {
  output$res <- renderPrint({
    input$id
  })
}

shinyApp(ui, server)
```

Note that format is applied to all pips labels.

VIctor

**Comment by tnelsen** [comment]
Thanks! That works wonders.
