### ISSUE TITLE
 airDatepickerInput should display start and end time in range-timepicker mode

### ISSUE THREAD

**Issue by holgerbrandl** [dreamRs/shinyWidgets#299]
Consider the following example

```
library(shiny)
library(shinyWidgets)

# ui ----

ui <- fluidPage(
airDatepickerInput(
inputId = "range",
label = "Select range of dates:",
timepicker = TRUE,
range = TRUE,
value = c(Sys.time()-7, Sys.time())
),
verbatimTextOutput(outputId = "res_range")
)

# server ----

server <- function(input, output, session) {
    output$res_range <- renderPrint( str(input$range) )
}

# app ----

shinyApp(ui = ui, server = server)
```

This code runs but does not produce the expected result: `range` and `timePicker` do not play nicely together because the widget is always showing *just* the time of one range endpoint, that is either start or end. 
![image](https://user-images.githubusercontent.com/200952/87315273-96ef9680-c524-11ea-96db-22900dc7f91d.png)

It would be better if both times could be shown together as for instance in the bootstrap example http://www.daterangepicker.com/#example2

Another, bug (imho) is that the widget in the configuration from above does not allow to select a date-time range on the same day, which seems a legit use case when analyzing time-series.

**Comment by pvictor** [comment]
Hello,
I agree this will be nice, but it's currently not supported by [air-datepicker](https://github.com/t1m0n/air-datepicker), there's discussion to implement it, so maybe possible in a near future.

Victor

**Comment by holgerbrandl** [comment]
Do you think it would make sense to submit the request there first?

**Comment by pvictor** [comment]
You can comment this issue : https://github.com/t1m0n/air-datepicker/issues/8
It's implemented on this branch : https://github.com/t1m0n/air-datepicker/tree/multiple-cals

Maintainer of the project have started to refactor the widget last week in this branch : https://github.com/t1m0n/air-datepicker/tree/v3.0.0

I don't know what his plans are for the inclusion of multiple calendars, but it is a possibility.

**Comment by holgerbrandl** [comment]
Isn't this ticket more about multiple month? I'm more concerned about setting a time range on the same day.

**Comment by raine-bianchini** [comment]
I also seem unable to select a timerange on the same day (even with toggleSelected = F, which seems to be what that flag is supposed to handle). Is there any update on this?
