### ISSUE TITLE
Disable downloadBttn as you can actionBttn

### ISSUE THREAD

**Issue by mcsiple** [dreamRs/shinyWidgets#301]
Hi shinyWidgets folks,

Thanks for making some great features. I would love to be able to use `shinyjs` (or something similar) to disable a `downloadBttn` in the same way that you can with an `actionBttn` (related to #68). 

I want my `downloadBttn` to be functional only if a set of conditions are met in my server logic (one related to input, another related to the value of a reactive object). I am sure this will also come in handy for lots of users building apps with downloaded reports-- it will help to do quality control before the report can be downloaded. 

Thank you so much in advance.

**Comment by pvictor** [comment]
Hello,

Thanls for your kind words :) 

To disable `downloadBttn` you need to paste `"_bttn"` at the end of the `outputId` used in `enable` / `disable`, that's because the actual download button is wrap into an other button (the bttn button). An example: 

```r
library(shiny)
library(shinyWidgets)
library(shinyjs)

ui <- fluidPage(
  useShinyjs(),
  tags$h2("Download bttn"),
  downloadBttn(
    outputId = "downloadData",
    style = "bordered",
    color = "primary"
  ),
  checkboxInput("disable", "Disabled?", value = FALSE)
)

server <- function(input, output, session) {
  
  output$downloadData <- downloadHandler(
    filename = function() {
      paste('data-', Sys.Date(), '.csv', sep='')
    },
    content = function(con) {
      write.csv(mtcars, con)
    }
  )
  
  observeEvent(input$disable, {
    if (input$disable) {
      disable(id = "downloadData_bttn")
    } else {
      enable(id = "downloadData_bttn")
    }
  })
}

shinyApp(ui, server)
```

Victor

**Comment by mcsiple** [comment]
Thank you Victor! This answers my question.
