### ISSUE TITLE
airDatepickerInput issues

### ISSUE THREAD

**Issue by tanthiamhuat** [dreamRs/shinyWidgets#302]
https://community.rstudio.com/t/airdatepickerinput-issues/73747

I must say this airDatepickerInput from shinyWidgets is a fantastic tool. It allows us to pick both date and time specifically.

But recently, when I test with it, I have some issue. When you want to select its Hour and Minute on the below of the two horizontal lines, if you "CLICK" either of them individually at one time, it is perfectly OK. It changes accordingly to what is desired.

Now, on either of the Hour or Minute line, if you "DRAG" one of them from one point to another point, the weird behaviour comes. It cannot decide which one to go to, and will toggle (or move forward and backward) between them. And it is quite annoying.

Does anyone face that issue before? Or can anyone just test it out? What are the settings to solve this issue?
Thanks.

**Comment by pvictor** [comment]
Hello,

Can you provide a minimal reproducible example where it's not working ? And include the browser used and your session info., thanks.

These examples works fine for me with CRAN version (0.5.3) :

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  airDatepickerInput(
    inputId = "datetime",
    label = "Pick date and time:",
    timepicker = TRUE
  ),
  verbatimTextOutput(outputId = "res_datetime"),
  
  airDatepickerInput(
    inputId = "time",
    label = "Pick time:",
    timepicker = TRUE,
    onlyTimepicker = TRUE
  ),
  verbatimTextOutput(outputId = "res_time")  
)

server <- function(input, output, session) {
  output$res_datetime <- renderPrint( input$datetime )
  output$res_time <- renderPrint( input$time )
}

shinyApp(ui, server)
```

Victor

**Comment by tanthiamhuat** [comment]
> ```r
> library(shiny)
> library(shinyWidgets)
> 
> ui <- fluidPage(
>   airDatepickerInput(
>     inputId = "datetime",
>     label = "Pick date and time:",
>     timepicker = TRUE
>   ),
>   verbatimTextOutput(outputId = "res_datetime"),
>   
>   airDatepickerInput(
>     inputId = "time",
>     label = "Pick time:",
>     timepicker = TRUE,
>     onlyTimepicker = TRUE
>   ),
>   verbatimTextOutput(outputId = "res_time")  
> )
> 
> server <- function(input, output, session) {
>   output$res_datetime <- renderPrint( input$datetime )
>   output$res_time <- renderPrint( input$time )
> }
> 
> shinyApp(ui, server)
> ```

Thanks Victor for your kind reply. I confirm it is on my side issue, which I have used "updateAirDateInput" inside a reactive context which causes this weird behaviour. We can effectively close the case. Thanks.

**Comment by tanthiamhuat** [comment]
But it is nevertheless interesting for your side to investigate why CLICK is not having issue, but DRAG is having that annoying behaviour. Thank You. And I do not see why putting inside a reactive context will cause issue for DRAG and not for CLICK.
