### ISSUE TITLE
Problems with rendering color choices in spectrumInput

### ISSUE THREAD

**Issue by fpsanz** [dreamRs/shinyWidgets#305]
I think I found a bug in the current version of spectrumInput, which didn't happen before. When I render a spectrumInput the color circles overlap.  Checking html code, I have noticed that the span tag of the second color appears as a child of the span tag of the first one, that's why it overlaps. If I edit the html by hand I get it right. I attach html code.

<span title="rgb(0, 0, 0)" data-color="rgb(0, 0, 0)" class="sp-thumb-el sp-thumb-dark sp-thumb-active">
  <span class="sp-thumb-inner" style="background-color:rgb(0, 0, 0);"></span>
  <span title="rgb(255, 0, 0)" data-color="rgb(255, 0, 0)" class="sp-thumb-el sp-thumb-light">
    <span class="sp-thumb-inner" style="background-color:rgb(255, 0, 0);"></span>
  </span>
</span>

regards

**Comment by pvictor** [comment]
Thanks for reporting that, that's fixed in dev version, please re-install from GitHub.

Victor
