### ISSUE TITLE
awesomecheckbox prints label in bold

### ISSUE THREAD

**Issue by bklingen** [dreamRs/shinyWidgets#307]
After updating to shiny version 1.5.0 and using shinyWidgets 0.5.3, I noticed that the label for an `awesomeCheckbox` is now printed in bold. Before it was in regular font, which I would prefer.

```{r}
library(shiny)
library(shinyWidgets)
ui <- fluidPage(
  awesomeCheckbox("check1", "This is now printed in bold")
)

server <- function(input, output) {}

shinyApp(ui = ui, server = server)
```
![image](https://user-images.githubusercontent.com/4784206/89449641-ad6ec380-d759-11ea-856c-dfd7b1735b3d.png)

**Comment by bklingen** [comment]
Inidentially, using `prettyCheckbox`, the label is not printed in bold:
```{r}
library(shiny)
library(shinyWidgets)
ui <- fluidPage(
  prettyCheckbox("check1", "This is NOT printed in bold")
)

server <- function(input, output) {}

shinyApp(ui = ui, server = server)

```

![image](https://user-images.githubusercontent.com/4784206/91332062-9c820280-e799-11ea-9ff4-18a12c53d122.png)

**Comment by pvictor** [comment]
Thanks for reporting this, should be fixed on dev version, please re-install from GitHub.

Victor

**Comment by bklingen** [comment]
Great, thanks, works as previously when installing the dev version.
