### ISSUE TITLE
Can't close pickerInput menu unless pressing Esc or double-clicking outside

### ISSUE THREAD

**Issue by vituri** [dreamRs/shinyWidgets#309]
I can't close the pickerInput dropdown menu, no matter where I click. The only two things that do the trick are double-clicking really fast outside the menu, or pressing Esc. If I just click outside the menu one time, it blinks and reappear. The same when I click in the "header" of the menu (the place where you click for the first time so it can open).

I use this package since long time ago, and didn't have this problem before. I tried different versions (including the github one) and updated shiny. The previous behaviour was closing the menu when clicking outside it.

Here is an example.

```
if (interactive()) {

  library(shiny)
  library(shinyWidgets)

  ui <- fluidPage(
    tags$h2("Select / Deselect all"),
    pickerInput(
      inputId = "p1",
      label = "Select all option",
      choices = rownames(mtcars),
      multiple = TRUE,
      options = list(`actions-box` = TRUE)
    ),
    verbatimTextOutput("r1"),
    br(),
    pickerInput(
      inputId = "p2",
      label = "Select all option / custom text",
      choices = rownames(mtcars),
      multiple = TRUE,
      options = list(
        `actions-box` = TRUE,
        `deselect-all-text` = "None...",
        `select-all-text` = "Yeah, all !",
        `none-selected-text` = "zero"
      )
    ),
    verbatimTextOutput("r2")
  )

  server <- function(input, output, session) {

    output$r1 <- renderPrint(input$p1)
    output$r2 <- renderPrint(input$p2)

  }

  shinyApp(ui = ui, server = server)

}
```

Here is a gif showing the situation.

![click-test-2020-08-17-112906](https://user-images.githubusercontent.com/56522687/90407827-546a2e00-e07d-11ea-8d77-6ba25af97760.gif)

**Comment by pvictor** [comment]
I can't reproduce this bug... Which browser do you use ? Is there any errors in the JavaScript console ?

Victor

**Comment by micahwilhelm** [comment]
I'm also experiencing this problem. Did you find a solution or workaround, @pvictor ?
Browser:

> Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)


R session info:

> R version 3.6.3 (2020-02-29)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 20.04.1 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
>  [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] shiny.i18n_0.1.0   rgdal_1.4-8        raster_3.3-13      sp_1.4-2           plotly_4.9.2.1     ggplot2_3.3.2      leaflet_2.0.3.9000
>  [8] lubridate_1.7.9    dplyr_1.0.1        shiny_1.5.0.9001  
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.5                    lattice_0.20-40               tidyr_1.1.1                   leaflet.providers_1.9.0       shinyWidgets_0.5.3           
>  [6] assertthat_0.2.1              digest_0.6.25                 mime_0.9                      R6_2.4.1                      plyr_1.8.6                   
> [11] leaflet.extras_1.0.0          evaluate_0.14                 httr_1.4.2                    pillar_1.4.6                  bsplus_0.1.2                 
> [16] rlang_0.4.7                   lazyeval_0.2.2                rstudioapi_0.11               data.table_1.13.0             geosphere_1.5-10             
> [21] rmarkdown_2.3                 shinyjs_2.0.0                 stringr_1.4.0                 htmlwidgets_1.5.1             munsell_0.5.0                
> [26] tinytex_0.25                  compiler_3.6.3                httpuv_1.5.4                  xfun_0.15                     pkgconfig_2.0.3              
> [31] htmltools_0.5.0.9000          tidyselect_1.1.0              tibble_3.0.3                  codetools_0.2-16              fansi_0.4.1                  
> [36] viridisLite_0.3.0             crayon_1.3.4                  withr_2.2.0                   later_1.1.0.1                 grid_3.6.3                   
> [41] jsonlite_1.7.0                xtable_1.8-4                  gtable_0.3.0                  lifecycle_0.2.0               magrittr_1.5                 
> [46] scales_1.1.1                  cli_2.0.2                     stringi_1.4.6                 promises_1.1.1                ellipsis_0.3.1               
> [51] vctrs_0.3.2                   generics_0.0.2                RColorBrewer_1.1-2            tools_3.6.3                   glue_1.4.1                   
> [56] purrr_0.3.4                   crosstalk_1.1.0.1             leaflet.minicharts_0.6.1      fastmap_1.0.1                 yaml_2.2.1                   
> [61] colorspace_1.4-1              shinydashboardPlus_0.7.5.9000 shinydashboard_0.7.1          knitr_1.29

**Comment by pvictor** [comment]
Hello,

Never encounter this bug...

Do you have the same problem with this application -> https://dreamrs.shinyapps.io/shinyWidgets309/

My session info is:

```r
- Session info ------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  French_France.1252          
 ctype    French_France.1252          
 tz       Europe/Berlin               
 date     2020-09-23                  

- Packages ----------------------------------------------------------------------------------------------------------------------------------------------------
 package      * version date       lib source        
 askpass        1.1     2019-01-13 [1] CRAN (R 3.6.2)
 assertthat     0.2.1   2019-03-21 [1] CRAN (R 3.6.2)
 cli            2.0.2   2020-02-28 [1] CRAN (R 3.6.3)
 crayon         1.3.4   2017-09-16 [1] CRAN (R 3.6.2)
 curl           4.3     2019-12-02 [1] CRAN (R 3.6.2)
 digest         0.6.25  2020-02-23 [1] CRAN (R 3.6.2)
 evaluate       0.14    2019-05-28 [1] CRAN (R 3.6.2)
 fansi          0.4.1   2020-01-08 [1] CRAN (R 3.6.2)
 fastmap        1.0.1   2019-10-08 [1] CRAN (R 3.6.2)
 glue           1.4.2   2020-08-27 [1] CRAN (R 3.6.3)
 htmltools      0.5.0   2020-06-16 [1] CRAN (R 3.6.3)
 httpuv         1.5.4   2020-06-06 [1] CRAN (R 3.6.3)
 jsonlite       1.7.1   2020-09-07 [1] CRAN (R 3.6.3)
 knitr          1.29    2020-06-23 [1] CRAN (R 3.6.3)
 later          1.1.0.1 2020-06-05 [1] CRAN (R 3.6.3)
 magrittr       1.5     2014-11-22 [1] CRAN (R 3.6.2)
 mime           0.9     2020-02-04 [1] CRAN (R 3.6.2)
 openssl        1.4.2   2020-06-27 [1] CRAN (R 3.6.3)
 promises       1.1.1   2020-06-09 [1] CRAN (R 3.6.3)
 R6             2.4.1   2019-11-12 [1] CRAN (R 3.6.2)
 Rcpp           1.0.5   2020-07-06 [1] CRAN (R 3.6.3)
 rlang          0.4.7   2020-07-09 [1] CRAN (R 3.6.3)
 rmarkdown      2.3     2020-06-18 [1] CRAN (R 3.6.3)
 rsconnect      0.8.16  2019-12-13 [1] CRAN (R 3.6.3)
 rstudioapi     0.11    2020-02-07 [1] CRAN (R 3.6.2)
 sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 3.6.2)
 shiny        * 1.5.0   2020-06-23 [1] CRAN (R 3.6.3)
 shinyWidgets * 0.5.3   2020-06-01 [1] CRAN (R 3.6.3)
 withr          2.2.0   2020-04-20 [1] CRAN (R 3.6.3)
 xfun           0.16    2020-07-24 [1] CRAN (R 3.6.3)
 xtable         1.8-4   2019-04-21 [1] CRAN (R 3.6.2)
 yaml           2.2.1   2020-02-01 [1] CRAN (R 3.6.2)
```

**Comment by vituri** [comment]
@pvictor Sorry for being late,

yes, I had this issue even when accessing your shinyapp here: http://shinyapps.dreamrs.fr/shinyWidgets/

I solved it by uninstalling all shiny and html-related packages and reinstalling them (the CRAN version). Not sure what was the problem or why these packages bugged the pickerinput in your shinyapp (in Chrome).
