### ISSUE TITLE
pickerInput title in html within choicesOpt disappears

### ISSUE THREAD

**Issue by Fideldue** [dreamRs/shinyWidgets#313]
I was using `choicesOpt` option quite frequently especially because it was an easy way to provide mouse overs to the different items in the `pickerInput` via a defined "title". Unfortunately it is not working any more, the last working version should be `0.4.3`. So is this a bug or intended? 

See example code for the problem:

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(

    # title mouse over ('n1', 'n2', 'n3') works in ‘0.4.3’
    # won't in the later version
    pickerInput("test", 
                choices = list("miau" = c("Miau1" = 1, "miau2" = 2, "miau3" = 3)),
                choicesOpt = list(content = list(
                    "<div style=\"display:inline-block\" title = \"n1\">Miau1</div>", 
                    "<div style=\"display:inline-block\" title = \"n2\">Miau2</div>",
                    "<div style=\"display:inline-block\" title = \"n3\">Miau3</div>"))
                )
)

server <- function(input, output) {

}

shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Hello,

Yes apparently custom content is sanitized and title attribute are striped, you can enable them with this JavaScript snippet:

```js
var myDefaultWhiteList = $.fn.selectpicker.Constructor.DEFAULTS.whiteList;
// To allow div elements with title attribute
myDefaultWhiteList.div = ['title'];
```

Tell me if you need to include this in your app.

Victor

**Comment by Fideldue** [comment]
Managed to include the snippet into my app and it works now - great thanks!
