### ISSUE TITLE
awesomeCheckboxGroup choice text is bold

### ISSUE THREAD

**Issue by ctpickard** [dreamRs/shinyWidgets#314]
After the update to `awesome checkbox` and `awesome radio` label `font-weight` in 0.5.2 ([commit](https://github.com/dreamRs/shinyWidgets/commit/e98b5bd1cd9ba55a1fab4f5f687d4cb5e63f1622)), the choice labels are now defaulted to bolded. If I try to override the `font-weight` it results in the icons turning into squares. Is there a way to keep the choices at a normal `font-weight`, but not lose the icons?

Here is a simple, reproducible example:
```
ui = shiny::fluidPage(
  shinyWidgets::awesomeCheckboxGroup(
    inputId  = "Id044",
    label    = "Checkboxes", 
    choices  = c("A", "B", "C"),
    selected = "A"
  )
)
server = function(input, output, session){ }
shiny::shinyApp(ui, server)
```

Image:
<img width="417" alt="Screen Shot 2020-09-01 at 4 57 50 PM" src="https://user-images.githubusercontent.com/20569748/91917261-466afe80-ec74-11ea-8e37-367fbb7b43b5.png">

Ideally, it would like the appearance of what is shown on the [demo site](http://shinyapps.dreamrs.fr/shinyWidgets/):
<img width="514" alt="Screen Shot 2020-09-01 at 5 00 19 PM" src="https://user-images.githubusercontent.com/20569748/91917388-a06bc400-ec74-11ea-9813-b8fa7645e9fd.png">

**Comment by pvictor** [comment]
Hello,

See https://github.com/dreamRs/shinyWidgets/issues/307, re-install from GitHub, should be ok

Victor

**Comment by ctpickard** [comment]
Ah, thank-you @pvictor! Should have done a more thorough review of other issues. Thanks for the response and will make sure to do that.
