### ISSUE TITLE
style placeholder for pickerInput

### ISSUE THREAD

**Issue by AlexanderBartholomaeus** [dreamRs/shinyWidgets#316]
I did not find a way to color the placeholder. Is there something similar to the  `choicesOpt`?

**Comment by pvictor** [comment]
Maybe you can look at https://github.com/dreamRs/shinyWidgets/issues/286

**Comment by AlexanderBartholomaeus** [comment]
Thank you! Strange that I could not find this via google ... tried hard for more than 2 hours, but sometimes the search terms are just wrong.
