### ISSUE TITLE
Options group error: "All sublists must be named"

### ISSUE THREAD

**Issue by kaijagahm** [dreamRs/shinyWidgets#317]
Hi there,
I have a question related to #240. I have grouped options in a pickerInput where some of the groups only have one item in them. I originally had code like this:

```
library(shiny)
library(shinyWidgets)
library(dplyr)

df <- data.frame(group = c("A", "A", "A", "B", "C", "C"), name = c("Mary", "Lina", "Peter", "Naomi", "Sam", "Ashley")) %>%
  mutate(name = as.character(name))

choicesList <- df %>%  # this returns a list of *vectors*, not a list of lists.
  split(., .[, "group"]) %>%  # split each group into a different list item
  lapply(., function(x) x %>% pull(name))# grab only the names

ui <- fluidPage(
  pickerInput(
    inputId = "id",
    label = "Select a person:",
    choices = choicesList)
)
server <- function(input, output, session) {
}
shinyApp(ui, server)
```
I ran into the same problem as described in #240: if there's a group with only one name in it, the name doesn't show up in the pickerInput.

After reading the answer to that issue, I decided that I needed to convert each item of choicesList into a list, instead of a vector. So I changed the choicesList part of the code above to this:
```
choicesList <- df %>%  # this returns a list of *lists*
  split(., .[, "group"]) %>%  # split each group into a different list item
  lapply(., function(x) x %>%  pull(name))# grab only the names
  lapply(., list) # make each item into a list
```

I thought this would work. However, when I tried to run the app, I got the following error:
```
Error in (function (choice, name)  : 
  All sub-lists in "choices" must be named.
```

I didn't really understand what was wrong, but I played around with it and ended up assigning names to each sub-list, like this:
```
choicesList <- df %>%  # this returns a list of *lists*
  split(., .[, "group"]) %>%  # split each group into a different list item
  lapply(., function(x) x %>%  pull(name))# grab only the names
  lapply(., list) # make each item into a list
for(i in 1:length(choicesList)){
  names(choicesList[[i]]) <- names(choicesList)[i]
}
```
Now, when I looked at the choicesList object, all of the sub-lists were named. I thought this would solve the issue.

However, now, when I run the code, I still get only the group names showing up for the lists of 1, instead of the people's names. It looks like this: 
![Screen Shot 2020-09-16 at 14 18 27](https://user-images.githubusercontent.com/37053323/93376370-7e9f3f00-f827-11ea-84ea-0a0007f65917.png)

So, we seem to be back to the original problem. I can't figure out what I'm doing wrong. Note that I need to automate the creation of the choicesList object because it's going to vary depending on earlier user input, so I can't go the route of manually writing out the `choices = list(list())` argument as shown in #240.

Thank you in advance for any help you can give!
Full reproducible example after adding the for-loop above:
```
library(shiny)
library(shinyWidgets)
library(dplyr)

df <- data.frame(group = c("A", "A", "A", "B", "C", "C"), name = c("Mary", "Lina", "Peter", "Naomi", "Sam", "Ashley")) %>%
  mutate(name = as.character(name))

choicesList <- df %>% 
  split(., .[, "group"]) %>%  # split each group into a different list item
  lapply(., function(x) x %>% pull(name)) %>%# grab only the names
  lapply(., list)
for(i in 1:length(choicesList)){
  names(choicesList[[i]]) <- names(choicesList)[i]
}
ui <- fluidPage(
  pickerInput(
    inputId = "id",
    label = "Select a person:",
    choices = choicesList)
)
server <- function(input, output, session) {
}
shinyApp(ui, server)
```

**Comment by kaijagahm** [comment]
And of course, I figured this out almost immediately after posting it. The problem was that the line `lapply(., list)` just takes each vector and makes it into a single list element, instead of separating out the elements of each vector into list items. I should instead have done `lapply(., as.list)` and skipped the naming for-loop. 

Minimal example that works as intended:

```
library(shiny)
library(shinyWidgets)
library(dplyr)

df <- data.frame(group = c("A", "A", "A", "B", "C", "C"), 
                             name = c("Mary", "Lina", "Peter", "Naomi", "Sam", "Ashley")) %>%
  mutate(name = as.character(name))

choicesList <- df %>% 
  split(., .[, "group"]) %>%  
  lapply(., function(x) x %>% pull(name)) %>%
  lapply(., as.list) # the key is to use `as.list` instead of `list` here

ui <- fluidPage(
  pickerInput(
    inputId = "id",
    label = "Select a person:",
    choices = choicesList)
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```

Resulting UI:
![Screen Shot 2020-09-16 at 14 38 25](https://user-images.githubusercontent.com/37053323/93378323-49e0b700-f82a-11ea-9052-72ab2ea72719.png)

I hope this helps someone else someday!

**Comment by pvictor** [comment]
Glad you found the solution, thank you for the detailed issue, as well as the answer, I'm sure it will help another user!

Victor
