### ISSUE TITLE
progressBar update w/ total does not work anymore

### ISSUE THREAD

**Issue by Gutschlhofer** [dreamRs/shinyWidgets#318]
What used to work previously and does not now is updating the progressBar by passing not only the `value` but also a `total`. This happens, when there is no `total` set when initializing the progressBar in `ui`. Workarounds: calculate the percentage manually or add the `total` also in the `ui`.

Here is a repex where the updating fails and it stays at 0%:

```R
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  actionButton(inputId = "go", label = "Start"),
  shinyWidgets::progressBar(id = "pb", value = 0, display_pct = TRUE)
)

server <- function(input, output, session) {
  
  observeEvent(input$go, {
    
    shinyWidgets::updateProgressBar(session = session, id = "pb", value = 0)
    
    for (i in 1:10) {
      updateProgressBar(session = session, id = "pb", value = 100/10*i, total = 100)
      
      Sys.sleep(.5)
    }
    
  })
  
}

shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Thanks that's fixed, please re-install from GitHub.

Victor
