### ISSUE TITLE
Supported icons in actionBttn?

### ISSUE THREAD

**Issue by thercast** [dreamRs/shinyWidgets#32]
I really like the `actionBttn` you've implemented in this great package, and I'd like to add an icon to the left of the label from [font awesome](http://fontawesome.io/icons/) like I can with the typical shiny `actionButton`.  But when I supply the `icon` parameter with a value, it just shows the icon text and not the actual icon.  I'm trying to put a [rocket](http://fontawesome.io/icon/rocket/) icon and tried the two methods below with no success.  Any suggestions on how to get an icon to properly appear?  I'm using version `0.3.6` from CRAN.

```r
# first try: no fa- prefix
actionBttn(inputId = "execProcess",
label = "Launch",
icon = "rocket",
style = "gradient",
color = "primary",
size = "md",
no_outline = FALSE)

# second try: fa-prefix
actionBttn(inputId = "execProcess",
label = "Launch",
icon = "fa-rocket",
style = "gradient",
color = "primary",
size = "md",
no_outline = FALSE)
```

**Comment by pvictor** [comment]
Hi!
Glad you like `actionBttn` ! This is a nice library, don't hesitate to add a star to the [bttn.css repo](https://github.com/ganapativs/bttn.css) !

To add an icon on the button, you need to use `icon` like this : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  br(),
  actionBttn(
    inputId = "execProcess",
    label = "Launch",
    icon = icon("rocket"),
    style = "gradient",
    color = "primary",
    size = "md",
    no_outline = FALSE
  )
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```

The result looks like : 

![image](https://user-images.githubusercontent.com/4415580/33034985-e4d9f7f4-ce29-11e7-842b-fa72e76408ef.png)

Victor
