### ISSUE TITLE
awesomeCheckbox doesn't allow status = "default"

### ISSUE THREAD

**Issue by trafficonese** [dreamRs/shinyWidgets#320]
The documentation of `awesomeCheckbox` says the value of `status` must be one of:

> default, primary, info, success, warning, danger.

But using `default` will result in an error:

> 'arg' should be one of “primary”, “success”, “info”, “warning”, “danger”

**Comment by pvictor** [comment]
Thanks, I added the possibility to set the status as default.

Victor
