### ISSUE TITLE
progressSweetAlert sometimes doesn't work

### ISSUE THREAD

**Issue by ArthurPERE** [dreamRs/shinyWidgets#321]
Hello, 

I really don't know what happen but sometimes the progressSweetAlert doesn't appear (or work i don't know). But I have some error and warning in the dev tools of my browser. 

```
Warning : The selector you chose ("#placeholder-916835") could not be found in the DOM. shinyapp.js:679:14
Warning : The selector you chose ("#sweet-alert-progress-sw") could not be found in the DOM. shinyapp.js:679:14
Error : Uncaught TypeError: a is null                      shinyWidgets-bindings.min.js:1:21910
    <anonymous> shinyWidgets-bindings.min.js:1
    _sendMessagesToHandlers shinyapp.js:529
    <anonymous> shinyapp.js:640
    _sendMessagesToHandlers shinyapp.js:529
    dispatchMessage shinyapp.js:515
    onmessage shinyapp.js:112
Warning : Erreur dans les liens source : Error: request failed with status 404
URL de la ressource : http://127.0.0.1:3839/shinyWidgets/selectPicker/js/bootstrap-select.min.js
URL du lien source : bootstrap-select.min.js.map
```

The error message repeat itself 6 times (each time I want to update the bar)

Thank you for your help,
Arthur

**Comment by pvictor** [comment]
Hello,

Can you share a bit of code? I'll try to look at what's going on, but hard to tell without reproducing it.
Otherwise I've an alternative in another package : https://dreamrs.github.io/shinybusy/reference/modal-progress.html

Victor
