### ISSUE TITLE
URL not normalized for switchInput

### ISSUE THREAD

**Issue by markuszinser** [dreamRs/shinyWidgets#324]
Hi,

I am using the switchInput from shinyWidgets in my Dashboard. I recently realized that some parts stopped working and found that the browser shows the following error:

`GET http://???/shinyWidgets/bootstrap-switch//bootstrap-switch-3.3.4/bootstrap-switch.min.js 500 (Internal Server Error)`

The error is caused by:

`org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.`

Could it be that the additional slash in the path went there by accident (bootstrap-switch// <--)?  

Thanks!

**Comment by pvictor** [comment]
Hello,

There was indeed an extra slash, I removed it, you can try if it's better by re-installing from GitHub.

Victor

**Comment by markuszinser** [comment]
Hi,

yes, now it works again. Thanks for the immediate help!

Markus
