### ISSUE TITLE
Feature: Add closeOnClickOutside and closeOnEscape parameters to inputSweetAlert

### ISSUE THREAD

**Issue by trudeaur** [dreamRs/shinyWidgets#325]
I am requesting for this feature to be added because I am using inputSweetAlert in a shiny app to obtain important information about the user, but have come across the issue of accidentally clicking outside of the box and it closing. I'd rather not have to call the function again if this happens, but instead just have options to prevent accidental clicking/closing of the dialog.

I have written my own version of the inputSweetAlert function where these options are added to the parameter list and allowOutsideClick = closeOnClickOutside and allowEscapeKey = closeOnEscape are added to the list for swal in the session$sendCustomMessage.

**Comment by pvictor** [comment]
Hello,

Sure, if you re-install from GitHub, you can now pass parameters directly to JavaScript method, e.g. : 

```r
library(shiny)
library(shinyWidgets)


ui <- fluidPage(
  tags$h1("Input sweet alert"),
  actionButton(inputId = "text", label = "Text Input"),
  verbatimTextOutput(outputId = "text")
)
server <- function(input, output, session) {
  
  observeEvent(input$text, {
    inputSweetAlert(
      session = session,
      inputId = "mytext",
      input = "text",
      title = "What's your name ?",
      inputPlaceholder = "e.g.: Victor",
      allowOutsideClick = FALSE,
      showCloseButton = TRUE
    )
  })
  output$text <- renderPrint(input$mytext)
  
}

shinyApp(ui = ui, server = server)
```

But please note that `closeOnClickOutside` was the ancient name I kept for compatibility issue, here you have to use `allowOutsideClick`.

Victor
