### ISSUE TITLE
the order of the return value of "colorSelectorInput" function

### ISSUE THREAD

**Issue by zhangjunjiang** [dreamRs/shinyWidgets#328]
hello 
I'm using the `colorSelectorInput` function to help the user pick their own color pallet.
I'm so happy to see this function can return more than 1 color, by setting `mode =  "checkbox"`.
The problem I find out is that the order of return value is based on the origin order of the choice list NOT the order I choose.

For example, the default choice is :`"red", "yellow", "blue", "green"`
the order I want is `"blue", "yellow"`, so the order I click is 3,2.
but the return value is :`"yellow", "blue"`
the color was what I want but the order was not.

Could anyone help me with it?

**Comment by pvictor** [comment]
Unfortunately no, it's not possible to know in which order colors are selected.

You can add an intermediate to sort colors tho, here an example to show selected color and remove them (you could also add something like {sortable} to allow reorder colors by drag-and-drop):

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  colorSelectorInput(
    inputId = "color",
    label = "Select colors :",
    choices = palette(),
    mode = "radio"
  ),
  tags$b("Selected colors (click to remove):"),
  uiOutput(outputId = "selected"),
  verbatimTextOutput("result1")
)

server <- function(input, output, session) {
  
  rv <- reactiveValues(selected = NULL)
  observeEvent(input$color, {
    rv$selected <- c(rv$selected, input$color)
  })
  
  output$selected <- renderUI({
    req(rv$selected)
    lapply(
      X = rv$selected,
      FUN = function(x) {
        tags$button(
          class = "btn btn-default btn-xs",
          style = paste0("width: 50px; height: 20px; border-radius: 50px; margin-right: 5px; margin-bottom: 5px; background:", x, ";"),
          onclick = sprintf(
            "Shiny.setInputValue('reset_color', '%s', {priority: 'event'});", x
          )
        )
      }
    )
  })
  
  observeEvent(input$reset_color, {
    rv$selected <- setdiff(rv$selected, input$reset_color)
  })
  
  output$result1 <- renderPrint({
    rv$selected
  })
}

shinyApp(ui = ui, server = server)
```

Victor
