### ISSUE TITLE
updateRadioGroupButtons expects character!

### ISSUE THREAD

**Issue by bklingen** [dreamRs/shinyWidgets#330]
I would have expected this code to update the selection of the buttons, but one has to specify a character for `selected` in `updateRadioGroupButtons` to get the desired behavior. If not, the update results in no (an empty, i.e., NULL) selection. May be related to issue #95 
```{r}
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  radioGroupButtons("bt1", "Select:", 
                    choices=1:3,
                    selected=2),
  actionButton("reset","Reset")
)

server <- function(input,output,session) {
  observeEvent(input$reset,{
    updateRadioGroupButtons(session, "bt1", selected=1) #this doesn't update and results in no selection
    #updateRadioGroupButtons(session, "bt1", selected="1") #this works
  })
}

shinyApp(ui,server)
```

**Comment by pvictor** [comment]
Thanks, that's fixed (for `updateRadioGroupButtons`, `updateCheckboxGroupButtons`, `updateAwesomeCheckboxGroup`, `updateAwesomeRadio`)

Victor
