### ISSUE TITLE
Uncaught handler must be a function that takes one argument

### ISSUE THREAD

**Issue by trafficonese** [dreamRs/shinyWidgets#331]
When using a `shinyWidgets` input, the following error shows up in the browser console:

> Uncaught handler must be a function that takes one argument. shinyapp.js:483:6
> addCustomMessageHandler shinyapp.js:483
> <anonym> shinyWidgets-bindings.min.js:1

The app seems to work normally though. I tried other inputs from other packages and didnt see that error occur anywhere else.

Here is a short app to reproduce that error, but I think any `shinyWidgets`-input would do.

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  actionBttn(inputId = "bttn1",label = "Go!",color = "primary",style = "bordered")
)

server <- function(input, output, session) {}
shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Which version ?

**Comment by trafficonese** [comment]
Ah it was version 0.5.0.920. The error didn't occur in other (newer or older) versions.
