### ISSUE TITLE
Options group does not work when list contains one element.

### ISSUE THREAD

**Issue by meldarionqeusse** [dreamRs/shinyWidgets#332]
This issue has already been brought up in [this ](https://github.com/dreamRs/shinyWidgets/issues/240#issue-526714386). My problem is that the list is dynamically generated and in some case I have a single list with a single item which would still be a problem. 

Furthermore shinywidgets documentation show group options like this. It should be update so that it says list() rather c()

![image](https://user-images.githubusercontent.com/21668964/99392422-f77c4f00-28db-11eb-819e-a56e1c304520.png)

**Comment by pvictor** [comment]
Sure, PR to improve documentation are welcome !
