### ISSUE TITLE
The popup for pickerInput falls behind shinydashboard dashboardHeader

### ISSUE THREAD

**Issue by reisner** [dreamRs/shinyWidgets#337]
Is there some way to either:

* Specify z-index for the `pickerInput`, so the popup window doesnt fall behind `shinyDashboard::dashboardHeader`
* Limit the number of items in the popup window so it doesnt reach the header?

Thanks!

**Comment by pvictor** [comment]
Hello,

Can you provide an example please?

Thx

Victor

**Comment by pvictor** [comment]
Thanks for the example. You can use `container = "body"` in the list of options to attach the popup to the entire body and not only the sidebar.
E.g. : 

```r
pickerInput("test8", "Test", 1:50, selected = c(), multiple = TRUE, options = list(`actions-box` = TRUE, container = "body"))
```

Victor

**Comment by reisner** [comment]
That works great, thanks for the help!
