### ISSUE TITLE
Bootstrap 4 Split Button

### ISSUE THREAD

**Issue by dbart79** [dreamRs/shinyWidgets#338]
Hi,

first of all thanks a lot for this really awesome package. I would love to have the Bootstrap 4 Split Button in my app, would it be difficult to implement? I could investigate a bit on my own, is that a a good first issue?

Not knowing a lot Javascript, but willing to learn :)

https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns

**Comment by lefec** [comment]
The above link redirects to the wrong place. Fixed link here

[https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns](https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns)

Would be a great feature for my apps as well.

**Comment by pvictor** [comment]
Hello,

You can do this using `tags` in plain Shiny, just convert the HTML markup to Shiny syntax: 

```r
library(shiny)

ui <- fluidPage(
  
  tags$div(
    class = "btn-group",
    actionButton("action", "Action"),
    actionButton("dropdown", icon("caret-down"), class = "dropdown-toggle", `data-toggle` = "dropdown"),
    tags$ul(
      class = "dropdown-menu",
      tags$li(actionLink("action1", "Action 1")),
      tags$li(actionLink("action2", "Action 2")),
      tags$li(actionLink("action3", "Action 3")),
      tags$li(role = "separator", class = "divider"),
      tags$li(actionLink("more", "Another action"))
    )
  )
  
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```

Note that the example above is for Bootstrap 3, the default for Shiny.

Victor
