### ISSUE TITLE
Disabling pickerInput using shinyjs::disable()

### ISSUE THREAD

**Issue by danliIDEA** [dreamRs/shinyWidgets#341]
Hi,

I tried to disable pickerInput using `shinyjs::disable()`.  Please see my example code below.

```r
library(shiny)
library(shinyjs)
library(shinyWidgets)

ui <- fluidPage(
    useShinyjs(),

    fluidRow(
        pickerInput("cyl", label = NULL, choices = c("", unique(mtcars$cyl)), selected = NULL),
        pickerInput("make", label = NULL, choices = rownames(mtcars))
    )
)

server <- function(input, output) {

    observeEvent(input$cyl, {

        if (input$cyl == "") {
            shinyjs::disable("make")
        } else {
            shinyjs::enable("make")
        }
    })
}

shinyApp(ui = ui, server = server)
```

I believed the second pickerInput was functionally disabled because the selection couldn't be updated even if the dropdown menu worked. Is there any way to disable the interface level completely? bootstrap-select has an [example of disabling the select box](https://developer.snapappointments.com/bootstrap-select/examples/#disabled-select-box). This might be also related to issue #68 and requires tweaking the css for cursor. Thank you!!

**Comment by pvictor** [comment]
Hello,

`selectpicker` need to be refreshed after being disabled which cannot be done with `shinyjs::disable()`, you have to do it in JavaScript, e.g. : 

```r
  observeEvent(input$cyl, {
    if (input$cyl == "") {
      shinyjs::runjs("$('#make').prop('disabled', true);")
      shinyjs::runjs("$('#make').selectpicker('refresh');")
    } else {
      shinyjs::runjs("$('#make').prop('disabled', false);")
      shinyjs::runjs("$('#make').selectpicker('refresh');")
    }
  })
```
`#make` refer to `inputId`, in a module you have to add prefix manually (something like `#moduleId-make`).

Victor

**Comment by danliIDEA** [comment]
It works like a charm! Thank you so much, Victor!

**Comment by jsinnett** [comment]
FWIW this solution does not work for me. The input disables as expected but the options duplicate when switching between enabled/disabled. 

[2738](https://github.com/snapappointments/bootstrap-select/issues/2738)

Below is my workaround, with two helper functions.

```
# Known bug with disabling a shinyWidget using shinyjs
# Also known bug with .refresh() in bootstrap-select
# Workaround to disable / enable inputs
force_disable_input = function(inp_id) {
  shinyjs::runjs(paste0("$('#",inp_id,"').prop('disabled', true);"))
  shinyjs::runjs(paste0("$('#",inp_id,"').data('selectpicker').selectpicker.main.data = null"))
  shinyjs::runjs(paste0("$('#",inp_id,"').selectpicker('refresh');"))
}

# Enable
force_enable_input = function(inp_id) {
  shinyjs::runjs(paste0("$('#",inp_id,"').prop('disabled', false);"))
  shinyjs::runjs(paste0("$('#",inp_id,"').data('selectpicker').selectpicker.main.data = null"))
  shinyjs::runjs(paste0("$('#",inp_id,"').selectpicker('refresh');"))
}
```
