### ISSUE TITLE
bs4Dash use dropdownbutton

### ISSUE THREAD

**Issue by Liripo** [dreamRs/shinyWidgets#345]
```R
if (interactive()) {
    library(shiny)
    library(shinydashboard) #library(bs4Dash)
    library(shinyWidgets)
    
    shinyApp(
      ui = dashboardPage(
        header = dashboardHeader(
        ),
        sidebar = dashboardSidebar(),
        body =  dashboardBody(
          dropdownButton(
            circle = TRUE, status = "danger", icon = icon("gear"),
            tooltip = tooltipOptions(title = "Click to see inputs !")
          )
      )),
      server = function(input, output) { }
    )
}
```
If I use bs4Dash instead, the two looks different.
![image](https://user-images.githubusercontent.com/54770415/104412065-8ccb5500-55a6-11eb-90f8-d60265ed26f6.png)
![image](https://user-images.githubusercontent.com/54770415/104412276-e29ffd00-55a6-11eb-95e1-f2688d7b630f.png)

>This is my package version
![image](https://user-images.githubusercontent.com/54770415/104412357-095e3380-55a7-11eb-815f-e0393b1943f3.png)

How can I make bs4dash like using shinydashboard？
Thank you!

**Comment by pvictor** [comment]
Hello,

Currently, you can hide the arrow with CSS with this code (use it in your UI, above dropdown button for example):

```r
tags$style(".btn-circle.dropdown-toggle::after {display: none;}")
```

Will implement something better in a future version.

Victor
