### ISSUE TITLE
pickerInput remove the data- attributes in choicesOpt$content

### ISSUE THREAD

**Issue by ColinFay** [dreamRs/shinyWidgets#349]
Hey, 

Given the following picker input:

```r
library(shiny)
library(shinyWidgets)
choices <- paste(
  "Badge", 
  c("info", "success", "danger", "primary", "warning")
)
ui <- function(request){
  fluidPage(
    pickerInput(
      inputId = "Id008",
      choices = choices,
      choicesOpt = list(
        content = sprintf(
          '<span data-blabla="xxx" style="color:red">%s</span>', 
          choices
        )
      )
    )
  )
}

server <- function(
  input, 
  output, 
  session
){
  
  
}

shinyApp(ui, server)

```

I would expect my span to keep the `data-` attribute, but it seems to be removed from the choices (the style is kept): 

![Screenshot 2021-01-26 at 16 52 58](https://user-images.githubusercontent.com/17936236/105868942-fe6bc000-5ff6-11eb-8091-179de92df154.png)

Anyway to bypass that? 

Thanks a lot, 
Colin

**Comment by pvictor** [comment]
See https://github.com/dreamRs/shinyWidgets/issues/313 for a quick answer

**Comment by ColinFay** [comment]
Great, thanks mate! 

Cheers
