### ISSUE TITLE
Specify inputID in dropdownButton

### ISSUE THREAD

**Issue by berndtlindner** [dreamRs/shinyWidgets#35]
Would this not be a "**quick**" change?

dropdownButton <- function (... ,**inputId=NULL**, circle = TRUE, status = "default", size = "default", 
                               icon = NULL, label = NULL, tooltip = FALSE, right = FALSE, 
                               up = FALSE, width = NULL) 
{
    status <- match.arg(arg = status, choices = c("default", 
                                                  "primary", "success", "info", "warning", "danger"))
    size <- match.arg(arg = size, choices = c("default", "lg", 
                                              "sm", "xs"))
    buttonID <- **inputId**
    html_ul <- list(class = paste("dropdown-menu", ifelse(right, 
                                                          "dropdown-menu-right", "")), class = "dropdown-shinyWidgets", 
                    id = paste("dropdown-menu", buttonID, sep = "-"), style = if (!is.null(width)) paste0("width: ", 
                                                                                                          htmltools::validateCssUnit(width), ";"), `aria-labelledby` = buttonID, 
                    lapply(X = list(...), FUN = htmltools::tags$li, style = "margin-left: 10px; margin-right: 10px;"))
    if (circle) {
        html_button <- circleButton(inputId = buttonID, icon = icon, 
                                    status = status, size = size, class = "dropdown-toggle", 
                                    `data-toggle` = "dropdown")
    }
    else {
        html_button <- list(class = paste0("btn btn-", status, 
                                           " dropdown-toggle "), class = if (size == "default") paste0("btn-", 
                                                                                                       size), type = "button", id = buttonID, `data-toggle` = "dropdown", 
                            `aria-haspopup` = "true", `aria-expanded` = "true", 
                            list(icon, label), tags$span(class = "caret"))
        html_button <- do.call(htmltools::tags$button, html_button)
    }
    if (identical(tooltip, TRUE)) 
        tooltip <- tooltipOptions(title = label)
    if (!is.null(tooltip) && !identical(tooltip, FALSE)) {
        tooltip <- lapply(tooltip, function(x) {
            if (identical(x, TRUE)) 
                "true"
            else if (identical(x, FALSE)) 
                "false"
            else x
        })
        tooltipJs <- htmltools::tags$script(sprintf("$('#%s').tooltip({ placement: '%s', title: '%s', html: %s });", 
                                                    buttonID, tooltip$placement, tooltip$title, tooltip$html))
    }
    else {
        tooltipJs <- ""
    }
    dropdownTag <- htmltools::tags$div(class = ifelse(up, "dropup", 
                                                      "dropdown"), html_button, do.call(htmltools::tags$ul, 
                                                                                        html_ul), tooltipJs)
    attachShinyWidgetsDep(dropdownTag, "dropdown")
}

**Comment by pvictor** [comment]
Not exactly like this, but yes, why ?

**Comment by berndtlindner** [comment]
I would like to perform some code on specific dropdownButtons (via server.R) or Java Script. For instance opening/closing a dropdownButton  (e.g. https://stackoverflow.com/questions/22842903/how-to-open-bootstrap-dropdown-programmatically)

**Comment by pvictor** [comment]
Thanks for the precision! That's a good idea, and you're right the user should pass an id to the dropdown for it to work. I'll look at it to not break previous behavior.
And for adding a new function to programmatically open/close dropdown in the server.

Victor

**Comment by pvictor** [comment]
I added a function `toggleDropdownButton` that you can use in server to open/close dropdown, here an example how to use it : 

```r

library("shiny")
library("shinyWidgets")

ui <- fluidPage(
  tags$h2("Toggle Dropdown Button"),
  br(),
  fluidRow(
    column(
      width = 6,
      dropdownButton(
        tags$h3("List of Inputs"),
        selectInput(inputId = 'xcol',
                    label = 'X Variable',
                    choices = names(iris)),
        sliderInput(inputId = 'clusters',
                    label = 'Cluster count',
                    value = 3,
                    min = 1,
                    max = 9),
        circle = TRUE, status = "danger",
        actionButton(inputId = "toggle2", label = "Close dropdown"),
        inputId = "mydropdown",
        icon = icon("gear"), width = "300px"
      )
    ),
    column(
      width = 6,
      actionButton(inputId = "toggle1", label = "Open dropdown")
    )
  )
)

server <- function(input, output, session) {
  
  observeEvent(list(input$toggle1, input$toggle2), {
    toggleDropdownButton(inputId = "mydropdown")
  }, ignoreInit = TRUE)
  
}

shinyApp(ui = ui, server = server)

```

**Comment by berndtlindner** [comment]
Very very nice
(Sorry took so long to comment, was on holiday)
