### ISSUE TITLE
Check Box issue with shinytheme("paper")

### ISSUE THREAD

**Issue by raimondsre** [dreamRs/shinyWidgets#350]
When adding function ```theme = shinytheme("paper")``` all check boxes stops working. The only other issue i found is "searchInput" function not removing content after pressing the cross.

**Comment by pvictor** [comment]
Hello,

Can you provide a minimal reproducible example ? Which checkbox exactly ?
Thx,

Victor

**Comment by raimondsre** [comment]
Hi, almost all checkboxes act weirdly with "paper" theme. The universal issue with all is that "clicking" area is relocated from actual checkbox area, meaning you have to click an empty space somewhere else but the checkbox in order to check the box.

Here is a minimal example:

```
  library(shiny)
  library(shinyWidgets)
  library(shinythemes)
  
  ui <- fluidPage(theme = shinytheme("paper"),
                  prettyCheckbox(
                    inputId = "pretty_1", label = "Check me!", icon = icon("check")
                  )
        )
  server <- function(input, output) {}
  shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Thanks, yes there's some incompatible CSS rules added by this theme. If you want to create custom theme for shiny application I suggest you to look at packages [fresh](https://github.com/dreamRs/fresh) or [bslib](https://github.com/rstudio/bslib) instead
