### ISSUE TITLE
chooseSliderSkin Issue

### ISSUE THREAD

**Issue by eyalspier** [dreamRs/shinyWidgets#351]
Creating a UI as follows:

```r
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(title = "Basic dashboard"),
  dashboardSidebar(),
  dashboardBody(
    # Boxes need to be put in a row (or column)
    fluidRow(
      box(plotOutput("plot1", height = 250)),
      
      box(
        title = "Controls",
        sliderInput("slider", "Number of observations:", 1, 100, 50)
      )
    )
  )
  ,chooseSliderSkin("HTML5", color = "orange"))

server <- function(input, output) {
  set.seed(122)
  histdata <- rnorm(500)
  
  output$plot1 <- renderPlot({
    data <- histdata[seq_len(input$slider)]
    hist(data)
  })
}

shinyApp(ui, server)
```
Leads to the app failing with a missing value error. Commenting out the chooseSliderSkin function allows the app to work. I just updated all my packages today, so I think this is a new issue.
Any ideas regarding this?

**Comment by pvictor** [comment]
Hello,

This is due to the latest version of shiny, try re-installing from GitHub with : 

```r
devtools::install_github("dreamRs/shinyWidgets")
```

and let me know if it works for you.

Victor

**Comment by eyalspier** [comment]
Hi Victor, 

Fantastic, it works again.  And I just want to add that the work you are doing on the shinyWidgets package is extremely impressive! It makes my apps look stunning, thank you so much!

Eyal

**Comment by pvictor** [comment]
You're welcome,

Thanks for your kind words, really appreciate it 😄
