### ISSUE TITLE
pickerInput volatility in shinydashboard

### ISSUE THREAD

**Issue by SFrav** [dreamRs/shinyWidgets#353]
The pickerInput widget is volatile when using in the sidebar of the shinydashboard package. The three behaviours were as follows:
- If the dropdown crosses over to dashboardBody the overhanging part flickers between visible and invisible. We set the width in css to resolve that (e.g .dropdown-menu {width: 193px;})
- With a long list of inputs the top of a dropup will be cut off by the shinydashboard header. We used the following pickerOptions to get resolve that dropupAuto = FALSE, size = 10, windowPadding = "[100,0,0,0]",
- With a pickerInput dropdown open part of the list can flick between visible and invisible when moving the mouse outside of the dropdown menu area. You can see what I mean in this [Shiny application](https://feastdata.ilri.org/reports), selecting the 'feed availability' option, then a country and you will see the behaviour on the 'Site' pickerInput dropdown. The code is [here](https://github.com/ilri/feast-data-shiny).

It would be great if we could resolve the last one. It may be worthwhile looking into it while working on a long term fix to [issue #346](https://github.com/dreamRs/shinyWidgets/issues/346).

**Comment by pvictor** [comment]
Hello,

Can you provide a reproducible example ?
I cannot access the application on your server and cannot launch the app locally because of this line:

```r
source('/var/www/html/webroot/rscripts/feastCred.R')
```

Thanks

Victor

**Comment by SFrav** [comment]
Hi Victor, 

Thanks for the speedy reply. 

I'll work-up a reprex over the next few months. I also need to test whether it's unique to shinydashboard. For now I'm behind on other things. 
Were you able to follow the link and see the volatile dropdown behaviour? It's embedded using iframe, but I get the same behaviour when accessing the app directly.

Best wishes,

Simon

**Comment by SFrav** [comment]
The issue is related to sidebarMenu and menuItem in shinydashboard. If the cursor goes out of the menuItem bounds then the dropdown gets cut-off.
Removing `sidebarMenu(menuItem())` resolves the issue. 
Should I close this and open an issue with shinydashboard when I've worked up that reprex?
