### ISSUE TITLE
AirDatePicker OnCellRender or date enable

### ISSUE THREAD

**Issue by sgawad** [dreamRs/shinyWidgets#355]
Hello,
First this is more of a feature or (how to) request than an actual issue...
I would like to indicate to the user dates in the picker which would have some content in a database.
So I make a query for entries and get a list of unique dates... which I then need to "tag" or "enable" in the calendarview.
I was wondering how to "enable" dates in the date picker (instead of the current "disable" list option)
also I saw in the js that the OnRenderCell could alternatively be used to add a dot under a list of interesting dates:

> $picker.datepicker({
>     language: 'en',
>     onRenderCell: function (date, cellType) {
>         var currentDate = date.getDate();
>         // Add extra element, if `eventDates` contains `currentDate`
>         if (cellType == 'day' && eventDates.indexOf(currentDate) != -1) {
>             return {
>                 html: currentDate + '<span class="dp-note"></span>'
>             }
>         }
>     },
> 

is there a way to use such a code in R and access the AirDatePicker object?

Thank you in advance

**Comment by pvictor** [comment]
Interesting, I added an `highlightedDates` argument, you can try it with:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  airDatepickerInput(
    inputId = "inputId",
    label = "Highlighted dates:",
    placeholder = "Select a date:",
    highlightedDates = c("2021-02-05", "2021-02-12", "2021-02-20")
  ),
  verbatimTextOutput("res")
)

server <- function(input, output, session) {
  output$res <- renderPrint(input$inputId)
}

shinyApp(ui, server)
```

Default is to add a point below the date like in AirDatepicker site, but highlighted dates also have a custom class, so you can add something like:

````r
tags$style(".airdatepicker-highlighted {border: 1px solid red;}"),
```

in UI to add red borders for example.

Let me know how it works for you.

Victor

**Comment by sgawad** [comment]
Hi @pvictor, (THAT WAS CRAZY FAST, thank you, wow)
Just tried it and it does work very well when I define it at picker creation in the 
airDatepickerInput()
but I believe I actually need to make queries to the database to get the highlights and as such this comes dynamicly 
later on in my code..
so I tried it in here: 
observeEvent(
updateAirDateInput()
)
which I call in the server function : but that seems to fail

Warning: Error in updateAirDateInput: unused argument (highlightedDates = c("2021-02-05", "2021-02-12", "2021-02-20"))

Best regards and thank you for your support!!!

**Comment by pvictor** [comment]
Sure, re-install from GitHub then try:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  
  tags$style(".airdatepicker-highlighted {border: 1px solid red;}"),
  
  airDatepickerInput(
    inputId = "inputId",
    label = "Highlighted dates:",
    placeholder = "Select a date:"
  ),
  verbatimTextOutput("res"),
  actionButton(inputId = "go", "Highlight dates")
)

server <- function(input, output, session) {
  output$res <- renderPrint(input$inputId)
  
  observeEvent(input$go, {
    updateAirDateInput(
      session = session, 
      inputId = "inputId", 
      options = list(
        highlightedDates = c("2021-02-05", "2021-02-12", "2021-02-20")
      )
    )
  })
}

shinyApp(ui, server)
```

**Comment by sgawad** [comment]
Hi @pvictor,

Works like a charm 👍  in my case:

observeEvent(input$CalibType,{
    calibtyperes <- dbSendQuery(con, paste("SELECT DISTINCT CreationDate d FROM `deviceLogs` WHERE Type=" , input$CalibType , " AND DATE(CreationDate) like '%'"))
    dates<<-dbFetch(calibtyperes)
    updateAirDateInput(
      session,
      inputId = "multiple",
      options = list(
        highlightedDates = as.character.Date(as.Date(dates$d))
      )
    )

Thank you
