### ISSUE TITLE
chooseSliderSkin is not working with with R v4.0.3

### ISSUE THREAD

**Issue by shubhrampandey** [dreamRs/shinyWidgets#356]
This command is not working in R v4.0.3. Please take a look.

**Comment by pvictor** [comment]
Hello,

This is due to the latest version of shiny, try re-installing from GitHub with : 

```r
devtools::install_github("dreamRs/shinyWidgets")
```

See https://github.com/dreamRs/shinyWidgets/issues/351

**Comment by shubhrampandey** [comment]
Thank you

**Comment by gabrielgesteira** [comment]
Dear @pvictor, 

We are facing the same issue after upgrading to R 4.0.4. All apps were working fine until we upgraded R and all packages on the server side. Tried reinstalling both `shiny` and `shinyWidgets` packages from GitHub as you suggested, without success.

Obs: all apps are rendered, but the sliders aren't rendered correctly and don't work as expected.
Obs2: commenting out the line `shinyWidgets::chooseSliderSkin("Simple")` makes it work again. 

We appreciate any suggestions.

Thank you!

**Comment by pvictor** [comment]
Hello,

Thanks for noticing that and sorry for the inconvenience. Skin "Simple" is no longer available... See here : http://ionden.com/a/plugins/ion.rangeSlider/skins.html for available ones. I added a warning and a fallback in dev version.

Victor

**Comment by gabrielgesteira** [comment]
Great! Thank you @pvictor
