### ISSUE TITLE
pickerInput() gets stuck

### ISSUE THREAD

**Issue by avisserquinn** [dreamRs/shinyWidgets#357]
I must have updated some of the dependencies to shinyWidgets today as since then the pickerInput() does not work properly. Effectively, it is "sticky" - it won't select properly and the picker won't close. 

After a lot of troubleshooting I learned it was not my code nor my install of R/RStudio. The same issue persists on my fresh install of base R with only shinyWidgets and its dependencies installed. 

The issue occurs whenever and however I use pickerInput(). Below is a screenshot of it being 'stuck' following the basic usage example from the shinyWidgets help text.

![image](https://user-images.githubusercontent.com/57040504/106761875-27123c00-662d-11eb-85d2-3b19a4b4323c.png)

This link - http://waterresilientcities.shinyapps.io/test - shows the problem in action on the app that I was trying to develop. (but as I say, it can be reproduced in a clean install of R with the basic examples provided with the package)

**Comment by pvictor** [comment]
Hello,

This is caused by the recent update of Shiny (see https://github.com/dreamRs/shinyWidgets/issues/346), you can either:
* re-install shiny `remotes::install_github("rstudio/shiny")`
* re-install shinyWidgets `remotes::install_github("dreamRs/shinyWidgets")`

Victor

**Comment by gowachin** [comment]
I had the same issue and re-install shinyWidgets did it ! Thx for all the good work btw !
