### ISSUE TITLE
updatePickerInput() : not really an issue but rather a question...

### ISSUE THREAD

**Issue by LoSpa** [dreamRs/shinyWidgets#360]
Hi everyone, 

Sorry to bother you cause I know this is not the right place to put this kind of query... I m going ahead anyway ;-)

Actually, I would like to know if it s possible to update the "options" (actions-box, max-option, ...) of a pickerInput with updatePickerInput().
E.g. : frequently in my Shiny app', I want to change the "max-options" value for a specific pickerInput().
I know that I can handle this by making the logic in the ui.R or server side with renderUI() but, i would prefer to first, create the pickerInput() client side and then, update it with updatePickerInput().
I hope I'm more or less clear... But I guess the updatePickerInput is not designed to allow that ?
Would it be possible to do that ? 

Many thanks for your reply.

Cheers,

Laurent

**Comment by pvictor** [comment]
Hello,

Yes, this is something I had in my TODO list for a while. If you install from GitHub, you can try that:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$h2("Update picker options"),
  fluidRow(
    column(
      width = 3,
      pickerInput(
        inputId = "pckr",
        label = "Choice:",
        choices = month.name,
        multiple = TRUE
      ),
      verbatimTextOutput("result")
    ), 
    column(
      width = 3,
      checkboxInput("action_box", "Add action box", value = FALSE),
      checkboxInput("live_search", "Add live search", value = FALSE),
      sliderInput(
        inputId = "max",
        label = "Max options selectable:",
        min = 1,
        max = 12,
        value = 5
      )
    )
  )
  
)

server <- function(input, output, session) {
  
  output$result <- renderPrint(input$pckr)
  
  observeEvent(input$action_box, {
    updatePickerInput(
      session, "pckr", 
      options = pickerOptions(actionsBox = input$action_box)
    )
  }, ignoreInit = TRUE)
  
  observeEvent(input$live_search, {
    updatePickerInput(
      session, "pckr", 
      options = pickerOptions(liveSearch = input$live_search)
    )
  }, ignoreInit = TRUE)
  
  observeEvent(input$max, {
    updatePickerInput(
      session, "pckr", 
      selected = character(0),
      options = pickerOptions(maxOptions = input$max)
    )
  }, ignoreInit = TRUE)
  
}

shinyApp(ui, server)
```

Tell me how it works for you.

Victor

**Comment by LoSpa** [comment]
Hi Victor,

Great ! It works like a charm :-) Thanks very much.
I really wanted to use {shinywidgets} and this behaviour made it difficult for me to find an happy end. Now I can go on, thank you :-)

One little thing :
If I got it, with for e.g updatePickerInput(), options sent by pickerOptions() are "kept" in the pickerInput() even if this pickerInput is updated in another way later on. That's right ?  It makes perfect sense but I was a little bit surprise with "maxOptions" which was kept in the pickerInput() even though I had not specified it in a specific updatePickerInput(). Here is an example :  


```
library(shiny)
#devtools::install_github("dreamRs/shinyWidgets")`
library(shinyWidgets)

ui <- fluidPage(
    tags$h2("Update picker options"),
    fluidRow(
        column(
            width = 3,
            pickerInput(
                inputId = "input1",
                label = "Choice:",
                choices = NULL,
                multiple = TRUE
            )
        ), 
        column(
            width = 3,
     prettyRadioButtons(inputId = "selectby", label = "Select by", choices = list("Site : 1 single choice" = "site", "Parameter : multi choices" = "parameter")),
     
     conditionalPanel("input.selectby == 'parameter'",
                      checkboxInput(inputId = "max", label = "max-options sets to Inf")
                      )
     
        )
    )
    
)

server <- function(input, output, session) {
    

    
    observeEvent(c(input$selectby, input$max), ignoreInit = FALSE, {
        
        if (input$selectby %in% "site") {
            
            site <- c("site1", "site2", "site3")
            
            updatePickerInput(
                session, "input1", 
                choices = site,
                selected = character(0),
                options = pickerOptions(maxOptions = 1, noneSelectedText =  "Make a single choice")
            )
            
        } else {
            
        
            param <- c("ozon", "PM10", "PM2.5")
            
            if (input$max == TRUE) {
                updatePickerInput(
                    session, "input1", 
                    selected = character(0),
                    options = pickerOptions(actionsBox = TRUE, noneSelectedText = "Multiple choices available", maxOptions = Inf)
                ) 
                
            } else {
                updatePickerInput(
                    session, "input1", 
                    selected = character(0),
                    options = pickerOptions(actionsBox = TRUE, noneSelectedText = "Multiple choices not available")
                )
                
            }
         
            
        }
   
    })
    
    
   
    
}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Hello,

Ah yes that's a side effect, I added an argument to clear options before setting new ones. Default is `FALSE`, so it works like in your example.

Victor

**Comment by LoSpa** [comment]
Hi Victor,

I did not quite understand : concerning this "clear" argument, you're talking about updatePickerInput() that's right ?
If so, is this "clear" argument reachable  ? Because it would be great to have the opportunity to choose whether or not to clear already available options :-)

Thanks,

Laurent

**Comment by pvictor** [comment]
Hello,

Yes `clearOptions` is an argument of `updatePickerInput`, so it there's two different ways to update options : 

* **default**: option will be added to existing ones:
```r
updatePickerInput(
  session, "pckr", 
  options = pickerOptions(actionsBox = TRUE)
)
```

* **clearOptions**: all previous options will be removed and the one specified will be set:
```r
updatePickerInput(
  session, "pckr", 
  options = pickerOptions(actionsBox = TRUE),
  clearOptions = TRUE
)
```

Let me know if it's clear or if documentation can be improved.

Victor

**Comment by LoSpa** [comment]
Hi Victor,

Great !! It's crystal clear. 
Thanks you for the work :-)

Cheers,

Laurent
