### ISSUE TITLE
Triggering airdatepicker with actionButton?

### ISSUE THREAD

**Issue by jat255** [dreamRs/shinyWidgets#362]
Sorry if I'm just not seeing something obvious, but it appears by default, the button next to an AirDatePicker does not do anything. I'm able to bind an action to that button with:

```R
# server.R
observeEvent(input$datepicker_button, { 
    shinyjs::runjs("console.log('clicking!');")
})
```

Is there an action I can put inside of that trigger to cause the AirDatePicker to display (i.e. like I've clicked in the date entry area)? I tried using the `shinyjs::click()` method and a few things in plain javascript, but couldn't seem to get it to work. Thanks!

**Comment by jat255** [comment]
Of course after lots of searching, I find an answer right after asking the question...

This appears to work:

`shinyjs::runjs("$('#datepicker_id').data('airdatepicker').show()")`

Is there any way to do this directly from within shiny? Or should I stick with the JS method?

**Comment by pvictor** [comment]
Hello,

I added `show` / `hide` arguments to `updateAirDateInput`.
But your solution is good.

Victor
