### ISSUE TITLE
pickerInput closing automatically upon selection

### ISSUE THREAD

**Issue by amanthapar** [dreamRs/shinyWidgets#365]
Hi All,
I'm having an issue (dropdown automatically closes, we have to keep clicking on it to multi select) when we use pickerInput with the following settings:
```
shinyWidgets::pickerInput(inputId = inputId, 
                                            label = 'Test', 
                                            choices = c('a', 'b', 'c'), 
                                            options = list (
                                              `actions-box` = TRUE,
                                              size = 5,
                                              `selected-text-format` = "count > 3"
                                            ),
                                            multiple = TRUE)
```

Let's say we want to select 'a' and 'b'. I click on 'a', then the drop-down closes, I have to click on it again and select 'b'. This can be an issue when we have our list of 25+ items and the user wants to select 5-10 items at once. 

I think this started happening recently, but can't figure out what is causing this? Thank you!

**Comment by pvictor** [comment]
Hi,

You have to update shinyWidgets from CRAN to 0.5.7, that's a bug caused by the recent update of shiny.
More info here : https://github.com/dreamRs/shinyWidgets/issues/346

Victor
