### ISSUE TITLE
autoClose not working

### ISSUE THREAD

**Issue by shosaco** [dreamRs/shinyWidgets#366]
Using shinyWidgets 0..5.7 and Shiny 1.5.0, it seems that the parameter `autoClose` does not work:

``` r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
    airDatepickerInput(
        inputId = "test",
        autoClose = TRUE
    )
)

server <- function(input, output) {}

shinyApp(ui, server)
```

``` r
packageVersion("shinyWidgets")
#> [1] '0.5.7'
packageVersion("shiny")
#> [1] '1.5.0'
```

**Expected behaviour:**
After selecting the date, the `airDatepickerInput` should close.

**Observed behavior:**
The `airDatepickerInput` stays open. This is the same for the `airMonthpickerInput`, where I initially observed the behaviour.

Best regards
sandro

**Comment by pvictor** [comment]
Thanks for reporting this, it should be fixed if you re-install from GitHub.

Victor

**Comment by shosaco** [comment]
Dear Victor,

thanks, it works when `range = FALSE`. However, with `range = TRUE`, i.e. the user selects a date range, the picker remains open. Is there any way to fix that?

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
    airDatepickerInput(
        inputId = "test",
        range = TRUE,
        autoClose = TRUE
    )
)

server <- function(input, output) {}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Unfortunately `autoClose` don't work when `range = TRUE`.
I added `show` / `hide` arguments to `updateAirDateInput`, so you can do something like: 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  airDatepickerInput(
    inputId = "test",
    range = TRUE
  ),
  verbatimTextOutput("res")
)

server <- function(input, output, session) {
  output$res <- renderPrint(input$test)
  observeEvent(input$test, {
    if (length(input$test) == 2) {
      updateAirDateInput(session, "test", hide = TRUE)
    }
  })
}

shinyApp(ui, server)
```

Victor

**Comment by shosaco** [comment]
Thanks Victor, that works for me.
