### ISSUE TITLE
incompatibility between actionBttn and prettyRadioButtons

### ISSUE THREAD

**Issue by harveyl888** [dreamRs/shinyWidgets#37]
I can't seem to use both actionBttn and prettyRadioButtons in the same app.  Looks like there could be an incompatibility between the libraries.

### actionBttn followed by prettyRadioButtons
```r
library(shiny)
library(shinyWidgets)

server <- function(input, output, session) {
}

ui <- fluidPage(
  actionBttn(inputId = 'but1', label = 'but1'),
  prettyRadioButtons(inputId = 'rad1', label = 'rad1', choices = c(1,2,3), inline = TRUE, shape = 'square')
)

shinyApp(ui, server)
```

![action-radio](https://user-images.githubusercontent.com/7786963/33943579-849bb4d4-dfe7-11e7-95df-5aa3499ba2a6.jpg)

### prettyRadioButtons followed by actionBttn 

```r
library(shiny)
library(shinyWidgets)

server <- function(input, output, session) {
}

ui <- fluidPage(
  prettyRadioButtons(inputId = 'rad1', label = 'rad1', choices = c(1,2,3), inline = TRUE, shape = 'square'),
  actionBttn(inputId = 'but1', label = 'but1')
)

shinyApp(ui, server)

```
![radio-action](https://user-images.githubusercontent.com/7786963/33943638-ae7d9fce-dfe7-11e7-97da-cb88fa15852c.jpg)

**Comment by pvictor** [comment]
Hello,
Sorry about this bug, there was a problem in the dependencies after the pull request #30 .
Try re-installing from Github.

Victor

**Comment by harveyl888** [comment]
Thanks!  I can confirm that it now works after reinstalling from Github.
