### ISSUE TITLE
Icons are missing from `switchInput`

### ISSUE THREAD

**Issue by euf** [dreamRs/shinyWidgets#376]
Reproducible example:

```r
library(shiny)
library(shinyWidgets)
ui <- fluidPage(
  switchInput("test1", offLabel = icon("moon")),
  switchInput("test2", label = as.character(icon("sun"))),
  verbatimTextOutput("value")
)
server <- function(input, output) {
  output$value <- renderPrint({ c(input$test1, input$test2) })
}
shinyApp(ui, server)
```

![image](https://user-images.githubusercontent.com/11754264/112059952-986e6580-8b6d-11eb-9150-6ab6b94e6362.png)

**Comment by pvictor** [comment]
Thanks, that's fixed if you reinstall from GitHub.
Currently you have to add icon's HTML dependency manually (by including an icon somewhere in your app).

Victor

**Comment by euf** [comment]
Thanks, it worked!
