### ISSUE TITLE
Can searchInput implements autocomplete?

### ISSUE THREAD

**Issue by ShixiangWang** [dreamRs/shinyWidgets#378]
I think this feature would be very helpful. Is there a solution?

**Comment by pvictor** [comment]
Yes that's interesting. With a JavaScript library such as [autoComplete.js](https://tarekraafat.github.io/autoComplete.js/#/) it's possible, maybe in a new widget it will be easier. Are you interested to submit a PR ? I can help

**Comment by ShixiangWang** [comment]
Sorry, I know little about js. :( I hope someone can implement it.
