### ISSUE TITLE
Headings in awesomeCheckboxGroup

### ISSUE THREAD

**Issue by simon-tarr** [dreamRs/shinyWidgets#383]
`pickerInput` allows you to pass a named list (e.g. `names(my_list)`) to the `choices` argument. The names become headings and the choices are items within each named list. Is it possible to replicate this heading functionality in `awesomeCheckboxGroup`? Thanks!

**Comment by pvictor** [comment]
No that's not possible with `awesomeCheckboxGroup`, but I think you can easily create a shiny module to do that.

Victor
