### ISSUE TITLE
update_on argument for pickerInput

### ISSUE THREAD

**Issue by shosaco** [dreamRs/shinyWidgets#392]
Hi there,

I'd like to update the value of the `pickerInput` only after closing the dropdown, not right after selecting a new option. There is an awesome argument `airDatePickerInput()` that solves exactly that: `update_on = c("change", "close")`

Is there any way that I can use that in `pickerInput()`?

Thanks,
sandro

**Comment by pvictor** [comment]
Hello,

No, there's no similar argument for `pickerInput`, but there's a special `input` to know if menu is open or not. So you can use an intermediate `reactiveValue` to achieve same result:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  fluidRow(
    column(
      width = 4,
      pickerInput(
        inputId = "ID",
        label = "Select:",
        choices = month.name,
        multiple = TRUE
      )
    ),
    column(
      width = 4,
      "Immediate:",
      verbatimTextOutput("value1"),
      "Updated after close:",
      verbatimTextOutput("value2")
    ),
    column(
      width = 4,
      "Is picker open ?",
      verbatimTextOutput("state")
    )
  )
)

server <- function(input, output) {
  
  output$value1 <- renderPrint(input$ID)
  output$value2 <- renderPrint(rv$ID_delayed)
  output$state <- renderPrint(input$ID_open)
  
  rv <- reactiveValues()
  observeEvent(input$ID_open, {
    if (!isTRUE(input$ID_open)) {
      rv$ID_delayed <- input$ID
    }
  })
}

shinyApp(ui, server)
```

Victor

**Comment by shosaco** [comment]
Thanks Victor,

that's exactly what I desperately needed! Terrific! It would be great to have any documentation about that in `?pickerInput`...

Best regards,
sandro
