### ISSUE TITLE
change background-color of selected item in verticaltabsetpanel

### ISSUE THREAD

**Issue by numberinho** [dreamRs/shinyWidgets#393]
First of all i want to thank you for creating and publishing so many awesome packages! Your work is awesome! With the new release of shinydashboardPlus you outdid yourself! =D

To my issue: I'm having trouble to switch the background-color of the selected item in the left hand side of  a verticaltabsetpanel. 

Adding 
```
tags$head(tags$style(HTML('
#MYID-tabbable > div.vrtc-tab-panel-menu div.list-group>a.active,
#MYID-tabbable > div.vrtc-tab-panel-menu div.list-group>a.active .glyphicon, 
#MYID-tabbable > div.vrtc-tab-panel-menu div.list-group>a.active .fa {
    background-color: green!important;
    background-image: green !important;
    color: #ffffff !important;}'
)))
```

is not working as it's supposed to do. (Is it supposed to do?)

Even if i change it directly in "vertical-tabset-panel.css" it is not working.
 ```
div.vrtc-tab-panel-menu div.list-group > a.active,
div.vrtc-tab-panel-menu div.list-group > a.active .glyphicon,
div.vrtc-tab-panel-menu div.list-group > a.active .fa {
  background-color: green;
  background-image: green;
  color: #ffffff;
}
```

Though, changing the same code in the browser while an app is running, works.

Could you please help me?

Edit: I'm using the new "midnight" skin, in the initial post i did not mention it. There should not be a conflict, right?

**Comment by pvictor** [comment]
Thanks :)
Using `color` argument doesn't do what you want ?

Victor

**Comment by numberinho** [comment]
Not really, because `color` does not change just the background-color. But it's such a rare case somebody will need this, I guess its not worth changing. I found out the .css file will be "overridden" by "/R/vertical-tab.R", so i modified it and pass an argument for "background_color_active". Now it's working!
Thank you for your help!

Simon

**Comment by pvictor** [comment]
Ok great if it works for you. I'm closing this, but I'm curious to see what you have changed, if you can post an example or just screenshots that will be great !

**Comment by numberinho** [comment]
Hey Victor, I edited the file "vertical-tab.R", which "overrides" the seperate .css file.  (Not really overrides, but places the css right before the element)

I added the following parameter to the "verticalTabsetPanel" function:

`verticalTabsetPanel <- function(..., selected = NULL, id = NULL, color = "#112446", contentWidth = 9, menuSide = "left", background_active = "#112446")`

and simply pasted it into "vtabStyle"

```
vtabStyle <- tags$style(
...
    HTML(sprintf(paste0(
      "#%s-tabbable > div.vrtc-tab-panel-menu div.list-group>a.active,
      #%s-tabbable > div.vrtc-tab-panel-menu div.list-group>a.active .glyphicon,
      #%s-tabbable > div.vrtc-tab-panel-menu div.list-group>a.active .fa{
       background-color: ", background_active ," !important;
       background-image: %s !important;
       color: #ffffff !important;
      }"),
      id, id, id, color
    )),
...
)
```

Seems to be quick'n'dirty but did the job! Thank you for replying to this issue and being so active and interested! You do an awesome job!!!! :-)
