### ISSUE TITLE
Faild to load resource: the server responded with a status of 404 

### ISSUE THREAD

**Issue by apalacio10** [dreamRs/shinyWidgets#394]
Hello,

In the developer version of shiny when a pickerInput is added the following error appears in the js console.

![imagen](https://user-images.githubusercontent.com/40868159/124047490-f23ac300-d9d9-11eb-8f80-0269eea73693.png)

**Comment by pvictor** [comment]
This file is only needed for debugging purposes, it won't affect your application.
