### ISSUE TITLE
sliderInput

### ISSUE THREAD

**Issue by MacBurt** [dreamRs/shinyWidgets#397]
sliderInput is having issues in 0.6.0 
![image](https://user-images.githubusercontent.com/87393769/125519677-d0290690-0c59-4225-8b0c-091153c477f6.png)

**Comment by MacBurt** [comment]
The issue might be a compatibility with shiny 1.6.0. 
Shiny 1.5.0 and shinywidget 0.5.3 will give me a nice sliderInput.

**Comment by pvictor** [comment]
Hello,

What's your code exactly ?
