### ISSUE TITLE
searchInput buttons not adhere to text box in shinydashboard sidebar area

### ISSUE THREAD

**Issue by steve-liang** [dreamRs/shinyWidgets#40]
Great work first of all!

I noticed my older app built in 0.3.2 behaves a little differently after I upgraded shinyWidgets to 0.3.4+. searchInput **in shinydashboard's sidebar** now gets separated into 3 components: Textbox, search button and remove button. This is likely due to changes from tags to htmltools::tags

I am no shiny expert but this is likely the only changes made that affects the searchInput functionality.

**Comment by pvictor** [comment]
Thank you!

Mmmh you're right, that's ugly :( 
Was it working before? I'll look into it !

Victor

**Comment by steve-liang** [comment]
Yup it was working perfectly with the three components adhered as one. I wonder if the sidebar width makes it quirky.

**Comment by pvictor** [comment]
Ok,' have found out what has changed, the buttons have been converted to actionButton in version 0.3.3, and shinydashboard adds css properties to those when they are placed in the sidebar...

Normally it's fixed, but just tested on this simple example : 

```r
library(shiny)
library(shinyWidgets)
library(shinydashboard)


shinyApp(
  ui = dashboardPage(
    dashboardHeader(title = "searchInput"),
    dashboardSidebar(
      searchInput(
        inputId = "search", label = "Enter your text",
        placeholder = "A placeholder",
        btnSearch = icon("search"),
        btnReset = icon("remove")
      )
    ),
    dashboardBody(
      searchInput(
        inputId = "search2", label = "Enter your text",
        placeholder = "A placeholder",
        btnSearch = icon("search"),
        btnReset = icon("remove")
      )
    ),
    title = "Dashboard example"
  ),
  server = function(input, output) { }
)
```


If that's good for you, I'll let you close the issue. 

Victor

**Comment by steve-liang** [comment]
Thanks for fixing that! I am closing the issue now.
