### ISSUE TITLE
confirmSweetAlert/ask_confirmation option to not set to `FALSE` on close button or outside

### ISSUE THREAD

**Issue by lz100** [dreamRs/shinyWidgets#400]
Can we have an option that `confirmSweetAlert` will only set the value to `FALSE` when the `cancel` button is clicked. Clicking outside or use the "X" button to close the modal will not set the value to `FALSE`?

This will be useful if we want to observe 3 types of event:

1. confirm, `TRUE`, do some things
2. cancel, `FALSE`, do some other things
3. dismiss, `NULL`, do nothing

Another possibility is to add one more dismiss button. This will be similar to what we see in most programs which ask you to save: `Cancel`, `No`, `Yes`

**Comment by pvictor** [comment]
Hello,

That's a good idea, I added a new argument `cancelOnDismiss` to allow this behavior.

If `cancelOnDismiss = TRUE` (default), value will be : 
* `TRUE` if confirm button is clicked
* `FALSE` in any other case

If `cancelOnDismiss = FALSE`, value will be : 
* `TRUE` if confirm button is clicked
* `NULL` if dialog is closed by clicking outside or the close button, or using `Esc` key (corresponding arguments needs to be `TRUE` to allow such behavior)
* `FALSE`  if cancel button is clicked

Let me know how it works for you.

Victor

**Comment by lz100** [comment]
Thank you! This is what I proposed.
