### ISSUE TITLE
updateAirMonthInput and Ability to Update More Parameters

### ISSUE THREAD

**Issue by szmsu2011** [dreamRs/shinyWidgets#402]
Thanks for the continuous development of the package.

I wonder if it is possible to update the parameters in `airMonthpickerInput()`, similar to the currently only available one `updateAirDateInput()`.

Moreover, is it possible update more parameters in this type of functions? For example, if I want to change the `minDate` and `maxDate` of my `airMonthpickerInput`.

Thank you in advance.

**Comment by pvictor** [comment]
Hello Stephen,

Thanks :). 
Sure you can use `updateAirDateInput()` for that, `airMonthpickerInput()` is in fact a wrapper of `airDatepickerInput()` with `view = "month"` and some other options.
And to update `minDate` and `maxDate` you can use a `list` in `options` parameter.

Here's an example:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  airMonthpickerInput(
    inputId = "month",
    label = "Select month:"
  ),
  verbatimTextOutput("res"),
  actionButton("update", "Update month picker")
)

server <- function(input, output, session) {
  output$res <- renderPrint(input$month)
  
  observeEvent(input$update, {
    updateAirDateInput(
      session = session,
      inputId = "month",
      options = list(
        minDate = "2021-02-01",
        maxDate = "2021-09-01"
      )
    )
  })
}

shinyApp(ui, server)
```

Victor
