### ISSUE TITLE
Using choiceOptions/icon in pickerInput with fontawesome requires at least one other icon consumer 

### ISSUE THREAD

**Issue by dmenne** [dreamRs/shinyWidgets#403]
I assume that `pickerInput` does not correctly initialize the fontawesome icon system; no such problem with glyphicon. By adding one arbitrary icon consumer in `ui`, one can enable dropdown icons.

Windows, shinywidgets from github 0.6.0, 2021-03-15 20:24:55 UTC; perri

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  pickerInput(
    "sel",
    "Select",
    selected = "all",
    choices = letters[1:3],
    options = list(`icon-base` = "fa"),
    choicesOpt = list(
      icon = c("fa-arrow-left",
               "fa fa-arrow-right",
               "fa fa-cog")
    ),
  ),
 actionBttn("forw", "forward")
  # No icons visible in the picker, but you can enable these
  # with the following line
  # ,actionBttn("back", NULL,  icon = icon("caret-left"))
)

server <- function(input, output, session) {}
shinyApp(ui = ui, server = server)

**Comment by pvictor** [comment]
When you use `icon()` in your UI definition, it attach to the page an [`htmlDependency`](https://rstudio.github.io/htmltools/reference/htmlDependency.html) to load FontAwesome CSS files.
When you use icons as characters, like in `pickerInput()`, the FontAwesome dependency is not attached.

So to attach the dependency you have to use an other icon else where in your UI, or you can use `htmltools::findDependencies(icon("home"))`.

Victor

**Comment by dmenne** [comment]
Thanks. Maybe put it into the documents? This has cost me half a day to resolve, because sometimes "it worked"
