### ISSUE TITLE
materialSwitch breaks layout when in centered column

### ISSUE THREAD

**Issue by pieterjanvc** [dreamRs/shinyWidgets#408]
Hi,

Let me start by saying I love these widgets and think you did a great job in designing them!

Unfortunately, I discovered that the `materialSwitch` (and possibly other widgets too) breaks its shape when used in a centered column in Shiny. I'm pretty sure it's a CSS inheritance issue, but I can't immediately figure it out and I'm sure you can fix this quickly.

REPREX
```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  fluidRow(
    column(12, materialSwitch("testSwitch", label = NULL, 
                              value = TRUE, inline = T, status = "success"),
           align = "center")
  )
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```

![image](https://user-images.githubusercontent.com/52793278/131120582-37748f8d-fd6e-47c7-a850-2e8133768915.png)

Thanks for looking into it,
PJ

**Comment by pvictor** [comment]
Hello PJ,

Yes some CSS rules inheritance problem, you can try:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  fluidRow(
    column(
      # style = "text-align: center;",
      align = "center",
      width = 12, 
      htmltools::tagAppendAttributes(
        materialSwitch(
          inputId = "testSwitch",
          label = NULL, 
          value = TRUE, 
          inline = TRUE,
          status = "success"
        ),
        style = "text-align: initial;"
      ),
      
    )
  )
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```

Or see alternative in https://github.com/dreamRs/shinyWidgets/issues/315#issuecomment-704122057

Victor
