### ISSUE TITLE
different colors for radioGroupButtons

### ISSUE THREAD

**Issue by systats** [dreamRs/shinyWidgets#41]
Hi folks, first you've created a wonderful package with dozens of features that I frequently use. Thanks for that! In one application I want to measure the sentiment of a given tweet. 

```
radioGroupButtons(
    inputId = "sent", 
    label = h3("Sentiment"), 
    choiceValues = -2:2, 
    choiceNames = paste0(-2:2),
    justified = T
)
```
The result is well known: 

![screenshot 2018-01-09 17 16 49](https://user-images.githubusercontent.com/22753281/34731048-6d8a0f86-f561-11e7-8303-37830461ef4d.png)

(`-2` is active)

But the coloring I'm looking for is 

![screenshot 2018-01-09 17 16 49 kopie](https://user-images.githubusercontent.com/22753281/34731124-a9bcdf74-f561-11e7-8ed5-5768f3fbde35.png)

Do you know how to tweak the code to get a kind of result?
Thanks in advance!
Simon

**Comment by pvictor** [comment]
Hi! Thank you for your compliments! We are delighted that you are using the package!
Unfortunately radioGroupButtons does not support individual CSS classes for buttons, but it's a good idea!

The only solution I see is to do some JavaScript: 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$h1("Custom for radioGroupButtons"),
  tags$br(),
  radioGroupButtons(
    inputId = "sent", 
    label = h3("Sentiment"), 
    choiceValues = -2:2, 
    choiceNames = paste0(-2:2),
    justified = TRUE, width = "300px"
  ),
  tags$script("$(\"input:radio[name='sent'][value='-2']\").parent().css('background-color', '#DE6B63');"),
  tags$script("$(\"input:radio[name='sent'][value='-1']\").parent().css('background-color', '#EDB6B2');"),
  tags$script("$(\"input:radio[name='sent'][value='0']\").parent().css('background-color', '#E7E7E7');"),
  tags$script("$(\"input:radio[name='sent'][value='1']\").parent().css('background-color', '#B2EDB5');"),
  tags$script("$(\"input:radio[name='sent'][value='2']\").parent().css('background-color', '#7EF373');"),
  verbatimTextOutput(outputId = "res")
)

server <- function(input, output, session) {
  output$res <- renderPrint(input$sent)
}

shinyApp(ui, server)
```

This is little verbose, but we get expected result : 

![image](https://user-images.githubusercontent.com/4415580/34732097-84951664-f564-11e7-8272-e54689435f4b.png)

Victor

**Comment by systats** [comment]
It works perfectly fine, very useful! Thank you Victor. Though I don't understand the javascript. This remains a goal of 2018...  One last question :D Do you know how to get a more precise/visual response when clicking the button?

**Comment by pvictor** [comment]
You're welcome !
An attempt to explain the JavaScript code : 

```
$("input:radio[name='sent'][value='-2']") // select with jQuery the input of type radio and name/inputId 'sent'
                                          // and button with specific value '-2' 
  .parent()                               // select the parent element, the button itself
  .css('background-color', '#DE6B63');    // set the background color
```

The easy way to get a more visual responce when button is clicked, is to put an icon on it with `checkIcon = list(yes = icon("check"))`, like this : 

```r
radioGroupButtons(
    inputId = "sent", 
    label = h3("Sentiment"), 
    choiceValues = -2:2, 
    checkIcon = list(yes = icon("check")),
    choiceNames = paste0(-2:2),
    justified = TRUE, width = "300px"
)
```
Result looks like this : 

![image](https://user-images.githubusercontent.com/4415580/34733651-668b2a32-f569-11e7-958c-9ebb4bea94d5.png)

You can also put an icon on buttons not clicked with `checkIcon = list(yes = icon("check"), no = icon("remove"))`

Hope it helps !

**Comment by systats** [comment]
Awesome!

**Comment by pvictor** [comment]
Since shinyWidgets [v0.6.3](https://github.com/dreamRs/shinyWidgets/releases/tag/v0.6.3), you can use a vector of status for the buttons, so you can style buttons directly with CSS, e.g. : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$h1("Custom colors via status for radioGroupButtons"),
  tags$br(),
  
  # Custom CSS for third button
  tags$style(
    ".btn-three {background-color: blue; color: white;}",
    ".btn-three.active {background-color: red; color: white;}"
  ),
  
  radioGroupButtons(
    inputId = "sent", 
    label = h3("Sentiment"), 
    choiceValues = -2:2, 
    choiceNames = paste0(-2:2),
    justified = TRUE, 
    status = c("one", "two", "three", "four", "five"), # custom status, will be prefixed by "btn-"
    width = "300px"
  ),
  verbatimTextOutput(outputId = "res")
)

server <- function(input, output, session) {
  output$res <- renderPrint(input$sent)
}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Yes and my example show how to change the color of the button when selected, have you run it ?
If you have a new question, open a new issue please.
