### ISSUE TITLE
Unable to change alert font size

### ISSUE THREAD

**Issue by rbcavanaugh** [dreamRs/shinyWidgets#411]
My knowledge of CSS is limited so I apologize if there is a simple solution to this that I'm not aware of. 

I'd like to change the size of the modal and the font size within for a confirmsweetalert. It's a bit too big and jarring (IMO). 

Changing the size of the modal wasn't too bad: 

```
.swal2-popup {
    width: 20em;
}
```

however, the default css on the font size uses `!important` and I can't figure out how to override it. Is this possible? 

```
.swal2-popup {
    font-size: 1.2rem !important;
}
```

**Comment by pvictor** [comment]
Hello,

If you put `tags$style(".swal2-popup {font-size: 1rem !important;}")` somewhere in your UI it should work, it'll change size of window, text and buttons, for text you can also use HTML directly:

```r
library(shiny)
library(shinyWidgets)


ui <- fluidPage(
  tags$h1("Ask the user for confirmation"),
  tags$style(".swal2-popup {font-size: 1rem !important;}"),
  actionButton(
    inputId = "launch",
    label = "Ask for confirmation"
  ),
  verbatimTextOutput(outputId = "res")
)

server <- function(input, output, session) {
  
  # Launch sweet alert confirmation
  observeEvent(input$launch, {
    ask_confirmation(
      inputId = "myconfirmation",
      text = tagList(
        tags$h1("H1 header"),
        tags$p("Normal text"),
        tags$p("Small text", style = "font-size: 50%;")
      ),
      html = TRUE
    )
  })
  
  # raw output
  output$res <- renderPrint(input$myconfirmation)

}

if (interactive())
  shinyApp(ui, server)
```

Victor

**Comment by rbcavanaugh** [comment]
Thank you! I had packaged the app using {golem} and it seems like the stylesheet added using `addResourcePath` was not the highest priority. 

Adding `tags$style(".swal2-popup {font-size: 1rem !important;}")` to the UI did the trick. Using HTML within the alert call was not ideal because the button sizes were still quite large (I'm sure easy enough to change).

**Comment by pvictor** [comment]
If you want to customize button, you can do this if you install last version from GitHub:

```r
library(shiny)
library(shinyWidgets)


ui <- fluidPage(
  tags$h1("Ask the user for confirmation"),
  tags$style(".btn-sw {margin: 10px;}"),
  actionButton(
    inputId = "launch",
    label = "Ask for confirmation"
  ),
  verbatimTextOutput(outputId = "res")
)

server <- function(input, output, session) {
  
  # Launch sweet alert confirmation
  observeEvent(input$launch, {
    ask_confirmation(
      inputId = "myconfirmation",
      text = tagList(
        tags$h1("H1 header"),
        tags$p("Normal text"),
        tags$p("Small text", style = "font-size: 50%;")
      ),
      html = TRUE,
      buttonsStyling = FALSE,
      customClass = list(
        cancelButton = "btn btn-danger btn-sw",
        confirmButton = "btn btn-success btn-sw"
      )
    )
  })
  
  # raw output
  output$res <- renderPrint(input$myconfirmation)
  
}

if (interactive())
  shinyApp(ui, server)
```
