### ISSUE TITLE
Display additional lines in pickerInput()

### ISSUE THREAD

**Issue by GitHunter0** [dreamRs/shinyWidgets#412]
Hi folks, `pickerInput()` is great, it offers a variety of useful options. 

However, I miss an important one, which is the ability to show more lines with custom additional information.

I would like to achieve a result like this:
![image](https://user-images.githubusercontent.com/26294221/132029351-152d91af-210d-4e0f-8440-3b488a97cb53.png)

The first line displays the item name as usual but there is a __second line__ which displays extra information relative to that item. 

This feature is incredibly useful (at least in my applications) and would allow me to build more professional Shiny apps.

Would you consider adding that to `shinyWidgets`?

Thank you

**Comment by pvictor** [comment]
You can already do something similar with `pickerInput()` by using custom HTML in `content` property of `choicesOpt` argument. Check this example:

```r

library(shiny)
library(htmltools)
library(shinyWidgets)

ui <- fluidPage(
  tags$style("span.text {display: block !important;}"), # to make items in dropdown full width
  pickerInput(
    inputId = "ID",
    label = "Select:",
    choices = month.name,
    choicesOpt = list(
      content = unlist(lapply( # create custom HTML to display in dropdown
        X = month.name,
        FUN = function(x) {
          doRenderTags(tags$div(
            tags$div(
              style = css(fontWeight = "bold"),
              x
            ),
            splitLayout(
              tags$div("AAA:", sample(100, 1)),
              tags$div("BBB:", sample(100, 1)),
              tags$div("CCC:", sample(100, 1))
            )
          ))
        }
      ))
    ),
    options = pickerOptions(showContent = FALSE) # if TRUE then HTML content is used in button, if FALSE only choice value
  ),
  verbatimTextOutput("res")
)

server <- function(input, output, session) {
  output$res <- renderPrint(input$ID)
}

shinyApp(ui, server)
```

Victor

**Comment by GitHunter0** [comment]
@pvictor thanks man! I will try to use that
