### ISSUE TITLE
PickerInput does not work with bslib 

### ISSUE THREAD

**Issue by apalacio10** [dreamRs/shinyWidgets#416]
Hello there,

I have been testing the library in an application that uses bslib to customize the ui. If I use bootstrap version 5> the pickerinput widget does not show the dropdown list. I think it is related to the z-index.
@cpsievert 

`library(shiny)
library(shinyWidgets)

ui <- fluidPage(
    theme =  bslib::bs_theme(version = 5),

    titlePanel("Test"),
    sidebarLayout(
        sidebarPanel(
            pickerInput("bins","Number of bins:",choices = seq(1,50),selected = 30)
            ),
        mainPanel(
           plotOutput("distPlot")
        )
    )
)

server <- function(input, output) {

    output$distPlot <- renderPlot({
        x    <- faithful[, 2]
        bins <- seq(min(x), max(x), length.out = as.numeric(input$bins) + 1)
        hist(x, breaks = bins, col = 'darkgray', border = 'white')
    })
}

shinyApp(ui = ui, server = server)`

Thanks

**Comment by pvictor** [comment]
Hello,

No `pickerInput` currently does not support Bootstrap 5.

Victor

**Comment by bcaessens** [comment]
Hi,

I think the same applies to the radioGroupButtons under Bootstrap 5, implemented through bslib. The UI elements show the radio (icons, always). In addition, the click behaviour is such that you need to click the radio icon to 'respond'. When I inspect the element in browser, I noticed that the btn radiobtn style is not found/applied, even through shinywidgets.css is correctly loaded and has the style. So somehow bootstrap 5 styles supercede/overwrite this. 

Kind regards,
Bernie

**Comment by pvictor** [comment]
Thanks @bcaessens for the report, should be fixed if you re-install from GitHub.

**Comment by bcaessens** [comment]
Hi @pvictor. Thanks for this. However, still seems to be an issue (or I am doing something wrong). 

re-installed using remotes::install_github()
new session opened

Here is how it looks for checkboxGroupButtons (similar for radioGroupButtons): 
![Screenshot 2021-12-07 at 13 28 18](https://user-images.githubusercontent.com/10197597/145029476-c1d22e42-87e2-44ed-9d35-3560cf47a3b8.png)

This is running bslib with the bootstrap 5 version. But still the radio icons show up, and also, I can only click these icons, not the button to select this. On closer inspection, the css styles in shinywidgets for these buttons are not loaded for these elements. 

The code gets called from a file called utilities.R (which build the input elements) and is passed into a module. The namespace of the module is passed to the function and back, and all of that is working correct. 

Weird stuff. Anyway, thx for looking into this. 
Bernie.

**Comment by pvictor** [comment]
Mmh maybe can you open a new issue ?
I think the problem is caused by the moment when you generate the buttons. 
I see two solutions:
* use input functions only in UI context (don't store result into objects)
* declare your theme globally with `shiny::shinyOptions(bootstrapTheme = bslib::bs_theme(version = 5))`

**Comment by bcaessens** [comment]
Hi Victor,

Thx for your response. The global options don't seem to have much of an effect. I will dive into this issue as soon as this customer project is finished. We work around it now anyways with classic radiobuttons. Still looks ok. I'll see what I can figure out and then open this in a new issue (hopefully with a solution :-) ) .
Thank you so much. 
Bernie.
