### ISSUE TITLE
wildcard search in pickerInput()

### ISSUE THREAD

**Issue by doncqueurs** [dreamRs/shinyWidgets#418]
I would like a wildcard search option in the the liveSearch of the pickerInput(). The use case would be if I have a long list of street addresses including multiple streets names and home numbers in all streets. A line could look like "Charles Ave #12",  "Charles Ave #34" or "Times sq #12". 

It would be great if in the liveSearch I can type something along the lines of "Charles 12" to find the first of the list above.

**Comment by pvictor** [comment]
Hello,

If [options](https://developer.snapappointments.com/bootstrap-select/options/) for `liveSearch` do not suit your needs, you should open an issue here: https://github.com/snapappointments/bootstrap-select/issues

Victor
