### ISSUE TITLE
Possible to remove spacing between every 3 numeric digits?

### ISSUE THREAD

**Issue by philstraforelli** [dreamRs/shinyWidgets#42]
For instance:

    sliderTextInput(inputId = "year", grid = TRUE, label = "Select year", choices = c("2012", "2014", "2016"))

[There appears to be a space between the 2 and the 0](https://i.imgur.com/iPTnJo3.png). Is there an option to remove the spacing?

**Comment by pvictor** [comment]
It's fixed ! Try re-install the package.

Note: what you're trying to achieve is doable with `sliderInput` from `shiny`.

**Comment by philstraforelli** [comment]
Thanks! I'll be honest - I have gotten so used to using your inputs over Shiny's default inputs that I've forgotten about it. :)

**Comment by pvictor** [comment]
Coool :) 
I close the issue, I plan to release on CRAN soon.
