### ISSUE TITLE
justified parameter of radioGroupButtons does not work with bslib

### ISSUE THREAD

**Issue by mhanf** [dreamRs/shinyWidgets#423]
Hello there,
I have been testing the library shinyWidgets in an application that uses bslib to customize the ui. If I use bootstrap version = 4 the justified parameter of radioGroupButtons does not work. A similar problem is observed for checkboxGroupButtons.

Here is an example :

ui<-shiny::fluidPage(
  theme = bslib::bs_theme(version = 4),
  shinyWidgets::radioGroupButtons(
    inputId = "Id066",
    label = "Label",
    choices = c("A", "B", "C"),
    justified = TRUE,
    status = "danger"
  )
)

server <- function(input, output, session) { }

shiny::shinyApp(ui = ui, server = server)

Many thanks in advance

**Comment by pvictor** [comment]
Hello,

Thanks for reporting this, should be fixed if you re-install from GitHub.

Victor

**Comment by mhanf** [comment]
hello Victor
thank you so much for your reply. I install shinyWidgets from github and this solved the problem. However this test made me discover another problem. When justified = TRUE the option individual doesn't work (both for bs3 and bs4) : no margin is visible between buttons for radioGroupButtons and checkboxGroupButtons. 
Here is an example in case of :

ui<-shiny::fluidPage(
  theme = bslib::bs_theme(version = 4),
  shinyWidgets::checkboxGroupButtons(
    inputId = "id1",
    label = "OK",
    selected = "A",
    choices = c("A","B","C"),
    individual = TRUE,
    justified = FALSE),
  shinyWidgets::checkboxGroupButtons(
    inputId = "id2",
    label = "Problem",
    selected = "A",
    choices = c("A","B","C"),
    individual = TRUE,
    justified = TRUE)
)

server <- function(input, output, session) { }

shiny::shinyApp(ui = ui, server = server)

Thank Again
Best regard
Matthieu
