### ISSUE TITLE
Bootstrap Multiselect

### ISSUE THREAD

**Issue by markwsac** [dreamRs/shinyWidgets#427]
Thanks for developing this useful package. I use it a lot. Kudos to the team!

Would it be possible to add this JS library for selecting multiple items -
https://davidstutz.github.io/bootstrap-multiselect/

**Comment by pvictor** [comment]
Seems interesting, do you want to contribute ? You can find documentation on how to implement such library here: https://divadnojnarg.github.io/outstanding-shiny-ui/

Victor
