### ISSUE TITLE
updatePickerInput encoding inconsistent with that of pickerInput

### ISSUE THREAD

**Issue by Eli-Berkow** [dreamRs/shinyWidgets#43]
Hi

Thanks so much for the amazing package.

Please see the example below (I edited your example for `pickerInput`):

```
library(shiny)
library(shinyWidgets)

test = "Jean Mare’"
ui <- fluidPage(
    pickerInput(inputId = "somevalue", label = "A label", choices = test),
    verbatimTextOutput("value"),
    actionBttn('update', 'Update')
)
server <- function(input, output, session) {
    output$value <- renderPrint({ input$somevalue })
    observeEvent(input$update, {
        updatePickerInput(session = session, 
                          inputId = 'somevalue', 
                          choices = test)
    })
}
shinyApp(ui, server)
```

The issue as far as I can tell is the apostrophe http://www.fileformat.info/info/unicode/char/92/index.htm. However, I am wondering why pickerInput displays an unknown character box whereas updatePickerInput displays nothing. Both display:

`[1] "Jean Mare<U+0092>"`

in the verbatimTextOutput.

The encoding seems to be latin1 as below:
```
> test
[1] "Jean Mare'"
> Encoding(test)
[1] "latin1"
```

It does not end there though...

If I run that script directly in the console I get the above but if I create an app and run the script then pickerInput displays Jean Mare’ correctly and verbatimTextOutput displays the unknown character box `[1] "Jean Mare"`, while updatePickerInput displays the unknown character box and `[1] "Jean Mare<U+0092>"` in the verbatimTextOutput.

Finally, my app at https://elib.shinyapps.io/EncodingBug/ displays Jean Mare’ for both pickerInput and updatePickerInput and [1] "Jean Mare’" for verbatimTextOutput.

for comparison, the basic selectInput and updateSelectInput both display Jean Mare’ but `[1] "Jean Mare"` in the verbatimTextOutput. A breakpoint for both displays:

```
Browse[2]> input$somevalue
[1] "Jean Mare’"
```
Here's the real problem for me. For pickerInput it displays the same above correctly but for updatePickerInput it displays:

```
Browse[2]> input$somevalue
[1] "Jean Mare\u0092"
```
That really is my biggest problem as I cannot use that value to get the relevant data. I could hard-code it in this case but thought there might be something more to it.

I am sorry this is so long but I decided to try be as comprehensive as possible. There may be OS differences at play too. I am using a Windows 10 64-bit.

Looking forward to hearing from you,
Eli

**Comment by pvictor** [comment]
Hi,
Thank you for the example and explanation!
This seems to be an encoding issue on Windows.

When I replace : 
```r
test = "Jean Mare’"
```
by : 
````r
test = iconv("Jean Mare’", to = "latin1")
```
it works (I'm on windows to).

Let me know if it helps !

Victor

**Comment by Eli-Berkow** [comment]
Hi Victor

Thanks for the quick response.

I tested your suggestion which works if pasted directly in the console. However, when I saved it in a folder and "ran the app" it displays NA.

```
library(shiny)
library(shinyWidgets)

test = iconv("Jean Mare’", to = "latin1")
ui <- fluidPage(
    selectInput(inputId = "somevalue", label = "A label", choices = test),
    verbatimTextOutput("value"),
    actionBttn('update', 'Update')
)
server <- function(input, output, session) {
    output$value <- renderPrint({ input$somevalue })
    observeEvent(input$update, {
        updateSelectInput(session = session, 
                          inputId = 'somevalue', 
                          choices = test)
    })
}
shinyApp(ui, server)
```

I agree though that this seems to be more of a Windows encoding issue so I will have to explore other avenues.

Thanks again.

Regards
Eli

**Comment by Eli-Berkow** [comment]
global <- function(){test = iconv("Jean Mare’", to = "latin1")}

**Comment by pvictor** [comment]
Indeed this depends on the system where you run the app. And on how the string is encoded at start. 
With `test = iconv("Jean Mare’", to = "latin1")` the start encoding is not specified, you need to correctly save this string with proper encoding before reading back to R.

**Comment by Eli-Berkow** [comment]
Thanks Victor.

And thanks again, this package has proven invaluable.

Eli

**Comment by madmark81** [comment]
Pvictor. Did you get my mail about the issue we closed here last week?
