### ISSUE TITLE
Add week calendar mode

### ISSUE THREAD

**Issue by AlejandroAyllon** [dreamRs/shinyWidgets#430]
Hello,

Please, could you consider implementing a week calendar mode as https://sensortower.github.io/daterangepicker/ in `airDatepickerInput()`? The month and year mode is already implemented with `view` and `minView` option, but this behaviour is not available for the weeks. I think it would be a very useful feature in order to select weeks comfortably when the charts are showed by week.

Thank you in advance.

**Comment by AlejandroAyllon** [comment]
In addition, the UX would be better if the user can select the option view (day/week/month/year mainly). I mean, similar as the widget in the previous comment.

**Comment by pvictor** [comment]
That's more a suggestion for [air-datepicker](https://github.com/t1m0n/air-datepicker) repo itself.
For [daterangepicker](https://github.com/sensortower/daterangepicker) widget, those features are interesting, but I don't have plan to integrate it in shinyWidgets yet.
