### ISSUE TITLE
prettyToggle resets actionBttn design

### ISSUE THREAD

**Issue by mrska** [dreamRs/shinyWidgets#44]
Hi!

Your package is really  super awesome!

Please see the example below. 

While using prettyToggle and actionBttn in one app, the design of the button is like resetted (not sure if it's the proper word - image below)

![obraz](https://user-images.githubusercontent.com/23221437/35141053-e5e889c2-fcf9-11e7-9668-8fef4a543998.png)

However when I delete prettyToggle from the app, the actionBttn looks nice
![obraz](https://user-images.githubusercontent.com/23221437/35141096-121fed00-fcfa-11e7-92b9-4c538b299abf.png)

Why is it like that?
Here is the code, just basic. 

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  # prettyToggle(inputId = "toggle1",
  #              label_on = "Checked!",
  #              label_off = "Unchecked..."),
 actionBttn('button','Button', style='gradient')
  
)

server <- function(input, output, session) {

}
shinyApp(ui, server)
```

Thank you
Marta

**Comment by pvictor** [comment]
Hi Marta,

Thanks for your kind words :)
Install the lastest version from Github, it should be fixed.
Sorry for the inconvenience, I release on CRAN as soon as possible.

Best,

Victor
