### ISSUE TITLE
updateNumericRangeInput() - label not updating

### ISSUE THREAD

**Issue by fanpageste** [dreamRs/shinyWidgets#441]
Hi,
I have a Conditional Panel with a numericRangeInput with a label. When I try to pass a new label through an updateNumericRangeInput, it is not updating. The value argument in the updateNumericRangeInput does update though. 

Is this possible to fix this please? Thanks! :)

**Comment by jassler** [comment]
This seems like a bug, since calling `updateNumericInput` for the equivalent shiny component seems to update its label.

Meanwhile as an alternative you could replace the `label` in your UI element with a `textOutput` and use `renderText` on it to change its value.

```R
library(shiny)

ui <- fluidPage(
  shinyWidgets::numericRangeInput('a', textOutput('aLabel'), value = c(0, 5)),
  actionButton('change', label = 'Change label')
)

server <- function(input, output, session) {
  # reactive text value of our label
  rangeLabel <- reactiveVal('BEFORE label')

  # actual rendering of the text value
  output$aLabel <- renderText({ rangeLabel() })

  observeEvent(input$change, {
    # change value of reactive variable
    # that way renderText is called automatically
    rangeLabel('AFTER label')
  })
}

shinyApp(ui, server)
```

Or, if you're using `shinyjs`, `html()` can be pretty convenient.

```R
library(shiny)

ui <- fluidPage(
  shinyjs::useShinyjs(),
  shinyWidgets::numericRangeInput('a', 'BEFORE label', value = c(0, 5)),
  actionButton(inputId = 'change', label = 'Change label')
)

server <- function(input, output, session) {
  shinyjs::onclick('change', shinyjs::html(selector = '#a label', html = 'AFTER label'))
}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Thanks for reporting this, it should be fixed if you re-install from GitHub.
