### ISSUE TITLE
How to programmatically toggle dropdown?

### ISSUE THREAD

**Issue by kyleweise** [dreamRs/shinyWidgets#442]
There is documentation for the [creation of a dropdownButton](https://dreamrs.github.io/shinyWidgets/reference/dropdownButton.html), along with it's corresponding [toggle function](https://dreamrs.github.io/shinyWidgets/reference/toggleDropdownButton.html). However, there doesn't seem to be such any such toggle function for a [dropdown](https://dreamrs.github.io/shinyWidgets/reference/dropdown.html), although the documentation for the `inputId` parameter suggests as much: 

> inputId | Optional, id for the button, the button act like an actionButton, and you can use the id to toggle the dropdown menu server-side.

There is a workaround described [here](https://community.rstudio.com/t/programatically-toggle-a-shinywidgets-dropdown/49227/2), but this feels like something `shinyWidgets` should handle without the need for custom JS. 

Any thoughts?

**Comment by pvictor** [comment]
Yes there's no function to toggle `dropdown()` server-side, documentation is misleading, probably a bad copy/paste.
Surely doable, but I'm more tempted to deprecate this function in favor of [dropMenu()](https://dreamrs.github.io/shinyWidgets/reference/dropMenu.html) (yes, a third implementation...)

**Comment by kyleweise** [comment]
@pvictor Ah, I didn't know this existed. Interesting. I'll look into it!

**Comment by pvictor** [comment]
The width should be the one you set with `width:600px;`, what's in your UI ?
See the `placement` argument, maybe something like `placement = "right-end"` ?

**Comment by kyleweise** [comment]
@pvictor UI code is here (`dropMenu` code is commented out, switched back to `dropdown` to work on some other things):

```
fieldmappingUI <- function(id) {
  
  tagList(
    div(
      column(8,
             selectInput(
               inputId = NS(id, "fieldmapping_selection"),
               label = "Select Field Mapping",
               choices = c(Choose = '', mappings$mapping_name) 
             ),
      ),
      column(4,
             # shinyWidgets::dropMenu(
             #   tag = shinyWidgets::actionBttn(
             #     inputId = NS(id, "create_new_fieldmapping_btn"),
             #     label = "New",
             #     style = "unite"
             #    ),
             #   uiOutput(outputId = NS(id, "new_fieldmapping")),
             #   trigger = "click",
             #   options = dropMenuOptions(animation = 'fade'),
             #   placement = "right-start"
             # )
             shinyWidgets::dropdown(
               uiOutput(outputId = NS(id, "new_fieldmapping")),
               style = "unite",
               #icon = icon("plus-square"),
               label = "New",
               color = "primary",
               animate = animateOptions(
                 enter = animations$fading_entrances$fadeInLeftBig,
                 exit = animations$fading_exits$fadeOutRightBig
               ),
               up = T,
               width = "600px",
               inline = T
             )
      ),
      style = "display:inline-block",
      class = "form-group shiny-input-container"
      )
  )
}
```
