### ISSUE TITLE
Add drag and drop and remove button functionality to pickerInput

### ISSUE THREAD

**Issue by gacolitti** [dreamRs/shinyWidgets#444]
It would be cool if this functionality could be carried over to `pickerInput()`.

For example:

```r
shinyApp(
  ui = fluidPage(
    selectizeInput(
      inputId = "id",
      label = "Input",
      choices = c("a", "b", "c"),
      multiple = TRUE,
      selected = NULL,
      options = list(plugins = list("drag_drop", "remove_button"))
    ),
  ),
  server = function(input, output, session) {
    
  }
)
```

**Comment by pvictor** [comment]
Those functionnalities are nice but unfortunately they are not available in [bootstrap-select](https://github.com/snapappointments/bootstrap-select/), the javascript library used by `pickerInput`.

Victor
