### ISSUE TITLE
input values not available until menu is opened

### ISSUE THREAD

**Issue by madmark81** [dreamRs/shinyWidgets#45]
Hello, 
I have been trying the dropdownbutton in my app to see if it would be a nice improvement. 
In my app I construct a plotly plot from a custom fuction that takes a lot of input$variables to make the plot, i.e. marker size, axis titles etc are all coming from options the user has to customize the app. 
In the test version, all these inputs are in the main panel, so today I tried to put them inside a dropdownButton. However, it seems that non of the input elements register (i.e. input values not available) until the menu is opened. This means for me that on start up of the app, no plot can be made until the dropdownButton menu is opened. 
Is this normal?

**Comment by pvictor** [comment]
Hello,
Are your inputs in a server-side renderUi?

Victor

**Comment by madmark81** [comment]
yes they are indeed. Just found out that using a conditional panel causes the same problem, so I realize its a fundamental flaw in my approach.

**Comment by pvictor** [comment]
Yes that's the same :) 
You need `outputOptions` like below (comment/uncomment to see difference) : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$h1("Dropdown & inputs"),
  dropdownButton(
    icon = icon("sliders"), status = "info",
    uiOutput(outputId = "params")
  ),
  verbatimTextOutput(outputId = "res")
)

server <- function(input, output, session) {
  
  output$params <- renderUI({
    tagList(
      tags$b("Parameters:"),
      sliderInput(inputId = "slider", label = "Slider", min = 1, max = 100, value = 4),
      selectizeInput(inputId =  "selectize", label = "Selectize", choices = letters),
      radioButtons(inputId = "radio", label = "Radio", choices = month.abb[1:4]),
      checkboxGroupButtons(inputId = "checkbox", label = "Checkbox", choices = month.abb[1:4])
    )
  })
  
  # >>>>>>>> You need this line ! <<<<<<<<<
  outputOptions(x = output, name = "params", suspendWhenHidden = FALSE)
  
  output$res <- renderPrint({
    reactiveValuesToList(input)
  })
  
}

shinyApp(ui, server)
```

Victor

**Comment by madmark81** [comment]
Oh very elegant! I have come across that line of code long ago I remember now, but forgot about it. Much appreaciate the tip! Good luck with the continuation of your work on ShinyWidgets, I'm sure there are many interesting new features to be imagined to add :+1:

**Comment by pvictor** [comment]
You're welcome :) Many thanks for your encouragement !

Best,

Victor

**Comment by madmark81** [comment]
Hey pvictor, I send an email to your address listed here a week ago with some suggestions fixes and follow up questions. Perhaps you missed it?
