### ISSUE TITLE
Set options for spectrumInput

### ISSUE THREAD

**Issue by sgvignali** [dreamRs/shinyWidgets#455]
How can I set the options in `spectrumInput`? I would like the set the option `showInput` but I get the following warning :

_Warning: Error in spectrumInput: formal argument "options" matched by multiple actual arguments_

and the app stops with an error with the same messge.

I tried with:

 -  `options = list("showInput" = TRUE)`
 -  `options = list("showInput" = "true")`
 -  `options = list("show-input" = TRUE)`
 -  `options = list("show-input" = "true")`
 -  ``options = list(`show-input` = TRUE)``
 -  ``options = list(`show-input` = "true")``
 
I tried also the example in the documentation but it causes the same error, any idea?

**Comment by pvictor** [comment]
It seems that you use `options = ...` several times, if you want to pass multiple options, put them in the same `list`, e.g.: 

```r
library(shiny)
library(shinyWidgets)
library(scales)

ui <- fluidPage(
  tags$h1("Spectrum color picker"),
  
  br(),
  
  spectrumInput(
    inputId = "myColor",
    label = "Pick a color:",
    choices = list(
      list('black', 'white', 'blanchedalmond', 'steelblue', 'forestgreen'),
      as.list(brewer_pal(palette = "Blues")(9)),
      as.list(brewer_pal(palette = "Greens")(9)),
      as.list(brewer_pal(palette = "Spectral")(11)),
      as.list(brewer_pal(palette = "Dark2")(8))
    ),
    options = list(
      "toggle-palette-more-text" = "Show more",
      "show-input" = TRUE
    )
  ),
  verbatimTextOutput(outputId = "res")
  
)

server <- function(input, output, session) {
  
  output$res <- renderPrint(input$myColor)
  
}

shinyApp(ui, server)
```

Victor

**Comment by sgvignali** [comment]
Sorry,
 I didn't have the time to test it till now, but it works, I don't know exactly what I did wrong, probably as you said there was a double call to options...
Anyway, thank you for your answer and also for this amazing package!

**Comment by pvictor** [comment]
You're welcome! Glad it works!

**Comment by sgvignali** [comment]
Is there a way to get the color value using jquery?

**Comment by pvictor** [comment]
Yes, you can use `$("#myColor").spectrum("get").toHexString()` or any other method from https://bgrins.github.io/spectrum/

**Comment by sgvignali** [comment]
Perfect, thank you!
