### ISSUE TITLE
Feature Request: Allow hiding value label for sliderTextInput() while moving the thumb 

### ISSUE THREAD

**Issue by fsalemi** [dreamRs/shinyWidgets#469]
I find sliderTextInput() very useful widget while we need text as the values. However I am using this slider for controlling animation speed and therefore I do not need the values between min and max to be shown as I move thumb back and force as it is shown in this image:

![slider](https://user-images.githubusercontent.com/54083813/151894501-95a0a268-9673-4804-81c4-af62eb30383e.gif)

I noticed you have an argument: "hide_min_max" which hides min and max labels. I could not find similar parameter for hiding the value labels. Can we add a "hide_value_labels" to the list of arguments which hides the value labels?

Thanks

**Comment by pvictor** [comment]
Hello,
There's no options to do that unfortunately. But you can use some CSS (note that code below will affect all sliders in your app, even numeric ones):

```r
library("shiny")
library("shinyWidgets")

ui <- fluidPage(
  
  tags$style(
    ".irs-single {display: none;}", # hide label
    ".irs-min, .irs-max {visibility: visible !important;}" # force edge label to be always visible
  ),
  
  br(),
  sliderTextInput(
    inputId = "mySliderText",
    label = "Month slider:",
    choices = month.name,
    selected = month.name[2]
  ),
  verbatimTextOutput(outputId = "result")
)

server <- function(input, output, session) {
  output$result <- renderPrint(str(input$mySliderText))
}

shinyApp(ui = ui, server = server)
```

Victor

**Comment by fsalemi** [comment]
Thank you very much Victor for your help here. This looks amazing. 
By the way I found a way to specify which slider you want to change the style. You have to add  "js-irs-0" to the beginning of your irs component. 
The following code only impacts the first slider:
```
library("shiny")
library("shinyWidgets")

ui <- fluidPage(
  
  tags$style(".js-irs-0 .irs-single {visibility: hidden !important;} "),
  tags$style(".js-irs-0 .irs-min, .js-irs-0 .irs-max {visibility: visible !important;} "),
  
  br(),
  sliderTextInput(
    inputId = "mySliderText",
    label = "Month slider:",
    choices = month.name,
    selected = month.name[2]
  ),
  
  sliderInput("test1", "slider", 1,100, value = 50), 
  
  verbatimTextOutput(outputId = "result")
)

server <- function(input, output, session) {
  output$result <- renderPrint(str(input$mySliderText))
}

shinyApp(ui = ui, server = server)
```
The result looks like this:

![image](https://user-images.githubusercontent.com/54083813/152042555-0d5c843d-1d02-43b9-ad4b-371ee5f2606b.png)

Thanks for your help anyways.
