### ISSUE TITLE
updateRadioGroupButtons does not reset

### ISSUE THREAD

**Issue by systats** [dreamRs/shinyWidgets#47]
Hey Victor,

you already helped me with the [sentiment input](https://github.com/dreamRs/shinyWidgets/issues/41). Now I tried to update this button or better reset. But `updateRadioGroupButtons(session, "sent", selected = "")` updates only the UI and not the value itself. Do you know how to fix this? `character(0)` instead of `""` an empty string does not seem to be the solution.

Thanks in Advance,
Simon

**Comment by pvictor** [comment]
Hello Simon,
Mmmh you cannot have no selection made in radio buttons, one item must be selected.
What are you trying to achieve ?

Victor

**Comment by pvictor** [comment]
I you want an 'unselected' state, maybe try this, it consists of putting an extra choice and hiding it while remaining selectable : 

```r

library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$h1("Hidden radioGroupButtons"),
  tags$br(),
  radioGroupButtons(
    inputId = "sent", 
    label = "Sentiment", 
    choiceValues = -2:3, 
    checkIcon = list(yes = icon("check")),
    choiceNames = paste0(-2:3),
    justified = TRUE, width = "300px"
  ),
  tags$script("$(\"input:radio[name='sent'][value='3']\").parent().css('display', 'none');"),
  verbatimTextOutput(outputId = "res"),
  actionButton(inputId = "update", label = "Update")
)

server <- function(input, output, session) {
  
  output$res <- renderPrint(input$sent)
  
  observeEvent(input$update, {
    updateRadioGroupButtons(session = session, inputId = "sent", selected = "3")
  }, ignoreInit = TRUE)
}

shinyApp(ui, server)

```

With same JavaScript than last time ;)

**Comment by systats** [comment]
Damn powerful. Thank you again!

**Comment by systats** [comment]
Damn powerful. **Thank you again**!
