### ISSUE TITLE
Multiple tags / strings as input

### ISSUE THREAD

**Issue by GitHunter0** [dreamRs/shinyWidgets#474]
Hi folks,

There is a cool and valuable feature native Shiny is missing that I thought could be a nice fit for shinyWidgets in the future.

The feature is the ability to accept multiple tags as input, there is a prototype here https://github.com/ThinkR-open/tagsinput and for reference a fully functional one for python streamlit here https://github.com/gagan3012/streamlit-tags .

What do you think?

Thank you

**Comment by pvictor** [comment]
Hello,

Looks very similar to: 

```r
library(shiny)
ui <- fluidPage(
  selectizeInput(
    inputId = "select", 
    label = "Select", 
    choices = NULL,
    multiple = TRUE,
    options = list(
      plugins = list("remove_button"),
      create = TRUE,
      persist = TRUE # keep created choices in dropdown
    )
  ),
  verbatimTextOutput("out")
)

server <- function(input, output){
  output$out <- renderPrint({
    input$select
  })
}

shinyApp(ui, server)
```
