### ISSUE TITLE
Adding "width" argument to confirmSweetAlert() 

### ISSUE THREAD

**Issue by fsalemi** [dreamRs/shinyWidgets#482]
Hello Victor,
Thanks for the great package you have designed. 
I was wondering if you can add a `width` argument to `confirmSweetAlert()` function? We do have this argument in `sendSweetAlert()` and `show_alert()`, but it does not work in `confirmSweetAlert()`.
I know that I can change the width by using this line of code:
```
tags$style(".swal2-popup.swal2-modal.swal2-show {width: 400px; }" ),
```
But this code will also change the width for `progressSweetAlert()` which I do not want. I need to be able to change the width of `confirmSweetAlert()` only.
Thanks in advance.

**Comment by pvictor** [comment]
It should work with (at least) last CRAN version if you add `width = ?` in `confirmSweetAlert` or `ask_confirmation`: 

```r
ask_confirmation(
    inputId = "myconfirmation",
    title = "Want to confirm ?",
    width = "100%"
)
```

Victor

**Comment by fsalemi** [comment]
I just checked my latest version of shinyWidgets. I have 0.6.0. Is that not
the latest version?
Thanks

**Comment by fsalemi** [comment]
Thanks Victor, got it. My version was not the latest. Thanks for help.
