### ISSUE TITLE
pickerInput not working as expected when used w/ semantic.dashboard

### ISSUE THREAD

**Issue by AlexPars** [dreamRs/shinyWidgets#495]
Let me start by saying that shinyWidgets is a great R package.

I also wanted to inquire about possible solution(s) for the following issues encountered when using pickerInput  in combination with semantic.dashboard:
-  visual output in UI, created using pickerInput, is not a dropdown menu
-  when clicking on the visual output the entire list of options (passed as input to pickerInput ) shows up in UI, and cannot be closed

See snapshot of UI as Shiny app starts , 
![First_shinyWidget](https://user-images.githubusercontent.com/37603697/172442328-3f82696e-2881-4f67-8b71-bad882d22431.PNG)
and then a second snapshot when clicking on the box containing the value to select  ![Second_shinyWidget](https://user-images.githubusercontent.com/37603697/172442465-94690fe6-75b9-49e3-a4d2-6c7a452e6869.PNG)

Here is the code used to create this dashboard

`if(interactive()){
  
  ui <- semantic.dashboard::dashboardPage(
    
    header = semantic.dashboard::dashboardHeader(
      color = "blue", 
      title = "Dashboard Test", 
      inverted = TRUE
    ),
    
    sidebar = semantic.dashboard::dashboardSidebar(
      size = "thin", 
      color = "teal",
      semantic.dashboard::sidebarMenu(
        semantic.dashboard::menuItem(
          tabName = "tabID_main", 
          "Main Tab"),
        semantic.dashboard:: menuItem(
          tabName = "tabID_extra", 
          "Extra Tab")
      )
    ),
    
    body = semantic.dashboard::dashboardBody(
      semantic.dashboard::tabItems(
        
        selected = 1,
        
        semantic.dashboard::tabItem(
          tabName = "tabID_main",
          semantic.dashboard::box(
            shiny::h1("Main body"), 
            title = "A b c", 
            width = 16, 
            color = "orange",
            
            shinyWidgets::pickerInput(
              inputId = "ID_One",
              choices = c("Value One","Value Two","Value Three"),
              label = shiny::h5("Value to select"),
              selected = "Value Two",
              width = "fit",
              inline = TRUE),
            
            shiny::verbatimTextOutput(outputId = "res_One")
          )
        ),
        
        semantic.dashboard::tabItem(
          tabName = "tabID_extra",
          shiny::h1("extra")
        )
        
      )
    )
  )
  
  server <- function(input, output, session) {
    output$res_One <- shiny::renderPrint(input$ID_One)
  }
  
  shiny::shinyApp(ui, server)
  
}

`

I am using

- R version 3.6.3 64-bit on Windows computer
- R packages as of checkpoint date 2021-05-15
- shinyWidget version 0.6.0
- semantic.dashboard version 0.2.0

**Comment by pvictor** [comment]
Hello,

That's because `pickerInput()` needs Bootstrap to work properly, and semantic.dashboard don't use Bootstrap like normal shiny applications.

An alternative can be to use [virtualSelectInput](https://dreamrs.github.io/shinyWidgets/reference/virtualSelectInput.html) widget which have similar functionalities (or even more) and comes with no framework dependencies (bootstrap, semantic, ...)

Victor
