### ISSUE TITLE
checkboxGroupButtons inside dropdownButton button does not work as expected

### ISSUE THREAD

**Issue by Swechhya** [dreamRs/shinyWidgets#5]
Hi,

Thank you for this amazing package.

I am trying to place a `checkboxGroupButtons` inside of a `dropdownButton` but the `checkboxGroupbutton` does not work as expected. I am not able to select more than one button at a time.

Following is a minimal example:
```
library(shiny)
library(shinyWidgets)
 
 ui <- fluidPage(
   
   dropdownButton(icon = icon("gear"), 
                  tooltip = tooltipOptions(title = "Settings"), circle = TRUE, status = "primary",
                  selectInput(inputId = "SI_Element", label = "Element:", choices = c("Title", "Body")),
                  selectInput(inputId = "SI_FontFam", label = "Choose Font Family:", 
                              choices = c("Sans", "Times New Roman"), selected = "Sans"),
                  numericInput(inputId = "Num_FontSiz", label = "Font Size:", value = 14, min = 1,max = 25),
                  checkboxGroupButtons(inputId = "CBK_Button", label = "Font Style:",
                                       choices = c(`<i class='fa fa-bold'></i>` = "bold", 
                                                   `<i class='fa fa-italic'></i>` = "italic", 
                                                   `<i class='fa fa-underline'></i>` ="underline"))
                  
   )
 )
 
 server <- function(input,output){
   
   
 }
 
 shinyApp(ui = ui, server = server)
  
```

**Comment by pvictor** [comment]
Hi,
Thank you for the compliment, it's nice :)

And thanks for the issue and the reproducible example, I was able to reproduce and correct the problem.

I use this solution to prevent the dropdown to close when you click inside it and don't mess with the emlement in it : https://stackoverflow.com/questions/25089297/twitter-bootstrap-avoid-dropdown-menu-close-on-click-inside/25253002#25253002

Victor

**Comment by Swechhya** [comment]
Thank you. Really appreciate for fixing the issue so quickly.

**Comment by BetweenTwoTests** [comment]
Hi @Swechhya, did this fix your bug / lead to any other bugs? For me the new version actually makes the dropdown close immediately. @pvictor Will try to verify & create reproducible example when I have time...

**Comment by Swechhya** [comment]
Hi @BetweenTwoTests, did this fix my bug and did not lead to any other bugs
