### ISSUE TITLE
How to open the modaldialog under a dropdownbutton from code

### ISSUE THREAD

**Issue by madmark81** [dreamRs/shinyWidgets#50]
Hi pvictor, 

I found out that the dialog window under a dropdownButton doesn't seem to have an easyclose = T/F option, 

related to that, is there a way to trigger the opening of the window from the server side? I have some code functionality that closes a modalDialog that is opened by a button inside the dropdownbutton modal window. Closing this second modalDialog sadly also closes the dropdownButton panel, which I would like to be able to re-open, or keep open even when it is closed by other modals. 

Would you know a solution for this in combination with your widget?

**Comment by madmark81** [comment]
ok, found out that there is a toggleDropdownButton function that does the trick. I will close this but open e new issue concerning the easyclose if I can't solve it.

**Comment by pvictor** [comment]
Yep you can use `toggleDropdownButton`, I just added an example.
The easyclose is an interesting feature, i'll give aa look.

**Comment by madmark81** [comment]
There is a code in the modalDialog function that takes care of the easyclose argument, you can probably copy and adjust that into your program. If your curious, I can show you a screenshot of what I have build in the near future

**Comment by pvictor** [comment]
Yes i'm aware of that, but `easyClose` is passed to Bootstrap and it's Bootstrap modal that have an option to prevent closing, there's no equivalent for dropdown. You can find docs here : https://getbootstrap.com/docs/3.3/javascript/#modals-options

**Comment by madmark81** [comment]
Ah I unwittingly assumed the dropdownmenu was basically a preconstructed
bsmodal panel. Keep me posted. I will do the same if I find something

**Comment by madmark81** [comment]
Perhaps this item on SO contains the answer ?
https://stackoverflow.com/questions/26639346/prevent-bootstrap-dropdown-from-closing-on-clicks
