### ISSUE TITLE
VirtualselectInput

### ISSUE THREAD

**Issue by Saidsssr** [dreamRs/shinyWidgets#502]
I am trying to use searchByStartsWith in virtualselectinput but It does not do what is supposed. It still does not search by start with method.

**Comment by pvictor** [comment]
That option is only available in last release of [virtual-select-plugin](https://github.com/sa-si-dev/virtual-select), you have to re-install shinyWidgets from GitHub to make it work :  

```r
remotes::install_github("dreamRs/shinyWidgets")
```
