### ISSUE TITLE
updatePickerInput results in duplicates

### ISSUE THREAD

**Issue by ticarki** [dreamRs/shinyWidgets#503]
Hi there,

I am frequently using your great `pickerInput`. Recently, I wanted to switch to bootstrap 5 and observed an issue with the `updatePickerInput `functionality. The update introduces many duplicates into the list of choices.  Any downstream update then also adds new duplicates and also remembers the previous ones. When exluding `theme = bslib::bs_theme(version = 5)` or downgrading to `version = 4` it works perfectely.

Example:
```{r}
library(shiny)
library(shinyWidgets)
library(bslib)

ui <- fluidPage(
  theme = bslib::bs_theme(version = 5),
  shinyWidgets::pickerInput("picker", 
                            choices = character(0)),
  shiny::actionButton("update", "Update")
)

server <- function(input, output, session) {
  
  shiny::observeEvent(input$update, {
    shinyWidgets::updatePickerInput(session,
                                    "picker",
                                    choices = letters[1:2])
  })
}

shinyApp(ui, server)
```

After clicking once on Update:
![image](https://user-images.githubusercontent.com/25581180/177724490-e5eddd90-e092-4419-924d-ffa4b95c9c4d.png)

**Comment by pvictor** [comment]
Hello,

Yes `pickerInput` has some troubles with Bootstrap 5 since the underlying JavaScript library [bootstrap-select](https://github.com/snapappointments/bootstrap-select/releases) is still in beta for bs5. Nonetheless this bug should be fixed if you unstall the dev version.

```r
# install.packages("remotes")
remotes::install_github("dreamRs/shinyWidgets")
```
