### ISSUE TITLE
updateNoUiSliderInput() - no "label" argument

### ISSUE THREAD

**Issue by FedericoConcas** [dreamRs/shinyWidgets#506]
Would it be possible to add the `label` argument to `updateNoUiSliderInput()` to make it more consistent with similar functions from the `shiny` package? This would avoid having to render the UI element in the server and issues arising from it (such as its input becoming available at a later time).

The following is a similar function from `shiny`, which has the `label` argument:
`updateRadioButtons(
  session = getDefaultReactiveDomain(),
  inputId,
  label = NULL,
  choices = NULL,
  selected = NULL,
  inline = FALSE,
  choiceNames = NULL,
  choiceValues = NULL
)`

**Comment by pvictor** [comment]
Hi,
Indeed you're right, I added a `label` argument to `updateNoUiSliderInput`. You have to re-install from GitHub :  

```r
# install.packages("remotes")
remotes::install_github("dreamRs/shinyWidgets")
```
