### ISSUE TITLE
numericRangeInput and virtualSelectInput z-value problem?

### ISSUE THREAD

**Issue by moturoa** [dreamRs/shinyWidgets#507]
The input fields of  a `numericRangeInput` are rendered on top of the dropdown of a `virtualSelectInput` :

![image](https://user-images.githubusercontent.com/74360445/179492032-b0a5f642-17af-4493-9f3b-0a911818b1ed.png)

```
library(shiny)
library(shinyWidgets)  # 0.7.1
ui <- fluidPage( 
  virtualSelectInput("sel", "Virtual", choices = rownames(mtcars),
                     search = TRUE),
  numericRangeInput("ran", "Nums", value = c(0,100)) 
)
server <- function(input, output, session) {}
shinyApp(ui, server)
```

Thank you for making `virtualSelectInput` available, it is an excellent alternative to `pickerInput`!

**Comment by pvictor** [comment]
Hello,
That's a CSS z-index issue, you can set `virtualSelectInput()`'s argument `zIndex` to something greater than one (the default), it should do the trick. Maybe I should set a higher default, I need to see the usage

```r
library(shiny)
library(shinyWidgets)  # 0.7.1
ui <- fluidPage( 
  virtualSelectInput(
    "sel", "Virtual", 
    choices = rownames(mtcars),
    search = TRUE,
    zIndex = 10
  ),
  numericRangeInput("ran", "Nums", value = c(0,100)) 
)
server <- function(input, output, session) {}
shinyApp(ui, server)
```

**Comment by moturoa** [comment]
Thank you! I did not realize virtual-select.js had a zIndex option - this works for me.
