### ISSUE TITLE
Update content

### ISSUE THREAD

**Issue by madmark81** [dreamRs/shinyWidgets#51]
Pvictor. Sorry it is me again with another question. 

I tried to use updatecheckboxinput code to try and change a checkbox from true to false of a checkboxinput inside a dropdownbutton panel. 
If this code to update is triggered by a button inside the panel, I.e. the panel is currently open, it works fine. However, I also need to load default on and offs for some checkboxes when the user starts the shiny app, while menu is closed. In this case the updatecheckbox fails to do anything. I even tried suspendwhenhidden  = false inside the outoutoption call on both the dropdownbutton ID, the uiOutput id that makes the checkboxes, also tried on checkboxes made directly inside the panel (I.e. not with renderUI) and on the checkboxinput ID tags directly but in non of the scenarios does update checkboxinput (id , .... , value = True ) actually work. 

Any clues what I am missing or doing wrong?

**Comment by madmark81** [comment]
False to true I meant in the start. I build all checkboxes starting without a value

**Comment by pvictor** [comment]
Hi, I've try to recreate the situation you described, this seems to work, can you provide an example where it doesn't ?

```r
library(shiny)
library(shinyWidgets)
ui <- fluidPage(
  tags$h2("dropdown update test"),
  fluidRow(
    column(
      width = 6,
      dropdownButton(
        uiOutput(outputId = "params"),
        icon = icon("sliders")
      ),
      verbatimTextOutput(outputId = "res")
    ),
    column(
      width = 6,
      checkboxInput(inputId = "update", label = "update")
    )
  )
)

server <- function(input, output, session) {
  
  output$params <- renderUI({
    checkboxInput(inputId = "my_cb", label = "a checkbox", value = FALSE)
  })
  outputOptions(x = output, name = "params", suspendWhenHidden = FALSE)
  
  observeEvent(input$update, {
    updateCheckboxInput(session = session, inputId = "my_cb", value = input$update)
  }, ignoreInit = TRUE)
  
}

shinyApp(ui, server)
```

**Comment by madmark81** [comment]
I fixed it but can't remember how exactly. I this it was because i build the checkboxes without a value argument which causes updating of it to true fail perhaps . 

Anyways..... Did you have any luck with looking at the easy close false solution to add to the dropdown buttons?

**Comment by pvictor** [comment]
No it's not working yet, I can prevent dropdown's closing but after it's really impossible to close it, i'll have 2~3 idea to go further. I close this for now and i'll keep you posted for the easyClose option.

**Comment by madmark81** [comment]
Ok thanks
