### ISSUE TITLE
Save and load input using shinyWidgets::updateVirtualSelect() lead Shiny app to crash

### ISSUE THREAD

**Issue by eden-fore** [dreamRs/shinyWidgets#514]
I recently posted question re issue using VirtualSelect
here's the post:

https://stackoverflow.com/questions/73109327/save-and-load-input-using-shinywidgetsupdatevirtualselect-lead-shiny-app-to

and this is why I cant use pickerInput instead:
https://github.com/dreamRs/shinyWidgets/issues/509#issue-1310705039

any help will be greatly appreciated!!!!!!

Thanks!

**Comment by pvictor** [comment]
The error is caused because first argument of `shinyWidgets::updateVirtualSelect()` is `label =` and not `session =`, contrary to other inputs. You have to use `session = session` explicitly, but you shouldn't have to specify this argument at all normally, it is retrieved automatically.

**Comment by pvictor** [comment]
Don't, that's the only `updateXX` function with the arguments in this order, it's quite unusual
