### ISSUE TITLE
full width dropdown button

### ISSUE THREAD

**Issue by stla** [dreamRs/shinyWidgets#519]
Hello,

I have a dropdown whose button is rendered like this:

![Xaxis](https://user-images.githubusercontent.com/4466543/184195527-85d41fe2-8f31-417e-97b7-2d2c272d23d4.png)

I'd like to make it full width, like an `actionBttn` with the argument `block = TRUE`.

**Comment by pvictor** [comment]
Hello,
With the CRAN version you have to modify the button tag, it can be done with {htmltools}: 

```r
library("shiny")
library("shinyWidgets")
library("htmltools")

# Create dropdown ----
dd <- dropdown(
  tags$h3("List of Input"),
  tags$p("Content"),
  style = "unite", 
  icon = icon("gear"),
  status = "danger"
)

# Modify button tag ----
dd <- tagQuery(dd)$
  find(".bttn")$
  addClass("bttn-block")$
  allTags()
```

With the dev version, I added `block` argument to `dropdown()`
