### ISSUE TITLE
updateSearchInput ?

### ISSUE THREAD

**Issue by steve-liang** [dreamRs/shinyWidgets#52]
Hi, 

I am wondering if you can add updateSearchInput just like other input UI. I understand there's a button involved so it may be a bit tricky. I personally attempted to do that using session$sendInputMessage but it won't simulate button click to trigger input value change. Any idea?

Steve

**Comment by pvictor** [comment]
Hi,
You're right, this function is missing, I added it in the last commit. Please re-install package from Github and see `?updateSearchInput` example.
There's an argument `trigger` to decide if only ui value must be updated and let user click button or both ui and server value must be updated at the same time.
If it works for you, I let you close the issue.

Victor

**Comment by steve-liang** [comment]
Thanks for your quick response with perfect solution. Looking forward to it being on CRAN later.
I need to study your code to see how you did it with the trigger.

**Comment by pvictor** [comment]
You're welcome :)
Maybe this week-end on CRAN but I can't promise anything.
The trigger is a JavaScript on the button, I don't find a better way... Code is [here](https://github.com/dreamRs/shinyWidgets/blob/master/inst/www/searchInput/search-bindings.js) in `receiveMessage` method if you're interested.

Victor
