### ISSUE TITLE
airDatePicker: month 00 since last update (0.7.2)

### ISSUE THREAD

**Issue by Greensway** [dreamRs/shinyWidgets#520]
since last update months are shown as 00 (although the value in the console is right), and the z-index got somehow modified getting behind other objects. 
![image](https://user-images.githubusercontent.com/53170368/184623998-cf1a6688-b1bf-48d7-8962-1aa53b5b8753.png)

**Comment by Greensway** [comment]
downgrading fixed it for me.

**Comment by pvictor** [comment]
In shinyWidgets last version (v0.7.2), the JavaScript library (air-datepicker)[https://github.com/t1m0n/air-datepicker] has been updated to the latest available, this may have caused the problem. 
Can you share some code ?
Maybe it's an issue with the argument `dateFormat` ? See https://air-datepicker.com/docs?scrollTo=dateFormat for possible options.
Otherwise, with last shinyWidgets version you can use the old air-datepicker  library and bindings by using `options("air-datepicker" = 2)`

**Comment by Greensway** [comment]
I leave some minimal example. 

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
    sidebarLayout(
        sidebarPanel(
          airMonthpickerInput("dateM",
                              label = "Datum",
                              value = Sys.Date(),
                              multiple = FALSE,
                              dateFormat = "yyyy-mm",
                              view = "months",
                              minView = "months",
                              monthsField = "monthsShort",
                              language = "en",
                              width = 250,
                              addon = 'none'),
          airDatepickerInput("dateD", 
                             label = "Day",  
                             value = Sys.Date(), 
                             multiple = FALSE,
                             dateFormat = "yyyy-mm-dd",
                             view = "days",
                             minView = "days",
                             monthsField = "monthsShort",
                             todayButton = FALSE,
                             autoClose = TRUE,
                             language = "en",
                             width = 250,
                             addon = 'none'), 
        ),
        mainPanel(
              verbatimTextOutput("dateoutM"),
              verbatimTextOutput("dateoutD")
        )
    )
)

server <- function(input, output) {
    output$dateoutM <- renderText({
        print(input$dateM)
        as.character(input$dateM)
      })
    output$dateoutD <- renderText({
      print(input$dateD)
      as.character(input$dateD)
    })
}

shinyApp(ui = ui, server = server)
```

**Comment by Greensway** [comment]
It seems that the date format has become less tolerant, not accepting "mm" but instead "MM"

**Comment by droosifer** [comment]
Can confirm that downgrading to 0.7.0 fixed all my issues. I had date format related issues as well as fa icons not appearing. I believe my issues were exaggerated due to other packages that were imported into my package.

**Comment by Greensway** [comment]
OK, so this is not an issue, it is a feature. It is how it is, right?

**Comment by pvictor** [comment]
Yes it will stay like that, please use the new format describe here : https://air-datepicker.com/docs?scrollTo=dateFormat
I have updated documentation and put a note in the NEWS file.
