### ISSUE TITLE
Demo version site offline

### ISSUE THREAD

**Issue by JulianoAtto** [dreamRs/shinyWidgets#521]
In the [README.md](https://github.com/dreamRs/shinyWidgets#readme) the demo link is offline. 

> "_A live version is available here : http://shinyapps.dreamrs.fr/shinyWidgets_"

**Comment by jhk0530** [comment]
Same issue. 
How about try `shinyWidgets::shinyWidgetsGallery()` ?
I'm not sure about it provides the same content as the demo page.

**Comment by pvictor** [comment]
The server is offline for some reason, I have to investigate.
You can indeed launch the gallery with `shinyWidgets::shinyWidgetsGallery()`, that's the same application.

**Comment by JulianoAtto** [comment]
Thanks for the answers, I'll use`shinyWidgets::shinyWidgetsGallery()` for now.

**Comment by pvictor** [comment]
Online gallery should be back here : https://www.shinyapps.dreamrs.fr/shinyWidgets/

**Comment by dwill023** [comment]
Online gallery (https://shinyapps.dreamrs.fr/shinyWidgets) is down. I am using the shinyWidgets::shinyWidgetsGallery() but prefer the online gallery. 

Thanks!
