### ISSUE TITLE
PickerInput - input$<inputId>_open is not working

### ISSUE THREAD

**Issue by KumarR18** [dreamRs/shinyWidgets#522]
input$<inputId>_open is always null now. It was working earlier. Please help

**Comment by KumarR18** [comment]
@mfanny Could you please help here?

**Comment by pvictor** [comment]
It's `NULL` when app starts and until the picker is first open.
This example works fine : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  pickerInput(
    inputId = "somevalue",
    label = "A label",
    choices = c("a", "b")
  ),
  verbatimTextOutput("value"),
  verbatimTextOutput("state")
)

server <- function(input, output) {
  output$value <- renderPrint(input$somevalue)
  output$state <- renderPrint(input$somevalue_open)
}

shinyApp(ui, server)
```

Please provide more informations about the context where it didn't work: reproducible example, session information (`sessioninfo::session_info()`), ...

**Comment by KumarR18** [comment]
@pvictor , thanks for replying. below find the reproducible example.

library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  pickerInput(
    inputId = "somevalue",
    label = "A label",
    choices = c("a", "b","c","d","e"),
    selected = c("a"),
    options <- pickerOptions(
      actionsBox = T,
      liveSearch = TRUE,
      deselectAllText = "Deselect All",
      size = 10),
    multiple = T
  ),
  verbatimTextOutput("value"),
  verbatimTextOutput("state")
)



server <- function(input, output, session) {
  updatePickerInput(
    session=session,
    inputId = "somevalue",
    label = "A label",
    choices = c("e", "b","c","d","a"),
    selected = c("e"))
  output$value <- renderPrint(input$somevalue)
  output$state <- renderPrint(input$somevalue_open)
  observeEvent(input$somevalue_open,{
    print(input$somevalue_open)
  })
}

shinyApp(ui, server)

**Comment by pvictor** [comment]
Thanks for the example, I was able to identify the problem and solve it. You have to reinstall the package from GitHub for this to work. I expect to update on the CRAN in the next couple of weeks.

```r
# install.packages("remotes")
remotes::install_github("dreamRs/shinyWidgets")
```

Victor

**Comment by KumarR18** [comment]
Thanks @pvictor
