### ISSUE TITLE
Italian language no longer works in airDatepicker version 0.7.2

### ISSUE THREAD

**Issue by msaltieri** [dreamRs/shinyWidgets#523]
After updating to v0.7.2 the **Italian** locale is no longer working in `airDatepicker` and its siblings. Other locales tested like French or German work perfectly.

<img width="310" alt="air-datepicker-bug" src="https://user-images.githubusercontent.com/26568338/186367876-a9f87bfb-8992-4273-983b-b4fefcc66510.png">

As you can see, while in the German version everything works smoothly, with the Italian locale the date field appears empty and the widget is unusable.

Here below a minimal example.

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
    titlePanel('Bug in air-datepicker v0.7.2'),
    fluidRow(
        column(
            width = 6,
            airDatepickerInput(
                inputId = "date",
                label = "Please select a date (in German)",
                value = Sys.Date(),
                dateFormat = 'dd/MM/yyyy',
                language = 'de'
            ),
            airDatepickerInput(
                inputId = "date",
                label = "Please select a date (in Italian)",
                value = Sys.Date(),
                dateFormat = 'dd/MM/yyyy',
                language = 'it'
            )
        )
    )
)

server <- function(input, output) {}

shinyApp(ui = ui, server = server)
```

Please, let me know if I can help in some way solving this bug.

**Comment by msaltieri** [comment]
I've just opened a [PR](https://github.com/t1m0n/air-datepicker/pull/498) directly on the [air-datepicker](https://github.com/t1m0n/air-datepicker) repo that should solve this issue. I will drop an update as soon as it is merged.

**Comment by pvictor** [comment]
Perfect for the PR, as soon as there is a new version, I will update on GitHub and on the CRAN in the following time
