### ISSUE TITLE
pickerInput unuseable when choices are large

### ISSUE THREAD

**Issue by info-rchitect** [dreamRs/shinyWidgets#524]
Hi,

This is not related to speed, rather how it behaves.  Best to just show a [video](https://www.dropbox.com/s/kx0vcmldihr8zx5/shiny_widgets_input_picker_misbehaving..mp4?dl=0).

thx

**Comment by pvictor** [comment]
You can try [virtualSelectInput()](https://dreamrs.github.io/shinyWidgets/reference/virtualSelectInput.html) as an alternative.
I can't see the video.

**Comment by info-rchitect** [comment]
Actually we can close this, found out I just had to set the `size` option to something reasonable
