### ISSUE TITLE
updateProgressBar updating for one loop but not another inside function

### ISSUE THREAD

**Issue by ProfessorPeregrine** [dreamRs/shinyWidgets#531]
Hi, not sure if this is an issue or me missing something. The progress bar updates for the first loop, but when I get to the longer loop it does not.

`
progressBar(id = "mvp_exp_prog",value = 0,display_pct = TRUE)

    mvp_exp<-function(x,bail=20000,max_sims=1000000){
       #Monte Carlo approach to exponential testing by Michael V. Petrovich
       #The expected value of mvp_e is 1
       samp_mean<-mean(x)
       samp_var<-var(x)
       samp_min<-min(x)
       mvp_e<-(samp_mean-samp_min)^2/samp_var
       n<-length(x)
       above<-0#count how many go above test statistic
       
       update_inc<-max_sims/100
      
       #early bail if it is clearly not exponential
       for (i in 1:bail){
         #take a sample of size n from theoretical exp dist
         sim<-samp_min+rexp(n = n,rate = samp_mean^-1)
         sim_mvp<-(mean(sim)-min(sim))^2/var(sim)
         if(sim_mvp>mvp_e){above<-above+1}
         if(update_inc/i==trunc(update_inc/i)){#only update a few times
           updateProgressBar(id = "mvp_exp_prog",value = update_inc/i,session = session)#this works
           }
       }
       if(above==0 || above==bail){
         updateProgressBar(id = "mvp_exp_prog",value = 100,session=session)#this works
         return(list("MVP(E) = "=mvp_e,"p-value"=0))
         }
       
       #continue
       for (i in (bail+1):max_sims){
         #take a sample of size n from theoretical exp dist
         sim<-samp_min+rexp(n = n,rate = samp_mean^-1)
         sim_mvp<-(mean(sim)-min(sim))^2/var(sim)
         if(sim_mvp>mvp_e){above<-above+1}
         if(update_inc/i==trunc(update_inc/i)){#only update a few times
           updateProgressBar(id = "mvp_exp_prog",value = update_inc/i,session = session)#this does not
         }
       }
       
       prop_above <- above/max_sims
       output<-list("MVP(E) = "=mvp_e,"p-value"=prop_above*2)
       return(output)
     }`

**Comment by pvictor** [comment]
I think that's because of the `return` statement in the middle, nothing is evaluated after that, e.g. :

```r
return(list("MVP(E) = "=mvp_e,"p-value"=0))
```

**Comment by ProfessorPeregrine** [comment]
Thanks for the quick reply!

It definitely gets to the second part of the function (after #continue) for exponentially distributed data. If it dumps out at the return(), it completes in <1 sec and shows the progress bar filled in. For exponential data, it takes about ten seconds and the bar never updates. I have attached exponential data should you want it.
[exp.txt](https://github.com/dreamRs/shinyWidgets/files/9567777/exp.txt)

**Comment by ProfessorPeregrine** [comment]
Ugh, no it was me messing up the logic. I had the division backwards!!!

Thanks for the suggestion, it sent me down the right way, and thanks for the great package!
