### ISSUE TITLE
Font Awesome warnings again?

### ISSUE THREAD

**Issue by ProfessorPeregrine** [dreamRs/shinyWidgets#533]
I am getting the following warnings again. I remember you put a fix in when something like this happened before.

Thanks again for the great widgets!

This Font Awesome icon ('fas fa-cog') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
This Font Awesome icon ('fas fa-cog') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`

**Comment by pvictor** [comment]
There was indeed a reference to this icon, it is corrected, thank you

Victor
