### ISSUE TITLE
Possible improvement of  input$<inputId>_open

### ISSUE THREAD

**Issue by apalacio9502** [dreamRs/shinyWidgets#534]
Hello,

I'm using the function input$<inputId>_open to prevent recalculations until the user closes the input. However, I find as a possible improvement that input$<inputId>_open defaults to FALSE when it is initialized, not until the input is opened for the first time.

Regards

**Comment by pvictor** [comment]
Yes, but this way we can know if the menu has been opened or not, we would not have the information if we used FALSE at initialization. And if we change the behavior now it could affect users who use this feature.

Victor
