### ISSUE TITLE
Feature suggestion: allow custom colors for checkboxes

### ISSUE THREAD

**Issue by jzadra** [dreamRs/shinyWidgets#538]
I have a map with markers in 6 colors.  I'd like to use either single or group checkboxes to toggle whether each group/color is shown or not, and I'd like the colors of the checkboxes to be able to be set manually to a hex value or named color to match the marker color on the map.

Is there any way to specify a custom color? It looks to me like you have to choose one of the presets like "success" or "danger".  
Either allowing this for a single checkbox, or textbook group (where you can specify the color for each checkbox int he group) would be awesome!

**Comment by pvictor** [comment]
Hello,
That's possible if you use `checkboxGroupButtons()`.

Victor
