### ISSUE TITLE
Don't delete text box on reset in searchInput

### ISSUE THREAD

**Issue by fbreitwieser** [dreamRs/shinyWidgets#54]
Thanks for the great package!

I'd like to use searchInput somewhat differently than intended, using the reset button as a secondary button for another kind of action. However, while I can observe the reset button-action, the text is already cleared at that time. 

What do you think of supporting not clearing the text on reset button-click? E.g with an option to allow the reset value being "" (default, clear it), NULL (not clearing the text box), or anything else

**Comment by pvictor** [comment]
You're welcome :)

There's no impact to present behavior so why not ! I added an argument `resetValue` to `searchInput` with behaviour you described, try example below : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$h1("Search Input"),
  br(),
  searchInput(
    inputId = "search", label = "Enter your text",
    placeholder = "A placeholder",
    btnSearch = icon("search"),
    btnReset = icon("remove"), 
    resetValue = NULL,
    width = "450px"
  ),
  br(),
  verbatimTextOutput(outputId = "res")
)

server <- function(input, output, session) {
  output$res <- renderPrint({
    input$search
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by fbreitwieser** [comment]
Wow, such a fast response :). Thank you, works perfectly!
