### ISSUE TITLE
Add text on hover to pickerInput choices

### ISSUE THREAD

**Issue by bdbmax** [dreamRs/shinyWidgets#541]
Space for each choice in a dropdown menu is limited, so we might want to use a shorter title for each of these choices to limit the size of the dropdown, but let to the user the ability to hover on each choice to see on screen the definition of each choice. Would this be a viable additional feature, probably in the pickerOptions function?

Thank you!

**Comment by pvictor** [comment]
Hello,
You can try that : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  
  tags$script(
    "var myDefaultWhiteList = $.fn.selectpicker.Constructor.DEFAULTS.whiteList;
    // To allow div elements with title attribute
    myDefaultWhiteList.div = ['title'];"
  ),
  
  pickerInput(
    inputId = "test",
    label = "Test :",
    choices = month.abb,
    choicesOpt = list(
      content = sprintf(
        '<div title="The month of %s" style="width: 100%%;">%s</div>', 
        month.name, month.abb
      )
    )
  )
)

server <- function(input, output) {
  
}

shinyApp(ui = ui, server = server)
```

Victor

**Comment by bdbmax** [comment]
Hello Victor,
This works great, thanks a lot!
While this works well, I have an additional question for you: It adds the hover on the text itself, but not the whole block that's clickable to pick the choice. Can we increase the size that div takes (more than the actual 100% width, which isn't taking all the available space), or add the `title` argument to the whole `<a>` tag?
![image](https://user-images.githubusercontent.com/64483932/198103314-0f658fb7-63b0-4f88-a021-8ae8c5b5c8f9.png)

Thanks again!
Max.

**Comment by pvictor** [comment]
You can try to add this CSS rule into your UI : 

```r
tags$style("span.text {display: block !important;}")
```

Victor

**Comment by bdbmax** [comment]
That's great. Thanks a lot!
