### ISSUE TITLE
custom slider widget

### ISSUE THREAD

**Issue by tbenschop** [dreamRs/shinyWidgets#55]
wow I love this package, to bad I didn't come across it earlier! Are you also planning to make some nicer sliderinputs? For example a vertical slider: https://angularscript.com/wp-content/uploads/2015/12/Mobile-friendly-Slider-Directive-For-AngularJS-Vertical.png
or slider that also accepts numericinputs: https://angularscript.com/basic-angular-2-slider-component/

**Comment by pvictor** [comment]
Glad you like the package !

Those librairies doesn't seems actively maintained... and i'm not familiar with Angular..
This one https://refreshless.com/nouislider/ however is a good candidate, I can look to integrate it in Shiny.

Victor

**Comment by tbenschop** [comment]
Hi Victor,

Thanks, that suggesties looks better Thanks angular! I’ll keep an eye out on GitHub to see if it gets added! Good stuff. 
Best regards, Tim

**Comment by tbenschop** [comment]
Hi Victor,

 

Is there a way to activate the inputs under a dropdown without collapsing the dropdown? I’d like my data to be loaded in directly based on some default filters under a dropdown. But it now only works when I click on the button.

 

BR Tim

**Comment by pvictor** [comment]
Hello,
Are your inputs in a `renderUI` / `uiOutput` ?

Victor

**Comment by tbenschop** [comment]
Hi Victor,

 

Yes, they are. Guess that’s an issue?

BR Tim

**Comment by tbenschop** [comment]
Hi Victor,

 

Just played around a bit, I just ignore those renderUI’s if they are NULL. We also like the dropdown function a lot. We are working with a global filter, but we like to have a wider dropdown:



 

Is there a way to allow the dropdown be wider than the global sidebar?

 

If you find all my questions annoying and too time consuming please don’t hesitate to ignore them and tell me 😉

 

BR Tim

 

 

 

From: tim benschop [mailto:timbenschop@me.com] 
Sent: Friday, 2 March 2018 16:13
To: 'dreamRs/shinyWidgets' <reply@reply.github.com>; 'dreamRs/shinyWidgets' <shinyWidgets@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [dreamRs/shinyWidgets] custom slider widget (#55)

 

Hi Victor,

 

Yes, they are. Guess that’s an issue?

 

BR Tim

**Comment by pvictor** [comment]
Hi,
Yes, Shiny is lazy, outputs are not rendered until display on screen, you can use `outputOptions` to change this behavior. See this issue for an example : https://github.com/dreamRs/shinyWidgets/issues/45
