### ISSUE TITLE
airDatepickerInput(): Bugs in language, inline and timezone

### ISSUE THREAD

**Issue by Riraro** [dreamRs/shinyWidgets#553]
Hey there, first thanks for the awesome Widgets your project provides, it's a pleasure to use them!

I'm trying to integrate the `airDatepickerInput()` into my app (`shinyWidgets v.0.7.5`), but ran into 3 bugs (minimal example at the end):
1) The displayed time is always `am` instead of `pm` when passing a time after midday.
2) When using `language = "de"` the widget displays `ii` instead of the minutes.
3) When using `inline = TRUE` the time specified in `value` is ignored and the widget uses the current time.

Thanks for your support!

![2022-12-06 12_15_24-Window](https://user-images.githubusercontent.com/119937365/205897550-23bca3f7-ac7f-4a0e-b4fc-be8a9227643f.png)

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  br(),
  airDatepickerInput(
    inputId = "timezone",
    label = "timezone wrong (should be pm)",
    value = as.POSIXct("2022-02-15 22:00:00"),
    timepicker = TRUE
  ),
  verbatimTextOutput(outputId = "timezone"),
  br(),
  airDatepickerInput(
    inputId = "language",
    label = "'language = \"de\"' broken (no minutes displayed)",
    value = as.POSIXct("2022-02-15 22:00:00"),
    timepicker = TRUE,
    language = "de"
  ),
  verbatimTextOutput(outputId = "language"),
  br(),
  airDatepickerInput(
    inputId = "inline",
    label = "'inline = TRUE' broken (wrong time)",
    value = as.POSIXct("2022-02-15 22:00:00"),
    timepicker = TRUE,
    inline = TRUE
  ),
  verbatimTextOutput(outputId = "inline")
)

server <- function(input, output, session) {
  output$timezone <- renderPrint(input$timezone)
  output$language <- renderPrint(input$language)
  output$inline <- renderPrint(input$inline)
}

shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Hello,
Thank you for reporting this, those issues have been fixed in latest [air-datepicker release](https://github.com/t1m0n/air-datepicker#v332), if you install shinyWidgets from GitHub it'll be ok.

Victor
