### ISSUE TITLE
`checkBoxGroupButtons()` completely broken in bs4Dash

### ISSUE THREAD

**Issue by AshesITR** [dreamRs/shinyWidgets#555]
`checkboxGroupButtons()` is completely broken when using `bs4Dash`, both with the most recent CRAN version.

```r
library(shiny)
library(bs4Dash)
library(shinyWidgets)

shiny::shinyApp(
    ui = bs4DashPage(
      header = bs4DashNavbar(),
        sidebar = bs4DashSidebar(),
        controlbar = bs4DashControlbar(
        ),
        footer = bs4DashFooter(),
        title = "test",
        body = bs4DashBody(
            checkboxGroupButtons(inputId = "somevalue",
                                 label = "Make a choice: ",
                                 choices = c("A", "B", "C")))
    ),
    server = function(input, output) {}
)
```

EDIT: I found the culprit to be `bslib` 0.4.1

<details>
<summary>Session Info</summary>

- Session info ----------------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 4.2.0 (2022-04-22 ucrt)
 os       Windows >= 8 x64 (build 9200)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  German_Germany.1252
 ctype    German_Germany.1252
 tz       Europe/Berlin
 date     2022-12-09
 rstudio  1.3.1056  (desktop)
 pandoc   NA

- Packages --------------------------------------------------------------------------------------------------------------------
 package      * version  date (UTC) lib source
 anytime        0.3.9    2020-08-27 [1] CRAN (R 4.2.1)
 askpass        1.1      2019-01-13 [1] CRAN (R 4.2.0)
 base64enc      0.1-3    2015-07-28 [1] CRAN (R 4.2.0)
 BH             1.78.0-0 2021-12-15 [1] CRAN (R 4.2.0)
 bs4Dash      * 2.1.0    2022-05-05 [1] CRAN (R 4.2.2)
 bslib          0.4.1    2022-11-02 [1] CRAN (R 4.2.2)
 cachem         1.0.6    2021-08-19 [1] CRAN (R 4.2.0)
 cli            3.4.1    2022-09-23 [1] CRAN (R 4.2.2)
 commonmark     1.8.1    2022-10-14 [1] CRAN (R 4.2.2)
 crayon         1.5.2    2022-09-29 [1] CRAN (R 4.2.2)
 curl           4.3.3    2022-10-06 [1] CRAN (R 4.2.2)
 digest         0.6.30   2022-10-18 [1] CRAN (R 4.2.2)
 ellipsis       0.3.2    2021-04-29 [1] CRAN (R 4.2.0)
 fastmap        1.1.0    2021-01-25 [1] CRAN (R 4.2.0)
 fontawesome    0.4.0    2022-10-25 [1] CRAN (R 4.2.2)
 fresh          0.2.0    2020-05-29 [1] CRAN (R 4.2.2)
 fs             1.5.2    2021-12-08 [1] CRAN (R 4.2.0)
 glue           1.6.2    2022-02-24 [1] CRAN (R 4.2.0)
 htmltools      0.5.3    2022-07-18 [1] CRAN (R 4.2.2)
 httpuv         1.6.6    2022-09-08 [1] CRAN (R 4.2.2)
 httr           1.4.4    2022-08-17 [1] CRAN (R 4.2.2)
 jquerylib      0.1.4    2021-04-26 [1] CRAN (R 4.2.0)
 jsonlite       1.8.3    2022-10-21 [1] CRAN (R 4.2.2)
 later          1.3.0    2021-08-18 [1] CRAN (R 4.2.0)
 lifecycle      1.0.3    2022-10-07 [1] CRAN (R 4.2.2)
 magrittr       2.0.3    2022-03-30 [1] CRAN (R 4.2.0)
 memoise        2.0.1    2021-11-26 [1] CRAN (R 4.2.0)
 mime           0.12     2021-09-28 [1] CRAN (R 4.2.0)
 openssl        2.0.4    2022-10-17 [1] CRAN (R 4.2.2)
 promises       1.2.0.1  2021-02-11 [1] CRAN (R 4.2.0)
 R6             2.5.1    2021-08-19 [1] CRAN (R 4.2.0)
 rappdirs       0.3.3    2021-01-31 [1] CRAN (R 4.2.0)
 Rcpp           1.0.9    2022-07-08 [1] CRAN (R 4.2.1)
 rlang          1.0.6    2022-09-24 [1] CRAN (R 4.2.1)
 rstudioapi     0.14     2022-08-22 [1] CRAN (R 4.2.2)
 sass           0.4.2    2022-07-16 [1] CRAN (R 4.2.2)
 shiny        * 1.7.3    2022-10-25 [1] CRAN (R 4.2.2)
 shinyWidgets * 0.7.5    2022-11-17 [1] CRAN (R 4.2.2)
 sourcetools    0.1.7    2018-04-25 [1] CRAN (R 4.2.0)
 sys            3.4.1    2022-10-18 [1] CRAN (R 4.2.2)
 waiter         0.2.5    2022-01-03 [1] CRAN (R 4.2.2)
 withr          2.5.0    2022-03-03 [1] CRAN (R 4.2.0)
 xtable         1.8-4    2019-04-21 [1] CRAN (R 4.2.0)

 [1] C:/Users/<User>/AppData/Local/R/win-library/4.2
 [2] C:/Program Files/R/R-4.2.0/library

-------------------------------------------------------------------------------------------------------------------------------
</details>

**Comment by pvictor** [comment]
Seems to be a problem with the Bootstrap version used by {bs4Dash} : 4.5.2
If you load stable release 4.6.0 provided by {bslib} it works fine, but I don't know if it impacts other components.

To load BS 4 from {bslib} use in your UI : 

```r
bslib::bs_theme_dependencies(bslib::bs_theme(version = 4L))
```

**Comment by AshesITR** [comment]
Thanks for your hint. Downgrading bslib to 0.3.1 fixed it for me.
The most apparent change is the default bs version changed from 4 to 5 for bslib 0.4.1
