### ISSUE TITLE
pickerInput does not display bottom of dropdown when choices list is too large

### ISSUE THREAD

**Issue by jonathanperrie** [dreamRs/shinyWidgets#557]
`pickerInput("tmp1","tmp1", choices=c(seq(100)), options = list("actions-box"= TRUE),multiple = F)`
Works as expected. You can go to the bottom of the list. 

`pickerInput("tmp2","tmp2", choices=c(seq(1000)), options = list("actions-box" = TRUE),multiple = F)`
Does not work as expected. You cannot see some of the choices near 1000, it just goes to white space. 

![dropdown_pickerinput](https://user-images.githubusercontent.com/12719005/207729240-80fb8347-dd62-41aa-8c36-5c422d1b948c.png)

**Comment by pvictor** [comment]
I can't reproduce the problem.
Which version of shinyWidgets are you using ? Which browser ?

**Comment by jonathanperrie** [comment]
It was R version 4.2.1 in Rstudio (outdated by one update) browser. I have since updated the R studio and R version and everything works gucci.
