### ISSUE TITLE
Bootstrap Accordion component

### ISSUE THREAD

**Issue by GitHunter0** [dreamRs/shinyWidgets#559]
Hi folks, 

Do you have plans to add Bootstrap Accordion components? It would be very nice and useful to have that easily in Shiny.

Here's a plotly dash example: https://dash-bootstrap-components.opensource.faculty.ai/docs/components/accordion/

Thank you

**Comment by pvictor** [comment]
Hello,

I think you have that for Bootstrap 3 in [{bsplus}](https://github.com/ijlyttle/bsplus) and for Bootstrap 5 in [{bsutils}](https://github.com/JohnCoene/bsutils), I don't think I integrate that in shinyWidgets.
You can also easily convert HTML code from [here for example](https://getbootstrap.com/docs/5.0/components/accordion/) with [{charpente}](https://github.com/RinteRface/charpente) and then customize as you want.

**Comment by GitHunter0** [comment]
Hey @pvictor , thanks man, I didn't know those packages, they will be very helpful.
