### ISSUE TITLE
pickerInput inside dropdownButton won't open

### ISSUE THREAD

**Issue by jslul** [dreamRs/shinyWidgets#56]
Hello. 

If i create a dropdownButton with a pickerInput inside, the pickerInput won't open when i click it, but just closes the popup.

`            dropdownButton(
        title = "Controls",
        pickerInput("test", "Number of observations:", 1, 100, 50)
      )`

is there a quickfix for this? 

Thanks for a great package!

**Comment by pvictor** [comment]
Hi,
Glad you like the package !
Yes `pickerInput` doesn't work in `dropdownButton`, the quick fix is to use `dropdown` instead : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  dropdown( 
    title = "Controls", 
    pickerInput("test", "Number of observations:", 1, 100, 50))
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```

Victor
