### ISSUE TITLE
`shinyWidgets:::normalizeChoicesArgs` broken?

### ISSUE THREAD

**Issue by gwd666** [dreamRs/shinyWidgets#561]
```
vec <- c(all = "All", other = "Select")
shinyWidgets:::normalizeChoicesArgs(choices = vec)
```
results in
```
Error in shinyWidgets:::normalizeChoicesArgs(choices = vec) : 
  argument "choiceNames" is missing, with no default
```

Alternative approach ie providing "choiceNames":
```
vec <- c(all = "All", other = "Select")
shinyWidgets:::normalizeChoicesArgs(choices = vec, choiceNames = names(vec))

$choiceNames[[2]]
[1] "other"


$choiceValues
$choiceValues[[1]]
[1] "All"

$choiceValues[[2]]
[1] "Select"


Warning message:
In shinyWidgets:::normalizeChoicesArgs(choices = vec, choiceNames = names(vec)) :
  Using `choices` argument; ignoring `choiceNames` and `choiceValues`.
```
 Looks like a minor bug, but breaks eg some {golem} R package tests.

A better guess is that it is line 156 in file `R/utils.R` that is causing this. 

Currently: `if (!is.null(choiceNames) || !is.null(choiceValues))` 

I think this should either be `!missing...` or 
probably better parameters `choiceNames` and `choiceValues` need to have `NULL` as default values in the `normalizeChoicesArgs` function header. 

```
packageVersion('shinyWidgets')
[1] '0.7.5'
```
```
sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9         shinyWidgets_0.7.5 digest_0.6.31      later_1.3.0
 [5] mime_0.12          R6_2.5.1           lifecycle_1.0.3    xtable_1.8-4
 [9] jsonlite_1.8.4     magrittr_2.0.3     rlang_1.0.6        cachem_1.0.6
[13] cli_3.5.0          promises_1.2.0.1   jquerylib_0.1.4    bslib_0.4.2
[17] ellipsis_0.3.2     tools_4.1.3        shiny_1.7.4        httpuv_1.6.7
[21] fastmap_1.1.0      compiler_4.1.3     htmltools_0.5.4    sass_0.4.4
```

**Comment by pvictor** [comment]
Mmh I think it's normal to have an error, the behavior of this function has not changed for a while.
Why are you using it directly ? What's in the failing test ?

**Comment by gwd666** [comment]
{golem} package seems to call this underneath some of its "auto" module tests
```
test_that("module ui works", {
  ui <- mod_folders_ui(id = "test")
  # golem::expect_shinytaglist(ui) either the test errors or the app won't run b/c of error Navigation containers expect a collection of ...
  golem::expect_shinytag(ui) # changed to shinytag instead of tagList to fix testing error
  # Check that formals have not been removed
  fmls <- formals(mod_folders_ui)
  for (i in c("id")) {
    expect_true(i %in% names(fmls))
  }
})
``` 
But this function will always break on line 156 in utils.R wouldn't it? Is that really intentional?

**Comment by gwd666** [comment]
tbh I am not sure if there wouldn't also need to be `choices = NULL` as a default otherwise the same breaks from calling ths func directly will also happen/apply when a user provides `choiceNames` and  `choiceValues` together and leaves out `choices`. 
But I have to admit that I do not know how or where the `normalizeChoicesArgs` func gets called in other places to be sure that this is relevant or not.

**Comment by pvictor** [comment]
Your problem is elsewhere, you're calling `` without any arguments (neither `choices` or `choiceNames` / `choiceValue`), the error is intended you have to provide choices. The behavior is the same in shiny so I won't update that : 

```r
> shinyWidgets::radioGroupButtons()
Error in normalizeChoicesArgs(choices, choiceNames, choiceValues) : 
  Please specify a non-empty vector for `choices` (or, alternatively, for both `choiceNames` AND `choiceValues`).
> shiny::radioButtons()
Error in normalizeChoicesArgs(choices, choiceNames, choiceValues) : 
  Please specify a non-empty vector for `choices` (or, alternatively, for both `choiceNames` AND `choiceValues`).
```

**Comment by gwd666** [comment]
Of course I am calling the radioGroupButton with choices I just made the example smaller

**Comment by pvictor** [comment]
Please provide code for `mod_module1_ui`, I still think the problem is here.
I understand your point, but `normalizeChoicesArgs()` should not be called without specifyng the 3 args or with both `choices` and `choiceNames`/`choiceValues` set to `NULL`

**Comment by gwd666** [comment]
You were absolutely RIGHT! 
The fix for my breaking test was to wrap the choices via `ns = NS(id)` and then `choices = ns(SomeNamedVector)` for the test to succeed. I had only put the inputId in `ns()` like 
```
shinyWidgets::radioGroupButtons(
inputId = ns("choose") 
label = ... 
choices = ns(SomeNamedVector)
```
Thank you very much for your patience! 
Sorry about my ignorance there. Of course you can skip that PR ....
