### ISSUE TITLE
Character management in `virtualSelectInput`

### ISSUE THREAD

**Issue by ocelhay** [dreamRs/shinyWidgets#565]
Differently from say `pickerInput`, `virtualSelectInput` will return return "& lt;25k" instead of "<25k". That seems a bit dangerous as one (like me!) can easily miss it and have downstream filtering not working as expected.

<img width="348" alt="SCR-20230109-jqm" src="https://user-images.githubusercontent.com/7565024/211419161-5d7ae7f9-6bb3-4a79-bc4d-c6cfdf61651b.png">

```r
library(shiny)

ui <- fluidPage(
  shinyWidgets::pickerInput(
    "income_household_1",
    "Income pickerInput:",
    choices = c("<25k", "other"),
    selected = c("<25k", "other"),
    multiple = TRUE
  ),
  textOutput("income_1"),
  br(), br(),
  
  # issue: returns "&lt;25k" instead of "<25k"
  shinyWidgets::virtualSelectInput(
    "income_household_2",
    "Income virtualSelectInput:",
    choices = c("<25k", "other"),
    selected = c("<25k", "other"),
    multiple = TRUE
  ),
  textOutput("income_2")
)


server <- function(input, output) {
  output$income_1 <- renderText(
    paste(input$income_household_1)
  )
  output$income_2 <- renderText(
    paste(input$income_household_2)
  )
}

shinyApp(ui = ui, server = server)

```

**Comment by pvictor** [comment]
HTML escaping is performed on the choices, try using `virtualSlectInput(..., html = TRUE)`, it's set to FALSE by default for performance reason.

**Comment by ocelhay** [comment]
Thanks for the help. Works well!
