### ISSUE TITLE
airDatePickerInput does not show anything to pick in version 0.7.6

### ISSUE THREAD

**Issue by shaenzi** [dreamRs/shinyWidgets#569]
The `airDatePickerInput` does not show anything to pick in version 0.7.6. Comparing `demoAirDatepicker()` in version 0.7.5 - there, as soon as I click into the widget, a calendar view appears below for me to choose a date. However, when I run the demo with version 0.7.6, nothing happens when I click in/on the widget. Since this is happening even with the demo, I assume it is independent of my use of `airDatePickerInput` in my particular app.

**Comment by pvictor** [comment]
Hello,
Everything is working fine for me, which browser are you using ?

Victor

**Comment by shaenzi** [comment]
Hi Victor,
ah, you are right. I was assuming because it worked in RStudio rather than in the Browser with version 0.7.5 it would be the same with 0.7.6, where it works in (any) browser but not in RStudio.
Sorry for the bother,
Sara

**Comment by pvictor** [comment]
I'll look at what's going on in the RStudio viewer, I admit I never use it.
