### ISSUE TITLE
Picker Input doesn't work after session reconnects and is inside a modal.

### ISSUE THREAD

**Issue by apalacio9502** [dreamRs/shinyWidgets#573]
I currently design a shiny application that allows the user to reconnect the session. and the user has the option of displaying a modal to select some options (pickerInput).

Case 1: If the user starts the app and opens the modal it works fine. And if the user later reconnects the session and opens the modal again, it works correctly.

**Case 2: If the user starts the application and never opens the modal and then the user reconnects the session and opens the modal again, the picker input does not work.**

Case 3: If we add a pickerInput to the base UI it works correctly as case 1.

I think this is related to the fact that in the second case the picker input dependencies were never loaded.

Regards

**Comment by pvictor** [comment]
Weird.. you can try to add the dependency explicitly somewhere in your UI with `shinyWidgets:::html_dependency_picker()`.
Otherwise I'll need more information about where the app is run, in which browser, which version of packages, an example, etc...

Victor
