### ISSUE TITLE
some skin option in chooseSliderSkin has deprecated. (may require function description update)

### ISSUE THREAD

**Issue by jhk0530** [dreamRs/shinyWidgets#575]
HI, thanks for the nice package and effort.

with `?chooseSliderSkin`

argument `skin`  is described as 

> The skin to apply. Choose among 5 different flavors, namely `Shiny`, `Flat`, `Modern`, `Nice`, `Simple`, `HTML5`, `Round`, and `Square`.

However, the below code will generate a warning message without working.

```{r}
library(shinyWidgets) 

chooseSliderSkin('Nice')
chooseSliderSkin('Simple')
chooseSliderSkin('HTML5')
```

> Warning message:
In shinyWidgets::chooseSliderSkin("HTML5") :
  Skin ' HTML5 ' is deprecated, please see http://ionden.com/a/plugins/ion.rangeSlider/skins.html for available ones.

shinyWidgets Version: **0.7.6**
shiny Version: **1.7.4**

---

I checked chooseSliderSkin.R

and found this.

```{r}
if (packageVersion("shiny") > "1.5.0.9000" & skin %in% c("Nice", "Simple", "HTML5")) {
    warning(paste(
      "Skin '", skin,
      "' is deprecated, please see http://ionden.com/a/plugins/ion.rangeSlider/skins.html for available ones."
    ))
    skin <- "Flat"
  }
```
and 

```{r}
   # } else if (skin == "Nice") {
    #   asb_ <- asb("#99a4ac", color)
    #   angle <- asb_[1]
    #   saturate <- asb_[2]
    #   brightness <- asb_[3]
    #   colImg <- paste0(
    #     ".irs-bar-edge, .irs-line-mid, .irs-single:after",
    #     " {",
    #     "-webkit-filter: hue-rotate(", angle, "deg) saturate(",
    #     saturate, "%) brightness(", brightness, "%); ",
    #     "filter: hue-rotate(", angle, "deg) saturate(",
    #     saturate, "%) brightness(", brightness, "%);",
    #     "}"
    #   )
    #   cssColor <- singleton(
    #     tags$head(
    #       tags$style(
    #         colImg,
    #         sprintf(".irs-single, .irs-from, .irs-to {background: %s;}", color)
    #       )
    #     )
    #   )
```

So, I just think removing these 3 deprecated options in the manual could be fine.

Thanks.

**Comment by pvictor** [comment]
Thanks, I removed those options since they were deprecated for a long time
