### ISSUE TITLE
Select option is not working for treeimput widget.

### ISSUE THREAD

**Issue by jgallegoalonso** [dreamRs/shinyWidgets#579]
I cant pre-select values in a treeimput widget ussing the select option. I've tried using ID's and text.

Apart from that. It is posible to have the folders icons in this widget as in the standar shinytree?

Tahnk you.

treeInput(
                             inputId = "tree",
                             label = "Marca los ámbitos que te interesen:",
                             choices = create_tree(ISCED_ARBOL,levels = names(ISCED_ARBOL)[1:3],levels_id = names(ISCED_ARBOL)[4:6]),
                             selected = "143",
                             returnValue = "id",
                             closeDepth = 1
                           )

**Comment by pvictor** [comment]
Hello,
Using text it should work with CRAN release, but if you re-install from GitHub it should work with ID.
The only way to use an icon is with some CSS.

Here an example:

```r
library(shiny)
library(shinyWidgets)

# data
cities <- data.frame(
  continent = c("<b>AA</b>America", "America", "America", "Africa",
                "Africa", "Africa", "Africa", "Africa",
                "Europe", "Europe", "Europe", "Antarctica"),
  country = c("Canada", "Canada", "USA", "Tunisia", "Tunisia",
              "Tunisia", "Algeria", "Algeria", "Italy", "Germany", "Spain", NA),
  city = c("Trois-Rivières", "Québec", "San Francisco", "Tunis",
           "Monastir", "Sousse", "Alger", "Oran", "Rome", "Berlin", "Madrid", NA),
  stringsAsFactors = TRUE
)
cities$continent_id <- as.numeric(cities$continent)
cities$country_id <- paste0(as.numeric(cities$continent), as.numeric(cities$country))
cities$city_id <- paste0(as.numeric(cities$continent), as.numeric(cities$country), as.numeric(cities$city))

# app
ui <- fluidPage(
  
  # load Icon dependencies
  icon("user"),
  
  # Use unicode for icon
  tags$style(
    ".treejs-label::before {content: '\\f07b'; font: var(--fa-font-regular); padding-right: 5px;}"
  ),
  
  treeInput(
    inputId = "ID",
    label = "Select cities:",
    choices = create_tree(cities, levels = names(cities)[1:3], levels_id = names(cities)[4:6]),
    selected = "378",
    returnValue = "id",
    closeDepth = 0
  ),
  verbatimTextOutput("res")
)

server <- function(input, output, session) {
  
  output$res <- renderPrint(input$ID)
  
}

shinyApp(ui, server)
```

Victor

**Comment by jgallegoalonso** [comment]
Hello Victor,

Thank you very much for your help, I was using ID but the CRAN version
works with text.

Congratulations for your work.

Best regards,
Jose M Gallego.
