### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by fsty** [dreamRs/shinyWidgets#580]
Hi thank you for this work, I came across ant design project : https://ant.design/components/overview  It will be great if we can use some of these components in shiny

**Comment by pvictor** [comment]
Hello,
That's a whole framework to integrate, not in my plan right now.
If you want to try to do it, I think you should look at https://github.com/Appsilon/shiny.react and https://github.com/Appsilon/shiny.fluent by Appsilon

Victor
