### ISSUE TITLE
pickerInput: how to disable individual options? (This is supported on bootstrap-select)

### ISSUE THREAD

**Issue by daattali** [dreamRs/shinyWidgets#588]
According to the bootstrap-select documentation, individual options in the dropdown can be disabled by adding a `disabled` attribute https://developer.snapappointments.com/bootstrap-select/examples/#disabled-options

I could not figure out how to do this using pickerInput.

**Comment by pvictor** [comment]
Hello,
There's an example in [`?updatePickerInput`](https://dreamrs.github.io/shinyWidgets/reference/updatePickerInput.html#ref-examples) documentation.

Victor

**Comment by daattali** [comment]
Ah thanks! I never did understand what "choicesOpt" was. Perhaps an extra sentence or two in the parameter's documentation about its syntax and what it does would help. Feel free to close this issue if you don't feel that's necessary.

**Comment by pvictor** [comment]
You're welcome, yes indeed the documentation could be improved, I will take care of it.
