### ISSUE TITLE
change color in css

### ISSUE THREAD

**Issue by dylancis** [dreamRs/shinyWidgets#59]
hi, how do we override colours in css ?
The below is not working because the external css is overriding with !important in there...
```
#.pretty.p-toggle .state.p-primary label :after .override{
    background-color: yellow !important;
}
```
Thank you

**Comment by pvictor** [comment]
Hi,
You can overwrite color for default status apparently : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$style(".pretty.p-default input:checked~.state label:after {background-color: #A901DB !important;}"),
  prettyCheckbox(
    inputId = "checkbox1",
    label = "Click me!",
    value = TRUE,
    shape = "square", 
    fill = TRUE,
    status = "default"
  ),
  verbatimTextOutput(outputId = "res1")
)

server <- function(input, output, session) {
  output$res1 <- renderPrint(input$checkbox1)
}

shinyApp(ui, server)
```

If needed, i can remove the limitation for argument status, to pass a custom one.

Victor

**Comment by dylancis** [comment]
Works like a charm ! Thanks.

**Comment by rdornas** [comment]
> Hi, You can overwrite color for default status apparently :
> 
> ```r
> library(shiny)
> library(shinyWidgets)
> 
> ui <- fluidPage(
>   tags$style(".pretty.p-default input:checked~.state label:after {background-color: #A901DB !important;}"),
>   prettyCheckbox(
>     inputId = "checkbox1",
>     label = "Click me!",
>     value = TRUE,
>     shape = "square", 
>     fill = TRUE,
>     status = "default"
>   ),
>   verbatimTextOutput(outputId = "res1")
> )
> 
> server <- function(input, output, session) {
>   output$res1 <- renderPrint(input$checkbox1)
> }
> 
> shinyApp(ui, server)
> ```
> 
> If needed, i can remove the limitation for argument status, to pass a custom one.
> 
> Victor

Sorry for reopening this old issue, but I'm having trouble with the background-color on the prettyCheckbox function.

I am able to fill the box with the desired color *as long as I don't use the argument* `icon`.

In my case, if the line with the argument `icon` is commented I get a box in the correct color. However, If `icon` is not commented and active, the box is white but with the check mark correctly rendered.

### Without `icon`
![image](https://github.com/dreamRs/shinyWidgets/assets/25906665/2822b1ad-282e-42e2-a925-7c9cb4d6e1f4)

### With `icon`
![image](https://github.com/dreamRs/shinyWidgets/assets/25906665/50fac188-cbc3-4029-9b34-0861e6ce3d58)

Code:
```
shinyWidgets::prettyCheckbox(
  inputId = ns("bar"),
  label = "Foo",
  value = FALSE,
  shape = "curve",
  fill = TRUE,
  status = "default",
  # icon = icon("check"),
  animation = "smooth"
)
```

What am I doing wrong?

Thank you for your patience and kindness.
