### ISSUE TITLE
radioGroupButtons: selected = character(0) can't be restored from url

### ISSUE THREAD

**Issue by nelstevens** [dreamRs/shinyWidgets#590]
Hi there,

First of all thank you very much for this awesome package. I've recently tried to implement bookmarkable states in a shinyapp using radioGrouButtons with nothing selected as default. When restoring the application (without selecting any radioGroupButton) radioGroupButtons automatically resolves to the first value in choices.

```r
library(shiny)
library(shinyWidgets)

ui <- function() {
  fluidPage(
    radioGroupButtons(
      "rad",
      choices = c("one", "two"),
      selected = character(0)
    ),
    bookmarkButton()
  )
}
server <- function(input, output, session) {
  observe(cat(input$rad))
}

shinyApp(ui, server, enableBookmarking = "url")
```

I think the problem is that the query string stores this as null, which turns to args$choiceValues[[1]] in:

https://github.com/dreamRs/shinyWidgets/blob/29067ac93ef4b51e3b8bb143af17a0409090f6be/R/input-radiogroupbuttons.R#L47-L48

I've already found a workaround but thought maybe it's of interest.

Thanks

**Comment by antilneeraj** [comment]
The code you provided appears to be a Shiny app that uses the `shiny` and `shinyWidgets` libraries. Based on the code, it seems that you are trying to create a radio group buttons input and a bookmark button, and observe the selected value from the radio group buttons.

However, there is an issue with the `observe` function call. The `cat` function is used to print the value of `input$rad` to the console, but `observe` expects a reactive expression as its argument. To fix this, you can use the `reactive` or `reactiveValues` functions to create a reactive variable that holds the value of `input$rad`, and then use that reactive variable in the `observe` function. 
Here's the fixed code:
```R
library(shiny)
library(shinyWidgets)

ui <- function() {
  fluidPage(
    radioGroupButtons(
      "rad",
      choices = c("one", "two"),
      selected = character(0)
    ),
    bookmarkButton()
  )
}

server <- function(input, output, session) {
  # Create a reactive variable to hold the value of input$rad
  rad_value <- reactive({
    input$rad
  })
  
  # Observe the value of rad_value and print to console
  observe({
    cat(rad_value())
  })
}

shinyApp(ui, server, enableBookmarking = "url")
```
In this fixed code, `rad_value` is a reactive variable that holds the value of `input$rad`. The `observe` function now refers to `rad_value()` to get the value of the reactive variable, and `cat` is used to print the value to the console.

**Comment by pvictor** [comment]
Hello, I understand the issue but I don't know what to do to fix it or if it need to be fixed.
