### ISSUE TITLE
`maxOptions` can be overridden by the "Select All" button when `actionsBox = TRUE`

### ISSUE THREAD

**Issue by yogat3ch** [dreamRs/shinyWidgets#595]
A workaround is to disappear the "Select All" button assuming you have only a single instance of the widget on your page for which you don't want "Select All" to be an option. You can do so by adding the following as the option for `selectAllText`. Not super elegant but it works

```r
pickerInput(
    inputId = "Id083",
    label = "Multiple", 
    choices = attr(UScitiesD, "Labels"),
    multiple = TRUE,
    options = shinyWidgets::pickerOptions(
        maxOptions = 4,
        actionsBox = TRUE,
        selectAllText = HTML(htmltools::doRenderTags(tags$style("button.actions-btn.bs-select-all {display:none;}")))
    )   
)

```

**Comment by pvictor** [comment]
Hello,
Yes this is an issue in the [bootstrap-select](https://github.com/snapappointments/bootstrap-select) library, this has been reported [here](https://github.com/snapappointments/bootstrap-select/issues/2277).
There's no soultion yet, the workaround suggested is to hide the select all button as you do. Note that you can put the CSS anywhere in your UI and that it will affects all `pickerInput`.

Victor

**Comment by yogat3ch** [comment]
Ah, thanks for investigating that @pvictor! Indeed, the code in the demo will effect all of the `pickerInput`s if the CSS selector targets the class that they all share. The selector could be prefaced with the ns(id) in the selector if we wanted to target just this instance like so (adding this just in case other folks land on this issue):
```r
pickerInput(
    inputId = "Id083",
    label = "Multiple", 
    choices = attr(UScitiesD, "Labels"),
    multiple = TRUE,
    options = shinyWidgets::pickerOptions(
        maxOptions = 4,
        actionsBox = TRUE,
        selectAllText = HTML(htmltools::doRenderTags(tags$style(glue::glue("#{id} button.actions-btn.bs-select-all {display:none;}"))))
    )   
)
```
Thank you!
