### ISSUE TITLE
`labelRenderer` property in virtualSearchInput?

### ISSUE THREAD

**Issue by moturoa** [dreamRs/shinyWidgets#601]
In [this example](https://sa-si-dev.github.io/virtual-select/#/examples?id=add-imageicon) we see the use of the `labelRenderer` option. I was wondering if you know whether it can be used from `virtualSelectInput`, as the option should be passed through `...`

Non-working example with selectizeInput for reference:

```
library(shiny)
chcs <- rownames(mtcars)

ui <- fluidPage(theme = bslib::bs_theme(version = 5),

  shinyWidgets::virtualSelectInput("sel1", "Select car (virtual select)",
                             choices = chcs,
                             labelRenderer = I('function(data){
                                                  return "<span style = \'font-size: 3em;\'>" + data.label + "</span>";
                                                }')
                             ),
  
  selectizeInput("sel2", "Select car (selectinput)", choices = chcs,
              options = list(
                render = I('{
                              item: function(data){
                                    return "<span style = \'color:red;\'>" + data.label + "</span>";
                              },
                              option: function(data){
                                    return "<div style = \'color: blue;\'>" + data.label + "</div>";
                              }
                           }
                           ')
              )
              )
)
server <- function(input, output, session) {}
shinyApp(ui, server)
```

Thank you!

**Comment by moturoa** [comment]
I need to add that making the HTML beforehand, and using argument `html = TRUE` renders the labels nicely **however** using `search = TRUE` is weird because it then displays raw HTML as a search result. <<Example will be inserted here>>.

**Comment by pvictor** [comment]
Hello,

For the moment, it is not possible to use the labelRenderer option: no javascript code passed as an argument is executed.
I see the issue but labelRenderer  doesn't seems to fix it according to that issue https://github.com/sa-si-dev/virtual-select/issues/249, this seems fixed with a PR but not released yet.
I suggest waiting for the next release to see if the problem has been corrected, and then we can look at labelRenderer if needed.

Victor

**Comment by pvictor** [comment]
I have updated virtual-select-plugin to 1.0.38, the issue seems fixed, install from GitHub to try and let me know if it's good for you.

**Comment by moturoa** [comment]
Yes that solved the issue, thank you!
