### ISSUE TITLE
updatePickerInput seems to be only able to have one value selected vs multiple, when called

### ISSUE THREAD

**Issue by AdrianAntico** [dreamRs/shinyWidgets#603]
Hi dreamRs team,

Is it possible to utilize updatePickerInput in a way that enables multiple values to be selected after it's called? Currently, it truncates the set of values to just a single one and ignores the rest.

**Comment by pvictor** [comment]
I'm not sure if I've understood the problem correctly. Yes, it is possible to select several values:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  pickerInput(
    inputId = "ID",
    label = "Select month",
    choices = month.name,
    multiple = TRUE
  ),
  verbatimTextOutput("value"),
  actionButton("update", "Select months finishing by 'er'")
)

server <- function(input, output, session) {
  output$value <- renderPrint(input$ID)
  observeEvent(input$update, {
    updatePickerInput(
      session = session,
      inputId = "ID",
      selected = grep("er$", month.name, value = TRUE)
    )
  })
}

shinyApp(ui, server)
```

**Comment by AdrianAntico** [comment]
@pvictor sorry, you guys were right, I was just messing up how I used the update version. I'll close the issue now
