### ISSUE TITLE
sliderTextInput doesn't take NULL as an argument

### ISSUE THREAD

**Issue by nfuryn** [dreamRs/shinyWidgets#608]
The following code in UI:
```
sliderTextInput(
    inputId = "TimeLine",
    label = NULL,
    grid = TRUE, 
    force_edges = TRUE,
    choices = NULL,
    selected = NULL
  )
```
Despite having a server-side update:
```
  observe({
  updateSliderTextInput(
    session = session,
    inputId = "TimeLine",
    label = NULL,
    choices = unique(df$MonthYear),
    selected = df$MonthYear[ncol(df)]
    )})
```
Gives me the following error:
`Invalid 'selected' arguments, probably not an element of 'choices'.`
It only works if I put month.name in choices and month.name[1] in selected in UI, but then it loads up month 1-12 instead of my defined choices.

**Comment by pvictor** [comment]
Maybe you can render the sliderText with `uiOutput / renderUI` so it won't be displayed with falsy values, and then use `req()` in your server logic to assure `input$Timeline` has a correct value.

**Comment by nfuryn** [comment]
> Maybe you can render the sliderText with `uiOutput / renderUI` so it won't be displayed with falsy values, and then use `req()` in your server logic to assure `input$Timeline` has a correct value.

yep, that's exactly what I did while I was waiting for a reply. Thanks!
