### ISSUE TITLE
airDatePickerInput not displaying properly in app (shiny, dashboard, and bs4Dash)

### ISSUE THREAD

**Issue by adamhaywood307** [dreamRs/shinyWidgets#609]
shinyWidgets (version 0.7.6), latest versions of shiny, shinyDashboard, and bs4Dash.

airDatePickerInput renders as a blank box, and when clicked, nothing happens. If we use shinyWidgets version 0.7.3, we are able to select a date and time, but everything appears as an "am" value. For example, when the value is initialized as "2023-06-27 14:00", the box will display as "2023-06-27 2:00 am", but when clicked, the timeslider shows "02:00 pm".

reprex below:

library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  titlePanel("Hello Shiny!"),

  sidebarLayout(

    sidebarPanel(

      sliderInput(inputId = "bins",
                  label = "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)

    ),

    mainPanel(

      plotOutput(outputId = "distPlot"),
      airDatepickerInput(
        inputId = "test",
        label = "TEST",
        timepicker = TRUE
      )

    )
  )
)

server <- function(input, output) {

  output$distPlot <- renderPlot({

    x    <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)

    hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "Waiting time to next eruption (in mins)",
         main = "Histogram of waiting times")

    })

}

shinyApp(ui = ui, server = server)

**Comment by adamhaywood307** [comment]
![image](https://github.com/dreamRs/shinyWidgets/assets/52833562/bfafc931-17b7-4083-b6ab-b0e84c830b86)

Example of the issue with shinyWidgets 0.7.3

**Comment by pvictor** [comment]
You can change time format with `timepickerOpts = timepickerOptions(timeFormat = "H:mm")`, here's an example with last CRAN version : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  airDatepickerInput(
    inputId = "test",
    label = "TEST",
    value = "2023-06-27 14:00",
    timepicker = TRUE,
    timepickerOpts = timepickerOptions(timeFormat = "H:mm")
  ),
  verbatimTextOutput("res")
)

server <- function(input, output) {
  
  output$res <- renderPrint(input$test)
  
}

shinyApp(ui = ui, server = server)
```

![image](https://github.com/dreamRs/shinyWidgets/assets/4415580/27be3bf0-0a45-4f66-ad21-18df1b5aa4b9)

![image](https://github.com/dreamRs/shinyWidgets/assets/4415580/ed99a382-1aa6-44e1-bb16-e2923b72e738)
