### ISSUE TITLE
switchInput seems to slow down fileinput

### ISSUE THREAD

**Issue by VincentGuyader** [dreamRs/shinyWidgets#61]
HI,

Please test this shiny app by uploading a big csv file (~150Mo):
 this is quite fast (depend on your computer), 
but if I add a `switchInput` this is very, very slow
```
library(shiny)
library(shinyWidgets)
options(shiny.maxRequestSize=3000*1024^2)  
allFileInput <- function(id, label = "Upload your file") {
  ns <- NS(id)
  
  tagList(
    fileInput(ns("file"), label)
    # ,column(6,switchInput(inputId = ns("header"),label="Header",value = TRUE,inline=TRUE))
    )
    }

allFile <- function(input, output, session, stringsAsFactors=TRUE) {
  observeEvent(input$file,{
    message("coucou")
  })
}

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      allFileInput("plop")
    )
    ,
    mainPanel(
      tableOutput("contents")
    )
  )
)
server <- function(input, output,session) {
  callModule(allFile,"plop")
}

shinyApp(ui, server)
```
Any idea why ?

Merci :)

> > sessionInfo()
> R version 3.4.3 (2017-11-30)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
> [4] LC_NUMERIC=C                   LC_TIME=French_France.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] shinyWidgets_0.4.1 cleanser_0.1       shiny_1.0.5       
> 
> loaded via a namespace (and not attached):
>  [1] settings_0.2.4    shinyjs_1.0       purrr_0.2.4       haven_1.1.1       colorspace_1.3-2  testthat_2.0.0   
>  [7] htmltools_0.3.6   yaml_2.1.18       validate_0.2.0    rlang_0.2.0       pillar_1.2.1      readit_1.0.0     
> [13] glue_1.2.0        withr_2.1.2       readxl_1.0.0      bindrcpp_0.2      plyr_1.8.4        bindr_0.1.1      
> [19] stringr_1.3.0     munsell_0.4.3     commonmark_1.4    gtable_0.2.0      cellranger_1.1.0  devtools_1.13.5  
> [25] htmlwidgets_1.0   memoise_1.1.0     forcats_0.3.0     crosstalk_1.0.0   httpuv_1.3.6.2    Rcpp_0.12.16     
> [31] xtable_1.8-2      readr_1.1.1       backports_1.1.2   scales_0.5.0      DT_0.4            desc_1.1.1       
> [37] jsonlite_1.5      mime_0.5          simplemagic_0.1.0 ggplot2_2.2.1     hms_0.4.2         digest_0.6.15    
> [43] stringi_1.1.7     dplyr_0.7.4       rprojroot_1.3-2   grid_3.4.3        tools_3.4.3       magrittr_1.5     
> [49] lazyeval_0.2.1    tibble_1.4.2      crayon_1.3.4      pkgconfig_2.0.1   rsconnect_0.8.8   xml2_1.2.0       
> [55] lubridate_1.7.2   assertthat_0.2.0  roxygen2_6.0.1    rstudioapi_0.7    R6_2.2.2          compiler_3.4.3

**Comment by pvictor** [comment]
Hi Vincent,

This depends on your computer but mostly on your browser.
`fileInput` use custom bindings for IE8 and Shiny viewer. Timing is pretty much the same on Chrome and Firefox : 

Without `switchInput` : 
![image](https://user-images.githubusercontent.com/4415580/38172291-136b1e94-35aa-11e8-94df-550014576a4d.png)
Range: 2.21 s – 4.04 s (1.43s)

With  `switchInput` : 
![image](https://user-images.githubusercontent.com/4415580/38172299-353f8bae-35aa-11e8-8664-e7bc43a4a6ea.png)
Range: 2.54 s – 4.37 s (1.43s)

There's a little difference when loading page due to scripting.

Victor
