### ISSUE TITLE
PickerInput not displaying choices when `Multiple = TRUE` and with `pickerOptions(mobile = TRUE)`

### ISSUE THREAD

**Issue by rprops** [dreamRs/shinyWidgets#610]
In a runtime shiny flexdashboard `pickerInput` does not render choices (but can be selected somehow by click and dragging) to select when:
-  `multiple = TRUE` and with
-  `pickerOptions(mobile = TRUE)` (crucial for my application)

```
renderUI(
  fluidRow(
  column(
    offset = 0,
    width = 12,
    setBackgroundColor = "#FFFFFF",
    pickerInput(
      "proj_id_sel",
      label = "Project ID:",
      choices = unique(projects),
      options = pickerOptions(mobile = TRUE),
      multiple = TRUE
    )
  )
))
```

On clicking the widget nothing happens, but sometimes you can suddenly select an option (but it never renders).

![image](https://github.com/dreamRs/shinyWidgets/assets/19682548/3e09ac5e-8ca0-43de-be6a-96126c00beba)

When the `pickerOptions(mobile = TRUE)` is removed it does work:

![image](https://github.com/dreamRs/shinyWidgets/assets/19682548/3ad4f4b0-3733-4c89-bb10-c4858349ddca)

**Comment by pvictor** [comment]
I never used that option but I think this works only on mobile, what are you trying to achieve with `mobile = TRUE` ?

**Comment by rprops** [comment]
I'm trying to achieve a widget that works both on mobile and web. The alternative by using two chunks with {.mobile} doesn't seem to work because runtime shiny cannot deal with two chunks with widgets with the same ID (even though they should be conditionally rendered using the .mobile flag).

**Comment by pvictor** [comment]
Ok, thanks. `pickerInput()` works fine on mobile without `mobile = TRUE`, if you need a different look on mobile tou can try `virtualSelectInput()` which has an option to open as a popup rather than dropdown according to screensize, see example below.
For your two chunks you have to use different IDs and use an intermediate `reactiveValues` to combine select's values.


```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$h2("Virtual Select"),
  virtualSelectInput(
    inputId = "ID",
    label = "Select :",
    choices = month.name,
    search = TRUE,
    showDropboxAsPopup = TRUE,
    popupDropboxBreakpoint = "500px" # minimize your window and relaunch/refresh app to see the popup
  ) ,
  verbatimTextOutput("res")
)

server <- function(input, output, session) {
  
  output$res <- renderPrint(input$ID)
  
}

shinyApp(ui, server)
```

**Comment by rprops** [comment]
Okay, by migrating to `virtualSelectInput()` I've managed to solve my problem. Thank you for your assistance, it has been much appreciated! @pvictor , I will close the issue for you.
