### ISSUE TITLE
bug in airDatepickerInput

### ISSUE THREAD

**Issue by AxelCode-R** [dreamRs/shinyWidgets#612]
If you change the date using the keyboard, no observer is triggered!

Example app:
Start App/ click in Date picker/ e.g. change the 2023 to 2024 / no notification is send. Its important that this will work, because users think they have changed it and press save or trigger and it uses the date from before....!

```
library(shiny)

ui <- fluidPage(
    shinyWidgets::airDatepickerInput(
        inputId = "picker",
        label = "Date:",
        value = Sys.Date()
    )
)


server <- function(input, output) {
    observeEvent(input$picker,{
        showNotification("hallo im changed!")
    })
}
 
shinyApp(ui = ui, server = server)
```

**Comment by AxelCode-R** [comment]
i suggest <input onkeydown="return false">

**Comment by pvictor** [comment]
I think we need to update the subscribe method in the JavaScript bindings : https://github.com/dreamRs/shinyWidgets/blob/60b205bb07357f0bf87c268536d037105e5f2994/srcjs/inputs/air-datepicker.js#L246

**Comment by pvictor** [comment]
That's not possible to send input field value to air-datepicker (easily at least, see https://github.com/t1m0n/air-datepicker/issues/41). To fix this I added `readonly` and `onkeydown` arguments to prevent editing the text field by using one or the other.
