### ISSUE TITLE
AirDateInput with range=T is not always a range

### ISSUE THREAD

**Issue by AxelCode-R** [dreamRs/shinyWidgets#615]
Its just a very small bug that any user can handle, but its somewhat not pretty. If you use the AirDateInput to always return a range with e.g. c(Sys.Date()-10, Sys.Date()) and it should be possible to select just one day with e.g. c(Sys.Date(), Sys.Date()), then it will return c(Sys.Date()). More explicit: It is possible to update a AirDateInput with value = c(Sys.Date(), Sys.Date()) which is great, but it isnt possible to select the same via the UI, because selecting the same day will deselect it. 

Example App to inspect the behavior:
```
library(shiny)

ui <- fluidPage(

    actionButton("update_to_1_day_range", toupper("update_to_1_day_range")),
    shinyWidgets::airDatepickerInput(
        inputId = "date_range",
        label = "DATE RANGE",
        range = TRUE
    )
)

server <- function(input, output) {

    observeEvent(input$date_range, {
        showNotification(paste0("length: ", length(input$date_range), "   selected: ", paste0(input$date_range, collapse = "; ")))
    })
    
    observeEvent(input$update_to_1_day_range, {
        shinyWidgets::updateAirDateInput(inputId = "date_range", value = c(Sys.Date(), Sys.Date()))
    })
}

shinyApp(ui = ui, server = server)
```
Used version of shinyWidgets: 0.7.6

I understand why deselecting by clicking the same day is maybe prefaired, especially if 1 day ranges are not accepted, example use-case: selected upper bound "2023-11-01"/ clicked until month 03/ selected wrong lower bound "2023-03-02"/ can deselect without reselecting upper bound/ selected correct lower bound "2023-03-01"

But if the following issue is solved: https://github.com/dreamRs/shinyWidgets/issues/612
It would decrease the benefit of deselecting, which will increase the benefits of having a consistent data format (range=T -> always returns c(isDate, isDate))

**Comment by pvictor** [comment]
Hello,
You can use argument `toggleSelected = FALSE` to allow selecting same day in range mode.

Victor
