### ISSUE TITLE
Air Date Picker Input mistake in documentation for minute format

### ISSUE THREAD

**Issue by iPerineum** [dreamRs/shinyWidgets#616]
I noticed the documentation states that the time format for minutes can or should be changed to "i" or "ii" in the timepickerOpts.

![doc](https://github.com/dreamRs/shinyWidgets/assets/98490042/832f8d8b-a0b5-4cf4-9b9f-fa394589ed91)

However including "ii" always led to the display of "ii" in the shiny dashboard. Intuitively, I simply tried "mm" to fix the issue and in fact the time format was displayed correctly.

I am coding in R and I am on shinyWidgets version: 0.7.6

here are two examples (issue and fix) in a simple shiny dashboard 
Note: In my final application seconds are necessary, therefore they are included as :00 in the timeFormat

**issue:**
```R
library(shiny)
library(shinydashboard)
library(shinyWidgets)

# Define the UI
ui <- dashboardPage(
  dashboardHeader(title = "Simple Shiny Dashboard"),
  dashboardSidebar(),
  dashboardBody(
    box(
      airDatepickerInput(
        inputId = "date_picker",
        label = "Date:",
        placeholder = "Please select a Time period",
        multiple = 2,
        minDate = "2021-01-01",
        clearButton = TRUE,
        timepicker = TRUE,
        todayButton = TRUE,
        range = TRUE,
        toggleSelected = FALSE,
        timepickerOpts = timepickerOptions(timeFormat = "hh:ii:00")
      )
    ),
    verbatimTextOutput("output") # Adding the output placeholder here
  )
)

# Define the server logic
server <- function(input, output) {
  output$output <- renderText({
    if (!is.null(input$date_picker)) {
      paste(
        "Selected date range:",
        format(input$date_picker[1], "%Y-%m-%d %H:%M"),
        "to",
        format(input$date_picker[2], "%Y-%m-%d %H:%M")
      )
    }
  })
}

# Run the Shiny app
shinyApp(ui, server)
```

![issue](https://github.com/dreamRs/shinyWidgets/assets/98490042/8dca5cf7-cb2b-4ea1-958c-b8a9209f7889)

**fix:**
```R
library(shiny)
library(shinydashboard)
library(shinyWidgets)

# Define the UI
ui <- dashboardPage(
  dashboardHeader(title = "Simple Shiny Dashboard"),
  dashboardSidebar(),
  dashboardBody(
    box(
      airDatepickerInput(
        inputId = "date_picker",
        label = "Date:",
        placeholder = "Please select a Time period",
        multiple = 2,
        minDate = "2021-01-01",
        clearButton = TRUE,
        timepicker = TRUE,
        todayButton = TRUE,
        range = TRUE,
        toggleSelected = FALSE,
        timepickerOpts = timepickerOptions(timeFormat = "hh:mm:00")
      )
    ),
    verbatimTextOutput("output") # Adding the output placeholder here
  )
)

# Define the server logic
server <- function(input, output) {
  output$output <- renderText({
    if (!is.null(input$date_picker)) {
      paste(
        "Selected date range:",
        format(input$date_picker[1], "%Y-%m-%d %H:%M"),
        "to",
        format(input$date_picker[2], "%Y-%m-%d %H:%M")
      )
    }
  })
}

# Run the Shiny app
shinyApp(ui, server)
```

![fix](https://github.com/dreamRs/shinyWidgets/assets/98490042/640dcdef-557c-4748-99a8-6685440becdb)

**Comment by pvictor** [comment]
Indeed the documentation was off, thanks for reporting this.

Correct possible values are : 

  * `h` — hours in 12-hour mode
  * `hh` — hours in 12-hour mode with leading zero
  * `H` — hours in 24-hour mode
  * `HH` — hours in 24-hour mode with leading zero
  * `m` — minutes
  * `mm` — minutes with leading zero
  * `aa` — day period lower case
  * `AA` — day period upper case

Victor
