### ISSUE TITLE
updateProgressBar doesn't work inside ShinyModule

### ISSUE THREAD

**Issue by VincentGuyader** [dreamRs/shinyWidgets#62]
Hi (again),

except error it seems to me that there is a problem with `updateProgressBar` inside a ShinyModule.
Please have a look to this app :

```
library(shiny)
library(shinyWidgets)
options(shiny.maxRequestSize=3000*1024^2)  
allFileInput <- function(id, label = "Upload your file") {
  ns <- NS(id)
  tagList(
    progressBar(id = ns("pb1"), value = 0),
    actionButton(inputId = ns("go"),label = "go")  )
}

allFile <- function(input, output, session) {
  observeEvent(input$go,{
    message("go")
    updateProgressBar(session = session, id = "pb1", value = input$go)
  })
}

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      allFileInput("plop")
    )
    ,
    mainPanel(
      tableOutput("contents")
    )
  )
)
server <- function(input, output,session) {
  callModule(allFile,"plop")
}

shinyApp(ui, server)
```

Merci :)

> > sessionInfo()
> R version 3.4.3 (2017-11-30)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
> [3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
> [5] LC_TIME=French_France.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] shinyWidgets_0.4.2 shiny_1.0.5       
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.16    digest_0.6.15   withr_2.1.2     mime_0.5       
>  [5] R6_2.2.2        jsonlite_1.5    xtable_1.8-2    git2r_0.21.0   
>  [9] httr_1.3.1      curl_3.1        devtools_1.13.5 tools_3.4.3    
> [13] rsconnect_0.8.8 httpuv_1.3.6.2  yaml_2.1.18     compiler_3.4.3 
> [17] memoise_1.1.0   htmltools_0.3.6

**Comment by pvictor** [comment]
Hi again ;)

Yes you have to namespace `progressBar` id manually with `session$ns` for the moment.
I'll change this behavior to avoid doing that in the dev version.

Victor

**Comment by VincentGuyader** [comment]
Hi Victor,

Can you explicit the tricks I have to do ?
