### ISSUE TITLE
multiInput limit option not working

### ISSUE THREAD

**Issue by ksong4** [dreamRs/shinyWidgets#623]
We recently updated shinyWidgets from 0.7.3 to 0.7.6. And one of our previously functioning codes for limit multiInput with the following options no longer functions:
```
multiInput(
  inputId = "Id010",
  label = "Carat:", 
  choices = unique(diamonds$carat),
  selected = NULL,
  options = list(
    limit = 1
  )
)
```
When rendering this widget, clicking any choices will not move the selected item to the selected columns (right column). The issue can be resolved by reverting back to 0.7.3.

**Comment by pvictor** [comment]
Thanks for reporting the issue, old behavior has been restored.
