### ISSUE TITLE
materialSwitch label issue

### ISSUE THREAD

**Issue by RightChain** [dreamRs/shinyWidgets#631]
I have a very large shiny application that has been running well for over a year, but it looks like the latest update to ShinyWidgets has broken the label for me (see image below). It is now consistently adding a `::before` and `::after` around the label text in the css. I have attempted a minimal reproducible example, but have not yet succeeded in doing so. 

<img width="87" alt="image" src="https://github.com/dreamRs/shinyWidgets/assets/47182952/446d1326-15f9-464e-b8f1-f3156897c6ab">

<img width="554" alt="image" src="https://github.com/dreamRs/shinyWidgets/assets/47182952/d18d4c52-3b86-41f5-90ef-a92b5d1bb7a2">

Details
1) The issue cropped up on my production server last week after building a new image of the shiny app. This used the latest CRAN version of "shinyWidgets" package (0.8.0) for R 4.3.1 on Ubuntu 22.04. 
2) The issue did not appear on my local Windows machine running R 4.3.1 until I updated to the latest CRAN version of shinyWidgets (0.8.0). Note that I only updated shinyWidgets. Now my application running locally reproduces the visual error.
3) I've attempted a minimal reproducible example, but have not succeeded. I've put the materialSwitch in a module, put it inside of similar divs/tabs, rendered it dynamically, encapsulating it in shinyBS, and had no luck.
4) I checked my css and js codes to see if they interfere, and they do not. No minimally reproduced error.
5) I've run my minimal reproducible attempts in the same environment created by the application in case there were packages interfering, but the visual error still only appears in my larger application.

I suspect the issue may be in the .css or .js scripts of one ui element interfering with another, but I'm not sure. That is not my forte. I need to move on to other tasks for the moment, so I was wondering if you had seen any similar issues and could advise me on how to move forward. My short term plan is to use the previous CRAN version until I can isolate the issue.

**Comment by pvictor** [comment]
Have you stored result of `materialSwitch()` before displaying it in the browser somehow ? In a `.rds` file or in raw HTML ?

**Comment by seepepdl1** [comment]
I had exactly the same issue after updating shinyWidgets from 0.7.6 to 0.8.0.
For me i just had to clear the cache of my google chrome navigator..
But i guess this could be a problem for your users if your app is in production

**Comment by RightChain** [comment]
I've revisited this issue after a long time of just using an old version of shinyWidgets (0.7.8), and I finally found the source of my issue. As usual it was a user/developer error. I had included the following code segment in a recurring module that uploaded inputs. Removing this code seems to have fixed the issue, now I just need to figure out why I had it in there in the first place and make sure removing it doesn't create any new problems.

```
tags$head(HTML('
    <script type="application/html-dependencies">selectPicker[1.13.10]</script>
    <link href="shinyWidgets/shinyWidgets.css" rel="stylesheet" />
    <script src="shinyWidgets/shinyWidgets-bindings.min.js"></script>
    <link href="shinyWidgets/selectPicker/css/bootstrap-select.min.css" rel="stylesheet" />
    <script src="shinyWidgets/selectPicker/js/bootstrap-select.min.js"></script>
     '
))
```
