### ISSUE TITLE
[Feature Request]Listbox with multi-select function and sorting function

### ISSUE THREAD

**Issue by toxintoxin** [dreamRs/shinyWidgets#632]
multi() is a excellent widgets, but we can't change the order of the selected value.  
Do you have plans to develop a new widget?  
I found a project meets needs. But I don't know how to use it in shiny.  
> Preserve Select Order Example in [this page](https://jakezatecky.github.io/react-dual-listbox/)  

I'm sure it will be very efficient

**Comment by pvictor** [comment]
Hello, 
You can try this package : https://github.com/dreamRs/reactwidgets which integrate dualListBox library.

Victor

**Comment by toxintoxin** [comment]
> Hello, You can try this package : https://github.com/dreamRs/reactwidgets which integrate dualListBox library.
> 
> Victor

Thank you! It's an awesome project!
