### ISSUE TITLE
[BUG]When using lapply() to batch generate dropMenu, it doesn't work very well

### ISSUE THREAD

**Issue by toxintoxin** [dreamRs/shinyWidgets#634]
I tried to generate some dropMenu with the same functionality using `lapply()` and `uiOutput()`, but had problems with it.  

In my shinyapp,  
- I firstly observed that the labels are not being applied,  
- and secondly, only one can be interacted with, the others not.  

And when I created the smallest example to express this bug, I found that  
- the number of dropMenu is also not right
- and the `placement` also didn't work
```
library(shiny)
library(shinyWidgets)
shinyApp(
  ui <- fluidPage(
    fluidRow(uiOutput("bar_export_UI")),
    fluidRow(uiOutput("volcano_export_UI")),
    fluidRow(uiOutput("heatmap_export_UI")),
    fluidRow(uiOutput("PCA_export_UI"))
  ),
  server <- function(input, output, session) {

    types <- c("bar", "volcano", "heatmap", "PCA")
    lapply(types, function(type) {
      output[[paste0(type, "_export_UI")]] <- renderUI({
        div(
          dropMenu(
            actionButton(inputId = paste0(type, "_ggsave"), "export", icon = icon("image")),
            div(
              downloadButton(inputId = paste0(type, "_ggsave_png"), "PNG", icon = NULL),
              downloadButton(inputId = paste0(type, "_ggsave_svg"), "SVG", icon = NULL)
            ),
            theme = "light", placement = "right", arrow = FALSE
          )
        )
      })
    })
  }
)
```

![image](https://github.com/dreamRs/shinyWidgets/assets/128743444/91fd0601-a681-4486-a15d-3622e9e6e331)

**Comment by toxintoxin** [comment]
Another problem is that numericInputIcon generate by lapply() won't alert in red when the keyed-in value exceeds the limit

**Comment by pvictor** [comment]
There's an error in your code, `downloadButton()` doesn't have an `inputId` argument but have an `outputid` one.
Why it's not working is that it use the second argument (`"PNG"`) as `outputId` for all 4 buttons and so you have duplicate bindings ID which Shiny doesn't like (you can see an error in the JavaScript console).

Victor
