### ISSUE TITLE
How to avoid useShinydashboard() change any CSS

### ISSUE THREAD

**Issue by toxintoxin** [dreamRs/shinyWidgets#636]
the `box()` of shinydashboard is amazing, but I build my app without shinydashboard, when I intro `useShinydashboard()`, I found that almost all the CSS had been changed, How can I avoid it?

**Comment by pvictor** [comment]
Hello,
`useShinydashboard()` is deprecated and will be removed in a future release, I do not recommend using it.
See `bslib::card` for a more modern alternative to `shinydashboard::box`: https://rstudio.github.io/bslib/articles/cards/index.html

Victor
