### ISSUE TITLE
Dropdown closes after running updatePickerInput

### ISSUE THREAD

**Issue by mmrancho** [dreamRs/shinyWidgets#638]
Hi,

I noticed the dropdown menu automatically closes after running `updatePickerInput()`. Is this intended?

I would need the dropdown to stay open. I noticed this is still working up until shinyWidgets 0.7.0 (dropdown stays open). Starting with 0.7.1 and later the dropdown closes, which can be annoying in some cases, and I don't know how to prevent this from happening.

For an example please check my [stackoverflow post](https://stackoverflow.com/questions/77183691/shiny-pickerinput-how-to-select-several-choices-by-clicking-one-choice-and-kee?noredirect=1#comment136070407_77183691).

Thanks for looking into this!

**Comment by pvictor** [comment]
If the functionality you seek is being able to select all options from a group, try `virtualSelectInput()` which has a built-in option to do that : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$h2("Virtual Select"),
  virtualSelectInput(
    inputId = "ID",
    label = "Select :",
    choices = list(
      lower = c("a", "b", "c"),
      upper = c("A", "B", "C")
    ),
    multiple = TRUE
  ) ,
  verbatimTextOutput("res")
)

server <- function(input, output, session) {
  
  output$res <- renderPrint(input$ID)
  
}

shinyApp(ui, server)
```
