### ISSUE TITLE
ConfirmSweetAlert not reset after use

### ISSUE THREAD

**Issue by aslomko** [dreamRs/shinyWidgets#64]
When using confirmsweetalert, after choosing yes the value does not get reset to NULL, causing it to not function in a row sequentially with an observeEvent or event reactive.

**Comment by pvictor** [comment]
Hello,
Can you provide an example please? 

Victor

**Comment by aslomko** [comment]
library(shiny)
library(shinyWidgets)
# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel("Old Faithful Geyser Data"),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
         sliderInput("bins",
                     "Number of bins:",
                     min = 1,
                     max = 50,
                     value = 30)
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
        actionButton("Testing","Click Me"),
         plotOutput("distPlot")
      )
   )
)

# Define server logic required to draw a histogram
server <- function(input, output,session) {
   
   output$distPlot <- renderPlot({
      # generate bins based on input$bins from ui.R
      x    <- faithful[, 2] 
      bins <- seq(min(x), max(x), length.out = input$bins + 1)
      
      # draw the histogram with the specified number of bins
      hist(x, breaks = bins, col = 'darkgray', border = 'white')
   })
   
   observeEvent(input$Testing,{
     confirmSweetAlert(
       session = session, inputId = "confirmed", type = "warning",
       title = "Confirm Adding Data?", danger_mode = TRUE
     )
   })
   
   
   
   observeEvent(input$confirmed,{
     if(input$confirmed){
       showModal(modalDialog(
         title = "Important message",
         "The current value of bins are:",
         input$bins
       ))
     }
   })
}

# Run the application 
shinyApp(ui = ui, server = server)

Once you click the click me button and confirm, it will not display the modal dialogue again until you click cancel and then confirm

**Comment by pvictor** [comment]
Thanks for the example.

Are you using the last version of `shinyWidgets`, e.g. `0.4.2` ?
I think your problem has been solved in [#53](https://github.com/dreamRs/shinyWidgets/issues/53).

Victor

**Comment by aslomko** [comment]
You are correct it was solved.  Sorry!  I did not realize there was a recent newer version.  Thank you so much!
