### ISSUE TITLE
setShadow deprecation warning shows up in UI

### ISSUE THREAD

**Issue by dcaud** [dreamRs/shinyWidgets#644]
I see the following at the top of my app in a web browser:

> 1: setShadow has been deprecated and will be removed in a future release of shinyWidgets. If you absolutely need to use this function, copy the source code into your project https://github.com/dreamRs/shinyWidgets/blob/26838f9e9ccdc90a47178b45318d110f5812d6e1/R/setShadow.R 

I am fine seeing the warning in the console of an interactive session, but I do not want this warning to be shown in the web browser. I tried options(warn = -1) and it still displayed. Any way to prevent this from being shown?

**Comment by pvictor** [comment]
This function will be deleted in a next release, if you want to use it the best is to put in a script in your project : 

```r
setShadow <- function(id = NULL, class = NULL) {

  # shadow css
  cssShadow <- paste0(
    " box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
      transition: 0.3s;
      border-radius: 5px;
   ")

  cssShadow <- if (!is.null(id)) {
    if (!is.null(class)) {
      paste0("#", id, " .", class, " {", cssShadow, "}")
    } else {
      paste0("#", id, " {", cssShadow, "}")
    }
  } else {
    if (!is.null(class)) {
      paste0(".", class, " {", cssShadow, "}")
    } else {
      NULL
    }
  }

  # hover effect css
  cssHover <- "box-shadow: 0 16px 32px 0 rgba(0,0,0,0.2);"

  cssHover <- if (!is.null(id)) {
    if (!is.null(class)) {
      paste0("#", id, ":hover .", class, ":hover {", cssHover, "}")
    } else {
      paste0("#", id, ":hover", " {", cssHover, "}")
    }
  } else {
    if (!is.null(class)) {
      paste0(".", class, ":hover", " {", cssHover, "}")
    } else {
      NULL
    }
  }

  css <- paste(cssShadow, cssHover)

  # wrap everything in the head
  htmltools::tags$head(
    htmltools::tags$style(css)
  )
}
```
