### ISSUE TITLE
`materialSwitch` label not centered vertically with switch in `bs4dash`

### ISSUE THREAD

**Issue by a-drumm** [dreamRs/shinyWidgets#647]
Comparison between `shinydashboard` and `bs4dash`:
<img width="148" alt="Screenshot 2023-12-19 at 18 50 55" src="https://github.com/dreamRs/shinyWidgets/assets/79289918/47dea033-1bc1-47d4-a25b-d9a075f4f6b2">      <img width="151" alt="Screenshot 2023-12-19 at 18 50 36" src="https://github.com/dreamRs/shinyWidgets/assets/79289918/b3b7e59b-4c95-422c-8e0a-62a77dfe4642">

My hunt to find a way to fix this with CSS has so far failed. I can't even figure out _why_ this is happening in the first place.

Code:

```
library(shiny)
library(bs4Dash)     # replace with library(shinydashboard) for comparison
library(shinyWidgets)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    materialSwitch(
      inputId = "Id075",
      label = "A label"
    )
  )
)

server <- function(input, output) {
}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
You have to manually fix the margin by putting this in your UI : 

```r
tags$style(
  HTML(".material-switch > label.switch::before { margin-top: -5px;}"),
  HTML(".material-switch > label.switch::after { margin-top: -5px;}")
)
```
