### ISSUE TITLE
VirtualSelectInput options

### ISSUE THREAD

**Issue by yandv** [dreamRs/shinyWidgets#654]
How i can change some options in virtualSelectInput like pickerInput?

**Comment by pvictor** [comment]
Hello,

You can use options listed here https://sa-si-dev.github.io/virtual-select/#/properties as arguments of `virtualSelectInput()`, e.g. to use `textDirection` property you can do : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  virtualSelectInput(
    inputId = "id",
    label = "Label :",
    choices = month.name,
    search = TRUE,
    textDirection = "rtl"
  )
)

shinyApp(ui, function(...) {})
```

Victor
