### ISSUE TITLE
updateProgressBar generates JS errors

### ISSUE THREAD

**Issue by TrainedMusician** [dreamRs/shinyWidgets#656]
When running updateProgressBar on a progressBar where total is _**not**_ set, the following error appears:

If you do initialize `total` no errors are generated, but you're stuck with the `progress-number` div in the top right corner. Both updateProgressBar calss work as intended.

Minimum working example:
```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
	progressBar(id = 'bar', value = 0L)
)

server <- function(input, output, session) {
	observe({
		invalidateLater(1000L, session)
		updateProgressBar(session = session, id = 'bar', value = sample.int(100L, 1L))
	})
}

shinyApp(ui, server)
```
When running this app, inspect element and open the Console log to see a new error being generated on every update (every second). When adding `total = 4L` to line 5, all errors are gone!

If more information is needed, please let me know

**Comment by pvictor** [comment]
Thanks for reporting. Should be fixed in dev version.

Victor

**Comment by TrainedMusician** [comment]
Awesome! Thank you Victor
