### ISSUE TITLE
Status is not updated in updateAwesomeRadio

### ISSUE THREAD

**Issue by jnhyeon** [dreamRs/shinyWidgets#657]
Hello.
Thank you for creating a useful package.

The status is not updated in updateAwesomeRadio.
  - After setting the initial status to primary, I want to change the status of the widget to warning when I press a specific button, but it doesn't work.

Thank you

**Comment by pvictor** [comment]
Hello,

You need to provide choices again to make it works because HTML markup needs to be regenerated. Exemple:

```r
library(shiny)
library(shinyWidgets)


ui <- fluidPage(
  awesomeRadio(
    inputId = "ID",
    choices = c("A", "B", "C"),
    label = "My label",
    status = "primary"
  ),

  selectInput(
    inputId = "updatestatus",
    label = "Status",
    choices = c("primary", "danger", "warning", "success", "info")
  )
)

server <- function(input, output, session) {

  observeEvent(input$updatestatus, {
    updateAwesomeRadio(
      session = session, 
      inputId = "ID",
      choices = c("A", "B", "C"),
      status = input$updatestatus
    )
  }, ignoreInit = TRUE)

}

shinyApp(ui = ui, server = server)
```

Victor

**Comment by jnhyeon** [comment]
Thank you so much for your quick solution.
Have a nice day !
