### ISSUE TITLE
Extend prepare_choices to include classNames

### ISSUE THREAD

**Issue by SverreFL** [dreamRs/shinyWidgets#658]
Hi, thanks for a great package. 

I am using `prepare_choices` to make options for virtual select. I want to provide classNames to conditionally style rows in the dropdown. It is one of the properties (https://sa-si-dev.github.io/virtual-select/#/properties), but it is not possible to provide it to `prepare_choices`.

From my minimal testing it seems sufficient to just extend the arguments in `prepare_choices`. Everything is already handled by body of the function.

**Comment by pvictor** [comment]
Sure this seems interesting.
I'll look into it but you're welcome if you want to make a PR.

**Comment by SverreFL** [comment]
Extending it with classNames should be straight forward, but maybe you want to handle the other options-properties also, possibly with a `...`.

I'll try to make a PR with just classNames and then you can consider if you want to generalize it further :)
