### ISSUE TITLE
State of pickerInput

### ISSUE THREAD

**Issue by tsolloway** [dreamRs/shinyWidgets#66]

**Comment by pvictor** [comment]
Hello,
Your question was interesting, you could have left it open. For the moment there is no way to recover server side events, but it may be possible. Can you tell me what you're trying to do?

Best, 

Victor

**Comment by pvictor** [comment]
Yes that's the way to do it.
I can implement this directly in the javascript bindings to make the input directly available without the javascript code.
I let you know.

Victor

**Comment by tsolloway** [comment]
I appreciate it.

**Comment by tsolloway** [comment]
Hey Victor, did you ever implement that change? / If you have how would one access that logical?
