### ISSUE TITLE
Make binding for clearing airDatePickerInput (return NA or NULL) 

### ISSUE THREAD

**Issue by chjacamp** [dreamRs/shinyWidgets#663]
Hello,

This is probably requesting a breaking change but I think airDatePickerInput should return NA (or NULL if easier) when blank because it is hard to capture a user clearing a date field in shiny otherwise.

The use case for a user clearing a date field is if they want the filter to be "inactive". 

Here is a small reprex

```
if (interactive()) {
  
  library(shiny)
  library(shinyWidgets)
  
  ui <- basicPage(
    
    airDatepickerInput(
      inputId = "my_airdatepicker",
      value='2018-01-01',
      minDate = "2018-01-01",
      maxDate = "2018-12-31",
      label = "Date:"    
), 
    
    htmlOutput('test')
    
  )
  
  server <- function(input, output, session) {
    
    date_reactive <- reactive(input$my_airdatepicker)
    
    output$test <- renderUI(tags$p(date_reactive()))
  }
  
  shinyApp(ui, server)
  
}
```

Thanks,
Christopher

**Comment by chjacamp** [comment]
I'm sorry for multiple edits. I have tested a bit more and found that the issue is actually that clearing the text box does not clear the date selected. Perhaps this is better to file with airDate JS library. Let me know. 

Thanks!
Christopher

**Comment by pvictor** [comment]
Hello,
Yes this is currently by the JS lib, there's some discussions about it in the air-datepicker repo.
Best solution I think is to make the field readonly with `airDatepickerInput(readonly = TRUE)`.

Victor

**Comment by chjacamp** [comment]
OK, got it - I felt editing the text box was so natural I hadn't even considered it was disconnected from the picker. The readonly solution is great, thank you! 

I changed the disabled look as well, posting that here if there's future interest in the solution - 

```
.form-control[readonly] {
  background-color:white !important;
}
```

Thanks for the excellent package and your quick response. 

Best,
Christopher
