### ISSUE TITLE
virtualSelectInput does not respect onServerChange

### ISSUE THREAD

**Issue by MichalLauer** [dreamRs/shinyWidgets#664]
Hello,

I am trying to use the `onServerChange` parameter to create a custom function for searching. However, the sample code from the [documentation ](https://sa-si-dev.github.io/virtual-select/#/examples?id=server-search) does not work and I can't seem to figure out why.

``` r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$script(HTML(
    "
      function onSampleSelectServerSearch(searchValue, virtualSelect) {
        console.log('this should run.');
      }
    "
  )),
  virtualSelectInput(
    inputId = "sel",
    label = "Select",
    choices = 1:10,
    search = T,
    onServerChange = "onSampleSelectServerSearch"
  )
)

server <- function(input, output, session) { }

shinyApp(ui, server)
```

<sup>Created on 2024-02-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Will appriciate any feedback! Once we identify the issue, I could try to create a PR to help with this :)

**Comment by MichalLauer** [comment]
I tried to investigate further and found that an issue on my end is that I do not use async functions. Once this is fixed, a VirtualSelect created purely in JS works as expected, but the one using `{shinyWidgets}` is not.

``` r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$script(HTML(
    "
    $(document).ready(function() {
      VirtualSelect.init({ele: '#mySel',
                          search: true,
                          onServerSearch: onSampleSelectServerSearch});

      async function anyMehodToGetDataFromServer(searchValue) {
        return searchValue + '?';
      }

      function onSampleSelectServerSearch(searchValue, virtualSelect) {
        anyMehodToGetDataFromServer(searchValue).then(function(ret) {
          console.log(ret);
        })
      }
    });
    "
  )),
  tags$div(id = "mySel"),
  virtualSelectInput(inputId = "shinyVS",
                     label = "shinyVS",
                     choices = -1,
                     search = T,
                     onServerSearch = "onSampleSelectServerSearch"
                     )
)

server <- function(input, output, session) { }

shinyApp(ui, server)
```

<sup>Created on 2024-02-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Could it be that using JS a reference to the function is passed but ShinyWidgets passes just a text? I found in the [source code](
https://github.com/sa-si-dev/virtual-select/blob/f89ca5e73a29d9187c019444caad61a46f14a5e7/docs/assets/virtual-select.js#L3252-L3257) this line

```js
this.onServerSearch(this.searchValue, this);
```

that calls the reference.

**Comment by pvictor** [comment]
Hello,
Options are passed to virtual-select as JSON which do not support JavaScript code in it normally. So when you do ` onServerChange = "onSampleSelectServerSearch"` that's just a string.
That's here in the bindings: https://github.com/dreamRs/shinyWidgets/blob/3660e041b3c0c82827e5fa5fb3c1be28e0563690/srcjs/inputs/virtual-select.js#L88

Solution will be to parse text as JavaScript code, either just for `onServerChange` option or for strings marked somehow to be JavaScript code (like in selectize with `I()`).

Something like `config.onServerChange = eval("(" + config.onServerChange + ")");` in the right place in the bindings.
