### ISSUE TITLE
add option to no wrap `dropdownButton()` item within an `ul` and `li`s

### ISSUE THREAD

**Issue by vbonhomme** [dreamRs/shinyWidgets#67]
Hi there,

I love shinyWidgets and I would like to use it to improve my app, where compacity is more than an option.

I think wrapping what's passed as `...` in dropdownButton is fine in most cases but I (and possibly others) would like to have more freedom in the way these `...` items are formatted. Typically, to be able to bypass the `do.call(htmltools::tags$ul, html_ul)` to format manually these items.

Graphically, I 'd like something around this:

![image](https://user-images.githubusercontent.com/4728854/38658984-98843450-3e27-11e8-9796-b7d36bfd5b60.png)

rather than:

![image](https://user-images.githubusercontent.com/4728854/38658993-a77d01ee-3e27-11e8-9b1b-436a9648d29b.png)

Would it be possible to add such an argument to `dropdownButton()`?

Thanks a bunch !

**Comment by pvictor** [comment]
Hi!

You can still do that despite the `do.call(htmltools::tags$ul, html_ul)` : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  dropdownButton(
    label = "Controls",
    icon = icon("sliders"),
    status = "primary",
    circle = FALSE,
    width = "300px",
    splitLayout(cellArgs = list(style = "overflow: visible;"),
      numericInput(inputId = "n1", label = "n1", value = 2),
      numericInput(inputId = "n2", label = "n2", value = 100),
      selectInput(inputId = "s1", label = "s1", choices = letters[1:5])
    ),
    checkboxGroupInput(
      inputId = "cb1", label = "cb1",
      choices = month.name
    )
  ),
  tags$div(style = "height: 140px;"), # spacing
  verbatimTextOutput(outputId = "out")
)

server <- function(input, output, session) {
  
  output$out <- renderPrint({
    reactiveValuesToList(input)
  })
  
}

shinyApp(ui, server)
```

Result: 
![image](https://user-images.githubusercontent.com/4415580/38672412-63b2ade8-3e4e-11e8-959d-e749307fe3ea.png)



Or wrap all tour elements in a `tags$div` or `tagList`.
I don't think the `ul` cause an issue, otherwise you have function `dropdown` which works in a similar way but without the `do.call(htmltools::tags$ul, html_ul)` .

Let me know if it works for you ! 

Victor

**Comment by vbonhomme** [comment]
Thanks a bunch Victor !
Cannot thank you before my computer crashed in the meantime :(

**Comment by pvictor** [comment]
You're welcome! And sorry for your computer ;)
