### ISSUE TITLE
possibility to disable actionBttn using shinyjs

### ISSUE THREAD

**Issue by Rozenn** [dreamRs/shinyWidgets#68]
Hi,

I use  shinyjs::disable("my_button") to disable my button, but it seems to not be comptible with shinyWidget actionBttn.
Is it possible to make an option to disable the button, or do you have any idea how I can deal with this issue ? 

Thanks in advance,

Rozenn.

**Comment by pvictor** [comment]
Hi Rozenn,

The button is disabled, on the other hand the cursor is not modified,  it is necessary to add a little css.
Check this example : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  shinyjs::useShinyjs(),
  tags$style(".bttn-bordered[disabled] {cursor: not-allowed;}"),
  tags$br(),
  actionBttn(
    inputId = "bttn1",
    label = "Go!",
    color = "primary",
    style = "bordered"
  ),
  tags$br(),
  verbatimTextOutput(outputId = "res_bttn1"),
  tags$br(),
  actionButton("goButton", "Go!"),
  tags$br(),
  verbatimTextOutput(outputId = "res_goButton")
  
)

server <- function(input, output, session) {
  shinyjs::disable(id = "goButton")
  shinyjs::disable(id = "bttn1")
  output$res_bttn1 <- renderPrint(input$bttn1)
  output$res_goButton <- renderPrint(input$goButton)
}

shinyApp(ui = ui, server = server)
```

But in dev version, you don't need this CSS, I added it to the dependencies.

Victor

**Comment by earnaud** [comment]
Hi, 
just to let you know, I use this CSS rule to get a disabled effect on {shinyWidgets} buttons:
```
.bttn.disabled, .bttn.disabled::after, .bttn.disabled::before  {
  cursor: not-allowed;
  transform: none !important;
}
```
Best.
