### ISSUE TITLE
virtualSelectInput hides element name when only one element for one group is present

### ISSUE THREAD

**Issue by le-raman** [dreamRs/shinyWidgets#680]
Hi devs,

Reporting following bug, with reproducible example:

```R
library("shiny")

ui <- fluidPage(
  shiny::HTML("<br><br>"),
  shinyWidgets::virtualSelectInput(
    "test_id",
    "Label",
    list("A group" = c("An element of this group"))
  )
)

server <- function(input, output, session) {
}

shinyApp(ui, server)
```

Result:

![image](https://github.com/dreamRs/shinyWidgets/assets/156107083/131105ec-3e96-4563-ae14-438b55db6217)

The element name itself is thus hidden; only the group name is shown. Using two elements, the behavior is ok, and both group name and elements are shown:

![image](https://github.com/dreamRs/shinyWidgets/assets/156107083/c8953312-2650-4081-9a31-95371adbad48)

Any ideas how to circumvent this?

Thanks!

Lennart

**Comment by pvictor** [comment]
Hello,
If there's only one element in a group you need to use a `list` rather than a `vector`, e.g. : 

```r
list("A group" = list("An element of this group"))
```

**Comment by le-raman** [comment]
Thanks for the quick response. Can confirm that this work-around works.
