### ISSUE TITLE
[docs] deprecated docs in switchInput()

### ISSUE THREAD

**Issue by jhk0530** [dreamRs/shinyWidgets#687]
Thank you for making such a great package. I always use it well.

I'm creating an issue because I'm using a recent feature and the documentation hasn't been updated.

The manual for `?switchInput` shows as below.
`width` parameter as The width of the input : 'auto', 'fit', '100px', '75%'.

Unfortunately, **'auto' doesn't work** with the following error message

``` r
Error in validateCssUnit(width) : "fit" is not a valid CSS unit (e.g., "100%", "400px", "auto")
```

How about removing "auto" to avoid confusion?

Thanks.

**Comment by pvictor** [comment]
Thank you, I've updated the docs. Glad you like the package!

Victor
