### ISSUE TITLE
Is it possible to renderUI on a pickInput within a dropdownbutton

### ISSUE THREAD

**Issue by peeyooshc** [dreamRs/shinyWidgets#7]
Firstly thank you for sharing - this is an excellent package. I'm hoping the answer to my question below is easy, as it has me a little stumped due to little knowledge of how the jQuery is being built up.

 I've setup a dropdownButton and want to be able to use the p
```
dropdownButton(
              "Select adverts to drill down",
              circle = TRUE, status = "default", icon = icon("sliders"), width = "300px",
              tooltip = tooltipOptions(title = "Click to see inputs !"),
              uiOutput("choose_adverts")
            )
```

I want to be able to render a pickerInput in this box, with dynamically updated list of choices

```
pickerInput(inputId = "Adverts", 
               label = "Adverts",
              choices = adverts, # a list of strings
               options = list(`actions-box` = TRUE, `live-search` = TRUE), 
              multiple = TRUE)
```

It currently renders the picker but does not populate choices.

Are you able to suggest what I might try to get it to work?

**Comment by pvictor** [comment]
Hello,

Thanks for using :)

There's an issue for using `pickerInput` in a `dropdownButton`, see issue #3 .
I'm working on an alternative to make it work, i'll let you know.

Victor

**Comment by peeyooshc** [comment]
Thanks for responding. Another short term solution might be to have it so that the inputs were held in a div that could have visibility toggled. Is that possible?

**Comment by pvictor** [comment]
That's what a dropdown do :)
The content is hidden until the button is clicked.
The issue was a conflict between two Bootstrap modules.

I wrote a new `dropdown` function which work with `pickerInput`, try this example and let me know if it works for you : 

```
library("shiny")
library("shinyWidgets")


# Countries
countries <- c(
  "United Kingdom", "Germany", "United States of America", "Belgium", "China", "Spain", "Netherlands", "Mexico",
  "Italy", "Canada", "Brazil", "Denmark", "Norway", "Switzerland", "Luxembourg", "Israel", "Russian Federation",
  "Turkey", "Saudi Arabia", "United Arab Emirates"
)
# Fruits
fruits <- c("Banana", "Blueberry", "Cherry", "Coconut", "Grapefruit", "Kiwi", "Lemon", "Lime", "Mango", "Orange", "Papaya")


ui <- fluidPage(
  radioButtons(inputId = "choices", label = "For pickerInput", choices = c("countries", "fruits")),
  dropdown(
    tags$p("Select adverts to drill down"),
    circle = TRUE, status = "default", icon = icon("sliders"), width = "300px",
    # animate = animateOptions(),
    uiOutput("choose_adverts")
  ),
  verbatimTextOutput(outputId = "res")
)

server <- function(input, output, session) {
  output$choose_adverts <- renderUI({
    if (input$choices == "countries") {
      adverts <- countries
    } else {
      adverts <- fruits
    }
    pickerInput(inputId = "Adverts",
                label = "Adverts",
                choices = adverts, # a list of strings
                options = list(`actions-box` = TRUE, `live-search` = TRUE),
                multiple = TRUE)
  })
  # outputOptions(output, "choose_adverts", suspendWhenHidden = FALSE)
  output$res <- renderPrint({
    input$Adverts
  })
}

shinyApp(ui = ui, server = server)
```


Note : 

`output$choose_adverts` is only rendered (and the code corresponding executed) when the dropdown is open (and the content visible), if you want to prevent that, check `outputOptions`.

**Comment by peeyooshc** [comment]
That works brilliantly - thank you!

Have you seen or used shinyjqui?

**Comment by pvictor** [comment]
Yes I seen it, nice package ! The drag and drop thingy is awesome
