### ISSUE TITLE
airDatepickerInput() can't show month number but use 00 instead

### ISSUE THREAD

**Issue by CongSIBR** [dreamRs/shinyWidgets#704]
Dear Author,

Thank you for the fantastic package! However, I encountered an issue with the `airDatepickerInput`. As shown in the screenshot, after selecting a date range, the displayed date does not match my selection—the month of the date is shown as "00," even though the date data in the backend is correct.

the code I used is:
```airDatepickerInput(
          inputId = ns("dateid"),
          label = "Select date range:",
          placeholder = "pick a range of dates",
          multiple = 2, 
          range = TRUE,
          dateFormat = "yyyy-mm-dd",
          clearButton = TRUE,
          minDate = '2017-03-18',
          maxDate = '2023-09-10',
          autoClose = TRUE
        ) 
```

<img width="352" alt="Screenshot 2024-09-10 at 16 45 35" src="https://github.com/user-attachments/assets/b3a06c06-6b51-4259-b2fb-a80b25c757c0">

**Comment by pvictor** [comment]
Hello, 
Thanks for your kind words.
I think this is a problem with `dateFormat`, `mm` is for minutes, you should try `MM` for months. More examples here : https://air-datepicker.com/docs and here : https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table

Victor

**Comment by CongSIBR** [comment]
Thanks for your help! It worked! It was indeed a mistake on my part.
