### ISSUE TITLE
selectize with images 

### ISSUE THREAD

**Issue by madmark81** [dreamRs/shinyWidgets#71]
Hi Victor, 

i have a question concerning the selectizeInput with images. 
I  saw your answer here on this SO issue, but I ran into a small problem. 
https://stackoverflow.com/questions/46635054/selectizeinput-with-image-icon/46645627#comment86735874_46645627

I managed to build my own one with images, but in both cases, the input$.... of this picker prints out as i.e. red.png while I assume we want it to print out 'red' or in my case 1 rather than 1.png

Also: is there a way to change this example to that the selected item also shows up as image? 

thanks, 
Mark.

**Comment by pvictor** [comment]
Hello Mark,
It's not related to `shinyWidgets`... It's a SO question.
Nonetheless I edited my answer, see the edit.

Victor
