### ISSUE TITLE
Output of virtualSelectInput does not handle special characters properly

### ISSUE THREAD

**Issue by joeramirez** [dreamRs/shinyWidgets#710]
I believe this is a similar/same issue as #6 , but when the virtualSelectInput choices contain items with special characters ('&' for example), the resulting output when those items are selected come out with URL encoding (ie, `'&amp;`).

shinyWidgets package version: 0.8.7
shiny package version: 1.9.1
R version: 4.4.1

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      virtualSelectInput(
        inputId = "test",
        label = "Test",
        choices = c("Oranges", "Berries", "Peaches & Plums", "Apples & Bananas"),
        multiple = T
      )
    ),
    mainPanel(
        textOutput("myOutput"),
      )
  )
)

server <- function(input, output) {

  output$myOutput <- renderText({
    paste0(input$test, collapse = " | ")
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Hello,
You have to use `html = TRUE` otherwise special characters in HTML are escaped.

Victor

**Comment by joeramirez** [comment]
Of course!! Sorry - didn't see that option somehow.  Thank you!
