### ISSUE TITLE
Add a parameter in searchInput() in order to mask the text with • as in the basic passwordInput() shiny function

### ISSUE THREAD

**Issue by CroixJeremy2** [dreamRs/shinyWidgets#721]
Hello,
Everything is in the title.

I am discovering the world of shiny apps, so I just hope that I have not missed any existing function that does that actually... Anyway, I just found that `searchInput()` is better than `textInput()` because we can simply press ENTER to validate the text the user has typed. However, for texts that should not be displayed on the screen, like passwords for example, I would like to combine `searchInput()` with `passwordInput()` in order to display texts like this: `•••••••••`

Could it be possible to add this simple parameter to `searchInput()` in order to allow us to do that please?

Thanks in advance for your respond,
Best regards,

**Comment by pvictor** [comment]
Hello,
Welcome to shiny! Sure this is possible, re-install from GitHub and then you can set input type like this : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  # theme = bslib::bs_theme(version = 5L, preset = "bootstrap"),
  tags$h1("Search Input"),
  br(),
  searchInput(
    inputId = "search", 
    label = "Enter your password",
    placeholder = "A placeholder",
    btnSearch = icon("arrow-right"),
    btnReset = icon("xmark"),
    inputType = "password"
  ),
  verbatimTextOutput(outputId = "res1"),
  br(),
  textInputIcon(
    inputId = "text",
    label = "Enter your password",
    icon = icon("key"),
    inputType = "password"
  ),
  verbatimTextOutput(outputId = "res2")
)

server <- function(input, output, session) {
  output$res1 <- renderPrint(input$search)
  output$res2 <- renderPrint(input$text)
}

shinyApp(ui = ui, server = server)
```

Victor

**Comment by CroixJeremy2** [comment]
Excellent! This is exactly what I was looking for.
Thank you so much, and thank you also for the fast response!
Best regards,
