### ISSUE TITLE
[Enhancement] A better version of DownloadButton

### ISSUE THREAD

**Issue by happyshows** [dreamRs/shinyWidgets#73]
Hi,

Is it possible to wrap around downloadbutton to make it look nicer and consistent with other shinywidgets?

I love this package but having a plain vanilla downloadbutton seems a bit odd.

**Comment by pvictor** [comment]
Hi!
Glad you like the package ! :)
Which kind of buttons do you use ? Are you refering to `actionBttn` ?

Victor

**Comment by happyshows** [comment]
yes, I didn't dive into the code, but I believe there are some unique features of the default download button that cannot be replaced by actionBttn directly.

**Comment by pvictor** [comment]
I added function `downloadBttn`, you can try it with : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  tags$h2("Download bttn"),
  downloadBttn(
    outputId = "downloadData",
    style = "bordered",
    color = "primary"
  )
)

server <- function(input, output, session) {

  output$downloadData <- downloadHandler(
    filename = function() {
      paste('data-', Sys.Date(), '.csv', sep='')
    },
    content = function(con) {
      write.csv(mtcars, con)
    }
  )

}

shinyApp(ui, server)
```

Tell me if it works for you !

Victor

**Comment by happyshows** [comment]
Looks fine, thanks for getting this done so fast.
