### ISSUE TITLE
Server side behaviour for dropdownButton vs dropdown

### ISSUE THREAD

**Issue by csliangy** [dreamRs/shinyWidgets#79]
Thanks again for this amazing work. 

Actually this is not a issue, it is just a difference I noticed between dropdownButton and dropdown when created on server side. 

**on ShinyUI:**

 ```
  shinyUI(fluidPage(
      uiOutput("uiWidget")
    ))
```

**On server side:**

 ```
output$uiWidget <- renderUI({
   dropdown(
     label = "Controls",
     icon = icon("sliders"),
     status = "primary",
     circle = FALSE,
     sliderInput(
       inputId = "n",
       label = "Number of observations",
       min = 10, max = 100, value = 30
     ),
     prettyToggle(
       inputId = "na",
       label_on = "NAs keeped",
       label_off = "NAs removed",
       icon_on = icon("check"),
       icon_off = icon("remove")
     ))
 })

```
So for **dropdown**, everything works fine. However, I found a problem in **dropdownButton**, which is the popup will be closed immediately once I click any inside widget. 

I understand there is no problem with dropdown, I am confused by this and would like to have an explanation?

**Comment by pvictor** [comment]
You're welcome :) 

I couldn't reproduce the problem, everything seems to work for me:

![dropdownbutton](https://user-images.githubusercontent.com/4415580/39930414-f9986354-553a-11e8-8dca-3c03e4124e0e.gif)

Can you provide an example where it doesn't work ?

Thanks,

Victor
