### ISSUE TITLE
issue in the addSpinner example

### ISSUE THREAD

**Issue by DivadNojnarg** [dreamRs/shinyWidgets#80]
Hi Victor,

While running your new feature "addSpinner", I saw that there is an issue with the 7th spinner ("double-bounce"), which is still displayed even though the plot is not loading.

<img width="1440" alt="capture d ecran 2018-05-22 a 10 07 55" src="https://user-images.githubusercontent.com/18291543/40349859-2b8fbb9e-5da8-11e8-918e-d95df8b2325d.png">

By the way, very cool feature. 

Cheers
David

**Comment by pvictor** [comment]
Hi David,
You're fast :D 
That's weird, I don't see that... but there was indeed an extra CSS class.
In which browser do you run the app ?
Can you re-test ?

Thanks!

Victor

**Comment by DivadNojnarg** [comment]
This is likely to be a Safari (11, my version, not tested on others) issue. I tested on chrome, chromium, opera, firefox, ... without being able to reproduce it.
