### ISSUE TITLE
Applying options to optgroups rather than to full list in pickerInput

### ISSUE THREAD

**Issue by phalteman** [dreamRs/shinyWidgets#83]
Hi there,

As everyone else says, this package is fantastic, and I really love everything you've done with it so far - so thank you again!

The issue/question I have is that I can't seem to find a way to apply options to the individual optgroups rather than to the full list. For example, I'd like to limit the number of selections within each option group rather than the entire list - in this case, 1 from each optgroup, rather than any two from the list.

    library(shiny)
    ui <- fluidPage(
      shinyWidgets::pickerInput("groups", "Select one from each group below:", 
                                choices = list(Group1 = c("1", "2"),
                                               Group2 = c("A", "B")),
                                multiple = T, options =  list('max-options'=2))
    )
    server <- function(input, output) {}
    shinyApp(ui, server)

I know that [it's possible to use data-max-options in the optrgroup line](https://silviomoreto.github.io/bootstrap-select/examples/#limit-the-number-of-selections) to do this, but I'm not sure whether it's possible in how the pickerInput function translates the list of options...

![grouplimits](https://user-images.githubusercontent.com/39632896/40562486-00ec5b48-6016-11e8-8662-a6c17a8fef7f.png)

Thanks!

**Comment by pvictor** [comment]
Hi!
You're welcome :) Consider adding a star to the Gihub repo :D 

I didn't plan this use case, it's a good idea! To be able to differentiate between the overall number of of options that can be selected and the number per option group, I renamed the option for groups : `max-options-group`.

Re-install package from Github and try this example : 

```r
### Limit the number of selections

# you'll need dev version
# devtools::install_github("dreamRs/shinyWidgets")

library(shiny)
library(shinyWidgets)
ui <- fluidPage(
  pickerInput(
    inputId = "groups",
    label = "Select one from each group below:",
    choices = list(
      Group1 = c("1", "2", "3", "4"),
      Group2 = c("A", "B", "C", "D")
    ),
    multiple = TRUE,
    options =  list("max-options-group" = 1)
  ),
  verbatimTextOutput(outputId = "res_grp"),
  pickerInput(
    inputId = "groups_2",
    label = "Select two from each group below:",
    choices = list(
      Group1 = c("1", "2", "3", "4"),
      Group2 = c("A", "B", "C", "D")
    ),
    multiple = TRUE,
    options =  list("max-options-group" = 2)
  ),
  verbatimTextOutput(outputId = "res_grp_2"),
  pickerInput(
    inputId = "classic",
    label = "Select max two option below:",
    choices = c("A", "B", "C", "D"),
    multiple = TRUE,
    options =  list(
      "max-options" = 2,
      "max-options-text" = "No more!"
    )
  ),
  verbatimTextOutput(outputId = "res_classic")
)
server <- function(input, output) {
  output$res_grp <- renderPrint(input$groups)
  output$res_grp_2 <- renderPrint(input$groups_2)
  output$res_classic <- renderPrint(input$classic)
}
shinyApp(ui, server)
```

**Comment by phalteman** [comment]
This is ideal! Thanks for the quick turnaround! I especially like the different behaviour between the one-per-group and the two-per-group selections. Very intuitive, very clean.

Well done! Star added!
