### ISSUE TITLE
observe checkboxGroupButton does not detect null state

### ISSUE THREAD

**Issue by chrisvwn** [dreamRs/shinyWidgets#85]
I am new to shinyWidgets so I hope this is not a wrong observation.

I want to run some code based on the values of the `checkboxGroupButton` value. The code is a side-effect so I use an `observeEvent` code block. While the code gets triggered for choices in the widget, it is not triggered when all values are deselected (deselecting when only one value is selected). I expect that deselecting the one selected value should trigger the `observeEvent` - essentially any time a value is clicked  whether to select or deselect?

A trivial example below:

```{r}
if (interactive()) {
  
  ui <- fluidPage(
    uiOutput("cbxGrp")
    verbatimTextOutput("value")
  )
  server <- function(input, output) {
    output$cbxGrp <- renderUI({
      checkboxGroupButtons(inputId = "somevalue",
                           label = "Make a choice: ",
                           choices = c("A", "B", "C"))
    })
    
    output$value <- renderText({
      print(input$somevalue)
      
      input$somevalue })
    
    observeEvent(input$somevalue, message("value=", input$somevalue))
    
  }
  shinyApp(ui, server)
}
```

While the `verbatimTextOutput` will print NULL when the last value is deselected the `observe` will not be triggered and will not print anything.

**Comment by pvictor** [comment]
Hello,
Default behavior of `observeEvent` is to ignore `NULL`, you'll have to use argument `ignoreNULL = FALSE`, e.g. : 

```r
observeEvent(input$somevalue, {
    message("value=", input$somevalue)
  }, ignoreNULL = FALSE)
```

Victor

**Comment by chrisvwn** [comment]
Thanks @pvictor! I did not know about this behaviour. Apologies for this.

**Comment by pvictor** [comment]
No worries, have fun with shinyWidgets! :D

**Comment by chrisvwn** [comment]
Thank you! I already am having fun with them! The shinyWidgets are awesome!!
