### ISSUE TITLE
Deselecting layers in Leaflet with ShinyWidget pickerInput

### ISSUE THREAD

**Issue by richardtc** [dreamRs/shinyWidgets#88]
I'm using ShinyWidget's pickerInput feature to allow users to select multiple layers (spatial data) to display in Leaflet. Checking multiple boxes displays the layers as desired, however, I'm unable to hide/deselect the layer after unchecking the box in the input menu.

Key code in my app.R script:
`tn_data <- c("Rail"="rail1", "Airports"="airports1", "Ferries"="ferries1")

pickerInput(inputId = "pickv", label = "Transportation", choices = tn_data, multiple = TRUE),

rail_vn <- readOGR(dsn = "./geospatial_files/osm", layer = "gis.osm_railways_free_1")

server <- function(input, output, session) {

observeEvent(input$pickv, {
  if (input$pickv == "rail1"){  # this diplays just the rail layer
  proxy <- leafletProxy("map")
  proxy %>% addPolylines(data=rail_vn, weight = 2, group = "railv", color = "#7f0000")}
  else {proxy %>% clearGroup("railv")} # this does not work, unable to deselect/hide layer in Leaeflet
 }
)`

Previously, when I used checkboxInput I was able to deselect the layer from Leaflet using the clearGroup function, but this does not work using pickerInput.

I notice that if I uncheck the box with the displayed layer (rail1) and then select another layer the rail1 layer is removed from display. It seems that unchecking the box on its own is not being detected by observeEvent. 

I've also tried adding  ignoreNULL = FALSE  but the app crashes with the error:
Warning: Error in if: argument is of length zero
Stack trace (innermost first):
    65: observeEventHandler [/home/aaa/RDATA/projects/taggg/app.R#554]
     1: runApp

`
`observeEvent(input$pickv, {
 proxy <- leafletProxy("map")
  if (input$pickv == "rail_vn"){
  proxy %>% addPolylines(data=rail_vn, weight = 2, group = "railv", color = "#7f0000")}
  else {
    proxy %>% clearGroup("railv")}
 }, ignoreNULL = FALSE)`
`

**Comment by mgaughan2019** [comment]
I have a very similar problem, but the answer provided above doesn't seem to be solving my issue. I have a list of bus routes that I want users to be able to select individually or select all of them. The "select all" functionality works well, but I cannot get pickerInput to detect when a route has been removed. The code I tried is below: 

```
routes <- routes <-  st_read(dsn = "data/MetroTransitData183.gdb", 
                             layer = "transitroute", stringsAsFactors= FALSE) %>% st_transform(., crs = 4326)  #reads layer of geodatabase


ui <- fluidPage(
  
  # Application title
  titlePanel("RKAAMP Priorty Tract Travelshed Viewer"),

sidebarLayout(
  sidebarPanel(
    pickerInput("routes",
                "Select Routes by Route Number:",
                choices =  as.list(routes$ROUTE_NUM),
                multiple = TRUE, 
                options= pickerOptions(actionsBox = TRUE), 
                width = "75%"
    )
  )
)
)


server <- function(input, output, session) {


select_routes <- reactive({
  routes %>% filter(routes$ROUTE_NUM %in% input$routes)
})

output$travelshed_map <- renderLeaflet({
  
  
  leaflet() %>%
    addProviderTiles("CartoDB.Positron") %>%
    setView(lng = -122.217064, lat = 47.482880, zoom = 11 ) 
}) 

observeEvent(input$routes, { 
  
  proxy<-  leafletProxy("travelshed_map")
  if(!is.null(input$routes) &&  routes$ROUTE_NUM %in% input$routes) {
    proxy %>% 
      addPolylines(data= select_routes(), color = "Black",  weight = 2,
                   opacity = 0.3, group = "routes" )
  } else {
    proxy %>% clearGroup("routes")
  }
  
}, ignoreNULL = TRUE) 
}
```
I'd appreciate any help you can provide!
