### ISSUE TITLE
"updateCheckboxGroupButtons" not working when selected = NULL

### ISSUE THREAD

**Issue by Swechhya** [dreamRs/shinyWidgets#9]
I am trying to use `updateCheckboxGroupButtons` to update the buttons that are selected but when I do `selected = NULL` the buttons selected does not get updated. The previous buttons that were selected remains in the selection.

Following is a minimal example to reproduce the issue:
 ```
  library(shiny)
  library(shinyWidgets)
   
   
   ui <- fluidPage(
     
     selectInput(inputId = "SI_Element", label = "Element:", choices = c("Title", "Body")),
     
     checkboxGroupButtons(inputId = "CBK_Button", label = "Font Style:",
                          choices = c("bold", "italic", "underline")
                          , selected = c("bold"))
     
   )
   
   server <- function(input,output, session){
     
     observeEvent(input$SI_Element,{
       
       if(input$SI_Element == "Body"){
         updateCheckboxGroupButtons(session, "CBK_Button", selected = NULL)
       }else{
         updateCheckboxGroupButtons(session, "CBK_Button", selected = "bold")
       }
       
       
     })
     
   }
   
   shinyApp(ui = ui, server = server)
```
   
The output that is seen is a follows:
![image](https://user-images.githubusercontent.com/6251412/28007209-1ed0714a-6570-11e7-9066-e3c474ab9e34.png)

**Comment by pvictor** [comment]
Hi !
That's not an issue 😁, if you want to remove all choices you have to use `character(0)`, e.g. : 

`updateCheckboxGroupButtons(session, "CBK_Button", selected = character(0))`

I have to admit that i didn't know that, i found it in the help page for `updateCheckboxGroupInput` 😉

Victor

**Comment by Swechhya** [comment]
Thank you for the quick reply, but the documentation of `updateCheckboxGroupInput`  gives the usage as `updateCheckboxGroupButtons(session, inputId, selected = NULL)` which is a kind of misleading. You might want to change that.

**Comment by pvictor** [comment]
You're right, I'll update the docs !
