### ISSUE TITLE
Action button and sliderTextInput together 

### ISSUE THREAD

**Issue by hiltonmbr** [dreamRs/shinyWidgets#91]
Is it possible to integrate a tiny action button on sliderTextInput allowing to get the selected values after click it? I think this feature would be great to avoid multiple reacts instantly.

**Comment by pvictor** [comment]
The issue is that server-side value is refreshed each time the slider changes ? I can put an option to refresh this value only when slider (mouse button) is released. 
You can already put an `actionButton` manually: 

```r
library("shiny")
library("shinyWidgets")

ui <- fluidPage(
  br(),
  sliderTextInput(
    inputId = "mySliderText",
    label = tags$div(
      style = "width: 300px;",
      "Month range slider:",
      actionButton(
        inputId = "refresh",
        label = NULL,
        icon = icon("refresh"),
        class = "btn-xs",
        style = "float: right;"
      )
    ),
    choices = month.name,
    selected = month.name[c(4, 7)]
  ),
  verbatimTextOutput(outputId = "result")
)

server <- function(input, output, session) {
  
  slider_val <- reactiveVal(month.name[c(4, 7)])
  observeEvent(input$refresh, {
    slider_val(input$mySliderText)
  })
  
  output$result <- renderPrint(str(slider_val()))
}

shinyApp(ui = ui, server = server)
```

Victor

**Comment by hiltonmbr** [comment]
Perfect! Please, consider put it as an option in SliderText function in the next release, i.e, something like "actionButton=TRUE/FALSE" .

Thanks.
