### ISSUE TITLE
airDatepickerInput gives underlying calendar

### ISSUE THREAD

**Issue by majvdvel** [dreamRs/shinyWidgets#98]
I have an issue when using an airDatePickerInput, where a second calendar pops up underneath the current calendar when a date is selected. Also when the `value` parameter is specified, this second calendar pops up immediately. In the screenshots you can see:

1. The calendar appearing underneath the widget:
![afbeelding](https://user-images.githubusercontent.com/32356358/42879058-8e997284-8a8f-11e8-9b05-927dbf89697a.png)
![afbeelding](https://user-images.githubusercontent.com/32356358/42879068-993c49aa-8a8f-11e8-9c31-32b264e43b1a.png)

2. The calendar appearing below the widget:
![afbeelding](https://user-images.githubusercontent.com/32356358/42879126-d66b2be8-8a8f-11e8-8f5d-04613a863e7f.png)

when the `inline` parameter is set to `FALSE` and `TRUE`, respectively.

I do not think I observed this behaviour before updating to the most recent shinyWidgets version, although I can not say it with 100% certainty...
It follows the `inline` behaviour, meaning that it stays on screen indefinitely when `inline` is TRUE, and disappears when exiting the widget when `inline` is FALSE.

I have used this code to create the widget:
```
div(
    style = 'display: inline-block; vertical-align: top; align: left; font-size: 80%;',
    airDatepickerInput(
        inputId = 'time_from',
        label = 'From:',
        timepicker = TRUE,
        todayButton = TRUE,
        clearButton = TRUE,
        timepickerOpts = timepickerOptions(timeFormat = 'hh:ii',  minutesStep = 5)
    )
),
```

**Comment by pvictor** [comment]
Hello,
I'm sorry, I haven't been able to reproduce your issue... Would you have a more detailed example?

Thanks,

Victor

**Comment by majvdvel** [comment]
I'm afraid I have to admit I have trouble creating a reproducible example as well in a reduced version of my application (which I can't share). It seems to be an unfortunate interaction with shiny modules and `outputOptions(suspendwhenHidden = FALSE)`. I will let you know if I can come up with something.

**Comment by majvdvel** [comment]
@pvictor I have found this to be the minimal working example. If any of the following components are commented or removed, the secondary calendar does not show up:
- the shinyjqui draggable/sortable/other statement
- the namespace statements
- the outputOptions statement
- the whole module (logical since it contains all of the above)

Kind regards
Mattias

`
# app.R
library(shiny)
library(shinyjqui)
library(shinyWidgets)

# global
plotGraph <- function(input, output, session, namespace) {
  ns <- NS(namespace)
  output$plot <- renderPlot(plot(rnorm(10)))
  output$plots <- renderUI({
    jqui_draggable(plotOutput(ns('plot')))
    })
  outputOptions(output, 'plots', suspendWhenHidden = FALSE)
}

plotGraphUI <- function(input, output, id) {
  ns <-NS(id)
  uiOutput(ns('plots'))
}

#server
server <- function(input, output, session) {
  module <- callModule(plotGraph, id = 'module', namespace = 'module')
}

#ui
ui <- fluidPage(
  airDatepickerInput(inputId = 'date', inline = TRUE),
  plotGraphUI(id = 'module')
)

# Run App
shinyApp(ui = ui, server = server)
`

**Comment by pvictor** [comment]
Thanks a lot for the example!
There's a conflict between Air Datepicker and JQueryUI Datepicker, I'll search a JS solution for this.
A quick fix is to declare JQueryUI dependency before AirDatepicker, this can be done by explicitly load `shinyjqui ` deps : 

```r
ui <- fluidPage(
  includeJqueryUI(),  # <---- here
  airDatepickerInput(inputId = 'date', inline = TRUE),
  plotGraphUI(id = 'module')
)
```

This works for me... I'll let you know if I find a better solution.

Victor

**Comment by majvdvel** [comment]
Great, thank you!
